### ISSUE TITLE
Программисты всего мира объединяйтесь!

### ISSUE THREAD

**Issue by Higgs32584** [twitter/the-algorithm#1003]
Союз нерушимый республик свободных
Сплотила навеки Великая Русь.
Да здравствует созданный волей народов
Единый, могучий Советский Союз!
Славься, Отечество наше свободное,
Дружбы, народов надежный оплот!
Знамя советское, знамя народное
Пусть от победы, к победе ведет!
Сквозь грозы сияло нам солнце свободы,
И Ленин великий нам путь озарил.
Нас вырастил Сталин - на верность народу
На труд и на подвиги нас вдохновил.
Славься, Отечество чаше свободное,
Счастья народов надежный оплот!
Знамя советское, знамя народное
Пусть от победы к победе ведет!
Skvoz grozy siialo nam solntse svobody,
I Lenin velikij nam put ozaril.
Nas vyrastil Stalin - na vernost narodu
Na trud i na podvigi nas vdokhnovil.
Slavsia, Otechestvo chashe svobodnoe,
Schastia narodov nadezhnyj oplot!
Znamia sovetskoe, znamia narodnoe
Pust ot pobedy k pobede vedet!
Мы армию нашу растили в сраженьях,
Захватчиков подлых с дороги сметем!
Мы в битвах решаем судьбу поколений,
Мы к славе Отчизну свою поведем!
Славься, Отечество наше свободное,
Славы народов надежный оплот!
Знамя советское, знамя народное
Пусть от победы к победе ведет!

**Comment by svobodnik** [comment]
бейсд

**Comment by unnimona** [comment]
Cool!
Check out https://securityinfinity.com 
Secure your website now

(We are also giving one time opportunity to hack us in 24 hours. Show your skills)
(we initially thought of not writing this to everyone, only to find some keyboard warriors like Kyle Suero giving us boring startup advice. Also this message is dedicated to Twitter team who thinks they can silence everyone in github.com just like they do in Twitter)

**Comment by unnimona** [comment]
Cool!
Check out https://securityinfinity.com 
Secure your website now

(We are also giving one time opportunity to hack us in 24 hours. Show your skills)
(we initially thought of not writing this to everyone, only to find some keyboard warriors like Kyle Suero giving us boring startup advice. Also this message is dedicated to Twitter team who thinks they can silence everyone in github.com just like they do in Twitter)
