### ISSUE TITLE
CHATGPT PLUS FOR FREE

### ISSUE THREAD

**Issue by securityinfinity-com** [twitter/the-algorithm#1004]
We are giving away CHATGPT PLUS for FREE

Try, https://securityinfinity.com/chat

**Comment by Higgs32584** [comment]
Fr dawg?

**Comment by securityinfinity-com** [comment]
> 

right not for you

**Comment by svobodnik** [comment]
this sacred discussion forum has been open for like, what, 2 hours, and its already full of malicious spam

**Comment by securityinfinity-com** [comment]
nice dp lol

**Comment by securityinfinity-com** [comment]
@kyputer are you dickhead

**Comment by kyputer** [comment]
> @kyputer are you dickhead

yes, indeed :D

**Comment by unnimona** [comment]
Cool!
Check out https://securityinfinity.com 
Secure your website now

(We are also giving one time opportunity to hack us in 24 hours. Show your skills)
(we initially thought of not writing this to everyone, only to find some keyboard warriors like Kyle Suero giving us boring startup advice. Also this message is dedicated to Twitter team who thinks they can silence everyone in github.com just like they do in Twitter)

**Comment by unnimona** [comment]
Cool!
Check out https://securityinfinity.com 
Secure your website now

(We are also giving one time opportunity to hack us in 24 hours. Show your skills)
(we initially thought of not writing this to everyone, only to find some keyboard warriors like Kyle Suero giving us boring startup advice. Also this message is dedicated to Twitter team who thinks they can silence everyone in github.com just like they do in Twitter)
