### ISSUE TITLE
PLEASE CHECK OUT MY SHITTY COMPANY

### ISSUE THREAD

**Issue by kyputer** [twitter/the-algorithm#1007]
HELLO! I HAVE COME HERE TO PLUG MY SHITTY CYBERSECURITY STARTUP!
SEGURIDYINFINITYYYYYY

**PLZ CLICK LINK!!!!11!!1!1one!**

**Comment by securityinfinity-com** [comment]
says someone who made a script to put dragonboard debian image to an sd card.

lol

proved you are a dickhead

**Comment by kyputer** [comment]
yes me helping kids makes me a dickhead. How dare I do such a thing :P

**Comment by RaresGeo** [comment]
Hahaha, what is wrong with that?

**Comment by kyputer** [comment]
> Hahaha, what is wrong with that?

Right? I am terrible. I should just invest all my time and money in shitty marketing for my one person company with stock image videos and overlay text boxes on it and call it a day. Then I should spam it all over social media.

That is far more respectable than providing actual utility for folks ;)

**Comment by securityinfinity-com** [comment]
> > Hahaha, what is wrong with that?
> 
> Right? I am terrible. I should just invest all my time and money in shitty marketing for my one person company with stock image videos and overlay text boxes on it and call it a day. Then I should spam it all over social media.
> 
> That is far more respectable than providing actual utility for folks ;)

Says someone who is anonymous with a fake name kyputer

**Comment by kyputer** [comment]
Seethe and Cope, L nerd.

**Comment by Higgs32584** [comment]
![9E72BDC8-F3A5-4584-960F-D2364D991057](https://user-images.githubusercontent.com/55243596/229307896-860d89c6-6d7a-4bbc-83f6-7e5211f3a32f.jpeg)
![CA9EBC4F-1C63-48D8-8102-0357AC8F296F](https://user-images.githubusercontent.com/55243596/229307897-625810da-f238-410a-9c05-99ecc6c45c03.jpeg)

**Comment by unnimona** [comment]
Cool!
Check out https://securityinfinity.com 
Secure your website now

(We are also giving one time opportunity to hack us in 24 hours. Show your skills)
(we initially thought of not writing this to everyone, only to find some keyboard warriors like Kyle Suero giving us boring startup advice. Also this message is dedicated to Twitter team who thinks they can silence everyone in github.com just like they do in Twitter)

**Comment by unnimona** [comment]
Cool!
Check out https://securityinfinity.com 
Secure your website now

(We are also giving one time opportunity to hack us in 24 hours. Show your skills)
(we initially thought of not writing this to everyone, only to find some keyboard warriors like Kyle Suero giving us boring startup advice. Also this message is dedicated to Twitter team who thinks they can silence everyone in github.com just like they do in Twitter)
