### ISSUE TITLE
Upvote here to show your solidarity against Twitter Blue 

### ISSUE THREAD

**Issue by securityinfinity-com** [twitter/the-algorithm#1008]
Show your solidarity against Twitter Blue here

Upvote now

**Comment by securityinfinity-com** [comment]
+1

**Comment by Menus74** [comment]
$7

**Comment by securityinfinity-com** [comment]
@Menus74  you will pay for Twitter blue?

**Comment by unnimona** [comment]
Cool!
Check out https://securityinfinity.com 
Secure your website now

(We are also giving one time opportunity to hack us in 24 hours. Show your skills)
(we initially thought of not writing this to everyone, only to find some keyboard warriors like Kyle Suero giving us boring startup advice. Also this message is dedicated to Twitter team who thinks they can silence everyone in github.com just like they do in Twitter)

**Comment by unnimona** [comment]
Cool!
Check out https://securityinfinity.com 
Secure your website now

(We are also giving one time opportunity to hack us in 24 hours. Show your skills)
(we initially thought of not writing this to everyone, only to find some keyboard warriors like Kyle Suero giving us boring startup advice. Also this message is dedicated to Twitter team who thinks they can silence everyone in github.com just like they do in Twitter)
