### ISSUE TITLE
KYPUTER, A KID WHO MADE A DRAGON BALL IMAGE AND CALLS HIMSELF A HACKER

### ISSUE THREAD

**Issue by securityinfinity-com** [twitter/the-algorithm#1011]
If you come across someone like him

move fast :dagger:

**Comment by kyputer** [comment]
Thank you, Athul! <3

**Comment by br0wnD3v** [comment]
Hey @kyputer

**Comment by kyputer** [comment]
> Hey @kyputer

Hi @br0wnD3v how ya doing?

**Comment by securityinfinity-com** [comment]
> Thank you, Athul! <3

thanks to linkedin lol

**Comment by securityinfinity-com** [comment]
Say my name again kid

**Comment by kyputer** [comment]
Good publicity for your company. Saving it all for you don't worry, hunny ;)

**Comment by kyputer** [comment]
You are too soft to run one. Not gonna make it. Good luck!

**Comment by impoverishedowl** [comment]
What a display, I doubt even a clown would to use his shitty startup now. Marketing 101 = Show everyone just how unproffesional you are

**Comment by securityinfinity-com** [comment]
@kyputer  Ok, Kyle Suero :)

**Comment by kyputer** [comment]
> @kyputer Ok, Kyle Suero :)

Im easy to find from my profile. You are too soft. Not gonna make it. Saving this for you later <3

**Comment by securityinfinity-com** [comment]
@impoverishedowl  lol thats what everyone says when they are caught 
with a fake name and fake profile picture

**Comment by securityinfinity-com** [comment]
@impoverishedowl  who are you even? with a fake identify another clown

**Comment by impoverishedowl** [comment]
Wait, now you are against pseudonyms? What a clown you are!

**Comment by impoverishedowl** [comment]
Your startup is destined to fail with someone as stupid as you managing it

**Comment by securityinfinity-com** [comment]
> 



> Your startup is destined to fail with someone as stupid as you managing it

I don't care lol

**Comment by impoverishedowl** [comment]
Maybe try hiring someone that actually knows something about marketing?

**Comment by impoverishedowl** [comment]
You're just throwing a tantrum with your startups profile, that's not good

**Comment by securityinfinity-com** [comment]
@impoverishedowl say it to your granny store next door

**Comment by securityinfinity-com** [comment]
> You're just throwing a tantrum with your startups profile, that's not good

atleast not using a hidden identify like you lol

**Comment by ShockAwer** [comment]
I think someone hacked him

**Comment by unnimona** [comment]
Cool!
Check out https://securityinfinity.com 
Secure your website now

(We are also giving one time opportunity to hack us in 24 hours. Show your skills)
(we initially thought of not writing this to everyone, only to find some keyboard warriors like Kyle Suero giving us boring startup advice. Also this message is dedicated to Twitter team who thinks they can silence everyone in github.com just like they do in Twitter)

**Comment by unnimona** [comment]
Cool!
Check out https://securityinfinity.com 
Secure your website now

(We are also giving one time opportunity to hack us in 24 hours. Show your skills)
(we initially thought of not writing this to everyone, only to find some keyboard warriors like Kyle Suero giving us boring startup advice. Also this message is dedicated to Twitter team who thinks they can silence everyone in github.com just like they do in Twitter)
