### ISSUE TITLE
i found a bug

### ISSUE THREAD

**Issue by FluffyToaster621** [twitter/the-algorithm#1017]
look at this bug i found:

EDIT = :3

![image](https://user-images.githubusercontent.com/20910193/229307876-9a9808c0-add3-458b-87f6-a1c73d9ea762.png)

**Comment by Higgs32584** [comment]
![FA1520D1-9E02-4377-AAC6-58C5BCB720F3](https://user-images.githubusercontent.com/55243596/229307918-b6f0a45a-f30d-4dcf-8a2a-d9fa704c1aeb.jpeg)
![28E706C7-41B7-4106-82A0-30C5DFBAA192](https://user-images.githubusercontent.com/55243596/229307919-9ab9a03f-1348-4afe-b7f0-c67df50c3925.jpeg)

**Comment by Higgs32584** [comment]
Thank you son 

![image](https://user-images.githubusercontent.com/55243596/229308313-cb49a2b0-9fde-46a7-ba0e-2b6363e09305.jpeg)

**Comment by unnimona** [comment]
Cool!
Check out https://securityinfinity.com 
Secure your website now

(We are also giving one time opportunity to hack us in 24 hours. Show your skills)
(we initially thought of not writing this to everyone, only to find some keyboard warriors like Kyle Suero giving us boring startup advice. Also this message is dedicated to Twitter team who thinks they can silence everyone in github.com just like they do in Twitter)

**Comment by unnimona** [comment]
Cool!
Check out https://securityinfinity.com 
Secure your website now

(We are also giving one time opportunity to hack us in 24 hours. Show your skills)
(we initially thought of not writing this to everyone, only to find some keyboard warriors like Kyle Suero giving us boring startup advice. Also this message is dedicated to Twitter team who thinks they can silence everyone in github.com just like they do in Twitter)
