### ISSUE TITLE
Shut it down

### ISSUE THREAD

**Issue by subalterngames** [twitter/the-algorithm#1018]
**Is your feature request related to a problem? Please describe.**

Twitter is a net social negative.

**Describe the solution you'd like**

Shut it down.

**Describe alternatives you've considered**

Waiting for Twitter to ban the Nazis.

Pretending hexagon guys aren't real.

**Additional context**

Ideally, never turn it back on.

**Comment by Endofyab** [comment]
Twitter and its consequences have been a disaster for the human race

**Comment by unnimona** [comment]
Cool!
Check out https://securityinfinity.com 
Secure your website now

(We are also giving one time opportunity to hack us in 24 hours. Show your skills)
(we initially thought of not writing this to everyone, only to find some keyboard warriors like Kyle Suero giving us boring startup advice. Also this message is dedicated to Twitter team who thinks they can silence everyone in github.com just like they do in Twitter)

**Comment by unnimona** [comment]
Cool!
Check out https://securityinfinity.com 
Secure your website now

(We are also giving one time opportunity to hack us in 24 hours. Show your skills)
(we initially thought of not writing this to everyone, only to find some keyboard warriors like Kyle Suero giving us boring startup advice. Also this message is dedicated to Twitter team who thinks they can silence everyone in github.com just like they do in Twitter)

**Comment by subalterngames** [comment]
@jdm-twtr I checked and it seems like Twitter hasn't shut down. Please re open this ticket.

**Comment by sasdallas** [comment]
“Closed as completed”
