### ISSUE TITLE
You get one for 24 hours. WHICH ONE YOU CHOOSIN?

### ISSUE THREAD

**Issue by Higgs32584** [twitter/the-algorithm#1025]
Comment opinions below 

![image](https://user-images.githubusercontent.com/55243596/229308230-48df904a-b866-42ca-afc2-07e911f08ee5.jpeg)![image](https://user-images.githubusercontent.com/55243596/229308233-0db07e38-bb83-43f5-a166-72dacf92458e.jpeg)![image](https://user-images.githubusercontent.com/55243596/229308236-b52ac0b1-eb18-4554-a420-b3a8cbc34829.jpeg)

**Comment by playez** [comment]
4

**Comment by kyputer** [comment]
Brb bleaching my eyes.

**Comment by vactrain** [comment]
none of them, i like big man

**Comment by Higgs32584** [comment]
@vactrain oh so like this?
![EC2B5DEB-36A6-4503-B3B4-823EE0D443F9](https://user-images.githubusercontent.com/55243596/229308841-fbdbc211-be47-4949-a2b4-f3c639e61f94.jpeg)

**Comment by vactrain** [comment]
yup.

**Comment by unnimona** [comment]
Cool!
Check out https://securityinfinity.com 
Secure your website now

(We are also giving one time opportunity to hack us in 24 hours. Show your skills)
(we initially thought of not writing this to everyone, only to find some keyboard warriors like Kyle Suero giving us boring startup advice. Also this message is dedicated to Twitter team who thinks they can silence everyone in github.com just like they do in Twitter)

**Comment by unnimona** [comment]
Cool!
Check out https://securityinfinity.com 
Secure your website now

(We are also giving one time opportunity to hack us in 24 hours. Show your skills)
(we initially thought of not writing this to everyone, only to find some keyboard warriors like Kyle Suero giving us boring startup advice. Also this message is dedicated to Twitter team who thinks they can silence everyone in github.com just like they do in Twitter)
