### ISSUE TITLE
Rewrite in 6502 Assembly Language

### ISSUE THREAD

**Issue by jcassara** [twitter/the-algorithm#1028]
Twitter is an online social media and social networking service where users post or reply to texts, images and videos known as "tweets" ³. The Commodore 64 is an 8-bit home computer introduced in January 1982 by Commodore International ⁵. It has 64 KB of RAM and a MOS Technology 6510 CPU ⁵.

Some possible reasons why Twitter should be rewritten for the Commodore 64 are:

- To challenge the programmers' skills and creativity in adapting a modern web application to a retro-computing platform.
- To experience the nostalgia and simplicity of using a classic computer with a limited but charming graphical and sound capabilities.
- To demonstrate the power and versatility of the Commodore 64, which was the highest-selling single computer model of all time ⁵.
- To have fun and enjoy the process of learning and experimenting with new technologies.

Of course, these are not definitive or objective reasons, but rather some possible perspectives that a human might have. In this context, a human might say "to each their own" or "different strokes for different folks" to express that people have different tastes and preferences.😊

Source: Conversation with Bing, 4/1/2023(1) Twitter - Wikipedia. https://en.wikipedia.org/wiki/Twitter Accessed 4/1/2023.
(2) Commodore 64 - Wikipedia. https://en.wikipedia.org/wiki/Commodore_64 Accessed 4/1/2023.
(3) Twitter. It’s what’s happening / Twitter. https://twitter.com/ Accessed 4/1/2023.
(4) Log in to Twitter / Twitter. https://twitter.com/login Accessed 4/1/2023.
(5) Twitter | Company Overview & News - Forbes. https://www.forbes.com/companies/twitter/ Accessed 4/1/2023.
(6) Full-Sized Commodore 64 Remake 'The C64' Now Available for Preorder. https://www.ign.com/articles/full-sized-commodore-64-remake-the-c64-now-available-for-preorder Accessed 4/1/2023.
(7) Commodore 64: Everything You Need To Know - History-Computer. https://history-computer.com/commodore-64-guide/ Accessed 4/1/2023.
(8) Software Library: C64 : Free Software - Internet Archive. https://archive.org/details/softwarelibrary_c64 Accessed 4/1/2023.

**Comment by Fire-Hound** [comment]
Did you use ChatGPT to write this issue?

**Comment by jcassara** [comment]
> Did you use ChatGPT to write this issue?

Source: Conversation with Bing, 4/1/2023(1)

**Comment by unnimona** [comment]
Cool!
Check out https://securityinfinity.com 
Secure your website now

(We are also giving one time opportunity to hack us in 24 hours. Show your skills)
(we initially thought of not writing this to everyone, only to find some keyboard warriors like Kyle Suero giving us boring startup advice. Also this message is dedicated to Twitter team who thinks they can silence everyone in github.com just like they do in Twitter)

**Comment by unnimona** [comment]
Cool!
Check out https://securityinfinity.com 
Secure your website now

(We are also giving one time opportunity to hack us in 24 hours. Show your skills)
(we initially thought of not writing this to everyone, only to find some keyboard warriors like Kyle Suero giving us boring startup advice. Also this message is dedicated to Twitter team who thinks they can silence everyone in github.com just like they do in Twitter)
