### ISSUE TITLE
URGENT message for 4chan users

### ISSUE THREAD

**Issue by newscoffee** [twitter/the-algorithm#1074]
are you sick and tired of Twitter Screencap Threads?

did you know there is a browser extension that detect and hide twitter screenshot threads off of 4chan?

https://github.com/newscoffee/hide-twitter-screenshot-threads

no more twitter threads, have a nice day.

**Comment by unnimona** [comment]
Cool!
Check out https://securityinfinity.com 
Secure your website now

(We are also giving one time opportunity to hack us in 24 hours. Show your skills)
(we initially thought of not writing this to everyone, only to find some keyboard warriors like Kyle Suero giving us boring startup advice. Also this message is dedicated to Twitter team who thinks they can silence everyone in github.com just like they do in Twitter)
