### ISSUE TITLE
LGBTQ+ related terms being flagged as "sensitive content" when it isn't, including in DMs

### ISSUE THREAD

**Issue by logicP** [twitter/the-algorithm#1077]

**Comment by Foxlass** [comment]
Elon just can't stand queers

**Comment by logicP** [comment]
> Elon just can't stand queers

Of course he can't, he can't stand the idea of his own child being trans either

**Comment by w1redch4d** [comment]
lmao feels good

**Comment by pixiekat** [comment]
Elon's wife left him for Chelsea Manning and now he just hates gay people

**Comment by jacobrogers256** [comment]
Elon is a terrible human being overall. The Twitter algorithm release was a stopped clock moment for him.

**Comment by unnimona** [comment]
Cool!
Check out https://securityinfinity.com 
Secure your website now

(We are also giving one time opportunity to hack us in 24 hours. Show your skills)
(we initially thought of not writing this to everyone, only to find some keyboard warriors like Kyle Suero giving us boring startup advice. Also this message is dedicated to Twitter team who thinks they can silence everyone in github.com just like they do in Twitter)

**Comment by Foxlass** [comment]
> Cool! Check out https://securityinfinity.com Secure your website now
> 
> (We are also giving one time opportunity to hack us in 24 hours. Show your skills) (we initially thought of not writing this to everyone, only to find some keyboard warriors like Kyle Suero giving us boring startup advice. Also this message is dedicated to Twitter team who thinks they can silence everyone in github.com just like they do in Twitter)

**Comment by jdm-twtr** [comment]
This issue was closed due to lack of useful description.

**Comment by p0rkchop** [comment]
Imagine being the dev who knows their algo is gamed against LGBTQ but has to sit here and close out comments and bug reports pointing out what a bunch of shitheels they work for.
