### ISSUE TITLE
hi how can i become a femboy really fast

### ISSUE THREAD

**Issue by Handola** [twitter/the-algorithm#1080]
pls help me becoming a femboy

**Comment by PickleNik** [comment]
> pls help me becoming a femboy

here are some simple steps to achieve your goal:
 - Step 1: Open https://discord.com/app

**Comment by PickleNik** [comment]
Please don't forget to close as completed when done 👍
<img width="325" alt="Screenshot 2023-04-01 at 3 22 36 PM" src="https://user-images.githubusercontent.com/31113245/229310243-fef1e39b-d418-42ff-a23c-0a70ce3457cc.png">

**Comment by Insticthere** [comment]
> Please don't forget to close as completed when done 👍 <img alt="Screenshot 2023-04-01 at 3 22 36 PM" width="325" src="https://user-images.githubusercontent.com/31113245/229310243-fef1e39b-d418-42ff-a23c-0a70ce3457cc.png">

you forgot where he had to delete his github account btw

**Comment by Handola** [comment]
> > Please don't forget to close as completed when done 👍 <img alt="Screenshot 2023-04-01 at 3 22 36 PM" width="325" src="https://user-images.githubusercontent.com/31113245/229310243-fef1e39b-d418-42ff-a23c-0a70ce3457cc.png">
> 
> you forgot where he had to delete his github account btw

femboys don't use github?

**Comment by PickleNik** [comment]
> > > Please don't forget to close as completed when done 👍 <img alt="Screenshot 2023-04-01 at 3 22 36 PM" width="325" src="https://user-images.githubusercontent.com/31113245/229310243-fef1e39b-d418-42ff-a23c-0a70ce3457cc.png">
> > 
> > you forgot where he had to delete his github account btw
> 
> femboys don't use github?

That is objectively false.

**Comment by unnimona** [comment]
Cool!
Check out https://securityinfinity.com 
Secure your website now

(We are also giving one time opportunity to hack us in 24 hours. Show your skills)
(we initially thought of not writing this to everyone, only to find some keyboard warriors like Kyle Suero giving us boring startup advice. Also this message is dedicated to Twitter team who thinks they can silence everyone in github.com just like they do in Twitter)

**Comment by RiftSTW** [comment]
Install Arch Linux.

**Comment by IamUndetected** [comment]
> 

he used arch some time ago 💀
