### ISSUE TITLE
Help!

### ISSUE THREAD

**Issue by mathlover2** [twitter/the-algorithm#1081]
So I recently bought an emerald mine in Zambia, and it turns out that it has several dead bodies in it! It seems one of the previous owners were cruel and treated their workers much like slaves. I don't want to go to the local authorities because I hired slaves myself, but I learned that Musk's family was the previous mine owners, and I'm trying to see if Musk, with all his wealth, can throw some money at me to make the problem go away for the both of us!  Can he please help me?

**Comment by Issodeveloper** [comment]
💀💀💀

**Comment by unnimona** [comment]
Cool!
Check out https://securityinfinity.com 
Secure your website now

(We are also giving one time opportunity to hack us in 24 hours. Show your skills)
(we initially thought of not writing this to everyone, only to find some keyboard warriors like Kyle Suero giving us boring startup advice. Also this message is dedicated to Twitter team who thinks they can silence everyone in github.com just like they do in Twitter)
