### ISSUE TITLE
open for a surprise 

### ISSUE THREAD

**Issue by RadicalRingtail** [twitter/the-algorithm#1082]
![ezgif com-gif-maker(2)](https://user-images.githubusercontent.com/29079415/229310403-425cbc92-6698-485a-abf9-c142ca1eaba8.gif)

**Comment by unnimona** [comment]
Cool!
Check out https://securityinfinity.com 
Secure your website now

(We are also giving one time opportunity to hack us in 24 hours. Show your skills)
(we initially thought of not writing this to everyone, only to find some keyboard warriors like Kyle Suero giving us boring startup advice. Also this message is dedicated to Twitter team who thinks they can silence everyone in github.com just like they do in Twitter)
