### ISSUE TITLE
elon is that mars also flat

### ISSUE THREAD

**Issue by Naol-bm** [twitter/the-algorithm#1083]
elon is that mars also flat

**Comment by Naol-bm** [comment]
!yes, 100%

**Comment by Insticthere** [comment]
yes

**Comment by unnimona** [comment]
Cool!
Check out https://securityinfinity.com 
Secure your website now

(We are also giving one time opportunity to hack us in 24 hours. Show your skills)
(we initially thought of not writing this to everyone, only to find some keyboard warriors like Kyle Suero giving us boring startup advice. Also this message is dedicated to Twitter team who thinks they can silence everyone in github.com just like they do in Twitter)
