### ISSUE TITLE
allow "AI" to tweet and like tweets on your behalf

### ISSUE THREAD

**Issue by fanfare** [twitter/the-algorithm#109]
if you have made a lot of tweets, twitter should have a firm understanding of you as a person by now. naturally, the next step would be a feature which allows "AI" to automatically creates tweets on your behalf -- tweeting what you _would_ have said, and liking tweets that you _would_ have liked. that way, you can just check in and see your virtual "self" tweeting on auto pilot, and nonetheless experience the pleasure of seeing people liking "your" posts. i imagine this is going to be implemented sooner or later by a third party so many as well implement it in-house to have more fine-tuned control over the experience.

**Comment by enzo-js** [comment]
fuck off

**Comment by ShockAwer** [comment]
LOL

**Comment by bcentner** [comment]
This is already possible using twitter's api. In fact, its been possible for over 10 years. Look into using tweepy for ease.

**Comment by zubyCharles** [comment]
What could possibly go wrong? Do you know that today's AI are just language models and aren't really sentient?

**Comment by chapainaashish** [comment]
> if you have made a lot of tweets, twitter should have a firm understanding of you as a person by now. naturally, the next step would be a feature which allows "AI" to automatically creates tweets on your behalf -- tweeting what you _would_ have said, and liking tweets that you _would_ have liked. that way, you can just check in and see your virtual "self" tweeting on auto pilot, and nonetheless experience the pleasure of seeing people liking "your" posts. i imagine this is going to be implemented sooner or later by a third party so many as well implement it in-house to have more fine-tuned control over the experience.

say no to AI

**Comment by jdm-twtr** [comment]
Thanks for filing. We've marked this issue as an unrelated bug or feature for future review.
                    In order to keep our issue count manageable, we will not be leaving these issues open. We apologize for
                    the inconvenience. If you feel that we closed your issue in error, please re-file the issue, stating how
                    the requested feature applies to the recommendation algorithm components that have been open-sourced thus far.
