### ISSUE TITLE
dam, sux2bu

### ISSUE THREAD

**Issue by TruncatedDinosour** [twitter/the-algorithm#1134]
i think this whole repo is nothing more than a cringeworthy
corporate stunt, a joke may i say, to just seem cool and hip and to be like one
of the cool kids or some shit, like nvidia, they dumped
half a mil lines of code in a single commit, twitter has been
proprietary for ages and doesnt know how to foss

they just want free fixes and shit from people he doesnt
have to pay or anything or maybe the fact that open sourcing
will maybe make some people trust twitter more but it only
uncovered how much bs it has been doing for this long,
how much information it has been collecting and shit,
how much bias it has, just a lot and i mean a lot of bs,
from seeing this you can only imagine what the proprietary
parts do

i dont fucking understand this, why do companies do this
shit, it wont help you recover from piles of shit when you
just release plain source code ( no documentation, no commit
history, nothing, barely a readme even ), literally just
another corporate scheme to make people sold into your shithole,
especially twitter, which feeds off users' toxicity and will
continue feeding shit to make toxic shit thrive

anyway, !! elon add tina #871 !!

**Comment by TruncatedDinosour** [comment]
( i only changed the title to get more attention bc im an attention seeking whore, jk, but still )

**Comment by errorware** [comment]
![my_code_sucks](https://user-images.githubusercontent.com/22510253/229314298-0aee4bad-a657-48fa-b690-29ee06fd204b.gif)

**Comment by TruncatedDinosour** [comment]
yeah what did i expect lol 🤡
