### ISSUE TITLE
Moderation for GitHub Issues

### ISSUE THREAD

**Issue by georg-stone** [twitter/the-algorithm#11349]
**Is your feature request related to a problem? Please describe.**
Yes, there is too much malware being promoted through this repo's Issues tab.

**Describe the solution you'd like**
Proper moderation. And many of these bots post multiple ads, so you could ban them.

Another potential solution is to turn off all Issues completely.

**Describe alternatives you've considered**
It's out of my power.
**Additional context**

**Comment by Exponential-Workload** [comment]
closed as not planned LMAOOOOO

**Comment by RetronicsYT** [comment]
nerd
