### ISSUE TITLE
Algorithm includes politically biased Scala hierarchy for candidates

### ISSUE THREAD

**Issue by regginator** [twitter/the-algorithm#121]
Should this be changed for the FOSS algorithm? Asking for a friend.

```scala
    (
      "author_is_elon",
      candidate =>
        candidate
          .getOrElse(AuthorIdFeature, None).contains(candidate.getOrElse(DDGStatsElonFeature, 0L))),
    (
      "author_is_power_user",
      candidate =>
        candidate
          .getOrElse(AuthorIdFeature, None)
          .exists(candidate.getOrElse(DDGStatsVitsFeature, Set.empty[Long]).contains)),
    (
      "author_is_democrat",
      candidate =>
        candidate
          .getOrElse(AuthorIdFeature, None)
          .exists(candidate.getOrElse(DDGStatsDemocratsFeature, Set.empty[Long]).contains)),
    (
      "author_is_republican",
      candidate =>
        candidate
          .getOrElse(AuthorIdFeature, None)
          .exists(candidate.getOrElse(DDGStatsRepublicansFeature, Set.empty[Long]).contains)),
  )
```

Refer: https://github.com/twitter/the-algorithm/blob/7f90d0ca342b928b479b512ec51ac2c3821f5922/home-mixer/server/src/main/scala/com/twitter/home_mixer/functional_component/decorator/HomeTweetTypePredicates.scala#L225

**Comment by edoardottt** [comment]
wtf... seriously ????

**Comment by enzo-js** [comment]
No. Working as intended.

**Comment by bluepilledgreat** [comment]
#138 fixes this issue

**Comment by GodlyGH** [comment]
elon can suck my dick and balls

**Comment by edoardottt** [comment]
saved https://web.archive.org/web/20230331191723/https://github.com/twitter/the-algorithm/issues/121

**Comment by znwhite** [comment]
> elon can suck my dick and balls

Agreed.

**Comment by PeasfulTown** [comment]
This is billionaire favoritism, please fix.

**Comment by iDroidGuy** [comment]
Elon confirmed in a Space that this wasn't known by him. Engineers then stated it was for stat tracking. Elon stated it will be removed. https://twitter.com/i/spaces/1jMJgLdenVjxL

**Comment by AbdelAzizMohamedMousa** [comment]
based on the code snippet provided, it appears to be written in Scala and defines four feature extraction functions that depend on certain keys being present in the input data dictionary.

If the goal is to make this code more amenable to the Free and Open Source Software (FOSS) community, there are several areas that could be improved upon. One suggestion would be to refactor the code to make it more modular, reusable, and easily extensible. This could be achieved by breaking down the feature extraction functions into smaller, more granular functions and using data structures that are more amenable to functional programming paradigms. Additionally, comments and documentation should be added to the code to help potential contributors understand the code's purpose, how it works, and how they can contribute.

Another suggestion would be to replace any proprietary libraries or tools that may be used in the current implementation with open-source alternatives. This would make it easier for contributors to set up and run the code on their own machines without having to worry about licensing issues or proprietary dependencies. Furthermore, it would align the project more closely with the FOSS ethos and values.

Overall, the decision to change the code snippet provided for a FOSS algorithm would depend on the specific goals and objectives of the project, as well as the technical and community considerations involved.

**Comment by PrimalZed** [comment]
Comment here says it's to ensure changes don't "negatively impact one group over others":
https://github.com/twitter/the-algorithm/blob/7f90d0ca342b928b479b512ec51ac2c3821f5922/home-mixer/server/src/main/scala/com/twitter/home_mixer/functional_component/feature_hydrator/RequestQueryFeatureHydrator.scala#L86-L95

**Comment by htmyname** [comment]
![image](https://user-images.githubusercontent.com/33270133/229280865-8b9fb898-952c-4f03-ab85-85a022664bb7.png)

**Comment by gumbarros** [comment]
Nobody outside of USA cares about Democrats and Republicans

**Comment by quenbyako** [comment]
You gotta be kidding... April 1st maybe? I can't believe tbh

**Comment by regginator** [comment]
> ![image](https://user-images.githubusercontent.com/33270133/229280865-8b9fb898-952c-4f03-ab85-85a022664bb7.png)
> 
> 

The repository was force updated yesterday. https://github.com/twitter/the-algorithm/commit/ec83d01dcaebf369444d75ed04b3625a0a645eb9

**Comment by dagelf** [comment]
That part does seem like an April Fools joke, but I do hope that the repo isn't. Like it was, last year... https://news.ycombinator.com/item?id=31160546

**Comment by nathan815** [comment]
> based on the code snippet provided, it appears to be written in Scala and defines four feature extraction functions that depend on certain keys being present in the input data dictionary.
> 
> 
> 
> If the goal is to make this code more amenable to the Free and Open Source Software (FOSS) community, there are several areas that could be improved upon. One suggestion would be to refactor the code to make it more modular, reusable, and easily extensible. This could be achieved by breaking down the feature extraction functions into smaller, more granular functions and using data structures that are more amenable to functional programming paradigms. Additionally, comments and documentation should be added to the code to help potential contributors understand the code's purpose, how it works, and how they can contribute.
> 
> 
> 
> Another suggestion would be to replace any proprietary libraries or tools that may be used in the current implementation with open-source alternatives. This would make it easier for contributors to set up and run the code on their own machines without having to worry about licensing issues or proprietary dependencies. Furthermore, it would align the project more closely with the FOSS ethos and values.
> 
> 
> 
> Overall, the decision to change the code snippet provided for a FOSS algorithm would depend on the specific goals and objectives of the project, as well as the technical and community considerations involved.

ok, GPT

**Comment by dav1312** [comment]
> saved [web.archive.org/web/20230331191723/https://github.com/twitter/the-algorithm/issues/121](https://web.archive.org/web/20230331191723/https://github.com/twitter/the-algorithm/issues/121)

Someone doesn't know how git works...

**Comment by Laim** [comment]
> > saved [web.archive.org/web/20230331191723/https://github.com/twitter/the-algorithm/issues/121](https://web.archive.org/web/20230331191723/https://github.com/twitter/the-algorithm/issues/121)
> 
> Someone doesn't know how git works...

They did a force new initial commit yesterday to remove personal data from it, so they could easily do it with other things.  No harm in having a wee web archive of things found.

**Comment by edoardottt** [comment]
> > saved [web.archive.org/web/20230331191723/https://github.com/twitter/the-algorithm/issues/121](https://web.archive.org/web/20230331191723/https://github.com/twitter/the-algorithm/issues/121)
> 
> Someone doesn't know how git works...

it's a web snapshot, git isn't even involved

**Comment by Mattis142** [comment]
> Comment here says it's to ensure changes don't "negatively impact one group over others":
> 
> https://github.com/twitter/the-algorithm/blob/7f90d0ca342b928b479b512ec51ac2c3821f5922/home-mixer/server/src/main/scala/com/twitter/home_mixer/functional_component/feature_hydrator/RequestQueryFeatureHydrator.scala#L86-L95

they shouldn't even messure political opinion in the first place

**Comment by dagelf** [comment]
@Mattis142 How can they measure if their choice of algorithm is biased or not? An unbiased algorithm is surely better?

**Comment by Alhadis** [comment]
> Someone doesn't know how git works...

GitHub issues aren't tracked by version control, and organisation owners can even delete them at their whim (something that a thin-skinned manchild like Elon Musk is likely to do). Speaking of web snapshots… say cheese! I'm about to take a new one. (**EDIT:** [Done!](https://web.archive.org/web/20230913003127/https://github.com/twitter/the-algorithm/issues/121))
