### ISSUE TITLE
 Add tipping feature using Shiba Inu tokens for dank memes and good/based takes

### ISSUE THREAD

**Issue by philipdaquin** [twitter/the-algorithm#1287]
**Is your feature request related to a problem? Please describe.**
This PR adds a new tipping feature to the project that allows users to tip each other using Shiba Inu tokens for posting dank memes or good/based takes. Shiba Inu tokens have gained significant popularity in recent months and adding support for it will provide users with another way to utilize their tokens and promote community engagement.

**Describe the solution you'd like**
To add the tipping feature using Shiba Inu tokens, the following changes have been made:

- Added a new "Tip with Shiba Inu" button to each post for users to click and enter the amount of tokens they want to tip
- Created a new "Shiba Inu Tip Jar" feature that allows users to see their Shiba Inu tips received and total earnings
- Implemented a new algorithm that calculates the tip amount based on the popularity of the post, the number of upvotes, and the time since posting
- Updated the project's documentation to include information on how to use Shiba Inu tokens for tips.

**Describe alternatives you've considered**
Other alternative payment options were considered, such as Bitcoin and Ethereum. However, Shiba Coin was chosen as it has gained significant popularity in recent months and is quickly becoming a preferred cryptocurrency for many users.

**Additional context**
Adding support for tipping using Shiba Inu tokens will provide users with another way to utilize their tokens and promote community engagement.

Thank you for considering this feature request! 🤣

**Comment by royeradames** [comment]
Adding tips would be interesting. Twitter can collect key from sender and receiver and start the coin exchange. It can give a financial incentive to Twitter
