### ISSUE TITLE
This issue was posted from a strip club

### ISSUE THREAD

**Issue by errorware** [twitter/the-algorithm#1327]
Believe it or not.

**Comment by jjmonteiro** [comment]
Send confirmation nudes

**Comment by Higgs32584** [comment]
Would you throw money on this girl

![image](https://user-images.githubusercontent.com/55243596/229323658-795bbc4e-7e25-4dbf-818a-85d178fa0b77.jpeg)

**Comment by errorware** [comment]
> Send confirmation nudes

You must be joking.... strip clubs are like the sistine chapel.... NO PICS ALLOWED!!!

**Comment by mateusmlo** [comment]
this n-word browsing github @ the club and scaring the hoes smh

**Comment by mateusmlo** [comment]
not fixed
