### ISSUE TITLE
Important feature

### ISSUE THREAD

**Issue by Foxlass** [twitter/the-algorithm#1338]
@jdm-twtr is SILENCING IMPORTANT ISSUES!!!! Two of my VERY IMPORTANT ISSUES have been DELETED. I WILL NOT STAND FOR THIS OPPRESSION!

**Comment by RottenSchnitzel** [comment]
this is not what free software stands for!!

**Comment by jdm-twtr** [comment]
Closing due to issue being off-topic. Please re-file as a bug or feature request directed toward the Twitter Recommendation Algorithm. 

Please note that repeated issue creation may result in a temporary or permanent block.
