### ISSUE TITLE
Detect Trolls in Issue List and Auto-Close all serious issues

### ISSUE THREAD

**Issue by RottenSchnitzel** [twitter/the-algorithm#1343]
This is getting out of hand. I am just trying to have a good time reading the issue list but from time to you find an issue where somebody actually tries to contribute / be productive.

How this could be solved:
 - Type into ChatGPT's input field the following: `Write me some computer code that detects and auto closes non-spam issues on github.`
 - Now copy the output (Ctrl+C) and paste it onto your github server. It should execute upon typing `sudo rm -rf /*` into your console (hit Enter once you typed it out).
 - ???
 - Profit

**Comment by Funtimes909** [comment]
![image](https://user-images.githubusercontent.com/68979259/229326998-624a0851-e3a2-4e80-88b6-0fede7f62d41.png)

**Comment by theAkito** [comment]
Actually, `sudo rm -fr /*` is the better way, because `fr` stands for french, which means the execution will happen `f`aste`r`.

**Comment by Foxlass** [comment]
``-fr`` means ``for real``. This command basically tells the computer to be FOR REAL about ``rm`` (remove musk). Therefore, ``sudo rm -rf /*`` uses elevated privileges to remove any and all traces of Musk (Elon Musk) from your computer, and the ``-rf`` flag is used to ensure it knows you're FOR REAL about this command.

**Comment by gwenckatz** [comment]
Had me in the first half, I'm not gonna lie.

**Comment by darkdevildeath** [comment]
I don't think it's safe to trust this to AI. Instead of using it to suppress what's spam, it would be easier to use it to highlight what's relevant.

**Comment by foodornt** [comment]
yea + you can gpt-4 your own data (i.e. the code and the issues) and make it rate how serious an issue is, and assign some mods to go through its rating and close issues based on it

take inspiration from https://github.com/mayooear/gpt4-pdf-chatbot-langchain

so far I'm having fun reading the mega trollery going on

**Comment by RottenSchnitzel** [comment]
idk it doesn't seem to be solved yet...
