### ISSUE TITLE
language selection

### ISSUE THREAD

**Issue by m-a-sch** [twitter/the-algorithm#1345]
**Describe the bug**
your advertisers do not advertise in the language of the user

**To Reproduce**
1. Go to 'Switzerland'
2. Click on 'anything'
3. Scroll down to 'an ad that is in German instead of French or English'

**Expected behavior**
Only ads in the language spoken by the user should be shown

**Comment by jdm-twtr** [comment]
Thanks for filing. We've marked this issue as an unrelated bug or feature for future review.
                    In order to keep our issue count manageable, we will not be leaving these issues open. We apologize for
                    the inconvenience. If you feel that we closed your issue in error, please re-file the issue, stating how
                    the requested feature applies to the recommendation algorithm components that have been open-sourced thus far.
