### ISSUE TITLE
Elaborate April Fools prank?

### ISSUE THREAD

**Issue by user670** [twitter/the-algorithm#1346]
Hi. Someone shared a screenshot of this repo and said something like "the twitter recommendation algorithm is hard-coded to boost Elon Musk tweets", but considering this repo's timeline (first commit and first issues/PRs are all on April Fools) as well as the weird naming of the repo, I'm suspecting this repo is an elaborate April Fools prank. Can anyone comfirm whether this is a prank? Thanks!

**Comment by sashakoshka** [comment]
yeah i invented twitter its a prank

**Comment by Fire-Hound** [comment]
Doesn't seem like an April fool's joke. 
By the way, the Elon Musk code was supposedly to "track" his metrics but who knows what it is used for lol.

**Comment by Rono0365** [comment]
am also suspecting the same

**Comment by DavidRConnell** [comment]
The first commit being today means they took the current state of the algorithm and moved it to a new git repo, which they published here. This removes the history of the project, giving them the ability to modify the code from what is actually used, to show the public a version without anything they don't want us to see. If there was a history we could see recent commits that modified aspects of the algorithm. (This also means if there was anything sketchy being done in the past there is no evidence of it here.)

As far as if this is an April fools prank: they published the code then immediately made another commit that removed code that would be used to boost the popularity of Musk's tweets. By making a commit they pull attention to something controversial. This seems to be too perfect. So yes, that aspect is likely a prank. Again, for the above reasons, they could have easily added the `author_is_elon` code to the repo before submitting it without it actually being apart of the code running on their servers.

And for whether it boosts Elon's tweets? There is code was code file `home-mixer/server/src/main/scala/com/twitter/home_mixer/functional_component/decorator/HomeTweetTypePredicates.scala` removed by #ec83d01 that added `author_is_elon` to the feature vector that the "for you" recommendation model used. This means the per user model would be trained with knowledge of whether the a tweet was authored by Elon. The models predict how likely an individual is to interact with a given tweet. By incorporating the `author_is_elon` predicate into the feature vector, they can ensure all Elon's tweets are sent to the feeds of those likely to interact with it, making sure his tweets get a lot of attention.

**Comment by theAkito** [comment]
Considering Twitter itself has become an April Fool's Joke, this publication seems probably too serious, already. 😉

I would also recommend everyone to independently clone **and** mirror this repository for the sake of having decentralised backups of it. The next time the grand master of disaster has a hiccup, this repository might get just deleted, including all its forks on Github.
