### ISSUE TITLE
Algorithm inappropriately hiding updog tweets

### ISSUE THREAD

**Issue by gwenckatz** [twitter/the-algorithm#1352]
**Describe the bug**
Tweets containing updog are hidden from followers

**To Reproduce**
1. Type a tweet that features updog
2. Send tweet
3. View timeline on another account following the updog account
4. Tweet is not visible

**Expected behavior**
Updog-containing tweets should display on the timeline. In fact, updog content should be promoted by the algorithm. Twitter engagement would increase appreciably if it had more updog.

**Environment**
Windows 11 and Google Chrome

**Additional context**
It seems probable that the Twitter team is not familiar with updog and therefore did not anticipate this problem.

**Comment by jdm-twtr** [comment]
What's updog?

**Comment by jdm-twtr** [comment]
:)
