### ISSUE TITLE
Introduce Mpesa as a means of payment on Twitter Blue for Kenyans

### ISSUE THREAD

**Issue by Rono0365** [twitter/the-algorithm#1357]
Since  Twitter blue has gone global could you guys work on integrating it with local payment services especially in Africa  .Mpesa is a great payment service used by almost all Kenyans with an easy to integrate api. will massively increase your revenue

**Comment by Rono0365** [comment]
[https://www.youtube.com/watch?v=Xy9qnItAfcU](url)
here's a great tutorial video on integration and usage of Mpesa api (daraja api)
[https://m.facebook.com/survtechKE/videos/daraja-api-obtaining-the-access-token-tutorial/2398918083664544/](url)
how to obtain Token
[https://developer.safaricom.co.ke/Documentation](url)
general documentation for Mpesa api

**Comment by 3mpj** [comment]
Mpesa app's global pay sorts this out

**Comment by Rono0365** [comment]
check this out .
[https://www.tuko.co.ke/facts-lifehacks/guides/495506-how-pay-spotify-m-pesa-kenya-phone-easily/#:~:text=Open%20the%20Spotify%20website%20on%20your%20browser.,Pesa%20as%20your%20payment%20option.](url)
like Spotify

> Mpesa app's global pay sorts this out

check this out .
[https://www.tuko.co.ke/facts-lifehacks/guides/495506-how-pay-spotify-m-pesa-kenya-phone-easily/#:~:text=Open%20the%20Spotify%20website%20on%20your%20browser.,Pesa%20as%20your%20payment%20option.](url)
like Spotify

**Comment by jdm-twtr** [comment]
Thanks for filing. We've marked this issue as an unrelated bug or feature for future review.
                    In order to keep our issue count manageable, we will not be leaving these issues open. We apologize for
                    the inconvenience. If you feel that we closed your issue in error, please re-file the issue, stating how
                    the requested feature applies to the recommendation algorithm components that have been open-sourced thus far.
