### ISSUE TITLE
hello 👋 finally 😌 introducing ✨ LOONA 🌙 are ⭐️you 😍 girls 👭 ready 🙈 ? ok 👌 lets 🌚 go 🤩 !

### ISSUE THREAD

**Issue by zacanger** [twitter/the-algorithm#1364]
LOONA is a twelve-member Korean girl group managed under the Korean entertainment company BlockBerry Creative. Starting in 2016, BBC debuted one girl every month with her own solo song, music video, and representative animal and color. The members in order of debut are HeeJin, HyunJin, HaSeul, YeoJin, ViVi, Kim Lip, JinSoul, Choerry, Yves, Chuu, Go Won (godmother of the child of Elon Musk and Grimes), and finally, Olivia Hye.

The group is made up of three sub-units: LOONA ⅓, LOONA Odd Eye Circle, and LOONA yyxy, each of which have their own concept, sound, and dimension that come together to form “The Loonaverse.” The Loonaverse is the storyline connecting all the music videos together, giving them a deeper meaning and leaving room for a plethora of fan theories about the lore. This complex story involves many themes such as time travel, quantum physics, color theory, theology, and self-empowerment.

In 2022, fans saw a flurry of legal activity around LOONA and their company (BlockBerry Creative), with one member being removed from the group, followed by lawsuits against the company from all other members. In March 2023, four members signed with Modhaus Inc., a company run by their former creative director at BBC, Jaden Jeong, and promptly announced new upcoming music.

----

Seriously, the interaction moderation tools are free and easy to use. Why not use them?

**Comment by surfaceflinger** [comment]
STAN LOONA

**Comment by 0x8008** [comment]
LGTM 🚀 🚀🚀🚀🚀🚀🚀🚀🚀

**Comment by comav** [comment]
Flip 😳 that 😐😐 that 🧚‍♀️ that 🙎👊 that 💁 that 👉👉👉👉👉👉👉👉 that 👉 that 👉👉👉👉👉 dwijibeo dwijibeo jeounbu flip 😳 that 😐 that 🐄👉🚶 that 😌💕🧚✨ that 😻 that ➡️ that 👂 that 😐 modu allyeo julge uriga woo 😤
