### ISSUE TITLE
Tweets disappearing

### ISSUE THREAD

**Issue by Karthikvenugopal** [twitter/the-algorithm#1372]
**Describe the bug**
As I scroll down the feed, there are a few tweets which randomly disappear. They reappear further down.
But it's kinda irritating that I'll be reading it and it suddenly disappears.

**To Reproduce**
Just keep scrolling. There's no exact way to reproduce.

**Expected behavior**
The tweets don't disappear.

**Environment**
Mobile - OnePlus 7T, Android 12

**Comment by ValZapod** [comment]
>As I scroll down the feed, there are a few tweets which randomly disappear. They reappear further down.

Nope. Usually they do not reappear. Cause they got deleted.

**Comment by jdm-twtr** [comment]
Thanks for filing. We've marked this issue as an unrelated bug or feature for future review.
                    In order to keep our issue count manageable, we will not be leaving these issues open. We apologize for
                    the inconvenience. If you feel that we closed your issue in error, please re-file the issue, stating how
                    the requested feature applies to the recommendation algorithm components that have been open-sourced thus far.
