### ISSUE TITLE
Bug Report on Parasite Infestation

### ISSUE THREAD

**Issue by datgreatkhan** [twitter/the-algorithm#1373]
**Describe the bug**
Elon Musk - the parasite that has infested this organization known as Twitter, and a good percentage of other organizations.

**To Reproduce**
1. Go to Twitter page of Elon Musk and/or news regarding him
2. View any of his tweets or recent doings
3. Realize that he (the parasite) is a narcissistic and incompetent manchild.

**Expected behavior**
A multi-billionaire that has a clear mind and knows how to run things properly without his massive ego getting in the way.

**Screenshot of the problem**
![image](https://user-images.githubusercontent.com/129341569/229330668-ec16dac2-44a0-4abe-913f-e5f3de3de343.png)

**Environment**
Twitter. Or even better - the world. He wanted to go to Mars, no? 

**Additional context**
None needed. A parasite is quite easy to spot out and get rid of.

**Comment by Protofall** [comment]
Ironic given how there would be no public repo to post issues on if we still had the old Twitter

**Comment by delgh1** [comment]
LGTM

**Comment by datgreatkhan** [comment]
> Ironic given how there would be no public repo to post issues on if we still had the old Twitter

Not ironic considering public opinion can be conveyed anywhere regardless of it being "new Twitter" or "old Twitter".

Whether it be on Twitter, on the news, or on the official Twitter FY algorithm repository. If you're an incompetent and ignorant buffoon like Mr. Musk and put yourself in front of the world with your massive ego, you best bet you'll be grilled for it.

**Comment by jdm-twtr** [comment]
This issue was closed due to one of these reasons: likelihood of spam, not enough context, or possibly inappropriate content. Please re-file with a useful title and description.
