### ISSUE TITLE
add gay sex

### ISSUE THREAD

**Issue by OoferBOOFER** [twitter/the-algorithm#1375]
i think it'd be really cool if you added gay sex, it'd be really funny

**Comment by syaomix** [comment]
SAY
GEX!

**Comment by mrepol742** [comment]
I AgRee!

**Comment by aditya-2403** [comment]
interesting

**Comment by delgh1** [comment]
LGTM, sounds gay, I'm in

**Comment by Joshument** [comment]
I think it would be beneficial if we added a gay sex tweet boosting feature to the algorithm to accomplish this.

**Comment by essesoul** [comment]
what about anime trap 🤣🤣🤣

**Comment by shrutigitte** [comment]
my friend needs this

**Comment by h3llo-wor1d** [comment]
LGTM, merge asap

**Comment by SharanSMenon** [comment]
We should have a Elon musk gay sex button.

**Comment by jdm-twtr** [comment]
This issue was closed due to one of these reasons: likelihood of spam, not enough context, or possibly inappropriate content. Please re-file with a useful title and description.

**Comment by OoferBOOFER** [comment]
you suck

**Comment by OoferBOOFER** [comment]
this "jdm-twtr" guy really stinks lets throw him into the pits of holy flame
