### ISSUE TITLE
There aren't enough funny issues

### ISSUE THREAD

**Issue by PFreemind** [twitter/the-algorithm#1379]
I was hoping this would be funnier, this is all you got, internet?

**Additional context**

**Comment by Foxlass** [comment]
The funny ones keep being censored

**Comment by delgh1** [comment]
twitter's github account should be terminated

**Comment by delgh1** [comment]
My issues keep being deleted

**Comment by Marioood** [comment]
literally 1984

**Comment by PFreemind** [comment]
Literally literally
