### ISSUE TITLE
elons strategy

### ISSUE THREAD

**Issue by swingcake** [twitter/the-algorithm#1391]
he buy twtr, fire devs, open-source code, gets code fixed (and improved) for free

**Comment by 0xManjeet** [comment]
> he buy twtr, fire devs, open-source code, gets code fixed (and improved) for free

Yup, he's a genius. He's selling free speech in 8 dollars.

**Comment by nobodyindustries** [comment]
That's why we should not call this open source.

**Comment by dagelf** [comment]
Your strategy: make even more work for the devs that are left by spamming their issue tracker with your opinions. Your comments are based on the assumption that the world revolves around money. Newsflash: 20% of the world population live happily without any money. Newsflash: even Musk can't have better things than you, like phone, internet, relationships. In fact, you probably have more free time.

**Comment by Foxlass** [comment]
> Your strategy: make even more work for the devs that are left by spamming their issue tracker with your opinions. Your comments are based on the assumption that the world revolves around money. Newsflash: 20% of the world population live happily without any money. Newsflash: even Musk can't have better things than you, like phone, internet, relationships. In fact, you probably have more free time.

How does Elon's dick feel

**Comment by GammaSoul** [comment]
Except any self respecting developer worth there salt to actually work on this will look at it and say 

"Aint Nobody Got Time For Tha!!!!!!"

**Comment by swingcake** [comment]
> Your strategy: make even more work for the devs that are left by spamming their issue tracker with your opinions. Your comments are based on the assumption that the world revolves around money. Newsflash: 20% of the world population live happily without any money. Newsflash: even Musk can't have better things than you, like phone, internet, relationships. In fact, you probably have more free time. 

![20230402_225301.jpg](https://user-images.githubusercontent.com/32037820/229368744-08c451e5-4752-454f-8261-df2d02793049.jpg)

**Comment by sashakoshka** [comment]
> Your strategy: make even more work for the devs that are left by spamming their issue tracker with your opinions. Your comments are based on the assumption that the world revolves around money. Newsflash: 20% of the world population live happily without any money. Newsflash: even Musk can't have better things than you, like phone, internet, relationships. In fact, you probably have more free time. 

wake up babe new copypasta dropped
