### ISSUE TITLE
Major Issue

### ISSUE THREAD

**Issue by ydfdas1f546g1df** [twitter/the-algorithm#1396]
[thunder rumbling]

- [phone ringing]
- [chattering]

[bell dings]

John Wick, Excommunicado.

In effect, 6:00 p.m.,
Eastern Standard Time.

[chattering]

I do hope that Mr. Wick
finds his way to safety.

He knew the rules, he broke them.

He killed a man
on company grounds, Charon.

Do you expect him to make it out?

Fourteen-million-dollar bounty
on his head.

Every interested party in this city
wants a piece of it.

I'd say the odds are about even.

[thunder rumbling]

[men chattering]

[man] You think the hospital's there to
help, man?

- [bottles clattering]
- [laughing] No way!

They'll kill you
just as soon as they'll make you better.

[laughs] But I know better, man.
I know better. I know what I'm...

Tick tock, Mr. Wick. Tick tock.

Tick tock. Tick tock. Tick... [laughs]

No time to dilly-dally, Mr. Wick!

[horns honking]

The New York Public Library.

You got it.

[horns blaring]

[horns continue blaring]

Change of plan.

To the Continental.

Can you see that he's received
by the concierge?

Yes, sir, Mr. Wick.

Good dog. Good dog.

[horns continue blaring]

John Wick, Excommunicado.
In effect, 20 minutes.

[a cappella singers singing]

[John panting]

Can I help you?

Russian Folktale. Alexander Afanasyev.

[speaking Russian]

1864.

- Level two.
- Thank you.

[thunder rumbling]

[man] "Consider your origins.

You were not made to live as brutes,
but to follow virtue and knowledge."

Dante.

Looking a little run down there, John.

Ernest. I still have time.

It's almost up.
Who's gonna know the difference?

You sure this is what you wanna do?

Fourteen million. It's a lot of money.

Not if you can't spend it.

[both grunting]

- [John groans]
- [grunting]

Shh.

[both grunting]

[John] Oh, shit.

[groaning]

- [bones crack]
- [screams]

[screams, grunting]

[neck snaps]

[thunder rumbling]

[panting]

[groans]

- [lead a cappella singer] Push it back.
- [a cappella singers singing]

[chattering]

John Wick, Excommunicado.
In effect, 10 minutes.

Let it be known the Bowery
will honor the Excommunicado.

No help, no services of any kind.

[chattering]

Doc! Doc, it's Wick!

[doctor] Mr. Wick.

No, no. You shouldn't be here.
Hour's almost up.

I know, Doc, please. There's still time.

No. I can't.

I still have five minutes.

Please.

[locks turning]

Come on. Come on.

All right, sit there.

[groans]

[doctor] All right, let me see.
Let me see.

Uh-huh.

Puncture wound.

Ah, went deep. Nicked the artery.

Here you go.

- [grunts]
- [tools clattering]

[doctor] All right.

[ticking]

John Wick, Excommunicado.
In effect, one minute.

[ticking continues]

- Doc?
- Hmm?

Doc?

Yeah. We're halfway there.

- Five seconds.
- Yeah.

John Wick, Excommunicado.

In effect in five, four...

- [ticking]
- Three, two...

One.

[clock tolling]

Sorry, Mr. Wick.

I know. Rules.

Ah, rules.

[tolling continues]

- [phones ringing]
- [chattering]

[operator] John Wick, 14 million.

Open contract is now in effect.

All services are suspended.

- [phones ringing]
- [chattering]

[phone chimes]

And away we go.

[phones chiming, ringing]

[John grunts]

[phone chimes]

[doctor] Top shelf. On the right.
Yeah. Take four.

It will give you energy.
Help with the pain.

[phone chimes]

[sighs] Mr. Wick?

They'll never believe
I stopped on the hour.

But you did.

They'll know.

Know what?

I told you where the medicine was.

[sighs, grunts]

Where?

Here. Just below my floating rib.
Be sure not to hit my...

[groans]

Oh, wait!

One may not be enough.

[gun cocks]

[grunts]

Yeah. All right.

Be sure not to graze my...

Oh! [groaning]

Good luck, Mr. Wick.

Thanks, Doc.

[doctor groans]

- [chattering]
- [horns honking]

[in Mandarin]

[men shouting]

[sighs]

[door slams]

[men shouting]

[in Mandarin]

[gunshots]

[gun chamber clicking]

- [men speaking Mandarin]
- [grunts]

[grunting]

[grunting]

[groaning]

[grunting]

[screams]

[man screams]

[screams]

[man grunting]

[both grunting]

[bones crack]

[bones crack]

[bones crack]

[gasping]

- [grunts]
- [screaming]

- [thunder rumbling]
- [panting]

[man coughing]

- [grunts]
- [knife clatters]

[grunts]

[thunder rumbles]

[horns honking]

[whines]

[grunts]

[men in Italian]

[vehicle approaching]

- [grunts]
- [tires screech]

[horses whinnying]

[grunting]

[grunts]

[grunting]

[horses whinnying]

[grunting]

[horse nickers]

[grunting]

- [man screaming]
- [horse whinnies]

[engines revving]

[grunting]

[car horn blaring]

John Wick. Open contract.
Increase, 15 million.

Where are you going, Jonathan?

We are closed.

[panting]

[piano playing]

[in Russian]

[ballet music playing]

[woman]

[ballerina panting]

[door closes]

[in English] Jardani.

Why have you come home?

You present this to me like an answer.

I still have my ticket.

After all the chaos you've caused
for the last few weeks,

you think your ticket is valid?

You forget that the Ruska Roma
is bound by the High Table,

and the High Table stands above all?

They could kill me
just for talking to you.

You honor me
by bringing death to my front door.

Oh, Jardani, what has become of you?

[in Russian]

[in English] You are bound...

and I am owed.

Rooney, enough!

[in Russian]

[in English] "You are owed."
You are owed nothing, Jardani.

You know, when my pupils first come here,
they wish for one thing.

A life free of suffering.

I try to dissuade them
from these childish notions,

but as you know,

art is pain.

Life is suffering.

Somehow, you managed to get out.

But here you are, back where you began.

All of this, for what?

[in Russian]

- [classical music playing]
- [instructor speaking Russian]

- [in English] Pirouette.
- [instructor vocalizing]

Pirouette, pirouette.

[instructor speaking Russian]

[woman in English] Sit.

[door closes]

Even if I wanted to,
I can't help you, Jardani.

The High Table wants your life.

How can you fight the wind?

How can you smash the mountains?
How can you bury the ocean?

How can you escape from the light?

Of course, you can go to the dark.
But they're in the dark, too.

So tell me, Jardani,
what do you really want?

Passage.

Where did you want to go?

Casablanca.

[scoffs]

The path to paradise begins in hell.

So be it.

You hand me your ticket, I will tear it.

If that's what you really desire.

With this, Jardani, your ticket is torn.

[yells]

[groaning]

[panting]

You can never come home again.

Take him to the lifeboat.

Do svidanya.

[door opens]

[John] Do svidanya.

[door closes]

Welcome to the Continental.
How may I help you?

Sir. There is an Adjudicator
here to see you.

Very well, sir.

The manager is in the lounge.

[Winston] I presume
you're here to discuss John Wick.

If that's so, we can make this short.

I told him to walk away,
he declined to do so.

And that's the all of it.

Mr. Wick broke the rules.

Oh, yes.

And I haven't got the slightest idea
where he is...

You're mistaken.
I'm not here for Mr. Wick.

I'm here because
Mr. Wick broke the rules in this hotel.

- Hmm.
- The blood was spilt

on the grounds of the Continental,
was it not?

Oh, yes.

As a matter of fact, the body gets colder
within these very walls.

I'd like to see it.

Santino D'Antonio.

A newly instated member of the High Table,

slain by Mr. Wick while
seeking sanctuary in the Continental.

With a.45 ACP, it appears.

I had no control over Mr. Wick's actions.

And yet, he lives
because you deemed it so, yes?

Yes.

You have known Mr. Wick
for a great many years.

It might even be fair
to call you friends, yes?

Instead of stopping him,
instead of killing him,

you stood by and let him walk away

after he shot Santino D'Antonio
in front of you.

I made him Excommunicado.

But not before
you gave him an hour to escape.

He broke the rules in my hotel.

This is exactly the problem: your hotel.
Where is your fealty?

I've been of service for over 40 years.

Under the Table. Serving the Table.
Everything is under the Table.

I understand that you have your loyalties,
but this cannot be overlooked.

Let me be clear. I am here to adjudge you.

You have one week
to get your affairs in order.

Excuse me?

At such time,
your successor will be named.

There are rules,

they are the only things
that separate us...

From the animals.

Yes. You have seven days.

In the meantime, if you need
any assistance with your transition,

you may look for me in room 217.

Enjoy your stay at the Continental.

There's an Adjudicator here to see you.

[sighs]

[pigeons cooing]

Welcome to my mission control.

Brain stem of my operation.
The information super flyway.

From whence I control
the word on the street,

the way of the world.

With pigeons.

Yes. You see rats with wings,
but I see the Internet.

No IP addresses. No digital footprint.

Can't track it, can't hack it,
can't trace it.

Can you get disease from it?

Well, I wouldn't recommend
that you eat one.

What the hell do you want?

I wanted to see where it didn't happen.

Where what didn't happen?

Where you didn't kill John Wick.

I've always been under the impression

that contracts
and executing them was optional.

I have no problem with John Wick.

And yet, you gave John
a seven-round Kimber 1911,

knowing that he intended to use it
to stand against the Table. Yes?

This Kimber 1911, to be exact.

You gave John Wick seven bullets,
the High Table is giving you seven days.

Seven days for what, exactly?

To settle your affairs
and find a new home for your birds.

In seven days, you abdicate your throne.

[chuckles]

[laughing]

Oh, my dear.

Tell me, do you know
what the Bowery is, Adjudicator?

Do you know what happens
when I wave my hand?

No, there will be no replacement for me
on the throne.

Because I am the throne, baby.

I am the Bowery!

I am all that you deign not to look at
when you walk down the street at night.

The Bowery is mine. Mine alone.

Do not make the mistake of thinking
you exist outside the rules, no men do.

You have seven days.

[chattering]

[man shouting in Arabic]

[grunting]

[screaming, yelling]

[all grunting]

[man] Enough!

I'm afraid our friend here is off limits.

But he's Excommunicado.

It seems the manager
has granted him amnesty.

Mr. Jonathan,
would you be so kind as to come with me?

Welcome to Casablanca, Mr. Wick.

Thanks.

[laughing]

[chattering]

Mr. Jonathan, it has been a long time

since our fine city
has been graced with your presence.

I need to talk to...

Yes, Ms. Al-Azwar, she's expecting you.

[music playing]

My, my,
welcome to the Moroccan Continental.

I hope you'll find it to your taste.

Right this way.

Ms. Al-Azwar, she waits for no man.

Best of luck, Mr. Jonathan. Best of luck.

[chuckling]

[door closes]

[muffled chatter in distance]

[growling]

[barking]

[growling]

[woman] You a dog person, John?

- [gun cocks]
- [John] Sofia?

[groans]

Sofia, you can't kill
the bearer of your marker.

I didn't kill you. I just shot you.

Nice suit.

[bullet casing clatters]

Good to see you, too.

I should shoot you in the head right now.

I know.

Don't you do it.

You're Excommunicado, John.

And that marker doesn't mean shit.

This is your blood.

Your bond.

When you needed help, I was there.

Sit.

I was talking to you, John.

You do realize
that I'm management now, right?

I'm not service anymore, John.

So I don't go around
shooting people in the head.

I'm not asking you to kill anyone.
I just need you to get me to him.

- [Sofia] To who?
- Your old boss.

You want to kill Berrada.

I'm not gonna kill him.
I just need to talk.

What could he possibly give to you?

[sighs]

Guidance.

Look, I made a deal
when I agreed to run this hotel.

And that deal said that I had to follow
the rules of the Table.

If you're not gonna kill him,
he is gonna kill you,

and then probably me, too,
for walking you up in there.

If I make one mistake, one enemy...

maybe somebody goes
looking for my daughter.

And I know what you did, John,
to get her out.

But that's not a chance I can take. Sorry.

Do you wanna know where she is?

No. I don't ever wanna know.

Because I don't trust
that I won't go find her.

A part of me longs for her.

And I have to kill that part
of myself every day,

just to keep her safe.

Because sometimes,
you have to kill what you love.

That's why I gave you that marker
in the first place.

That's why I'm sitting here right now
and that's why I'm fucked!

[sighs]

Consequences.

[Sofia] Yeah.

Consequences.

I'm just asking you to try.

Either way, you and me, we'll be even.

No.

After this, we are less than even.

We leave in 10 minutes.

[dog whines]

[J-pop song playing on speakers]

[man speaking Japanese]

[men greeting in Japanese]

[music continues]

[in English] How can I help you?

I wasn't expecting the High Table so soon.

[Adjudicator] There is a task.

It involves someone who broke the rules
and stood against the Table.

John Wick, you mean.

My students have not been idle.

John Wick and all who've helped him.

You've heard the stories
about him, of course.

Killed scores of men
this past week alone because of...

A dog, a car.

I'm familiar.

And I'm interested.

Very.

Blowfish. Very fatal.

No soy.

I have served, I will be of service.

[ethereal music playing]

[grunting]

[grunting]

[music continues]

- Stop!
- [music stops]

Out!

The High Table and the Ruska Roma
have an understanding.

Yes, and you helped John Wick.

He had a ticket.

But a ticket does not stand
above the Table.

Your penance will be paid in blood.

Now...

hold out your helping hands
and pledge your fealty.

I have served, I will be of service.

[gasps]

[dog growling]

We're not going in like the old days.

It's just a conversation.

[sighs] Nothing's ever
just a conversation with you, John.

[dog yawns]

Let's go.

[chattering]

[man] Sofia.

Always so nice to see you.

And the dogs, of course, how marvelous.
May I pet one?

Certainly. [speaks Arabic]

[in English] Fantastic.

Jonathan Wick.

I had heard
you had made your way to our shores.

Come along now.

I am certain we have much to discuss.

I must admit, I am curious.
What brings you to my domain?

Tell me, do you come here to kill me?

No.

Mr. Wick, do you know
where the word "assassin" comes from?

People argue. "Assassin."

Hashasheen, followers of Hassan-i...

Eaters of hashish. [chuckles]

No, thank you.

But others contend
it comes from asasiyyun.

Meaning, "men who are faithful
and who abide by their beliefs."

You see that coin?

The first coin ever minted
in this facility.

Next to it, the first marker.

Not easy to track down, believe me.

Now, this coin, of course,
it does not represent monetary value.

It represents
the commerce of relationships,

a social contract
in which you agree to partake.

Order and rules.

You have broken the rules.
The High Table has marked you for death.

Why would I allow you to leave here alive,

when your life has been,
by your own actions, forfeit?

I seek to make amends.

To pay for what I've done.

I seek a meeting
with the one who sits above the Table.

This dog, I do so love it. Hmm.

Tell me, does it shed a great deal?

Occasionally.

When I leave,
you can tell the Elder I'm coming,

and if he wants me dead...

Then he will see to it
that your bones bleach under the sun.

I see.

And I would have provided him
with a choice.

I am sorry, Mr. Wick.

I cannot tell you where to find the Elder.

You fail to understand.

The Elder is not a man you find.
He can only choose to find you.

You wish to speak with him?

Go to the edge of the desert, look up.

Canis Minor,

the dog that followed Orion
through the sky.

You follow the brightest star,
walk until you are almost dead,

then, keep walking.

When you are on your last breath,
he will find you...

or he will not.

I am grateful.

Thank you, sir.

Perhaps you were not listening before.

The social contract.

The commerce of relationships.

You have received a great gift.
I have hosted your friend.

What do you offer in return?

So soft and yet so fierce.

I love it, this dog.

I will keep it.

Excuse me?

This will be my gift.
This will be how you show me your fealty.

No.

Surely it's the least you can do.

No, you cannot keep my dog.

Very well.

Very well.

Then I will kill it.

- [dog yelps]
- [Sofia screams]

- [dog whining]
- [speaking Arabic]

I'm sorry, Sofia.
This was for you to learn.

[whining]

Don't.

[men shouting]

[grunting]

- [barking]
- [screaming]

[barking]

[screaming]

[Berrada screaming]

Sofia, don't.

[screaming]

He shot my dog.

I get it.

[continues screaming]

[Sofia] We gotta go. Now.

[men clamoring]

[dogs barking]

[shouting]

[grunting]

- [shouts]
- [barking]

- [screaming]
- [gunshot]

[chattering]

[men shouting]

[barking]

[grunting]

[Sofia grunting]

[man yells]

[dogs growling]

[man shouting in Arabic]

- [barking]
- [screaming]

[dogs snarling]

[grunts]

[shouts]

[screams]

[dogs snarling]

[men shouting]

[grunting]

[snarling]

[screams]

[grunting]

[guns clicking]

[grunting]

[men shouting]

[choking]

[grunting]

- [shouts]
- [snarling]

[snarling]

[panting]

- [shouts]
- [dogs barking]

[prayer chanting on speakers]

[tires screeching]

[people clamoring]

[dogs barking]

- [dogs snarling]
- [men screaming]

[shouts]

[dogs barking]

[grunts]

Here you go.

You're gonna die, John.

Whether out here in this desert,

or somewhere else down the road.

But you are gonna die.

Consequences.

Consequences.

Better get going.

Sofia.

[grunts]

[grunts]

[grunting]

[grunting]

[grunting]

Okay.

[pigeon cooing]

You made your point.

You have earned my fealty.

Matter of fact,
I'm gonna shove so much fealty up your ass

it's gonna come
spilling out of your mouth.

You had your chance.

Well, since you see it that way,

I guess it's time I told you

to climb down off your High Table
and go fuck yourself.

Duly noted.

You gave John Wick seven bullets,
your penance will be paid with seven cuts.

Well, sometimes you gotta
cut a motherfucker.

Avert your eyes, my sweet.

The king is dead.

Long live the king.

[groaning, grunting]

[camel grunting]

[camel grunting]

[man] Drink.

Don't worry, your weapon is still there.

Please drink.

My son, how have you come to be so lost?

[John] Not lost.

Looking for you.

[Elder] You think
I speak of your location?

Never seen a man fight so hard
to end up back where he started.

So tell me, Jonathan.

Why do you wish to live?

My wife, Helen.

To remember her.

To remember us.

So you seek to live
for the memory of love?

At least a chance to earn it.

I can give you one last chance
to earn a life.

However, it might not be
the life that you wish.

Complete a task for us,
and your Excommunicado will be reversed.

The open contract closed.

You would be permitted
to continue to live.

Not free under the Table, but bound to it.

Doing what you do best
for the rest of your days.

The choice is yours.

Die here and now

or continue to live
and remember through death.

What must be done?

The cost of your life
will be the death of others.

The first of which will be
the man they call Winston.

What?

[Elder] He has forgotten his fealty.

Neither the open contract
nor the Excommunicado will be lifted

until you complete your task.

So if you wish to live,
and if you wish to remember,

this is the choice you must make.

I will serve.

I will be of service.

[Elder] Very well, my son.

Cast aside your weakness
and reaffirm your fealty to the Table.

Mr. John Wick.

[in Arabic]

[screaming]

[breathing heavily]

[groans]

[Elder in English] Thank you.

I accept this offering and your fealty.

[John grunts]

[groans]

I wish you good luck on your path.

Zahir will help you prepare
for your departure.

And, Mr. Wick...

[in Arabic]

[announcer on PA]
JFK Express now arriving on platform nine.

JFK Express now arriving on platform nine.

[chattering]

[indistinct announcement on PA]

[woman] Stick together, kids.

Make sure you're holding the hand
of the person in front and behind you.

You see?
That's why you're special, John Wick.

I wouldn't have stopped.

It's good to have you back.

How was your trip?

Going to the Continental?

He with you?

- [thuds]
- He was.

[indistinct announcement on PA]

Nice trick.

[phones ringing]

[vehicles approaching]

[grunts]

[grunting]

[engine revving]

[grunting]

[tires screeching]

[engines revving]

[grunting]

[biker screams]

[tires screeching]

[grunting]

[grunts]

[grunts]

Sir! Put your weapon down.

[Zero] He's Excommunicado.

Unless you wish to become the same,
I suggest you lower your gun.

[panting]

I'd like to see the manager.

Of course.

If you would be so kind as to follow me.

- [soft music playing]
- [chattering]

Please take a seat.
I will let him know you have arrived.

[John sighs]

I gotta tell you,

I've been looking forward
to meeting you for a long time.

I'm a huge fan, John Wick.

[chuckles]
And so far, you haven't disappointed.

Is that the dog? He likes you. [chuckles]

Me? I'm more of a cat person myself.

Hey, dog.

We're the same, you know.
Both given the same gift.

We're not the same.

[Zero] Yes, we are.

No, we're not.

The manager is ready for you now.
In the administrative lounge, sir.

[in Japanese]

Mr. Wick.

[dog panting]

Sit.

Stay.

Good dog.

[dog whines]

[elevator bell dings]

[footsteps approaching]

Tread carefully, Jonathan.

We only use this room
on special occasions.

When you simply have to see
what your opponent is holding

under the table.

[chuckles]

How was your journey here? Eventful?

Yeah.

Well, of course.

They sent men to kill you,
and now you to kill me.

Isn't that why you're here?

I have served, I will be of service.

But you're having doubts.

Just don't make the mistake of pretending
this is personal.

If you feel you must...

put a bullet through my heart.

The High Table has asked me to step down.

The hour?

The hour.

You should have killed me
in the Continental.

Maybe I should have.

Rules and consequences.

[Winston] Hmm.

It seems like everyone is suffering
from the consequences of their actions.

And you're not stepping down?

No.

I don't think I am.

[John] So it's war?

You're going to war with the High Table?

Skirmish.

Unless you decide to shoot me.

But then, I'd rather die
at the hand of a friend

than that of an enemy.

No, I've made my choice.
It's up to you to make yours.

What choice?

You shoot me, you sell your soul.

But I'll be alive. And I can remember her.

Until you die as a servant
of the High Table.

Now, you did the impossible,
you stopped, you got out.

You only came back because
Helen was taken away from you.

The real question is,
who do you wish to die as?

The Baba Yaga?

The last thing many men ever see?

Or as a man who loved
and was loved by his wife?

Who do you wish to die as, Jonathan?

[footsteps approaching]

Mr. Wick, it's a pleasure to meet you.
I am an Adjudicator.

Have you decided to step down?

I think not.

And you? Will you be putting
a bullet in his head?

No, I don't think I will.

Very well.

[line ringing]

- [chattering]
- [phone ringing]

Administration.

[Adjudicator]
I'd like to change a designation.

Verification?

Adjudication 1-0-1-1-9-7-9.

The Continental Hotel, New York.

[administrator] New designation?

Deconsecrated.

Processing.

Administrator.

File. The New York Continental Hotel.

The New York Continental Hotel
has been deconsecrated. Goodbye.

Gentlemen, this institution
is now deconsecrated.

Business may now be conducted
on Continental grounds.

Since you are refusing to step down
and you are refusing a direct order,

your lives are now forfeit.

High Table emissaries
will be joining you presently

to see the removal
of your souls from the property.

Good evening, gentlemen.

This haven is safe no more.

Are services still off limits to me?

Under the circumstances, your privileges
are reinstated immediately.

What do you need?

Guns. Lots of guns.

[trilling]

[door unlocks]

Let's make a withdrawal.

- [chattering]
- [phones ringing]

[Charon] Remember, sir,
these will be High Table forces.

We may have to consider
our choices carefully.

Why?

Much has changed during your time away.

Like what?

Well, let us say
they have made armor improvements.

May I suggest the 2011 Combat Master

in combination with
the nine millimeter Major.

[phones ringing]

[announcer on PA] Attention, all guests.

The Continental Hotel
is closing for fumigation.

We apologize for the inconvenience.
Please make your way to the nearest exit.

Attention, all guests.
The Continental Hotel...

It seems circumstances
have changed in your favor.

Your transaction may now be conducted
on Continental grounds.

We'll be sending some of our finest
for additional support.

Cool. Very cool.

[gun clicks]

125 grain,
1,425 feet per second. Serious business.

Thank you.

Let us begin.

[orchestral music playing]

[explosions in distance]

Charon, would you help set
the mood for our new guests?

Of course, sir.

I know you'll do the Continental proud.

I'll see you soon, sir.

And you, Jonathan, do what you do best.

What's that?

Hunt.

[in Latin]

[music stops]

[footsteps approaching]

[man 1 screams]

[man 2 coughs]

[grunting]

[grunting]

[John yelling]

Winston! Winston!

[grunts]

I need more firepower.

[orchestral music continues playing]

Armor improvements.

Twelve-gauge steel slugs. Armor-piercing.

- [beeps]
- [whirring]

[man screams]

[screams]

[rapid gunfire]

[groaning]

- [man yells]
- [grunting]

[rapid gunfire]

[grunting]

- [blade slashes]
- [groans]

[in Japanese]

[in English] Only by my sword, John.

[grunts]

[phone ringing]

[Adjudicator] I know you
believe you can keep this up.

But I assure you...

[line disconnects]

[grunting]

[groans]

[panting]

[grunting]

[both grunting]

[groaning]

[grunts]

[clanging]

[yelling]

[grunting]

[grunting]

[screams]

[grunting]

[grunts]

[clapping]

- [man yells]
- [grunting]

[in Indonesian]

[grunts]

[grunting]

[grunting]

[grunting]

[John shouts]

[glass cracks]

[groans]

[in Indonesian]

[in English] John, you're incredible.

Exhausted, outnumbered, obviously in pain,

and you still beat all of my students.

If I didn't have to kill you,
we'd be... pals.

Let's do this.

[grunting]

See? We're the same.

[grunting]

[yells]

- [bone cracks]
- [Zero yells]

[panting]

[grunting]

- [bone cracks]
- [yells]

[both grunt]

[yells, groans]

[grunts]

[yells]

[grunting]

[groans]

[line ringing]

[phone ringing]

I would like to suggest a parley.

A parley would be good.

Very well.

Are we in play, sir?

Oh, very much so.

[John panting, groans]

[Zero groaning]

[Zero chokes]

Hey, John.

That was a pretty good fight, huh?

Yeah.

[John grunts]

[Zero] Yeah.

Don't worry about me, John.

I just gotta catch my breath.

I'll catch up to you, John.

No, you won't.

[grunts]

[Adjudicator] You gentlemen, of course,
realize that was the first wave.

Merely an amuse-bouche.

We can keep this up as long as you'd like,
but it only ends one way.

Are you sure a protracted war
is the best way forward?

There won't be anything
"protracted" about it.

Oh, you can take the Continental,
I have no doubt about that,

but keeping it,
that's a different matter entirely.

My allegiances run
way beyond this building.

We are High Table.

And we...

are New York City.

Are we negotiating?

Hmm. I believe we are.

Parley?

[Winston] Parley.

[Adjudicator] What do you propose we do?

Let me keep my power.

Under the Table.

I have served
and been a beacon of order and stability

to our industry for over 40 years.

Now, I humbly acknowledge I overstepped
and re-pledge my fealty to the High Table.

Winston.

You were merely showing strength
so we would let you keep the Continental.

The High Table accepts your fealty.

But what about him?

What are we going to do about John Wick?

Oh, he has to die.

- Sorry, Jonathan.
- [groans] Winston!

Don't see any other way.

[John grunts]

[grunting]

Very well, gentlemen.
The Continental will now be reconsecrated.

Good day to you both.

Well played, sir.

- [chattering]
- [metal clinking]

How long do you estimate until we reopen?

Oh, should be no time at all.

Mr. Wick is gone.

A true tragedy.

You misunderstand.
I mean that he is no longer on the street.

That seems improbable.

And yet, true.

[whimpers]

I trust you understand
the repercussions if he survives.

Both from above and below.

The last thing either one of us needs is
Mr. Wick paying us a visit in the night.

For both our sakes,
I'll hope you see to it

that this situation is taken care of, yes?

Absolutely. How far can he get?

Baba Yaga.

[wheels squeaking]

[whimpers]

[groans]

[Bowery King] How you doing, John?

You look as bad as I feel.

[chuckles] Johnny, Johnny, Johnny.

Raise a hand if you can hear me, John.

Oh, shit. They took a finger.

Ain't that a bitch? [chuckling]

[laughs and groans]

Oh, John fucking Wick.

So, the old boy keeps his hotel
and you take the fall.

Can't say I blame him.

I would've done the same thing
if I was in his shoes.

But this High Table shit...

Seven cuts.

[chuckles]

Under the Table is where shit gets done.

And they're about to find out,
if you cut a king,

you better cut him to the quick.

[sighs]

So...

Let me ask you, John.

How do you feel?

'Cause I am really pissed off.

You pissed, John? Hmm? Are you?

[groans]

Yeah.

**Comment by end-me-please** [comment]
do you spam-call the fire brigade to complain about the police too?

**Comment by Foxlass** [comment]
> do you spam-call the fire brigade to complain about the police too?

I think comparing Twitter to the fire brigade is absolutely insane

**Comment by jdm-twtr** [comment]
This issue was closed due to one of these reasons: likelihood of spam, not enough context, or possibly inappropriate content. Please re-file with a useful title and description.
