### ISSUE TITLE
Does twitter access wifi networks?

### ISSUE THREAD

**Issue by ayasa520** [twitter/the-algorithm#1397]

**Comment by rodsan0** [comment]
is it tracking my pupils??

**Comment by Issodeveloper** [comment]
If I turn on airplane mode, can it access my plane?

**Comment by nobodyindustries** [comment]
I have heard it can smell your farts

**Comment by ujjwalbe** [comment]
It can detect your neighbours doing nasty things

**Comment by jdm-twtr** [comment]
This issue was closed due to lack of useful description.
