### ISSUE TITLE
Split the subprojects out of the monorepo into own repositories

### ISSUE THREAD

**Issue by KOLANICH** [twitter/the-algorithm#1399]
**Is your feature request related to a problem? Please describe.**
While we now can use partiwl clones on GitHub, it'd ge easier to accrss them by different URIs, and I guess each subproject deserves its own bug tracker.

**Describe the solution you'd like**
This repo is split into multiple ones and replaced with a repo using git submodules.

**Comment by dagelf** [comment]
You mean **partial** clones I guess? How would that work?

I think better docs on how they pull this repo into their CI would be more useful.

**Comment by KOLANICH** [comment]
>You mean partial clones I guess? How would that work?

https://github.blog/2020-12-21-get-up-to-speed-with-partial-clone-and-shallow-clone/

I don't think that monorepos are convenient to handle. When each project has an own repo, it is possible to version and release each pronect separately in the form of git tags, that can be used by build systems (or scripts/extensions for them) to populate package version information automatically. While monorepos provide the way to fetch the consistent state of all the subproject at once, git submodules also allow this, but the same time they allow the projects live in separate repos.

**Comment by GabenGar** [comment]
Git submodules aren't convenient to handle either.
