### ISSUE TITLE
Tweet timer 

### ISSUE THREAD

**Issue by fidelmak** [twitter/the-algorithm#140]
**Timer** 
** Their should be a button or slide to set tweet timer with date stamp for example  assign a tweet a specific time to display 

**My Solution**
Include a slide or add new feature to assign tweets with timer using kotlin or a suitable language 
.
For example
MyTweet 1--- (12:13am) 
MyTweet 2 --- (05:15pm)

**Comment by couldbejake** [comment]
Similar to that of email clients? TweetDeck has this support, but I think it would reduce the human aspect of the interaction.

**Comment by Alotab** [comment]
That wouldn't be a bad idea and a timer for a deletion which is a rare thing for user to do but it's a way to make twitter easy to control.

**Comment by jdm-twtr** [comment]
Thanks for filing. We've marked this issue as an unrelated bug or feature for future review.
                    In order to keep our issue count manageable, we will not be leaving these issues open. We apologize for
                    the inconvenience. If you feel that we closed your issue in error, please re-file the issue, stating how
                    the requested feature applies to the recommendation algorithm components that have been open-sourced thus far.
