### ISSUE TITLE
Support markdown for tweets?

### ISSUE THREAD

**Issue by ryhkml** [twitter/the-algorithm#1402]
I love Twitter

**Comment by jtbx** [comment]
this is only the recommendation algorithm, not the entire website

**Comment by algonacci** [comment]
> this is only the recommendation algorithm, not the entire website

Where is the website repo?

**Comment by Foxlass** [comment]
Elon hasn't open sourced the entirety of Twitter yet because he's a little pussy

**Comment by jdm-twtr** [comment]
This issue was closed due to one of these reasons: likelihood of spam, not enough context, or possibly inappropriate content. Please re-file with a useful title and description.

**Comment by algonacci** [comment]
Wait
