### ISSUE TITLE
Add option to switch from reverse chronological to best Tweets sorting in Following view

### ISSUE THREAD

**Issue by ypatios** [twitter/the-algorithm#1405]
The current Twitter Home view offers the **Following** Home Timeline (as well as Lists) only in reverse chronological order. This is frustrating, as users must often scroll through a lot of Tweets that occurred recently but may be of little importance.
For example, if a user opens Twitter after an absence of several hours and want to see the most important Tweets from accounts they follow, they might need to scroll through hundreds of Tweets before reaching the most significant ones.

A solution to this issue would be to offer users the option to switch between reverse chronological order and "best" Tweets in all home timelines (or at least the Following home timeline).

In oder to determine which Tweets are the "best", the same algorithm as in the **For you** Home Timeline could be used (perhaps slightly modified to exclude out-of-network content). But in general "best" Tweets should be the ones with most interaction (views, likes, retweets, etc.)

From the current home-mixer readme:
> Home Mixer is the main service used to construct and serve Twitter's Home Timelines. It currently powers:
> * For you - best Tweets from people you follow + recommended out-of-network content
> * Following - reverse chronological Tweets from people you follow
> * Lists - reverse chronological Tweets from List members

Which with this feature deployed would be changed too:
> Home Mixer is the main service used to construct and serve Twitter's Home Timelines. It currently powers:
> * For you - best Tweets from people you follow + recommended out-of-network content
> * Following - reverse chronological Tweets from people you follow **OR best Tweets from people you follow**
> * Lists - reverse chronological Tweets from List members **OR best Tweets from List members**

Offering this feature might be the ultimate test for the **For you** Home Timeline: if users still prefer it over **Following** this would prove that the additional recommended out-of-network content is actually good (including ads).

**Comment by jdm-twtr** [comment]
Thanks for filing. We've marked this issue as an unrelated bug or feature for future review.
                    In order to keep our issue count manageable, we will not be leaving these issues open. We apologize for
                    the inconvenience. If you feel that we closed your issue in error, please re-file the issue, stating how
                    the requested feature applies to the recommendation algorithm components that have been open-sourced thus far.
