### ISSUE TITLE
This repository could become the new Never Gonna Give You Up

### ISSUE THREAD

**Issue by essesoul** [twitter/the-algorithm#1410]
This repository could become the new Never Gonna Give You Up
You only have to look at this repository for a bunch of weird stuff popping up in the comments section just a day after it was published.

**Comment by Prisko** [comment]
Never gonna give you up
Never gonna let you down
Never gonna run around and desert you
Never gonna make you cry
Never gonna say goodbye
Never gonna tell a lie and hurt you
