### ISSUE TITLE
Can we just make this repo a complete meme forum just for fun

### ISSUE THREAD

**Issue by its-rav** [twitter/the-algorithm#1417]

**Comment by Sqaaakoi** [comment]
yea

**Comment by sunglocto** [comment]
i agree

**Comment by realpxd** [comment]
Agree 🗿

**Comment by AjaykrishnanR-axon** [comment]
lets goo

**Comment by osktobi** [comment]
agree

**Comment by e-hamza** [comment]
it is already

**Comment by f0rttnite** [comment]
![image](https://user-images.githubusercontent.com/41347805/229353892-082d4639-1db7-4e87-8a26-4e4824c4aa30.png)

**Comment by aragubas** [comment]
💀

**Comment by Marioood** [comment]
Would you like to sign my petition? 

To make whiney Github users stop taking everything so seriously.

**Comment by famellad** [comment]
Best use for this space really

**Comment by jdm-twtr** [comment]
This issue was closed due to lack of useful description.
