### ISSUE TITLE
I may be too late but is this real?

### ISSUE THREAD

**Issue by innocentvoice** [twitter/the-algorithm#1425]
Real!?

**Comment by realpxd** [comment]
Real what?

**Comment by mansour1233** [comment]
yse Boy

**Comment by innocentvoice** [comment]
> Real what?

Is this the algorithm and not april fools?

**Comment by mateusmlo** [comment]
> > Real what?
> 
> Is this the algorithm and not april fools?

it's kinda both really

**Comment by jdm-twtr** [comment]
This issue was closed due to one of these reasons: likelihood of spam, not enough context, or possibly inappropriate content. Please re-file with a useful title and description.
