### ISSUE TITLE
i think my posts should get boosted instead

### ISSUE THREAD

**Issue by 99kaits** [twitter/the-algorithm#1430]
im very cool and attractive and everyone needs to see my thoughts even if they dont want to

**Comment by YassieJ** [comment]
I agree.

**Comment by AleksLi1** [comment]
lgtm

**Comment by Easy1000** [comment]
indeed

**Comment by mateusmlo** [comment]
100% correct.

**Comment by wmonecke** [comment]
merged

**Comment by 99kaits** [comment]
thank you i love democracy whenever it benefits me

**Comment by 99kaits** [comment]
i cant believe its been completed thank you twitter

**Comment by 99kaits** [comment]
i will be in contact to arrange the boosting of my posts

**Comment by 99kaits** [comment]
my people can talk to your people and we're gonna make it happen

**Comment by 99kaits** [comment]
i think this will be a very fruitful partnership

**Comment by 99kaits** [comment]
i feel like eventually we could pivot the site into just being a blog for me and everyone's only allowed to comment i think that would be really nice

**Comment by 99kaits** [comment]
i mean idk what alls going on over there with that guy youre boosting right now but i think im a lot better than him im cool and im attractive

**Comment by 99kaits** [comment]
i feel like we can have a good thing going with the site thats all im saying bright future ahead
