### ISSUE TITLE
記念カキコ

### ISSUE THREAD

**Issue by Coordinate-Cat** [twitter/the-algorithm#1431]
風呂入ろうと思って裸になって車に乗り込んだ時は自分でも驚いた

**Comment by delgh1** [comment]
> 裸になって車に乗り込んだ

男だったら写真をください

**Comment by jdm-twtr** [comment]
This issue was closed due to one of these reasons: likelihood of spam, not enough context, or possibly inappropriate content. Please re-file with a useful title and description.
