### ISSUE TITLE
What color is the sky?

### ISSUE THREAD

**Issue by UmairMukhtar** [twitter/the-algorithm#1442]

**Comment by Richmond-Nunoo** [comment]
Ukraine?

**Comment by Het-AbobaMuhmuh** [comment]
the color of twitter

**Comment by Posandu** [comment]
...

**Comment by Jumicode** [comment]
The color of Twitter x2

**Comment by sameer-m-dev** [comment]
Ay, mi amor
Ay, mi amor

**Comment by UmairMukhtar** [comment]
> Ay, mi amor Ay, mi amor

Where should i put my shoes?

**Comment by vixalien** [comment]
Ay, mi amor
Ay, mi amor

**Comment by UmairMukhtar** [comment]
> Ay, mi amor Ay, mi amor

You say put them on your head

**Comment by Aaditiyakansal** [comment]
¡ay, Mi Amor! ¡ay, Mi Amor!

**Comment by UmairMukhtar** [comment]
> ¡ay, Mi Amor! ¡ay, Mi Amor!

You make me
Un poco loco

**Comment by Aaditiyakansal** [comment]
The way you keep me guessing,
I'm nodding and I'm yesing,
I'll count it as a blessing,
That I'm only un poco loco!

**Comment by UmairMukhtar** [comment]
(Musical interlude)

**Comment by jdm-twtr** [comment]
This issue was closed due to lack of useful description.
