### ISSUE TITLE
Follow for Follow on GitHub!!

### ISSUE THREAD

**Issue by Richmond-Nunoo** [twitter/the-algorithm#1443]
**Describe the bug**
Let's follow each other here on GitHub . I promise to follow back🥲.

**To Reproduce**
I have only 7 followers!!

**Expected behavior**
Any kind of developer ! 

**Screenshots**

**Environment**
For web, specify your OS and browser version.  For mobile, specify device, OS
and version.  For libraries, what version of build tools are you using?

**Additional context**

**Comment by AjaykrishnanR-axon** [comment]
Followed !

**Comment by kinggoesgaming** [comment]
Followed !

**Comment by Richmond-Nunoo** [comment]
Followed both of you back!!

**Comment by combo23** [comment]
lmao
