### ISSUE TITLE
blue tweets should only display to fellow blue users 

### ISSUE THREAD

**Issue by stevepatter** [twitter/the-algorithm#1445]
As a valued Twitter Blue customer, I am disappointed that my choice takes are also distributed to the freeloaders who are not subscribed to Supreme Ruler Elon's bluetick project. If I have to pay to tweet, my tweets should only be shown to  fellow Blue users, who have proved that they are valuable enough to receive my golden words.

**Comment by 99kaits** [comment]
god emperor elons program should be for paying users only  
freeloaders dont get my holy posts

**Comment by jdm-twtr** [comment]
Thanks for filing. We've marked this issue as an unrelated bug or feature for future review.
                    In order to keep our issue count manageable, we will not be leaving these issues open. We apologize for
                    the inconvenience. If you feel that we closed your issue in error, please re-file the issue, stating how
                    the requested feature applies to the recommendation algorithm components that have been open-sourced thus far.
