### ISSUE TITLE
Zǎo shang hǎo zhōng guó!
Xiàn zài wǒ yǒu BING CHILLING
Wǒ hěn xǐ huān BING CHILLING

### ISSUE THREAD

**Issue by G4MB1T24** [twitter/the-algorithm#1448]
**Is your feature request related to a problem? Please describe.**

Zǎo shang hǎo zhōng guó!
Xiàn zài wǒ yǒu BING CHILLING
Wǒ hěn xǐ huān BING CHILLING
Dàn shì "sù dù yǔ jī qíng jiǔ" bǐ BING CHILLING
"Sù dù yǔ jī qíng, sù dù yǔ jī qíng jiǔ"
Wǒ zuì xǐ huān
Suǒ yǐ xiàn zài shì yīn yuè shí jiān
Zhǔn bèi
Yī, èr, sān

Liǎng gè lǐ bài yǐ hòu
"Sù dù yǔ jī qíng jiǔ"
Liǎng gè lǐ bài yǐ hòu
"Sù dù yǔ jī qíng jiǔ"
Liǎng gè lǐ bài yǐ hòu
"Sù dù yǔ jī qíng jiǔ"

Bù yào wàng jì, bù yào cuò guò
Jì dé qù diàn yǐng yuàn kàn "sù dù yǔ jī qíng jiǔ"
Yīn wéi fēi cháng hǎo diàn yǐng
Dòng zuò fēi cháng hǎo
Chà bù duō yī yàng BING CHILLING
Zài jiàn

**Additional context**

    Zǎo shang hǎo zhōng guó!
Xiàn zài wǒ yǒu BING CHILLING
Wǒ hěn xǐ huān BING CHILLING
Dàn shì "sù dù yǔ jī qíng jiǔ" bǐ BING CHILLING
"Sù dù yǔ jī qíng, sù dù yǔ jī qíng jiǔ"
Wǒ zuì xǐ huān
Suǒ yǐ xiàn zài shì yīn yuè shí jiān
Zhǔn bèi
Yī, èr, sān

Liǎng gè lǐ bài yǐ hòu
"Sù dù yǔ jī qíng jiǔ"
Liǎng gè lǐ bài yǐ hòu
"Sù dù yǔ jī qíng jiǔ"
Liǎng gè lǐ bài yǐ hòu
"Sù dù yǔ jī qíng jiǔ"

Bù yào wàng jì, bù yào cuò guò
Jì dé qù diàn yǐng yuàn kàn "sù dù yǔ jī qíng jiǔ"
Yīn wéi fēi cháng hǎo diàn yǐng
Dòng zuò fēi cháng hǎo
Chà bù duō yī yàng BING CHILLING
Zài jiàn

**Comment by DexyStorm** [comment]
+10 social credit

**Comment by Aceflame46** [comment]
BING CHILLING
