### ISSUE TITLE
rewrite in mongodb

### ISSUE THREAD

**Issue by elmarti** [twitter/the-algorithm#1450]
mongodb is web scale

**Comment by HolyNetworkAdapter** [comment]
mongodb is web scale

**Comment by swingcake** [comment]
monke

**Comment by elmarti** [comment]
You turn it on and it scales right up

**Comment by jdm-twtr** [comment]
This issue was closed due to one of these reasons: likelihood of spam, not enough context, or possibly inappropriate content. Please re-file with a useful title and description.

**Comment by HeyBanditoz** [comment]
Bro it's Sunday
