### ISSUE TITLE
看不懂代码怎么办?help me

### ISSUE THREAD

**Issue by huawuque404** [twitter/the-algorithm#1453]
如果你能看懂这些代码,可以教教我吗,谢谢giegie
![image](https://user-images.githubusercontent.com/109327586/229367225-1ae33e12-a498-4370-ac80-c8253eb0d67a.png)
If you can understand these codes, can you teach me? Thank you.

**Comment by 404Dev-404** [comment]
it does that thing forever

**Comment by VainXploits** [comment]
早上好中国 现在我有冰淇淋 我很喜欢冰淇淋 但是 速度与激情9 比冰淇淋 速度与激情 速度与激情9 我最喜欢 所以…现在是音乐时间 准备 1 2 3 两个礼拜以后 速度与激情9 ×3 不要忘记 不要错过 记得去电影院看速度与激情9 因为非常好电影 动作非常好 差不多一样冰淇淋 再见

中共万岁 😎😎🇨🇳🇨🇳🇨🇳💪💪😎🇰🇵🇰🇵🇰🇵🇰🇵🇰🇵🇰🇵🇨🇳🇨🇳🇨🇳🇨🇳🇨🇳🇨🇳🇨🇳💪💪💪💪💪💪😎😎😎😎😎😎😎😎😎💪🇨🇳🇨🇳🇨🇳🇨🇳🇨🇳🇨🇳🇨🇳🇨🇳🇨🇳🇨🇳🇨🇳🇨🇳😳🇨🇳🇨🇳🇨🇳🇨🇳🇨🇳😎😎💪🇨🇳🇰🇵🇨🇳🇰🇵🇨🇳🇨🇳🇨🇳🇰🇵🇰🇵🇨🇳🇨🇳🇰🇵🇨🇳🇰🇵🇨🇳😎😎💪🇨🇳🇨🇳🇨🇳🇨🇳🇨🇳🇨🇳🇨🇳🇨🇳🇨🇳🇨🇳🇨🇳💪💪💪😎😎💪🇨🇳🇨🇳🇨🇳🇨🇳
