### ISSUE TITLE
my issues here have more reach than my tweets

### ISSUE THREAD

**Issue by swingcake** [twitter/the-algorithm#1463]
fml.

**Comment by VainXploits** [comment]
WHOPPER 🍔 WHOPPER 🍔 WHOPPER 🍔 WHOPPER 🍔 JUNIOR 🤏 DOUBLE 2⃣ TRIPLE 3⃣ WHOPPER 🍔 IMPOSSIBLE 🤯 OR 🤔 BACON 🥓 WHOPPER 🍔 I 👁️ RULE 👑 THIS 😎 DAY 🌞 AT BK 🧑‍🍳 HAVE IT YOUR WAY 🤷‍♂️

YOU RULE 🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥

**Comment by jdm-twtr** [comment]
This issue was closed due to one of these reasons: likelihood of spam, not enough context, or possibly inappropriate content. Please re-file with a useful title and description.
