### ISSUE TITLE
cool feature idea 

### ISSUE THREAD

**Issue by ech0devv** [twitter/the-algorithm#1471]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I see that Elon Musk still has a Twitter account.

**Describe the solution you'd like**
Ban Elon musk from Twitter.

**Describe alternatives you've considered**
Delete twitter

**Additional context**
@twitter-service fix this urgently

**Comment by jdm-twtr** [comment]
This issue was closed due to one of these reasons: likelihood of spam, not enough context, or possibly inappropriate content. Please re-file with a useful title and description.
