### ISSUE TITLE
THE ONE PIECE IS REAL!!!!

### ISSUE THREAD

**Issue by rcmtcristian** [twitter/the-algorithm#1472]
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⠀⠈⠉⠀⠈⠀⠁⡉⢉⠉⡉⢉⠉⡉⢉
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣀⣤⣤⣤⣦⣴⣤⣶⣤⣦⣴⣤⣀⣄⡀⠀⠐⢀⠀⢀⠠⠀⠐⠀⢂⠈⡀⠡⢈⠀⠄⡁⠈⠄⠡⢈⠠⠀⠌⠠⠁⠌⡈⠁⠌⢂⠡⢀⠠⢁⡐⠠⡈⢐⠠⡁⢌⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣤⣶⣿⣿⣿⠿⡛⠟⢻⠛⣛⠛⣛⠻⣛⠿⣿⣿⣿⣾⣤⣤⣈⡀⡐⢀⠂⡈⢀⠀⡀⠄⢀⠈⢀⠀⡁⢈⠀⠄⡀⠡⢈⠀⡁⢂⠠⠉⡀⠂⠄⢂⠐⡠⢀⠡⠐⡠⢁⠐⡈⠄
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣠⡶⠟⣾⣦⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣰⣾⣿⣿⠟⡋⠅⣆⠢⣑⠸⣀⠓⡌⢒⠡⠆⠥⠒⠤⣉⠛⡻⢿⣿⣿⣿⣶⣤⡒⢀⠀⠠⠀⠈⠀⠀⠀⠀⠄⠀⠀⢂⠀⠁⡀⠂⠄⠠⠀⡐⠀⠡⠈⠄⢂⠐⠠⢁⠂⠡⠠⠘⡀⠂
⠀⠀⠀⠀⠀⠀⠀⠀⠀⣼⠟⣠⣿⣿⣿⠇⠀⠀⠀⢀⣀⣄⡀⠀⣠⣿⣿⡿⠛⡄⠎⢬⠑⢢⠑⣄⠣⢄⢣⡘⠬⡑⠬⢡⠙⡰⢈⡒⢡⠊⡍⠻⢿⣿⣿⣿⣶⣌⠀⠌⠐⡀⢈⠀⠄⠀⠠⠀⠂⠀⠐⠀⠠⢀⠀⠁⠠⠐⠀⡐⠈⠀⠌⠐⠂⢁⠂⠡⠁⠤⠁
⠀⠀⠀⠀⠀⠀⠀⠀⣸⡟⡐⣾⣿⣿⠟⠀⠀⠀⣰⣿⠋⣿⡿⠀⣿⠿⣣⠐⢣⡘⢜⣠⣿⠶⠟⠛⢿⣆⢆⡘⡡⠜⡐⢣⢁⢣⠡⡌⠄⢎⠰⣉⠦⠹⢿⣿⣿⣿⣷⣌⠠⠀⠀⠀⢀⠂⠀⠄⠀⠈⠀⠠⠁⠀⠠⠀⠀⢀⠐⠀⡀⠡⠈⠐⠈⠠⠈⠄⢁⠂⠄
⠀⠀⠀⠀⠀⠀⠀⢰⡿⠰⣱⣿⣿⠏⠀⠀⠀⢀⣿⢃⣼⣿⣷⡟⢀⡼⢏⡘⠤⣱⡾⠋⠁⠀⠀⠀⠀⠻⣦⡐⢡⠚⢌⠒⡌⢢⡑⣌⣚⣬⣶⣦⡎⠱⡌⢹⣿⣿⣻⣿⣧⡐⢈⠀⠀⢀⠠⠀⠂⠀⠁⠀⠄⠀⠠⠀⠀⠀⠀⢀⠀⢀⠀⠁⠌⢀⠐⢈⠀⠌⡀
⠀⠀⠀⠀⠀⠀⢠⣿⠃⣅⣿⣿⡿⠀⠀⠀⠀⣸⣿⣾⣿⣿⣿⠃⠟⡡⢆⡉⢆⡹⣧⠀⠀⠀⠀⠀⠀⠀⠹⣷⣢⣉⣦⡷⠾⠟⠛⠉⠉⠁⠀⠈⢿⡕⣈⠦⡘⢻⣷⣯⢿⣿⣆⡐⠈⠀⠀⠠⠐⠀⡈⠀⡀⠂⠁⠠⠐⠈⢀⠀⣂⠠⠐⡠⠐⡠⢀⠤⣘⢰⡰
⠀⠀⠀⠀⠀⠀⣸⣿⠈⣴⣿⣿⣇⠀⠀⠀⢀⣿⣿⣯⣿⣿⢃⠜⢢⢑⠢⣉⠆⡔⢻⣆⠀⠀⠀⠀⠀⠀⠀⠘⠋⠉⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⣿⡔⢢⠉⢆⠻⣿⣟⡾⣿⣷⡀⠁⠠⢀⠠⢀⠠⠐⡠⣀⢇⢦⣑⣎⢦⢳⣤⣋⢷⣡⠷⣡⡓⡞⣬⢣⣓
⠀⠀⠀⠀⠀⠀⣾⡇⢎⣼⣿⣿⣿⣿⠀⠀⣼⣿⣷⣯⣿⣏⣬⣘⣄⣊⡱⡠⢎⠰⣁⣻⣇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣸⡇⢜⡈⠦⣁⠻⣿⡷⢯⣿⣷⡠⣅⡲⣆⢧⣎⢷⣱⢯⣞⡷⣫⣞⡭⢷⢮⡝⣮⢳⣝⣣⠽⣱⢎⡳⣜
⠀⠀⠀⠀⠀⠀⣿⡇⢢⣿⣿⣿⣿⣿⣶⣾⣿⣿⣿⠿⡿⢟⠿⣿⡿⢿⣿⣿⣿⣿⣿⣋⡁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣀⣠⣤⣶⠾⠟⠟⣋⢑⠢⡘⠤⡑⢢⠹⣿⣟⠾⣿⣿⣷⣻⣽⣻⣞⣯⢯⡷⣯⣽⡳⣽⣚⡯⢾⣹⢎⡷⣺⠼⣹⢣⡞⣱⢎
⠀⠀⠀⠀⠀⠀⢸⣧⣶⣿⣿⡟⢻⣿⢻⡟⠋⡅⢢⠑⡌⡌⠒⣤⠘⠂⣦⠙⠛⢻⢻⣿⣿⣿⣷⣦⡔⠒⣤⡄⠀⠀⠀⢠⣶⣿⠛⠉⢩⡄⠊⢱⠘⣤⠊⢱⠈⡆⢱⢢⢡⢻⣿⡏⣿⣿⣿⣯⣷⡟⣾⣭⡟⣷⠛⣶⢻⣵⡏⣾⢻⡜⠋⡖⢡⡟⣵⢫⡜⢳⡎
⠀⠀⠀⠀⠀⢀⣼⡿⢋⠿⢃⡜⠸⣧⡿⢃⡱⢉⠆⡱⢈⡔⢡⠢⡑⠎⣄⠓⡌⠲⣈⠍⣉⠛⠻⠿⣿⣷⣬⣉⠒⠢⣄⠀⢿⡖⣨⠑⣢⠘⣌⠡⡒⢌⡘⢢⠑⡸⢄⢪⠐⡪⣿⣿⣱⢿⣿⣿⢯⣟⡷⣯⢿⣽⡻⣽⢯⣶⣛⣧⢯⡝⣯⣔⣫⡜⣧⢯⡹⢞⡼
⠀⠀⠀⢀⣴⡿⢋⢄⠣⢚⣤⣼⡷⠿⠷⠿⠾⠿⠾⢳⠛⠾⢷⣦⣵⣭⣤⣉⡒⠱⣠⠚⡄⢫⠔⡡⢂⢿⡍⠀⠀⠀⢻⣄⠘⣿⣦⣱⡀⠧⢠⠓⡌⢒⠌⢢⢉⡔⢊⠤⢃⡅⢻⣷⣏⣿⣻⣿⢿⡽⣻⢽⣻⢾⣽⡳⣟⣶⡻⣼⣣⢟⣶⡹⢶⡹⣎⢷⡹⢯⡜
⠀⠀⢀⣾⠏⡰⢌⣦⣿⠟⣫⠱⡘⠤⠓⡌⢆⠣⠌⡅⢎⡑⠢⡔⠌⡬⢉⠛⡻⢷⣦⣵⣈⠖⡨⢒⠡⢺⣇⠀⠀⠀⠸⢿⣿⣿⣿⣿⣿⣦⡃⡜⢠⠣⢌⡡⢆⡘⢄⠃⢎⡐⢣⢿⣞⡾⣽⣿⠁⠂⠡⢚⡽⣯⢾⣽⣛⣶⣻⢧⣏⣟⢶⣛⡧⣟⡼⣣⢟⣣⠽
⠀⡡⣸⡟⣠⣵⣾⠛⠤⣉⠄⢣⠘⡔⢣⠘⠤⡉⡜⣐⠊⡔⢣⠘⡌⠔⢣⠡⡑⠦⡘⢌⡹⢛⢶⡣⢜⡠⢙⠳⢦⣤⠖⡨⠙⠿⣿⣿⣿⣿⣿⣾⣤⡃⢎⠰⢂⠜⣠⠉⠆⡜⢡⣿⣯⡟⣽⣿⣳⣌⣦⣟⡾⣽⣻⣾⣿⣾⣷⣛⣮⡟⣮⢟⡼⢧⡻⣵⢫⡞⡽
⠠⢱⣿⢡⡾⢋⡤⢉⠖⡨⠌⡅⢎⠰⡁⢎⠱⢠⠱⢠⢩⣰⣡⣧⣬⣽⣤⣧⣼⣄⡱⡈⡔⠩⣌⠳⠸⢿⣦⣑⠢⡔⣘⠰⣉⠒⡈⠽⣿⣽⣻⣿⣿⣿⣦⡉⣌⠲⠠⢍⡘⣤⣷⣿⡳⣿⣽⣿⣿⣟⡾⣽⣻⡿⢛⠡⣄⣽⣿⣿⣞⡽⢧⣯⣛⢧⡛⠐⢫⢞⡽
⣀⠣⣿⡆⡏⡜⣶⣥⣎⡐⠣⠜⡠⢣⠱⣈⠎⣡⣾⠷⠛⠉⠉⠀⠀⠀⣀⣾⠄⠉⠙⠛⠳⣷⣤⣉⠱⢂⡍⠻⣷⣖⣈⠖⣠⠃⡜⠰⡈⢿⣷⣯⢿⣿⣿⣿⣦⡁⢏⣴⣾⡿⢯⣗⠿⣵⣻⣿⡿⣽⣿⠿⢋⣔⣣⣿⣿⣿⣿⣿⣏⡿⣳⢮⣝⠾⣐⢌⢲⣫⢞
⢀⠣⢻⣷⡃⡜⣿⡯⡝⢣⢉⠬⡑⢢⠱⣸⣾⠋⠁⠀⠀⠐⠳⠲⣤⠞⣿⡏⠀⠀⠀⣿⡄⠀⠈⠙⠳⣧⣌⠱⣠⠙⡛⣾⣄⢣⠘⡡⠜⣠⠛⣿⣷⣫⢿⣿⣿⣿⣾⢿⡽⣹⣛⣮⣟⣷⣿⣿⣿⡿⣫⣶⣿⢿⣿⣻⣽⣾⣿⣛⣾⢳⣏⡷⣞⢯⡽⣮⣷⣝⡮
⠈⢆⠡⢹⣷⡖⣐⡻⢿⣐⢊⡔⢡⣦⣷⣿⠁⣠⣤⣶⠖⢦⡈⢷⣤⠟⠁⠀⠀⠀⢸⡏⢿⡄⠀⠀⠀⠀⠙⢷⣤⠙⡰⣈⠹⢻⣮⣔⠱⡠⢍⡘⢿⣷⣏⡾⣽⢿⣞⣧⣟⢷⣻⡼⣞⣾⣿⣿⣿⣿⣿⣻⣽⣻⣾⣿⡿⣯⣗⡟⣾⢳⣞⣳⣽⣿⣟⣯⠷⣉⢻
⠈⠆⡡⢂⠹⢿⣦⣁⠎⡹⢻⣾⣿⣿⣿⠇⠀⠙⠿⢿⠳⠿⢷⣎⣀⣠⣴⣄⠀⠀⠘⣷⡄⠙⠳⣦⣤⡀⠀⠀⠙⢿⣴⡢⢍⠒⣌⠹⢷⣦⡑⢌⣂⠻⣿⣾⢭⣻⢿⣷⣞⡯⣷⢻⣿⣿⣿⣟⣷⣻⣞⣷⣻⣿⣟⣯⢷⣛⣮⣟⠾⣽⢮⣿⣿⣻⢾⡝⡒⢄⣺
⠀⠡⠐⠈⠀⠀⠉⣻⣶⣁⢎⣿⣿⠋⠁⠀⠀⠀⠀⠀⢰⣿⡟⡻⢿⣿⣿⣿⣧⡄⠀⢸⣷⣾⣗⠒⢦⡀⠀⠀⠀⠀⠻⣿⣮⣒⠌⡜⢤⠙⢿⣦⢢⡑⡘⢿⣯⣷⣛⡾⣿⣿⣽⣿⣿⣿⣟⣾⠳⣻⣞⣿⣿⣿⣿⣞⣯⣟⡾⣭⣟⣳⣿⣿⣳⢯⣿⠘⡐⣾⣯
⠀⠀⠀⠀⠀⠀⠀⠈⡾⣿⣿⡟⠀⠀⠀⠀⠀⠀⠀⠀⠀⢿⣷⠿⢾⠿⠉⠙⠻⠟⠀⠙⣇⢻⣏⢻⣶⣿⡆⠀⠀⠀⠀⢹⣿⣿⣾⡔⡌⢚⠤⡙⢷⣎⠔⡊⠽⣷⣯⡽⣞⡿⣿⣿⣿⡟⠋⠀⠀⠀⣿⣿⣟⣾⣿⣿⢾⣹⠿⣵⣾⣿⡿⣾⣽⠿⡁⢎⣾⣿⢲
⠀⠀⠀⠀⠀⠀⠀⠀⡐⢼⡿⠀⣀⣀⣠⣤⣤⡀⠀⠀⢠⡾⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⠳⣝⣿⣷⣿⣷⢶⡀⠀⠀⠀⢻⣿⣿⢿⣮⡐⠜⠤⢃⢻⣮⡑⢆⠹⣿⣷⣫⠿⣽⣿⣿⠀⠀⠀⠀⣠⣿⣿⣾⣿⣿⢯⣿⣽⣿⣽⣿⢯⣟⣷⠟⣠⣱⣿⡿⣎⠷
⠀⠀⠀⠀⠀⠀⠀⠀⠄⢺⡇⢰⡟⠁⠀⠀⠀⠙⠳⣄⣾⠁⠀⠀⢀⡀⠀⠀⠀⠀⣀⠀⠀⠀⠀⠠⣀⠐⠚⠋⠁⠀⠀⠀⠈⣿⣿⣯⣟⣷⡨⢑⠪⢄⠹⣿⡌⢒⠹⣿⣧⡟⣷⡽⣿⣶⣶⣶⣾⣿⣿⣿⣿⣿⣽⣿⣿⣿⣿⣻⣽⣻⣾⠏⣢⣿⡿⣏⠷⣭⣛
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠘⣿⡈⠧⣄⡀⠀⠀⠀⠀⠀⠉⠉⠉⠉⠉⠉⠛⢦⡀⠀⢻⡆⠀⠀⠀⠀⠈⣧⠀⠀⠀⠀⠀⠀⠀⣿⡟⣿⡾⣽⣷⡍⠢⣉⠒⡌⢿⣌⢒⠹⣿⡽⣞⡽⣽⣿⣯⢿⡝⣯⣿⣿⣿⢿⡿⣟⣯⡷⣯⢷⣯⡿⢡⣾⣿⣿⣟⡾⣽⢣⡟
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⠹⣦⢿⣿⣿⣶⣤⣄⣤⣄⠀⠀⠀⠀⠀⠀⠀⠛⢦⠈⣷⠀⠀⠀⠀⠀⢸⡀⠀⠀⠀⠀⠀⣼⡿⣩⢿⣿⢶⡻⣿⡄⠤⡑⠬⡘⢻⣎⢒⡹⣿⡽⢾⣱⡟⣿⣿⣜⢠⢛⣷⣯⢿⣽⣻⢾⡽⣯⡿⣫⣼⣿⣿⣻⣿⣟⡾⡵⣯⢽
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⣿⣿⣿⣿⣿⣿⣿⣿⣿⣶⣶⣤⣀⠀⠀⠀⠈⢳⡘⢇⠀⠀⠀⠀⠀⠇⠀⠀⠀⠀⣼⡿⣳⣙⢾⣿⢯⣽⢻⣿⣆⠱⢌⠒⡡⢻⣧⠒⣹⣿⣏⢷⣻⣽⣿⣯⢷⣯⣟⣾⣻⢾⡽⣯⣿⣽⣿⢿⣻⣽⣿⣿⣻⠾⣝⡷⣏⡾
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢸⣿⣿⣿⣿⣿⡿⣟⢻⡛⣟⠻⣿⣿⣷⣶⣄⡀⢱⡌⠀⠀⠀⠀⠀⠀⠀⠀⢀⣾⡿⣱⢇⣻⣾⣟⣻⡼⣳⠽⣿⡜⠢⢍⠴⡁⢾⣷⠠⢻⣿⣧⣻⡼⣻⣿⣻⢾⡽⣾⣽⣿⢿⡿⢿⣻⣯⣿⣿⡿⣟⡾⣽⣻⣽⣛⡾⣽
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢸⣿⣿⢟⣽⣿⢱⢪⣑⠞⣬⢓⡖⣬⢛⡿⣿⣿⣿⡇⠀⠀⠀⠀⠀⡀⠀⢠⣿⣿⣶⣽⣮⣿⣟⣾⣿⣳⢿⣝⣻⢿⣧⣌⢢⠑⡌⢻⣎⢡⢻⣷⣳⣽⢻⣿⣿⡿⢟⡛⣍⣢⣦⣿⣿⣿⣿⣿⣻⣽⢿⡽⣷⣻⢾⣽⣻⡼
⠀⠀⠀⠀⠀⠀⠀⠀⣀⣠⣤⣤⣴⢾⣿⢋⡾⠋⠀⠈⠙⠻⢿⣤⣋⢶⣬⣧⣽⣿⣷⡿⠃⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠻⣿⣿⢾⣿⣿⣿⣯⡿⣿⣯⡿⣷⣘⡰⢁⢿⣆⢹⣿⣷⢫⣟⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣯⣷⡿⣯⣿⣻⢷⣻⣟⡾⡵⣛
⠀⠀⠀⠀⠀⠀⢠⡾⠋⢁⣴⠞⣣⡿⠁⣿⠁⡀⠀⠀⠀⠀⠀⠙⠻⣤⣄⠠⠘⢿⣿⠇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠙⢿⣷⣿⣿⣳⡻⣿⣿⣿⡛⣅⠪⣿⢼⣿⢞⣻⣞⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣷⣿⣟⣿⣟⣷⢿⣻⣟⣾⣽⣳⢯
⠀⠀⠀⠀⠀⠀⠹⣷⣤⡾⠃⢠⣿⠃⠀⣿⡀⠉⠷⣄⡀⠀⠀⠀⠀⠈⠉⠛⠶⣼⡛⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠉⠙⠛⠛⠻⠿⢾⣿⣿⣦⣃⠝⣾⣯⢯⣳⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣯⣿⣯⣿⣟⣾⣟⣾⣽⢿
⠀⠀⠀⠀⠀⠀⠀⠛⠉⠀⠀⣾⢿⡀⠀⠻⢿⣦⣄⡈⠙⢶⣤⣀⣀⠀⠀⠀⢀⣼⢿⠆⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠘⠙⣿⣿⡿⣏⣷⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣽⣿⣿⣽⣿⣻⣿⣾⣟⣾⣿
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠹⣎⠳⣄⠀⠀⠉⠛⠿⣿⣶⣤⣤⣭⣴⣬⣶⠟⢡⡞⠀⢨⣾⠃⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣶⣿⣿⣶⣶⣶⣶⣶⣦⣤⣤⣀⣀⠀⠀⠘⠻⢿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡟⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⢿⣾⣿⢿⣾
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠘⣿⡜⠻⢄⡀⠀⠀⠀⠘⠻⠿⠿⠻⠛⠃⢠⡟⠀⣠⣿⡿⠧⣤⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠛⠻⠟⢛⣿⣿⣿⣿⣿⣤⣿⣿⣿⣄⠀⠀⠀⠀⣻⣿⣿⣿⣿⣿⣿⣿⣿⣿⣧⢿⣼⣿⣿⣿⣿⣿⣿⣟⣿⣿⣿⣿⢿⣿⣿
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣴⡏⠹⣦⡀⠈⠓⠦⣄⣀⠀⣀⣀⣀⣤⠞⢣⣿⡼⠛⠁⠀⠀⠈⠛⠙⠓⠓⢦⣶⣀⠀⠀⣤⣀⠀⠀⠾⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣧⡀⠀⠀⠻⢿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⢿⣿⣿⣿
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢸⠏⠳⠀⠀⠉⠛⠶⣤⣀⣉⣿⣭⣈⣁⣠⡾⠛⠁⠀⠀⠀⠀⠀⢀⣠⠟⠀⢠⣾⣿⡹⣷⣄⠈⢿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣄⣀⣀⣤⣼⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⢿⣻
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣿⠀⠀⠀⠀⠀⠀⠀⠀⠀⠉⠉⠀⠉⠉⠁⠀⠀⠀⠀⠀⠀⠀⢾⡏⠀⠀⠀⠀⣿⡷⣭⣿⠟⣧⡀⠻⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⢿⣻⣿⢿
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣿⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠰⢦⠀⠑⠀⠀⠀⠀⣿⣟⢶⣿⠀⠈⢷⡀⠹⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣞⣽⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡿⣿⠽⣞⢯⠳⣭⢫
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣿⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠛⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢠⣿⢏⣾⡇⠀⠀⠀⢻⣄⠹⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⢿⣻⠳⢏⢇⡛⢬⡒⣍⠦⢣
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢹⡆⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣾⣟⣾⡟⠀⠀⠀⠀⢈⣿⣆⢻⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡿⣟⠯⢏⢇⢣⠙⡌⠦⡙⠦⡱⢌⡚⢥
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢨⣿⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣼⣿⣳⡟⠀⠀⠀⠀⠀⣸⣿⣿⡆⢿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⢿⣟⢯⠓⢏⠺⡙⢯⠻⡙⢯⠻⡹⠞⡹⠌⠣⢌⠢⢌⢊⠴⣁⠣⢣⢑⠪⢜⠢
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢠⣿⣿⣧⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣼⣿⣿⡿⠁⠀⠀⠀⠀⣰⣿⣿⡟⠃⣸⣿⣿⠿⡝⠯⠻⡽⢳⠏⡞⠹⠈⠂⠉⠀⠀⠁⠂⠁⠈⡀⠡⢀⠡⠐⣈⠡⢂⠱⡈⢆⠒⡄⠓⡄⡃⢎⢂⠣
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠙⠿⠿⣿⣦⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣾⣿⣿⣿⠇⠀⠀⠀⢠⣶⣿⣿⠋⠀⣰⣿⣿⠃⠀⠀⠀⠁⠀⠁⠈⠀⠁⠀⠀⠀⠀⠀⠀⠀⠁⠐⠀⠀⡀⠂⠡⢀⠒⡈⢐⡐⢂⠡⢈⠑⠤⡑⢌⠸⡐
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⠻⣿⣦⣄⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣀⣠⣾⣿⣿⣿⠋⠀⠀⠀⣠⣿⣿⣿⣿⣷⣄⣻⡿⠃⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠁⠀⠄⠁⠄⡐⢀⠂⡐⠤⠈⢄⠩⢐⠡⢊⠔⠡
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⠙⢿⣿⣷⣶⣦⣤⣤⣤⣤⣤⣤⣴⣶⣾⣿⢿⣿⣿⣿⡿⠋⠀⢀⣠⣾⣿⡿⠟⠉⠀⡛⠛⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠄⠀⠀⠄⠀⠐⠠⠁⠂⡐⠂⠡⠂⠌⠡

**Comment by HondaChan14** [comment]
CAN WE GET MUCH HIGHER?!!!!!!!

**Comment by adropofilm** [comment]
LGTM

**Comment by jamilsinno** [comment]
Is that you Tony?!

**Comment by HoldUpFjord** [comment]
This is all the confirmation I need that twitter is here to stay. The meme's are too strong.
