### ISSUE TITLE
Turn everyone's profile photo into my cat Pasha

### ISSUE THREAD

**Issue by erenkulaksiz** [twitter/the-algorithm#1476]
**Is your feature request related to a problem? Please describe.**
Turn everyone's profile photo as my cat Pasha.
<img src="https://imgur.com/QZHzeIf.png" alt="pasha" width="200" />

**Describe the solution you'd like**
Changing source of images on profile photos as like this.
`<img src="https://imgur.com/QZHzeIf.png" alt="pasha" />`

**Describe alternatives you've considered**
I wouldn't suggest any other alternatives.

**Additional context**
No.

**Comment by HondaChan14** [comment]
<img src="https://imgur.com/QZHzeIf.png" alt="pasha" />

**Comment by Horlawhumy-dev** [comment]
Cruise

**Comment by MurphyAdam** [comment]
LGTM :+1: ship ASAP

**Comment by jdm-twtr** [comment]
This issue was closed due to possibility of spam. Please re-file with a useful title and description.

**Comment by april83c** [comment]
Seems useful to me

**Comment by TheMemeSniper** [comment]
#JUSTICEFORPASHA ✊✊✊

**Comment by basicallygit** [comment]
jdm-twtr just hating, i think this should be introduced on every social media platform
