### ISSUE TITLE
Join the Fediverse!

### ISSUE THREAD

**Issue by spiralw** [twitter/the-algorithm#1480]
twitter sucks (you most likely already know why twitter sucks), join the federated microblogging (and more) network based on ActivityPub: https://fediverse.party/

Find an instance: https://fediverse.observer/

Software:

Mastodon -> https://joinmastodon.org
Pleroma -> https://pleroma.social (or Akkoma fork: https://akkoma.social)
Misskey -> https://misskey-hub.net/ (mainly JP, [Foundkey](https://akkoma.dev/FoundKeyGang/FoundKey) has better EN docs)

**Comment by Omega207** [comment]
No

**Comment by thekifake** [comment]
where is mastodon

**Comment by samdisk11** [comment]
> where is mastodon

mastodon is server software. its like running your own twitter. you can run your own copy if you want.
