### ISSUE TITLE
Meow

### ISSUE THREAD

**Issue by rrufat** [twitter/the-algorithm#1483]
Update algorithm to show cat tweets only
![image](https://user-images.githubusercontent.com/57920176/229377733-5c2c2698-98a0-4f3d-8803-62bfbef758b6.png)

**Comment by MurphyAdam** [comment]
Please ship ASAP

**Comment by sylentpunk** [comment]
![image](https://user-images.githubusercontent.com/111111098/229378686-8a3f423b-1bfa-46f1-9d9e-d92377f0eb23.png)
My cat inspecting the sink that Elon brought in

**Comment by ankitkat042** [comment]
me furiously searching for cat memes to post here
<img src="https://media.giphy.com/media/heIX5HfWgEYlW/giphy.gif"  />

**Comment by sylentpunk** [comment]
![ket](https://user-images.githubusercontent.com/111111098/233803936-ed119a98-756d-42ca-98a4-81f7e175f2f2.jpg)

**Comment by sogful** [comment]
shark demands this issue to be immediately reopened and reconsidered
![image](https://github.com/twitter/the-algorithm/assets/86375852/7284c6f3-2cf0-42fc-9db3-631fa73d4cb0)
