### ISSUE TITLE
My wife left me

### ISSUE THREAD

**Issue by MurphyAdam** [twitter/the-algorithm#1484]
**Describe the bug**
My wife left me for Chad

**To Reproduce**
1. Chad uses Rust
2. I used Scala
3. Wife left me for Chad

**Expected behavior**
Wife should not leave me

**Possible fix**
Rewrite this in Rust

**Comment by K4rakara** [comment]
Elon should be able to provide some useful insight into this, seeing as his wife left him for a trans woman, and so many trans women are also programmers :thinking:

**Comment by MurphyAdam** [comment]
@K4rakara that sounds very reasonable. @twitter-service can we please get Elon involved ASAP. This urgent. TNX.

**Comment by logicP** [comment]
"I miss my wife Tails, I miss her a lot"

**Comment by fdciabdul** [comment]
what about beta ?

**Comment by lostbox66** [comment]
> Elon should be able to provide some useful insight into this, seeing as his wife left him for a trans woman, and so many trans women are also rust programmers thinking

Can confirm, I've made that mistake more times than I'm willing to admit online.

**Comment by K4rakara** [comment]
1984

**Comment by JGallium** [comment]
I doubt that's why she left you.

**Comment by scottbeamer** [comment]
Have you tried turning yourself off and back on again?

**Comment by C4mperpr0** [comment]
Grrrrrr 😡
