### ISSUE TITLE
Woke up in an emerald mine owned by Elon Musk!

### ISSUE THREAD

**Issue by nonbinarypotus** [twitter/the-algorithm#1487]
**Describe the bug**
Help, I woke up and found myself being a slave in an emerald mine owned by Elon Musk!

**To Reproduce**
1. Get invited to Elon's house
2. Pass out after having a glass
3. Wake up about a day later
4. Find yourself in emerald mine

**Expected behavior**
Wake up normally, not in an emerald mine

**Screenshots**
![image](https://user-images.githubusercontent.com/7067375/229381355-ba3741b2-807d-42cd-8e21-e371dd239d8d.png)
![image](https://user-images.githubusercontent.com/7067375/229381444-8521d97f-4633-48a0-99fb-c3585606bebe.png)

**Environment**
The conditions here are below optimal, everyone is malnourished and receiving the bare minimum of living conditions.

**Additional context**
I haven't been fed in about a week.

**Comment by jdm-twtr** [comment]
This issue was closed due to possibility of spam. Please re-file with a useful title and description.

**Comment by Joshument** [comment]
> This issue was closed due to possibility of spam. Please re-file with a useful title and description.
why is your profile picture the twitter logo there's no way you don't have any better options
