### ISSUE TITLE
The “Kubrick Stare" is one of Stanley Kubrick's most recognizable directorial techniques, a method of shot composition where a character stares at the camera with a forward tilt, to convey to the audience that the character in question is at the peak of their derangement.

### ISSUE THREAD

**Issue by aliu-here** [twitter/the-algorithm#1488]
The “Kubrick Stare" is one of Stanley Kubrick's most recognizable directorial techniques, a method of shot composition where a character stares at the camera with a forward tilt, to convey to the audience that the character in question is at the peak of their derangement.

**Comment by jdm-twtr** [comment]
This issue was closed due to possibility of spam. Please re-file with a useful title and description.
