### ISSUE TITLE
Safety Label Types and Categorization in Code

### ISSUE THREAD

**Issue by danielhaim1** [twitter/the-algorithm#1489]
Please reference to #1524

**Comment by danielhaim1** [comment]
Slava Ukraini 🇺🇦

**Comment by webknjaz** [comment]
@danielhaim1 thanks for the analysis!

**Comment by webknjaz** [comment]
> the Ukraine crisis

I must also add that this is a poor word choice. People who want to represent the objective reality or support Ukraine, aren't afraid to call it invasion/war, as it is. The word "crisis" is mostly used by the ruscist supporters or "neutral" media (which usually also counts as working against Ukraine) — would one call an armed robbery of a convenience store a "store crisis"? Why not?

**Comment by danielhaim1** [comment]
@webknjaz while considering the safety concerns and the fact that the file is easy to read and stands out, I found myself wondering if the code was added around 2014. Regardless of politics, it is clear that the code does not belong in this file. Additionally, I believe this file is frequently accessed.

> > the Ukraine crisis
> 
> I must also add that this is a poor word choice. People who want to represent the objective reality or support Ukraine, aren't afraid to call it invasion/war, as it is. The word "crisis" is mostly used by the ruscist supporters or "neutral" media (which usually also counts as working against Ukraine) — would one call an armed robbery of a convenience store a "store crisis"? Why not?

@webknjaz while considering the safety concerns and the fact that the file is easy to read and stands out, I found myself wondering if the code was added around 2014. Regardless of politics, it is clear that the code does not belong in this file. Additionally, I believe this file is frequently accessed.

**Comment by danielhaim1** [comment]
> > the Ukraine crisis
> 
> I must also add that this is a poor word choice. People who want to represent the objective reality or support Ukraine, aren't afraid to call it invasion/war, as it is. The word "crisis" is mostly used by the ruscist supporters or "neutral" media (which usually also counts as working against Ukraine) — would one call an armed robbery of a convenience store a "store crisis"? Why not?

while considering the safety concerns and the fact that the file is easy to read and stands out, I found myself wondering if the code was added around 2014. Regardless of politics, it is clear that the code does not belong in this file. Additionally, I believe this file is frequently accessed.

**Comment by webknjaz** [comment]
> I found myself wondering if the code was added around 2014

Well, it was still a war in 2014.

**Comment by danielhaim1** [comment]
Why did you close the ticket @maksimru ?

**Comment by chrisidakwo** [comment]
Firstly, sorry for doing this. I see the issue is closed and the change has been made anyway but wanted to give my two cents. No matter how irrelevant that might be.

@webknjaz I think what was being pointed out is that:

1. Rather than single out the Russia/Ukraine conflict, crisis, or war (whatever word you choose), there should be a more generic label to describe these things. From at least 2014 till 2020, UN reports and several others said that the Ukraine government was shelling its own citizens, what label could that have been given for that? Maybe `UkraineShellingCitizensLabel`? When you start going this way, it becomes a slippery slope; making code more political than it should be. Do you then create labels for every single war or conflict or crisis? Remember that there will always be opposing views on issues such as this. So why be too specific?

> Example: Just like there is`MedicalMisinfo` instead of `CovidMisinfo`

**Comment by webknjaz** [comment]
> Do you create labels for every single war or conflict or crisis?

Following the same logic, I suppose you would be fine with a label for racist label tweets being called `MasterSlaveCollab`, right? Words do matter. Making a name generic doesn't mean that using harmful terminology along the way is okay, does it?

**Comment by chrisidakwo** [comment]
Haha, that's totally off from what I said though.

To be honest with you, I really do not care much about nitpicking these things anyway. But at no point did I say it's okay to use "harmful" terminology so the question does not follow.

But then I'm a bit confused (or say curious) as to how you somehow think using generic terms also means allowing "harmful" terminology. It's not a "one come with the other" kind of situation now, is it?

**Comment by chrisidakwo** [comment]
Haha, that's totally off from what I said though.

To be honest with you, I really do not care much about nitpicking these things anyway. But at no point did I say it's okay to use "harmful" terminology so the question does not follow.

But then I'm a bit confused (or say curious) as to how you somehow think using generic terms also means allowing "harmful" terminology. It's not a "one comes with the other" kind of situation now, is it?

**Comment by webknjaz** [comment]
I never said generic is bad. But this specific example was harmful just like your attitude implying that it's okay to call genocide a crisis.
