### ISSUE TITLE
Ukraine Crisis downranked?

### ISSUE THREAD

**Issue by ccstoragedrivez** [twitter/the-algorithm#1497]
Why Ukraine Crisis getting downranked?!

https://twitter.com/aakashg0/status/1641976869460275201
https://www.reddit.com/r/worldnews/comments/129gpui/analysis_of_twitter_algorithm_code_reveals_social/

This is a threat to our freedom of speech and extremely dangerous for our democracy!

**Comment by amicus-veritatis** [comment]
Use Mastodon if you don't like

**Comment by Floofbutt** [comment]
> Use Mastodon if you don't like

Feature request:

Clown emoji for this mans comment.

**Comment by amicus-veritatis** [comment]
@Floofbutt Why? Twitter is a private platform while mastodon is a decentralized, open-source alternative. You can literally build your own platform(instance) if you want. Like or not, Twitter is a scaled-up subreddit (and elon musk is a subreddit moderator) at this point.

**Comment by Floofbutt** [comment]
@amicus-veritatis 

The clown emojii is because you are treating Github comments like they are twitter.

**Comment by amicus-veritatis** [comment]
@Floofbutt You're saying as if this issue is an issue related to the development. If you want to fix this, then make a PR request instead of creating an issue. But this is essentially a discussion thread.

**Comment by NotFlyLoongQaQ** [comment]
fuck you,Twitter!

**Comment by srghma** [comment]
@amicus-veritatis Russians have tourtured by 18 years old friend for flag of Ukraine in mobile phone

https://twitter.com/srghma/status/1766051685632188546

My father is in the army, my mother calls me and cries "russian approach every day to Rodynskoye"

And You defend this idiot Elon Musk in silencing ukranians

I hope after Ukraine putin will attack Your country and rape your mother, like they did in Bucha
