### ISSUE TITLE
April 1st tweet expiration

### ISSUE THREAD

**Issue by m-a-sch** [twitter/the-algorithm#1499]
**Is your feature request related to a problem? Please describe.**
Users don't mention if their April 1st tweet are pranks. 

**Describe the solution you'd like**
All tweets dated April 1st are deleted on April 2nd

**Describe alternatives you've considered**
profile picture of the user is replaced with the picture of a clown

**Comment by shubshub** [comment]
I see this Issues List is gonna become a steaming pile of unproductability very quickly as the Developers struggle to find genuine issues being reported with stupid stuff like this
