### ISSUE TITLE
Python code is broken on musl

### ISSUE THREAD

**Issue by w3bb** [twitter/the-algorithm#1500]
**Describe the bug**
When loading the below images, as well as others on musl systems with the NSFW model, it has a segmentation fault
**To Reproduce**
1. Install the toolchain on a distro running musl
2. Run the model with the below images:
![](https://webber.rocks/ebcb3aff.webp)
![](https://webber.rocks/b4587a9e.jpg)
![](https://webber.rocks/93eb996a.jpg)
![](https://webber.rocks/4d83c21b.jpg)
![](https://webber.rocks/ff2adcc8.png)
![](https://webber.rocks/6c3bc393.jpg)
![](https://webber.rocks/1a6e65de.jpg)
![](https://webber.rocks/40db49c9.jpg)
4. Observe error

**Expected behavior**
It should execute as expected without segfaulting

**Environment**
Void Linux x64 (musl)

**Comment by Joshument** [comment]
concerning!
