### ISSUE TITLE
"For you" Actually just full of Gore, Porn, and Conspiracy theories/other not safe for life content on new account creation

### ISSUE THREAD

**Issue by Floofbutt** [twitter/the-algorithm#1501]
**Describe the bug**
Read Title. Not even trending stuff or blue checks. What the actual Fuck elon

**To Reproduce**
1. Clear browser cache/cookies/history
2. Log onto twitter with a new account, follow no trends or individuals
3. Wait and see

**Expected behavior**
NOT THIS

**Screenshots**
If I attached them I'd be actually banned

**Environment**
Any browser I assume. Occurs on both chrome/firefox

**Additional context**
This is actually not a shitpost What the actual fuck.

**Comment by newscoffee** [comment]
take a screenshot and use blur to censor out stuff, im curious about this

**Comment by foodornt** [comment]
fr wtf this never happened to me, even though I create accounts pretty regularly

**Comment by ValZapod** [comment]
I got these mailed to me:

![Screenshot_20230407_042134_Yandex Mail](https://user-images.githubusercontent.com/31514790/230521361-49b4663a-10fe-4813-81d2-d7d917802d7e.png)
