### ISSUE TITLE
Maia Arson Crimew does not appear 100% of the time 

### ISSUE THREAD

**Issue by TheMemeSniper** [twitter/the-algorithm#1502]
**Describe the bug**
Maia Arson Crimew does not appear 100% of the time  on For You

**To Reproduce**
Go to "For You", press CTRL+F and type "maia". No results will appear 

**Expected behavior**
Gay kitten appears on the timeline

**Screenshots**

**Environment**
Arch Linux x86_64 Firefox v111

**Additional context**
if you're a twitter employee i'm sorry

**Comment by TouchstoneTheDev** [comment]
LOL @TheMemeSniper
