### ISSUE TITLE
Segmentation fault error

### ISSUE THREAD

**Issue by w3bb** [twitter/the-algorithm#1511]
Reposting because the original issue was closed for no reason?

**Describe the bug**
When loading the below images, as well as others on musl systems with the NSFW model, it has a segmentation fault
**To Reproduce**
1. Install the toolchain on a distro running musl
2. Run the model with the below images:
4. Observe error

**Expected behavior**
It should execute as expected without segfaulting

**Environment**
Void Linux x64 (musl)

**Comment by yhw2003** [comment]
hhh
