### ISSUE TITLE
Topic/Interests block/Filter

### ISSUE THREAD

**Issue by mikedepo** [twitter/the-algorithm#1512]
**I get frustrated when my feed gets flooded everyday by a specific topic I would like to not hear about. Example: you engage on a Tweet about woke stuff, the algorithm thinks you're likely to engage and begins feeding you with woke content. After a while, you just want to forget about it and it keeps coming in your thread. 

**Describe the solution you'd like**
We need a way to see which topics or interests we're currently attached to and allow us to remove them, or block them. 

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by JMD110** [comment]
Agree with you. Perhaps if the recommended content is browsed for a short period of time within a certain time frame, it should be considered to gradually decrease its frequency until it is no longer recommended.

**Comment by jdm-twtr** [comment]
Thanks for filing. We've marked this issue as an unrelated bug or feature for future review.
                    In order to keep our issue count manageable, we will not be leaving these issues open. We apologize for
                    the inconvenience. If you feel that we closed your issue in error, please re-file the issue, stating how
                    the requested feature applies to the recommendation algorithm components that have been open-sourced thus far.
