### ISSUE TITLE
Increase the outgoing DM message cap for Twitter Blue users

### ISSUE THREAD

**Issue by shylaatchison** [twitter/the-algorithm#1529]
**Is your feature request related to a problem? Please describe.**
I'm in a bunch of groupchats and this is the second time I've hit the outgoing DM message cap. There's not even a warning system. I literally pay for this despite price discrimination for being a power user ($11/month instead of $8 in CA). What's fair is fair, so please let me be the power user that I am, INCLUDING VIA DMs. Some of us just type out our paragraphs sending them a few sentences at a time instead of sending long, overwhelming messages.

**Describe the solution you'd like**
Please add a warning system for users to be notified when they're approaching their outgoing DM limit and additionally increase the outgoing DM limit for Twitter Blue users.

**Describe alternatives you've considered**
I've tweeted at Elon and at Twitter Blue but that's useless. I cannot touch grass at this time as it's 2:30am.

**Additional context**
I'm sad. Other people are sad because they don't know what happened. This hurts people and could potentially cause interpersonal communication issues for people. Please fix this soon so we can all be less sad. :(

**Comment by jdm-twtr** [comment]
Thanks for filing. We've marked this issue as an unrelated bug or feature for future review.
                    In order to keep our issue count manageable, we will not be leaving these issues open. We apologize for
                    the inconvenience. If you feel that we closed your issue in error, please re-file the issue, stating how
                    the requested feature applies to the recommendation algorithm components that have been open-sourced thus far.

**Comment by shylaatchison** [comment]
Where shall I file this feature/bug issue instead? There's no customer service on Twitter.
