### ISSUE TITLE
The Primeagen

### ISSUE THREAD

**Issue by ma1ted** [twitter/the-algorithm#1536]
**Is your feature request related to a problem? Please describe.**
No Primeagen

**Describe the solution you'd like**
The Primeagen

**Describe alternatives you've considered**
Theo

**Comment by maddsua** [comment]
lol it's not twitch

**Comment by FrostyNick** [comment]
> lol it's not twitch

ThePrimeagen is active on GitHub lol

**Comment by chikof** [comment]
ThePrimeagen

**Comment by chikaof** [comment]
ThePrimeagen

**Comment by Yowezy** [comment]
c--

**Comment by maddsua** [comment]
> > > no fucking clue what a primeagen is but please dont write it in rust
> > 
> > 
> > The Holy C will do
> 
> at least not rust what can i say

oh by the way, is Rust any good? for real

**Comment by joshmuente** [comment]
context: https://www.youtube.com/watch?v=2gG08VUuwzg

**Comment by TruncatedDinosour** [comment]
> > > > no fucking clue what a primeagen is but please dont write it in rust
> > > 
> > > 
> > > The Holy C will do
> > 
> > 
> > at least not rust what can i say
> 
> oh by the way, is Rust any good? for real

im not a fan of rust, people like it though, so i mean if you want to try it you should, programming is fun, go for it

**Comment by maddsua** [comment]
> > > > > no fucking clue what a primeagen is but please dont write it in rust
> > > > 
> > > > 
> > > > The Holy C will do
> > > 
> > > 
> > > at least not rust what can i say
> > 
> > 
> > oh by the way, is Rust any good? for real
> 
> im not a fan of rust, people like it though, so i mean if you want to try it you should, programming is fun, go for it

So I tried. It asked me if the GCC is installed. I launched my GCC environment and coded the damn thing in C. Heck yeah

**Comment by phoenix5k** [comment]
XDD
