### ISSUE TITLE
remove bots

### ISSUE THREAD

**Issue by LimePotato** [twitter/the-algorithm#1542]
There is this not account (at)elonmusk that needs to be dealt with, it won't stop spamming everything. Make bot stop being recommended in algorithm.

I dont like it.

**Comment by TruncatedDinosour** [comment]
L + bozo + didnt ask

**Comment by LimePotato** [comment]
> L + bozo + didnt ask

I am infact, winning.

**Comment by username24532** [comment]
ratio

**Comment by sokorototo** [comment]
win deez nutz fool
