### ISSUE TITLE
Disable nsfw content/accounts

### ISSUE THREAD

**Issue by 3mpj** [twitter/the-algorithm#1545]
**Problem**
Ease of access to nsfw content on the timeline. 

**Solution**
Tweets with nsfw content to be tagged as nsfw by the authors.  
A button to disable nsfw tagged content from the timeline.

**Comment by TruncatedDinosour** [comment]
i like seeing hot men though :(

**Comment by hasanpasha** [comment]
> i like seeing hot men though :(

Nobody asked.

**Comment by cupofdirtfordinner** [comment]
i love seeing penis on the timeline

**Comment by Foxlass** [comment]
![stock-photo-businessman-relaxing-office-chair-standing-on-his-head-isolated-7869196](https://user-images.githubusercontent.com/53279832/229576175-9435a807-120d-43cb-9a17-e6ca54dac5ea.jpg)
Some real Not Safe For Work content right here

**Comment by TruncatedDinosour** [comment]
> > i like seeing hot men though :(
> 
> Nobody asked.

yeah, nobody asked to reply

**Comment by TruncatedDinosour** [comment]
> i love seeing penis on the timeline

me too
i dont use twitter though lmfao

**Comment by atharvbhagya** [comment]
> **Problem** Ease of access to nsfw content on the timeline.
> 
> **Solution** Tweets with nsfw content to be tagged as nsfw by the authors. A button to disable nsfw tagged content from the timeline.

We may use the ligma engine

**Comment by jdm-twtr** [comment]
Thanks for filing. We've marked this issue as an unrelated bug or feature for future review.
                    In order to keep our issue count manageable, we will not be leaving these issues open. We apologize for
                    the inconvenience. If you feel that we closed your issue in error, please re-file the issue, stating how
                    the requested feature applies to the recommendation algorithm components that have been open-sourced thus far.
