### ISSUE TITLE
Unless you like a post, refreshing shows it again

### ISSUE THREAD

**Issue by JensDevWoW** [twitter/the-algorithm#1554]
**Describe the bug**
When refreshing the "For You" tab, I expect it to show me things I have yet to see. I don't want to have to like every single post I see in order to not see it again when refreshing. However, it will still show the same post over and over again until I like it.

**To Reproduce**
Simply refresh the "For You" tab after scrolling a bit down and you will see the same posts.

**Expected behavior**
I expect it to log the "seen" posts I have and removes them from the For You list.

**Screenshots**
Simply test it yourself, works every time.

**Environment**
Currently using Android OS

**Additional context**
None

**Comment by jdm-twtr** [comment]
Thanks for filing. We've marked this issue as an unrelated bug or feature for future review.
                    In order to keep our issue count manageable, we will not be leaving these issues open. We apologize for
                    the inconvenience. If you feel that we closed your issue in error, please re-file the issue, stating how
                    the requested feature applies to the recommendation algorithm components that have been open-sourced thus far.
