### ISSUE TITLE
Legacy badges, but new badges shouldn’t be in badges shape it

### ISSUE THREAD

**Issue by tamaghan** [twitter/the-algorithm#1559]
Title is enough!

I need different badges for different professions which tells me the authenticity of the user by profession.

**Comment by jdm-twtr** [comment]
Thanks for filing. We've marked this issue as an unrelated bug or feature for future review.
                    In order to keep our issue count manageable, we will not be leaving these issues open. We apologize for
                    the inconvenience. If you feel that we closed your issue in error, please re-file the issue, stating how
                    the requested feature applies to the recommendation algorithm components that have been open-sourced thus far.
