### ISSUE TITLE
add my cat to the algorithm 

### ISSUE THREAD

**Issue by NishantMajumdar** [twitter/the-algorithm#1566]
add my cat to the algorithm.

**Comment by TruncatedDinosour** [comment]
https://github.com/twitter/the-algorithm/issues/871 lets add my cat too

**Comment by bogdanbpeterson** [comment]
oh boi, it's you @TruncatedDinosour

**Comment by bogdanbpeterson** [comment]
I def need your twitter or smth

**Comment by TruncatedDinosour** [comment]
> I def need your twitter or smth

i dont use twitter, i just think twitter deserves to be clowned on by releasing two joke repos lmfao

**Comment by austinjohnson14** [comment]
Why was this closed?
