### ISSUE TITLE
"Tweet" button drop shadow is cropped

### ISSUE THREAD

**Issue by fanfare** [twitter/the-algorithm#1568]
this has been an issue for years

 ![Tweet](https://i.jollo.org/VUWfJHJ6.png)

**Comment by avezqureshi14** [comment]
can you assign me this issue, I can work on it

**Comment by TruncatedDinosour** [comment]
i mean this isnt an algorithm issue
this is purely the frontend

anyway L + bozo + didnt ask

**Comment by pratik-wadhai** [comment]
can you assign this issue to me  check my profile to see my work

**Comment by UraxUser** [comment]
Assign this issue to me, would done in no time. I am pro at backend dev.

**Comment by jdm-twtr** [comment]
Thanks for filing. We've marked this issue as an unrelated bug or feature for future review.
                    In order to keep our issue count manageable, we will not be leaving these issues open. We apologize for
                    the inconvenience. If you feel that we closed your issue in error, please re-file the issue, stating how
                    the requested feature applies to the recommendation algorithm components that have been open-sourced thus far.
