### ISSUE TITLE
Pinned Replies

### ISSUE THREAD

**Issue by MichelleWhitzel** [twitter/the-algorithm#157]
I have found when replying to someone, the reply can quickly become misunderstood and can easily start a firestorm of hate. If you reply again to your tweet or the original tweet, it just gets lost in all the hate replies. What would help with avoiding this would be to have the option to pin a reply to your original reply. Only to your reply though. This would make a better overall user experience and cause less hate and misunderstandings.

**Comment by TheRedLancer** [comment]
"Better overall user experience"? Are you trying to make twitter a better place?

Please provide a way to replicate this issue. I will need something problematic to add as a reply to a politician's Tweet by EOD. Thank you.

**Comment by jdm-twtr** [comment]
Thanks for filing. We've marked this issue as an unrelated bug or feature for future review.
                    In order to keep our issue count manageable, we will not be leaving these issues open. We apologize for
                    the inconvenience. If you feel that we closed your issue in error, please re-file the issue, stating how
                    the requested feature applies to the recommendation algorithm components that have been open-sourced thus far.
