### ISSUE TITLE
Elon i think it was a bad idea...

### ISSUE THREAD

**Issue by th3knv** [twitter/the-algorithm#1576]
It was a bad idea making algorithm open source. Now everyone can post their sh*ts in issues 😆

**Comment by TruncatedDinosour** [comment]
no it wasnt
i love when companies look idiotic by not knowing how to open source
and just release the plain source code with 0 commit history, docs or anything

god, i love corporate

**Comment by TruncatedDinosour** [comment]
also love to see the creepy shit in the src, imagine whats going on in the proprietary parts

**Comment by th3knv** [comment]
> also love to see the creepy shit in the src, imagine whats going on in the proprietary parts

haahahah

**Comment by cupofdirtfordinner** [comment]
reopen!!!
