### ISSUE TITLE
Add an exception option

### ISSUE THREAD

**Issue by LyAVALE95** [twitter/the-algorithm#1577]
Please add an exception option to the search engine, to avoid some users or text when you're looking for certain info.
And take care of your employees ;)

**Comment by jdm-twtr** [comment]
Thanks for filing. We've marked this issue as an unrelated bug or feature for future review.
                    In order to keep our issue count manageable, we will not be leaving these issues open. We apologize for
                    the inconvenience. If you feel that we closed your issue in error, please re-file the issue, stating how
                    the requested feature applies to the recommendation algorithm components that have been open-sourced thus far.
