### ISSUE TITLE
fix troll issues 

### ISSUE THREAD

**Issue by aymaneallaoui** [twitter/the-algorithm#1593]
https://github.com/aymaneallaoui/isuess-lol

"Haha look guis I'm soo funny :DD". Here's my recommendation: Stop being a scatterbrained imbecile. Fabricating capricious and flimsy arguments (such as the one proffered above in your first comment here) in order to justify defecating upon this place due to your ideologically motivated opposition to the wealthy elite (although I believe that's just some made-up excuse to troll) is, quite frankly, one of the dumbest and obvious hypocritical takes one can provide. Especially since it's on discord which is a subsidiary of Microsoft.

**Comment by TensorsWillFlow** [comment]
I agree. The cringe left wingers have to make *everything* political. 

You don't like the rocket man, we get it. Move on.

**Comment by datgreatkhan** [comment]
> I agree. The cringe left wingers have to make _everything_ political.
> 
> You don't like the rocket man, we get it. Move on.

So in the very same sentence where you whine about making everything political, you make it political by assuming anyone who criticizes or disagrees with Elon Musk and what he does is a "cringe left winger"? The irony is hilarious. Sounds to me you are the only one making it political.

**Comment by TensorsWillFlow** [comment]
> 

Don't think so sir. I think I'm pointing out what already happens to be the case. 

Also, nice strawman - I never said *any* Elon criticism makes someone a cringe left winger, just the ones literally spamming the communist manifesto on a GitHub repository meant to bring transparency to the most prominent social media platform in the western hemisphere, which has long been used to manipulate debates and astroturf society at large.

**Comment by TensorsWillFlow** [comment]
> > I agree. The cringe left wingers have to make _everything_ political.
> > You don't like the rocket man, we get it. Move on.
> 
> So in the very same sentence where you whine about making everything political, you make it political by assuming anyone who criticizes or disagrees with Elon Musk and what he does is a "cringe left winger"? The irony and hypocrisy is hilarious. Sounds to me you are the only one making it political.

Don't think so sir. I think I'm pointing out what already happens to be the case.

Also, nice strawman - I never said any Elon criticism makes someone a cringe left winger, just the ones literally spamming the communist manifesto on a GitHub repository meant to bring transparency to the most prominent social media platform in the western hemisphere, which has long been used to manipulate debates and astroturf society at large.

**Comment by aymaneallaoui** [comment]
> > > I agree. The cringe left wingers have to make _everything_ political.
> > > You don't like the rocket man, we get it. Move on.
> > 
> > 
> > So in the very same sentence where you whine about making everything political, you make it political by assuming anyone who criticizes or disagrees with Elon Musk and what he does is a "cringe left winger"? The irony and hypocrisy is hilarious. Sounds to me you are the only one making it political.
> 
> Don't think so sir. I think I'm pointing out what already happens to be the case.
> 
> Also, nice strawman - I never said any Elon criticism makes someone a cringe left winger, just the ones literally spamming the communist manifesto on a GitHub repository meant to bring transparency to the most prominent social media platform in the western hemisphere, which has long been used to manipulate debates and astroturf society at large.

It is unfortunate to witness political polarization and conflict between individuals with differing ideologies, particularly when it results in physical altercations or violence. Such behavior not only undermines the principles of democracy and civil discourse, but it also perpetuates a cycle of divisiveness and animosity that can have long-lasting and harmful effects on society as a whole. As citizens, we have a responsibility to engage in productive and respectful dialogue with those who hold differing views, and to seek common ground and solutions that benefit all members of society. It is only through thoughtful and collaborative efforts that we can hope to overcome our differences and build a more just and equitable world for all.

**Comment by TensorsWillFlow** [comment]
> 

I agree, but when a certain faction just wants to burn it all down whenever they don't get their way, what is the point of a reasonable discourse anymore?

**Comment by TensorsWillFlow** [comment]
> > > > I agree. The cringe left wingers have to make _everything_ political.
> > > > You don't like the rocket man, we get it. Move on.
> > > 
> > > 
> > > So in the very same sentence where you whine about making everything political, you make it political by assuming anyone who criticizes or disagrees with Elon Musk and what he does is a "cringe left winger"? The irony and hypocrisy is hilarious. Sounds to me you are the only one making it political.
> > 
> > 
> > Don't think so sir. I think I'm pointing out what already happens to be the case.
> > Also, nice strawman - I never said any Elon criticism makes someone a cringe left winger, just the ones literally spamming the communist manifesto on a GitHub repository meant to bring transparency to the most prominent social media platform in the western hemisphere, which has long been used to manipulate debates and astroturf society at large.
> 
> It is unfortunate to witness political polarization and conflict between individuals with differing ideologies, particularly when it results in physical altercations or violence. Such behavior not only undermines the principles of democracy and civil discourse, but it also perpetuates a cycle of divisiveness and animosity that can have long-lasting and harmful effects on society as a whole. As citizens, we have a responsibility to engage in productive and respectful dialogue with those who hold differing views, and to seek common ground and solutions that benefit all members of society. It is only through thoughtful and collaborative efforts that we can hope to overcome our differences and build a more just and equitable world for all.


I agree, but when a certain faction just wants to burn it all down whenever they don't get their way, what is the point of a reasonable discourse anymore?

**Comment by shylaatchison** [comment]
> > > > I agree. The cringe left wingers have to make _everything_ political.
> > > > You don't like the rocket man, we get it. Move on.
> > > 
> > > 
> > > So in the very same sentence where you whine about making everything political, you make it political by assuming anyone who criticizes or disagrees with Elon Musk and what he does is a "cringe left winger"? The irony and hypocrisy is hilarious. Sounds to me you are the only one making it political.
> > 
> > 
> > Don't think so sir. I think I'm pointing out what already happens to be the case.
> > Also, nice strawman - I never said any Elon criticism makes someone a cringe left winger, just the ones literally spamming the communist manifesto on a GitHub repository meant to bring transparency to the most prominent social media platform in the western hemisphere, which has long been used to manipulate debates and astroturf society at large.
> 
> It is unfortunate to witness political polarization and conflict between individuals with differing ideologies, particularly when it results in physical altercations or violence. Such behavior not only undermines the principles of democracy and civil discourse, but it also perpetuates a cycle of divisiveness and animosity that can have long-lasting and harmful effects on society as a whole. As citizens, we have a responsibility to engage in productive and respectful dialogue with those who hold differing views, and to seek common ground and solutions that benefit all members of society. It is only through thoughtful and collaborative efforts that we can hope to overcome our differences and build a more just and equitable world for all.

STOP FIGHTING YOU'RE TEARING THIS FAMILY APART :'(

**Comment by Floofbutt** [comment]
Honestly some are trolling because Twitter is expecting free labor while providing negligible tools to do said free labor. 

Also seeing weirdo Elon fans freak out when legitimate issues get reported and they deem them as trolling is pretty funny.

**Comment by shylaatchison** [comment]
> Honestly some are trolling because Twitter is expecting free labor while providing negligible tools to do said free labor.
> 
> Also seeing weirdo Elon fans freak out when legitimate issues get reported and they deem them as trolling is pretty funny.

I originally came here to legitimately request a minor feature tweak but then saw all the trolling issues and couldn't help myself but troll on the trolling a lil. Mostly because I'm bored from being maxed out of being able to send outgoing DMs. Anyways, my legitimate issue got lost amongst these noisemakers. Super annoying. I'd imagine the Twitter engineers just said fuck it at this point and have gone to the pub.

**Comment by Funtimes909** [comment]
> @adam-singer you literally fucking made your GitHub account to troll. You are an imbecile. Elon Musk is having a cosy time living without rent in your tiny brain. Go get a fucking job.


Ironic

**Comment by TheSilkky** [comment]
@TensorsWillFlow 
![fuck you](https://i.imgur.com/9idPvp0.jpeg)

**Comment by datgreatkhan** [comment]
> > > > > I agree. The cringe left wingers have to make _everything_ political.
> > > > > You don't like the rocket man, we get it. Move on.
> > > > 
> > > > 
> > > > So in the very same sentence where you whine about making everything political, you make it political by assuming anyone who criticizes or disagrees with Elon Musk and what he does is a "cringe left winger"? The irony and hypocrisy is hilarious. Sounds to me you are the only one making it political.
> > > 
> > > 
> > > Don't think so sir. I think I'm pointing out what already happens to be the case.
> > > Also, nice strawman - I never said any Elon criticism makes someone a cringe left winger, just the ones literally spamming the communist manifesto on a GitHub repository meant to bring transparency to the most prominent social media platform in the western hemisphere, which has long been used to manipulate debates and astroturf society at large.
> > 
> > 
> > It is unfortunate to witness political polarization and conflict between individuals with differing ideologies, particularly when it results in physical altercations or violence. Such behavior not only undermines the principles of democracy and civil discourse, but it also perpetuates a cycle of divisiveness and animosity that can have long-lasting and harmful effects on society as a whole. As citizens, we have a responsibility to engage in productive and respectful dialogue with those who hold differing views, and to seek common ground and solutions that benefit all members of society. It is only through thoughtful and collaborative efforts that we can hope to overcome our differences and build a more just and equitable world for all.
> 
> I agree, but when a certain faction just wants to burn it all down whenever they don't get their way, what is the point of a reasonable discourse anymore?

Hmm, last time I checked the far-right stormed the Capitol Building. Others tried kidnapping or killing mayors and other political figures. One even tried shooting up an FBI building. A good chunk of Republicans in the House and Senate sheepishly defend Trump and pursue his agenda as if they are apart of a cult of personality.

Still doesn't mean I'm going to generalize every single right leaning person, or sum them up based on the actions of others like you are doing. You are quite literally trying to polarize by having that type of generalizing rhetoric.

**Comment by nobodyindustries** [comment]
If you are working for free for a billionaire that just laid off thousands of people, you are just an idiot, left or right winger.

**Comment by zombie200** [comment]
yall mfs need to watch shrek
