### ISSUE TITLE
Rent free

### ISSUE THREAD

**Issue by therealbluepandabear** [twitter/the-algorithm#1595]

**Comment by Xpenzz** [comment]
NOOOO YOU CAN'T JUST CHANGE TWITTER LOGO TO DOGE!!!

**Comment by logicP** [comment]
> > Weren't you already bitching about trans people and drag show story times earlier?
> > btw, someone already made it so that you can change the doge icon back to the bird lol
> 
> Suck a dick motherfucker.

https://gizmodo.com/elon-musk-crypto-dogecoin-tesla-1850293273

**Comment by logicP** [comment]
> 

You can't own what you don't have

**Comment by logicP** [comment]
> > > > Weren't you already bitching about trans people and drag show story times earlier?
> > > > btw, someone already made it so that you can change the doge icon back to the bird lol
> > > 
> > > 
> > > Suck a dick motherfucker.
> > 
> > 
> > You're only mad because some of us got on your ass for being a hypocrite. By the way, Elon's trying to dismiss a lawsuit against him for racketeering and ripping people off https://gizmodo.com/elon-musk-crypto-dogecoin-tesla-1850293273
> 
> Stay mad and salty little faggot. Elon Musk owns u

You can't own what you don't have

**Comment by logicP** [comment]
Nah, I like it here instead

**Comment by logicP** [comment]
> > Nah, I like it here instead
> 
> Why? We'll have a civil debate. I want to understand and listen to what you have to say, GitHub is just jokes for me bud.

You sure don't sound like an adult making jokes to me. Why even bother?

**Comment by Xpenzz** [comment]
> Elon's trying to dismiss a lawsuit against him for racketeering and ripping people off https://gizmodo.com/elon-musk-crypto-dogecoin-tesla-1850293273

Please tell me you don't actually believe any of this right? This lawsuit is complete bogus. Also Elon would be in jail if he bought and dumped. I don't know why people think he can do that legally.

**Comment by logicP** [comment]
> > > > Nah, I like it here instead
> > > 
> > > 
> > > Why? We'll have a civil debate. I want to understand and listen to what you have to say, GitHub is just jokes for me bud.
> > 
> > 
> > You sure don't sound like an adult making jokes to me. Why even bother? And if these were meant to be a joke then hardly anyone's laughing
> 
> Look, we've all said bad shit. What I said to you is not personal, all right? You are probably a good person in real life.
> 
> We won't get anywhere as a society if we don't have mature conversations about this.
> 
> I'm extending an olive branch to you.



> > > > Nah, I like it here instead
> > > 
> > > 
> > > Why? We'll have a civil debate. I want to understand and listen to what you have to say, GitHub is just jokes for me bud.
> > 
> > 
> > You sure don't sound like an adult making jokes to me. Why even bother? And if these were meant to be a joke then hardly anyone's laughing
> 
> Look, we've all said bad shit. What I said to you is not personal, all right? You are probably a good person in real life.
> 
> We won't get anywhere as a society if we don't have mature conversations about this.
> 
> I'm extending an olive branch to you.
> 
> I want to hear your perspective on things.

Then why do it in private, where no one can see? Wouldn't it be better to let other people be able to see you learn, change and grow as a person?

**Comment by Funtimes909** [comment]
> > Nah, I like it here instead
> 
> Why? We'll have a civil debate. I want to understand and listen to what you have to say, GitHub is just jokes for me bud.
> 
> We can move on when it came to the bad blood between us here and have an adult conversation.


"Lets have an adult conversation" Words from the man that just called people slurs and told them to go fuck themselves

**Comment by Funtimes909** [comment]
Can't wait to see the day you get sent to prison for hate speech out in public and wonder how you ended up there

**Comment by Funtimes909** [comment]
This guy has a public humiliation fetish 🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓🤓

**Comment by Funtimes909** [comment]
Care to share how being LGBT is worse than what you're doing, harassing people online for enjoying their own lives

**Comment by Funtimes909** [comment]
How does someone being trans affect you in anyway, why do you make it your problem, Why do you hate it so much that you feel the need to be a dick about it

**Comment by logicP** [comment]
Why do sizes matter to you so much?

**Comment by logicP** [comment]
She's not a child you know. She's a grown ass adult. And she said it herself, she's no feminist either

**Comment by logicP** [comment]
Don't take the bait y'all

**Comment by logicP** [comment]
Also it's true, she went up on the stand and said it herself that she was not a feminist. It's not hard to find if you look

**Comment by logicP** [comment]
> > Also it's true, she went up on the stand and said it herself that she was not a feminist. It's not hard to find if you look
> 
> bro just shutup you almost killed her 😆

Except that I don't live in Auckland, I'm all the way in the states

**Comment by logicP** [comment]
> ![image](https://user-images.githubusercontent.com/50536495/229676473-5aa27b00-ee60-4994-9231-36524c853d74.png)

lol you think that that's an own? Holy shit

Just screenshot something related to issues with the site because it contains LGBTQ+ in the title, totally an own there!

**Comment by logicP** [comment]
How come your overview isn't public I wonder

**Comment by logicP** [comment]
> > How come your overview isn't public I wonder
> > And you're the one that wrote "based Elon" onto the screenshot
> 
> because he is, kiddo. :)

Can I ask you something? What's your favorite video game?

**Comment by logicP** [comment]
> > > > How come your overview isn't public I wonder
> > > > And you're the one that wrote "based Elon" onto the screenshot
> > > 
> > > 
> > > because he is, kiddo. :)
> > 
> > 
> > Can I ask you something? What's your favorite video game?
> 
> none, I don't play games

Okay
Earliest tv show you remember watching?

**Comment by Funtimes909** [comment]
> How come your overview isn't public I wonder
> 
> And you're the one that wrote "based Elon" onto the screenshot


lmao I already called this fucker out for having his overview private, I bet you anything in the world its because he doesn't want anyone to see the clownery he gets up to on this platform, ignore everything he says against this

**Comment by Funtimes909** [comment]
> > > How come your overview isn't public I wonder
> > > And you're the one that wrote "based Elon" onto the screenshot
> > 
> > 
> > lmao I already called this fucker out for having his overview private, I bet you anything in the world its because he doesn't want anyone to see the clownery he gets up to on this platform, ignore everything he says against this
> 
> 'called out'
> 
> this is a wendy's, sir.


Who asked?

**Comment by logicP** [comment]
> wbu?

I mean, mine is Final Fantasy X. It's a surprisingly enlightening game for the early 2000's, especially considering 9/11. I was a child during that time and remembered my parents scurrying to figure out what was going on on TV when the twin towers were hit

**Comment by logicP** [comment]
> > > wbu?
> > 
> > 
> > I mean, mine is Final Fantasy X. It's a surprisingly enlightening game for the early 2000's, especially considering 9/11. I was a child during that time and remembered my parents scurrying to figure out what was going on on TV when the twin towers were hit
> 
> damn u old i wasn't even born on 9 /11

I knew it! I knew something didn't sit right. What's someone like you doing arguing with complete strangers online anyways?

**Comment by Funtimes909** [comment]
"do a bit of trolling" hmm yes saying slurs, running from being banned, changing github username to avoid being banned, hate speech and bullying, but yeah sure you totally won't get banned because it falls under "Free Speech"

**Comment by Funtimes909** [comment]
you keep wording it like it was me specifically, I wasn't at the protest bro, and how in the world does that justify what you are doing

**Comment by Funtimes909** [comment]
"Someone was beaten up!! Lets use that as an opportunity to harass minorities and get away with it!!!!!!"

**Comment by logicP** [comment]
> you keep wording it like it was me specifically, I wasn't at the protest bro, and how in the world does that justify what you are doing

I feel some part of me thinks that this alex person is actually a kid. A kid that unfortunately thinks that this is how you get attention

**Comment by logicP** [comment]
> > > you keep wording it like it was me specifically, I wasn't at the protest bro, and how in the world does that justify what you are doing
> > 
> > 
> > I feel some part of me thinks that this alex person is actually a kid. A kid that unfortunately thinks that this is how you get attention
> 
> nah g I'm pretty much almost an adult, I think you're the fucking bafoon who still listens to the media in 2023

Almost an adult still means you're a minor by legal standards, kiddo. And if by media you mean Twitter where I've been getting some of my recent news on the shenanigans of Elon Musk then yeah, I do listen to media in 2023.

**Comment by Funtimes909** [comment]
> [<img alt="@Funtimes909" width="40" height="40" src="https://avatars.githubusercontent.com/u/68979259?s=80&amp;v=4">](/Funtimes909)


He is 100% just attention seeking, he says elon musk is rent free in our heads, but look at this fool, hes the one actually preaching elons bullshit, trying to ride his dick off all the attention this recently open sourced project is getting, he knows spreading hate is the best way to gain attention, regardless of if its good or not

**Comment by logicP** [comment]
> > > > > you keep wording it like it was me specifically, I wasn't at the protest bro, and how in the world does that justify what you are doing
> > > > 
> > > > 
> > > > I feel some part of me thinks that this alex person is actually a kid. A kid that unfortunately thinks that this is how you get attention
> > > 
> > > 
> > > nah g I'm pretty much almost an adult, I think you're the fucking bafoon who still listens to the media in 2023
> > 
> > 
> > Almost an adult still means you're a minor by legal standards, kiddo. And if by media you mean Twitter where I've been getting some of my recent news on the shenanigans of Elon Musk then yeah, I do listen to media in 2023.
> 
> A 'minor' is just a dumb legal concept, I can drive, go out, do most adult things. Child != Minor.
> 
> And the fact that you listen to what the media is saying about Elongated Musket is just you admitting that you're an idiot, I bet you live in Cali or NY.

Hun I live in the south

**Comment by logicP** [comment]
> > > [<img alt="@Funtimes909" width="40" height="40" src="https://avatars.githubusercontent.com/u/68979259?s=80&amp;v=4">](/Funtimes909)
> > 
> > 
> > He is 100% just attention seeking, he says elon musk is rent free in our heads, but look at this fool, hes the one actually preaching elons bullshit, trying to ride his dick off all the attention this recently open sourced project is getting, he knows spreading hate is the best way to gain attention, regardless of if its good or not
> 
> spreading hate is fun
> 
> > > > > > > you keep wording it like it was me specifically, I wasn't at the protest bro, and how in the world does that justify what you are doing
> > > > > > 
> > > > > > 
> > > > > > I feel some part of me thinks that this alex person is actually a kid. A kid that unfortunately thinks that this is how you get attention
> > > > > 
> > > > > 
> > > > > nah g I'm pretty much almost an adult, I think you're the fucking bafoon who still listens to the media in 2023
> > > > 
> > > > 
> > > > Almost an adult still means you're a minor by legal standards, kiddo. And if by media you mean Twitter where I've been getting some of my recent news on the shenanigans of Elon Musk then yeah, I do listen to media in 2023.
> > > 
> > > 
> > > A 'minor' is just a dumb legal concept, I can drive, go out, do most adult things. Child != Minor.
> > > And the fact that you listen to what the media is saying about Elongated Musket is just you admitting that you're an idiot, I bet you live in Cali or NY.
> > 
> > 
> > Hun I live in the south
> 
> even funnier

Nah what's funny is that you assume that leftists only live in NY and Cali. Quite the opposite

**Comment by Funtimes909** [comment]
> look dude, if you're willing to have an adult conversation, I will @logicP. We can do a voice call and hear each others' perspectives, deal?


Stop being so mentally unstable that you can't resist trying to debate on discord :nerd_face:

**Comment by Funtimes909** [comment]
> > > look dude, if you're willing to have an adult conversation, I will @logicP. We can do a voice call and hear each others' perspectives, deal?
> > 
> > 
> > Stop being so mentally unstable that you can't resist trying to debate on discord nerd_face
> 
> I mean the last two debates were pretty good.


With each passing hour I am becoming more and more certain you have a humiliation fetish

**Comment by Funtimes909** [comment]
Doesn't have a proper argument so just resorts to insults lmao, typical idiot online

**Comment by Funtimes909** [comment]
I could ask the same about you, were you drop kicked by your dad out the house at 12 years old?

**Comment by Funtimes909** [comment]
> > I could ask the same about you, were you drop kicked by your dad out the house at 12 years old?
> 
> my dad is based and agrees with me on things, he would drop kick a troon if he saw u come near my 10 yr old sister bitch


Yeah, you were definitely the one that got abused

**Comment by Funtimes909** [comment]
Not everyone around me, just the brain damaged idiots such as yourself

**Comment by Funtimes909** [comment]
> > Not everyone around me, just the brain damaged idiots such as yourself
> 
> you're a man, you know that, right?


Nope, believe it or not, I'm actually a women, and I'm really happy with it
inb4: calls me 4 slurs

**Comment by Funtimes909** [comment]
> > > > Not everyone around me, just the brain damaged idiots such as yourself
> > > 
> > > 
> > > you're a man, you know that, right?
> > 
> > 
> > Nope, believe it or not, I'm actually a women, and I'm really happy with it inb4: calls me 4 slurs
> 
> you're a man who thinks he's a woman. I hope you get help.


That last part, I sure hope you get some help as well, what do I need to get help for? Being perfectly happy with my life?

**Comment by Funtimes909** [comment]
> > > > > > Not everyone around me, just the brain damaged idiots such as yourself
> > > > > 
> > > > > 
> > > > > you're a man, you know that, right?
> > > > 
> > > > 
> > > > Nope, believe it or not, I'm actually a women, and I'm really happy with it inb4: calls me 4 slurs
> > > 
> > > 
> > > you're a man who thinks he's a woman. I hope you get help.
> > 
> > 
> > That last part, I sure hope you get some help as well, what do I need to get help for? Being perfectly happy with my life?
> 
> i don't care whether or not you're happy, you're still living in a delusion.


Thats an L on your part for caring so much

**Comment by Funtimes909** [comment]
> > > > > > > Not everyone around me, just the brain damaged idiots such as yourself
> > > > > > 
> > > > > > 
> > > > > > you're a man, you know that, right?
> > > > > 
> > > > > 
> > > > > Nope, believe it or not, I'm actually a women, and I'm really happy with it inb4: calls me 4 slurs
> > > > 
> > > > 
> > > > you're a man who thinks he's a woman. I hope you get help.
> > > 
> > > 
> > > That last part, I sure hope you get some help as well, what do I need to get help for? Being perfectly happy with my life?
> > 
> > 
> > i don't care whether or not you're happy, you're still living in a delusion.
> 
> Thats an L on your part for caring so much


Imagine losing an argument so hard you have to result to transphobia

**Comment by Funtimes909** [comment]
> > > > > > > > > Not everyone around me, just the brain damaged idiots such as yourself
> > > > > > > > 
> > > > > > > > 
> > > > > > > > you're a man, you know that, right?
> > > > > > > 
> > > > > > > 
> > > > > > > Nope, believe it or not, I'm actually a women, and I'm really happy with it inb4: calls me 4 slurs
> > > > > > 
> > > > > > 
> > > > > > you're a man who thinks he's a woman. I hope you get help.
> > > > > 
> > > > > 
> > > > > That last part, I sure hope you get some help as well, what do I need to get help for? Being perfectly happy with my life?
> > > > 
> > > > 
> > > > i don't care whether or not you're happy, you're still living in a delusion.
> > > 
> > > 
> > > Thats an L on your part for caring so much
> > 
> > 
> > Imagine losing an argument so hard you have to result to transphobia
> 
> I am transphobic. You're right.
> 
> I used to have no issue with you guys, it changed a couple of years ago.


ok, I never actually asked because I don't care, no one cares about your past, you can feel free to hate trans people, but why do you have to bully other people for it, keep it to yourself bro

**Comment by Funtimes909** [comment]
What makes this women that got assaulted any different from the rest of us, we're all still people

> > > > > > > > > > Not everyone around me, just the brain damaged idiots such as yourself
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > you're a man, you know that, right?
> > > > > > > > 
> > > > > > > > 
> > > > > > > > Nope, believe it or not, I'm actually a women, and I'm really happy with it inb4: calls me 4 slurs
> > > > > > > 
> > > > > > > 
> > > > > > > you're a man who thinks he's a woman. I hope you get help.
> > > > > > 
> > > > > > 
> > > > > > That last part, I sure hope you get some help as well, what do I need to get help for? Being perfectly happy with my life?
> > > > > 
> > > > > 
> > > > > i don't care whether or not you're happy, you're still living in a delusion.
> > > > 
> > > > 
> > > > Thats an L on your part for caring so much
> > > 
> > > 
> > > Imagine losing an argument so hard you have to result to transphobia
> > 
> > 
> > I am transphobic. You're right.
> > I used to have no issue with you guys, it changed a couple of years ago.
> 
> ok, I never actually asked because I don't care, no one cares about your past, you can feel free to hate trans people, but why do you have to bully other people for it, keep it to yourself bro

**Comment by Funtimes909** [comment]
> > > > > > > > > > > Not everyone around me, just the brain damaged idiots such as yourself
> > > > > > > > > > 
> > > > > > > > > > 
> > > > > > > > > > you're a man, you know that, right?
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > Nope, believe it or not, I'm actually a women, and I'm really happy with it inb4: calls me 4 slurs
> > > > > > > > 
> > > > > > > > 
> > > > > > > > you're a man who thinks he's a woman. I hope you get help.
> > > > > > > 
> > > > > > > 
> > > > > > > That last part, I sure hope you get some help as well, what do I need to get help for? Being perfectly happy with my life?
> > > > > > 
> > > > > > 
> > > > > > i don't care whether or not you're happy, you're still living in a delusion.
> > > > > 
> > > > > 
> > > > > Thats an L on your part for caring so much
> > > > 
> > > > 
> > > > Imagine losing an argument so hard you have to result to transphobia
> > > 
> > > 
> > > I am transphobic. You're right.
> > > I used to have no issue with you guys, it changed a couple of years ago.
> > 
> > 
> > ok, I never actually asked because I don't care, no one cares about your past, you can feel free to hate trans people, but why do you have to bully other people for it, keep it to yourself bro
> 
> Because you are an evil which must be stopped.
> 
> You are all demons.


ok, enjoy getting banned from github, say bye to all thosee shitty android app repositories

**Comment by Funtimes909** [comment]
> > > > > > > > > > > > > Not everyone around me, just the brain damaged idiots such as yourself
> > > > > > > > > > > > 
> > > > > > > > > > > > 
> > > > > > > > > > > > you're a man, you know that, right?
> > > > > > > > > > > 
> > > > > > > > > > > 
> > > > > > > > > > > Nope, believe it or not, I'm actually a women, and I'm really happy with it inb4: calls me 4 slurs
> > > > > > > > > > 
> > > > > > > > > > 
> > > > > > > > > > you're a man who thinks he's a woman. I hope you get help.
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > That last part, I sure hope you get some help as well, what do I need to get help for? Being perfectly happy with my life?
> > > > > > > > 
> > > > > > > > 
> > > > > > > > i don't care whether or not you're happy, you're still living in a delusion.
> > > > > > > 
> > > > > > > 
> > > > > > > Thats an L on your part for caring so much
> > > > > > 
> > > > > > 
> > > > > > Imagine losing an argument so hard you have to result to transphobia
> > > > > 
> > > > > 
> > > > > I am transphobic. You're right.
> > > > > I used to have no issue with you guys, it changed a couple of years ago.
> > > > 
> > > > 
> > > > ok, I never actually asked because I don't care, no one cares about your past, you can feel free to hate trans people, but why do you have to bully other people for it, keep it to yourself bro
> > > 
> > > 
> > > Because you are an evil which must be stopped.
> > > You are all demons.
> > 
> > 
> > ok, enjoy getting banned from github, say bye to all thosee shitty android app repositories
> 
> I don't really care to be honest rofl I already quit GitHub like half a year ago.


Quick question, do you remember that panda guy from earlier?

**Comment by Funtimes909** [comment]
Better question, what are your thoughts on Dreamsexuals

**Comment by Funtimes909** [comment]
> > > > > > > > > > > > > > > Not everyone around me, just the brain damaged idiots such as yourself
> > > > > > > > > > > > > > 
> > > > > > > > > > > > > > 
> > > > > > > > > > > > > > you're a man, you know that, right?
> > > > > > > > > > > > > 
> > > > > > > > > > > > > 
> > > > > > > > > > > > > Nope, believe it or not, I'm actually a women, and I'm really happy with it inb4: calls me 4 slurs
> > > > > > > > > > > > 
> > > > > > > > > > > > 
> > > > > > > > > > > > you're a man who thinks he's a woman. I hope you get help.
> > > > > > > > > > > 
> > > > > > > > > > > 
> > > > > > > > > > > That last part, I sure hope you get some help as well, what do I need to get help for? Being perfectly happy with my life?
> > > > > > > > > > 
> > > > > > > > > > 
> > > > > > > > > > i don't care whether or not you're happy, you're still living in a delusion.
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > Thats an L on your part for caring so much
> > > > > > > > 
> > > > > > > > 
> > > > > > > > Imagine losing an argument so hard you have to result to transphobia
> > > > > > > 
> > > > > > > 
> > > > > > > I am transphobic. You're right.
> > > > > > > I used to have no issue with you guys, it changed a couple of years ago.
> > > > > > 
> > > > > > 
> > > > > > ok, I never actually asked because I don't care, no one cares about your past, you can feel free to hate trans people, but why do you have to bully other people for it, keep it to yourself bro
> > > > > 
> > > > > 
> > > > > Because you are an evil which must be stopped.
> > > > > You are all demons.
> > > > 
> > > > 
> > > > ok, enjoy getting banned from github, say bye to all thosee shitty android app repositories
> > > 
> > > 
> > > I don't really care to be honest rofl I already quit GitHub like half a year ago.
> > 
> > 
> > Quick question, do you remember that panda guy from earlier?
> 
> Quick question, who asked?


Are you fucking dumb? the first part of that question specifies that it was me that asked, so are you going to answer it or hide behind a wall of insults?
Whos the real pussy?

**Comment by Funtimes909** [comment]
> > > > > > > > > > > > > > > > > Not everyone around me, just the brain damaged idiots such as yourself
> > > > > > > > > > > > > > > > 
> > > > > > > > > > > > > > > > 
> > > > > > > > > > > > > > > > you're a man, you know that, right?
> > > > > > > > > > > > > > > 
> > > > > > > > > > > > > > > 
> > > > > > > > > > > > > > > Nope, believe it or not, I'm actually a women, and I'm really happy with it inb4: calls me 4 slurs
> > > > > > > > > > > > > > 
> > > > > > > > > > > > > > 
> > > > > > > > > > > > > > you're a man who thinks he's a woman. I hope you get help.
> > > > > > > > > > > > > 
> > > > > > > > > > > > > 
> > > > > > > > > > > > > That last part, I sure hope you get some help as well, what do I need to get help for? Being perfectly happy with my life?
> > > > > > > > > > > > 
> > > > > > > > > > > > 
> > > > > > > > > > > > i don't care whether or not you're happy, you're still living in a delusion.
> > > > > > > > > > > 
> > > > > > > > > > > 
> > > > > > > > > > > Thats an L on your part for caring so much
> > > > > > > > > > 
> > > > > > > > > > 
> > > > > > > > > > Imagine losing an argument so hard you have to result to transphobia
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > I am transphobic. You're right.
> > > > > > > > > I used to have no issue with you guys, it changed a couple of years ago.
> > > > > > > > 
> > > > > > > > 
> > > > > > > > ok, I never actually asked because I don't care, no one cares about your past, you can feel free to hate trans people, but why do you have to bully other people for it, keep it to yourself bro
> > > > > > > 
> > > > > > > 
> > > > > > > Because you are an evil which must be stopped.
> > > > > > > You are all demons.
> > > > > > 
> > > > > > 
> > > > > > ok, enjoy getting banned from github, say bye to all thosee shitty android app repositories
> > > > > 
> > > > > 
> > > > > I don't really care to be honest rofl I already quit GitHub like half a year ago.
> > > > 
> > > > 
> > > > Quick question, do you remember that panda guy from earlier?
> > > 
> > > 
> > > Quick question, who asked?
> > 
> > 
> > Are you fucking dumb? the first part of that question specifies that it was me that asked, so are you going to answer it or hide behind a wall of insults? Whos the real pussy?
> 
> lol


So you gonna answer the question or continue being a :cat: :nerd_face: 
Dumb piece of shit calls everyone who doesn't add him on discord "pussies" yet can't even answer a simple question

**Comment by Funtimes909** [comment]
> yall this convo been fun tho troon, fr.
> 
> backed up all my github repos cuz I know I aboutta get banned laughing


What happened to not caring about being banned? LMFAOOOOOOOOOOOOOOOOOOOOOOOOO

**Comment by Funtimes909** [comment]
> > > > > > > > > > > > > > > > > > > Not everyone around me, just the brain damaged idiots such as yourself
> > > > > > > > > > > > > > > > > > 
> > > > > > > > > > > > > > > > > > 
> > > > > > > > > > > > > > > > > > you're a man, you know that, right?
> > > > > > > > > > > > > > > > > 
> > > > > > > > > > > > > > > > > 
> > > > > > > > > > > > > > > > > Nope, believe it or not, I'm actually a women, and I'm really happy with it inb4: calls me 4 slurs
> > > > > > > > > > > > > > > > 
> > > > > > > > > > > > > > > > 
> > > > > > > > > > > > > > > > you're a man who thinks he's a woman. I hope you get help.
> > > > > > > > > > > > > > > 
> > > > > > > > > > > > > > > 
> > > > > > > > > > > > > > > That last part, I sure hope you get some help as well, what do I need to get help for? Being perfectly happy with my life?
> > > > > > > > > > > > > > 
> > > > > > > > > > > > > > 
> > > > > > > > > > > > > > i don't care whether or not you're happy, you're still living in a delusion.
> > > > > > > > > > > > > 
> > > > > > > > > > > > > 
> > > > > > > > > > > > > Thats an L on your part for caring so much
> > > > > > > > > > > > 
> > > > > > > > > > > > 
> > > > > > > > > > > > Imagine losing an argument so hard you have to result to transphobia
> > > > > > > > > > > 
> > > > > > > > > > > 
> > > > > > > > > > > I am transphobic. You're right.
> > > > > > > > > > > I used to have no issue with you guys, it changed a couple of years ago.
> > > > > > > > > > 
> > > > > > > > > > 
> > > > > > > > > > ok, I never actually asked because I don't care, no one cares about your past, you can feel free to hate trans people, but why do you have to bully other people for it, keep it to yourself bro
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > Because you are an evil which must be stopped.
> > > > > > > > > You are all demons.
> > > > > > > > 
> > > > > > > > 
> > > > > > > > ok, enjoy getting banned from github, say bye to all thosee shitty android app repositories
> > > > > > > 
> > > > > > > 
> > > > > > > I don't really care to be honest rofl I already quit GitHub like half a year ago.
> > > > > > 
> > > > > > 
> > > > > > Quick question, do you remember that panda guy from earlier?
> > > > > 
> > > > > 
> > > > > Quick question, who asked?
> > > > 
> > > > 
> > > > Are you fucking dumb? the first part of that question specifies that it was me that asked, so are you going to answer it or hide behind a wall of insults? Whos the real pussy?
> > > 
> > > 
> > > lol
> > 
> > 
> > So you gonna answer the question or continue being a cat nerd_face Dumb piece of shit calls everyone who doesn't add him on discord "pussies" yet can't even answer a simple question
> 
> u know where the nearest maccas is?



> We good now @Funtimes909 ?


LMAOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO YOU GOT SO SCARED YOU COULDN'T ANSWER MY QUESTION SO JUST TRY TO MAKE IT ALL SOUND LIKE IT WAS JUST SUCH A BIG JOKE
"Yeah yeah sorry I called you multiple slurs it was just a joke you see, no real harm done really"

**Comment by Funtimes909** [comment]
> 

LMAOOOOOOO
Must just be a coincidence that you get tired of arguing moments after you refuse to answer a simple question of mine, maybe that proves something?

**Comment by Funtimes909** [comment]
> 


Did you honestly think you could go on github issues and spread hate and scream slurs and not expect to be banned LMFAO

**Comment by Funtimes909** [comment]
> > > 
> > 
> > 
> > LMAOOOOOOO Must just be a coincidence that you get tired of arguing moments after you refuse to answer a simple question of mine, maybe that proves something?
> 
> This is going in circles


Yeah, and I'd like to remind you this all started because you're a piece of shit who can't keep his opinions to himself

**Comment by Oman395** [comment]
Yknow it's funny-- you claim that Elon lives rent free in our heads, and yet you're the one who's spamming issues and constantly fighting about random shit literally nobody cares about. Right now you have a group of people laughing their asses off at you, while you do what-- get mad and say slurs on the internet? Don't forget to wipe the cheeto dust off your fingers.

**Comment by Funtimes909** [comment]
We win until you decide to come back and make a third issue, I'll be waiting for that with the exact same question that scared you off the first time :nerd_face:

**Comment by Funtimes909** [comment]
> let's meet up and talk


I ain't going within 3 miles of something as disgusting as you

**Comment by Oman395** [comment]
Hey if you'll foot the bill I'm down to fly over there and talk

**Comment by Funtimes909** [comment]
> > let's meet up and talk
> 
> I ain't going within 3 miles of something as disgusting as you


and no, I'm not a "scared woke pussy" I just don't want to be around people such as yourself, whats the point anyway, you're just gonna threaten violence and get yourself arrested :nerd_face: 
I hope you are aware that you can get in serious trouble for death threats and threats of violence in general even if its online right? or did you skip that part of basic internet rules and jump straight to bullying

**Comment by Funtimes909** [comment]
lmao, scared
