### ISSUE TITLE
The FitnessGram™ Pacer Test

### ISSUE THREAD

**Issue by azeng4499** [twitter/the-algorithm#1598]
The FitnessGram™ Pacer Test is a multistage aerobic capacity test that progressively gets more difficult as it continues. The 20 meter pacer test will begin in 30 seconds. Line up at the start. The running speed starts slowly but gets faster each minute after you hear this signal *boop*. A single lap should be completed each time you hear this sound *ding*. Remember to run in a straight line and run as long as possible. The second time you fail to complete a lap before the sound, your test is over. The test will begin on the word start. On your mark, get ready, start.

**Comment by shylaatchison** [comment]
I will invoice you the bill for my therapy since you exposed me to this

**Comment by valiantuser** [comment]
so true

**Comment by kasplat** [comment]
+1
