### ISSUE TITLE
PR’s

### ISSUE THREAD

**Issue by NeonGamerBot-QK** [twitter/the-algorithm#1603]
Some of the PRs seem very necessary and need to be merged, I will tag them below.

**Comment by NeonGamerBot-QK** [comment]
#1503

**Comment by NeonGamerBot-QK** [comment]
#1535 I don’t see any syntax errors?

**Comment by jtbx** [comment]
> #1535 I don’t see any syntax errors?

It doesn't have any, that reply was a joke. It's unnecessary and pointless though, see my comment on it

**Comment by nobodyindustries** [comment]
None are going to get merged, this repo should not exist, DELET THIS

**Comment by jdm-twtr** [comment]
One PR was closed with a commit, the other was deleted by the author.
