### ISSUE TITLE
somebody 

### ISSUE THREAD

**Issue by izner32** [twitter/the-algorithm#1605]
once told me

**Comment by angela-wang1** [comment]
the world

**Comment by william-fecteau** [comment]
was gonne roll me

**Comment by mfahadshah** [comment]
Until you fall off the flat earth

**Comment by Parazytee** [comment]
in the sheeEEEEd

**Comment by LeBeDevCode** [comment]
She was looking kind of dumb

**Comment by briocherockets** [comment]
With her finger and her thumb

**Comment by Adamkaram** [comment]
and the words she tell , don't worry he's just a friend
