### ISSUE TITLE
Twitter Color Themes Native 

### ISSUE THREAD

**Issue by Arv18** [twitter/the-algorithm#1617]
**Is your feature request related to a problem? Please describe.**
No is a problem but can help to read better and take care of the eyes.

**Describe the solution you'd like**
Full color themes, high or low contrast, with pickcolor.

**Describe alternatives you've considered**
A custon import by small code, example: in json.

**Additional context**

**Comment by ArslanYM** [comment]
what kind of import would you suggest @Arv18

**Comment by Arv18** [comment]
This would be an advanced option.  Import a json (or text plain), with automatic validation, with basic color customization options, for example: comments color, link color, title color, etc.

**Comment by Arv18** [comment]
> 

This would be an advanced option. Import a json (or text plain), with automatic validation, with basic color customization options, for example: comments color, link color, title color, etc.

**Comment by jdm-twtr** [comment]
Thanks for filing. We've marked this issue as an unrelated bug or feature for future review.
                    In order to keep our issue count manageable, we will not be leaving these issues open. We apologize for
                    the inconvenience. If you feel that we closed your issue in error, please re-file the issue, stating how
                    the requested feature applies to the recommendation algorithm components that have been open-sourced thus far.
