### ISSUE TITLE
do gifs work 

### ISSUE THREAD

**Issue by rarchai** [twitter/the-algorithm#1619]
![XwI7.gif](https://user-images.githubusercontent.com/52048694/229689035-7f965b40-0f6c-4de9-ada6-55a38b4fdf33.gif)

**Comment by rarchai** [comment]
Thats crazy

**Comment by TheSilkky** [comment]
![wow](https://i.imgur.com/HMhyf1s.png)

**Comment by Angus1811** [comment]
![skull](https://user-images.githubusercontent.com/102298861/230167679-a6639d53-17d3-4e12-870d-d890085ba6f7.gif)

**Comment by Angus1811** [comment]
![skull-skull-emoji](https://user-images.githubusercontent.com/102298861/230167760-cc466f3b-4098-43ff-be4d-536b5828ca74.gif)
![skull](https://user-images.githubusercontent.com/102298
![rotating-skull](https://user-images.githubusercontent.com/102298861/230167823-75372d7f-17ff-4e1c-9648-467f30b271c1.gif)
861/230167767-f57e6b84-b632-49dc-b6a5-239b68a97a91.gif)

**Comment by Angus1811** [comment]
![rotating-skull](https://user-images.githubusercontent.com/102298861/230167926-dc21afc4-b6b9-4a96-9e34-6a5c9f1bb24d.gif)
![skull-skull-emoji](https://user-images.githubusercontent.com/102298861/230167939-0edbe36d-8f16-4195-a8e6-a6a074d0fa5f.gif)
![skull](https://user-images.githubusercontent.com/102298861/230167950-3bda65d9-a0bb-4a58-baa3-330210ebc4f5.gif)

**Comment by Angus1811** [comment]
# yes they do

**Comment by jdm-twtr** [comment]
Thanks for filing. We've marked this issue as an unrelated bug or feature for future review.
                    In order to keep our issue count manageable, we will not be leaving these issues open. We apologize for
                    the inconvenience. If you feel that we closed your issue in error, please re-file the issue, stating how
                    the requested feature applies to the recommendation algorithm components that have been open-sourced thus far.
