### ISSUE TITLE
Please add unicorn confetti

### ISSUE THREAD

**Issue by JasonDeving** [twitter/the-algorithm#1623]
https://dev.to/loonywizard/js-confetti-library-with-emojis-2152

Just add the library I think it would be fun. If people tweet unicorn and that happens.

**Comment by ilovelinux** [comment]
Spam, please close.

**Comment by TheSilkky** [comment]
@ilovelinux CUM CUM CUM CUM CUM CUM CUM

**Comment by TruncatedDinosour** [comment]
ill quote myself again

>  why do people post frontend and backend issues here, this is purely the algorithm, no backend, no nothing, like i think you should clown on twitter bc both repos are a joke, but if youre making actual suggestions its only painful to see issues posted under wrong repos
> basically clown twitter but be correct abt it

**Comment by nobodyindustries** [comment]
@ilovelinux simp, please disappear

**Comment by jdm-twtr** [comment]
Thanks for filing. We've marked this issue as an unrelated bug or feature for future review.
                    In order to keep our issue count manageable, we will not be leaving these issues open. We apologize for
                    the inconvenience. If you feel that we closed your issue in error, please re-file the issue, stating how
                    the requested feature applies to the recommendation algorithm components that have been open-sourced thus far.
