### ISSUE TITLE
Hey elon you should switch to Arch Linux

### ISSUE THREAD

**Issue by Funtimes909** [twitter/the-algorithm#1624]
Arch linux is objectively the best operating system
Elon I'll send u feet pics in dms if you use arch linux :pleading_face:

**Comment by Zvicii** [comment]
lmao

**Comment by Ibrahim2750mi** [comment]
Please don't shitpost. This should be closed immediately.

**Comment by TruncatedDinosour** [comment]
he should be using arch btw
or be a real chad and come join us, the trans people of gentoo

**Comment by stealthpaladin** [comment]
Obviously he'll be using FreeBSD like a chad

**Comment by TruncatedDinosour** [comment]
> Obviously he'll be using FreeBSD like a baus

openbsd and netbsd are true chads, freebsd is an uwu little beta

**Comment by PravithBA** [comment]
> Nahh arch is gay

That only makes it better

**Comment by Funtimes909** [comment]
> Nahh arch is gay


Thats 

> he should be using arch btw or be a real chad and come join us, the trans people of gentoo

I'm trans and I use arch linux, not every trans person uses gentoo you know ;)

**Comment by stealthpaladin** [comment]
> > Obviously he'll be using FreeBSD like a baus
> 
> openbsd and netbsd are true chads, freebsd is an uwu little beta

oh oh oh aight we gonna get into a drama if we are gonna get serious about how vastly better FreeBSD is on everything but security lol 

which OpenBSD is sooorta maaybe better on security depending on your deployment. 

Once upon a time I mean, there was a comparison if you wanna talk true chads, that's performance and customizing ur driver stack like freesbsd which runs almost every mature enterprise cloud. but i mean hey if you wanna play it safe...... 

And then netbsd? I mean, compatibility spec? being such a chad it should be easy to get *-nix tools installed on any of them why would u need netbsd? ;J

**Comment by TruncatedDinosour** [comment]
> > Nahh arch is gay
> 
> Thats
> 
> > he should be using arch btw or be a real chad and come join us, the trans people of gentoo
> 
> I'm trans and I use arch linux, not every trans person uses gentoo you know ;)

no shit its like people are unique individuals lo, im just saying that a large portion of gentoo users are trans and most trans people dont even use linux

**Comment by TruncatedDinosour** [comment]
> > > Obviously he'll be using FreeBSD like a baus
> > 
> > 
> > openbsd and netbsd are true chads, freebsd is an uwu little beta
> 
> oh oh oh aight we gonna get into a drama if we are gonna get serious about how vastly better FreeBSD is on everything but security lol
> 
> which OpenBSD is sooorta maaybe better on security depending on your deployment.
> 
> Once upon a time I mean, there was a comparison if you wanna talk true chads, that's performance and customizing ur driver stack like freesbsd which runs almost every mature enterprise cloud. but i mean hey if you wanna play it safe......
> 
> And then netbsd? I mean, compatibility spec? being such a chad it should be easy to get *-nix tools installed on any of them why would u need netbsd? ;J

too bad people have preferences, netbsd being a much more minimal BSD distrobution
is a bit more advanced than fbd for e.g.

**Comment by stealthpaladin** [comment]
i mean you can have preference, but the differences between the BSD family are pretty well documented and intentional. It is a known fact that FreeBSD is way more performant and trims down further than either of the others. Whether your preference is security, performance or compatibility is up to you but which is which is known ;p

**Comment by ValZapod** [comment]
Debian. Ubuntu derived from it, so I use original Debian testing.

The only thing no v3 arch packets.
