### ISSUE TITLE
Add a button for anti-social profile where only see the tweets the people handle follows

### ISSUE THREAD

**Issue by abhinesh09** [twitter/the-algorithm#1625]
**Is your feature request related to a problem? Please describe.**
I get overly engaged in twitter at some times and just want to stop the addiction of opening the twitter again and again. I then put the timer on the app so that I don't spend too much time on twitter. 

**Describe the solution you'd like**
I want to have a button on the profile which when turned on will show the tweets from the profiles you follow. This will let user only see the content he follows and not the other 50% of the content which is from interests he may/may not have.

**Describe alternatives you've considered**
The user can toggle this button easily to read or not go into anti-social zone. 

**Additional context**
The button could be put on the main page or in the settings of the user.

**Comment by jdm-twtr** [comment]
Thanks for filing. We've marked this issue as an unrelated bug or feature for future review.
                    In order to keep our issue count manageable, we will not be leaving these issues open. We apologize for
                    the inconvenience. If you feel that we closed your issue in error, please re-file the issue, stating how
                    the requested feature applies to the recommendation algorithm components that have been open-sourced thus far.
