### ISSUE TITLE
Add an angry react😡 

### ISSUE THREAD

**Issue by silverhand7** [twitter/the-algorithm#1626]
Please add an angry react because most of the people on Twitter are angry. 
😡 😡 😡

**Comment by TruncatedDinosour** [comment]
why do people post frontend and backend issues here, this is purely the algorithm, no backend, no nothing, like i think you should clown on twitter bc both repos are a joke, but if youre making actual suggestions its only painful to see issues posted under wrong repos

basically clown twitter but be correct abt it

**Comment by ValZapod** [comment]
So just clone facebook? Google messages allows any emoji as a reaction, BTW. RCS...
