### ISSUE TITLE
Hide liked tweets

### ISSUE THREAD

**Issue by Yowezy** [twitter/the-algorithm#1627]
Allowing users to hide their liked tweets would be a useful feature for those who want to keep their activity private or for those who want to curate their public profile more carefully.

**Comment by Yowezy** [comment]
On tumbler you can make your liked posts either public or private,
why not provide such an option in twitter?

Think from a user experience point of view, some users prefer to hide _some_ of their activity.

**Comment by Yowezy** [comment]
> So you are trying to say that suppose Elon likes a tweet of NYTimes, now Elon must have a facility to either let others know that Elon liked a tweet or Elon can hide and no one can see what activity Elon did. Obviously his tweet, retweet, and comments are still world readable.
> 
> I think this defats the purpose of LIKE, by liking a user is saying that I like it and I want to let the world know that I like it.

On tumbler you can make your liked posts either public or private,
why not provide such an option in twitter?

I think from a user experience point of view, some users prefer to hide some of their activity.

**Comment by jdm-twtr** [comment]
Thanks for filing. We've marked this issue as an unrelated bug or feature for future review.
                    In order to keep our issue count manageable, we will not be leaving these issues open. We apologize for
                    the inconvenience. If you feel that we closed your issue in error, please re-file the issue, stating how
                    the requested feature applies to the recommendation algorithm components that have been open-sourced thus far.
