### ISSUE TITLE
 Track and delete sexual content

### ISSUE THREAD

**Issue by Yowezy** [twitter/the-algorithm#1661]
Exposure to sexual content can have negative effects on people's attitudes towards sex, their sensitivity to sexual stimuli, and their perception of others as objects. It can also lead to an increase in risky sexual behavior and emotional distress, depending on factors such as age, culture, and the nature of the content. It's important to be cautious about sexual content and consider its potential impact, especially for vulnerable groups like children and adolescents.

**Comment by nobodyindustries** [comment]
I thought this was about free speech

**Comment by drychlik76** [comment]
Should at minimum place an adult content flag.  The end user at that point can 'decided' to whether to engage or no.  

It helps protect the community as a whole going forward and doesn't infringe on 1st.

My .02.

**Comment by jdm-twtr** [comment]
Thanks for filing. We've marked this issue as an unrelated bug or feature for future review.
                    In order to keep our issue count manageable, we will not be leaving these issues open. We apologize for
                    the inconvenience. If you feel that we closed your issue in error, please re-file the issue, stating how
                    the requested feature applies to the recommendation algorithm components that have been open-sourced thus far.
