### ISSUE TITLE
notify users who seem to develop an addiction

### ISSUE THREAD

**Issue by m-a-sch** [twitter/the-algorithm#1662]
**Is your feature request related to a problem? Please describe.**
Some studies (growing number) document social network addiction.

**Describe the solution you'd like**
Social network operators can most likely detect users who display that behaviour and could find ways to provide help to these users.

**Describe alternatives you've considered**
Document current status and work with addiction researchers. Ensure that algorithm enhancements does not make the problem worse than it already is.

**Comment by Aditya-Naresh** [comment]
It's just a thought process and I'm **not an expert** but I think if we have the data relating to the time spent by an addict and what is the highest recommended time to spend.We can track the time this user is spent on the app and send an alert to warn them.

**Comment by 170031284** [comment]
May be you should consider number of logins per day and time spend parllely you should also compare this with previous weeks months just to see if it is getting worse .

**Comment by jdm-twtr** [comment]
Thanks for filing. We've marked this issue as an unrelated bug or feature for future review.
                    In order to keep our issue count manageable, we will not be leaving these issues open. We apologize for
                    the inconvenience. If you feel that we closed your issue in error, please re-file the issue, stating how
                    the requested feature applies to the recommendation algorithm components that have been open-sourced thus far.

**Comment by m-a-sch** [comment]
Oh well, at least the issue is now documented and assessed to not relate to the recommendation algorithm. Your call!
