### ISSUE TITLE
How to apply this Recommender system for my website?

### ISSUE THREAD

**Issue by quangbilly79** [twitter/the-algorithm#1664]
Currently, we're running a book website. We are using the Universal Recommender System, a kind of recommend system that is based on user activities like read, buy, rate,... But now I want to apply this Twitter recommender algorithm to our website. Where to start?

**Comment by nobodyindustries** [comment]
not possible, this is not even close to be usable

**Comment by ABSanthosh** [comment]
Did you read [this](https://github.com/twitter/the-algorithm/blob/main/home-mixer/README.md)?

**Comment by 170031284** [comment]
I feel for websites we do seo to get recognised by other on google .

**Comment by jdm-twtr** [comment]
Thanks for the feedback! Unfortunately we don't have any current plans to provide instructions on how to apply any of our code to other use cases.
