### ISSUE TITLE
Fix "not interested in this tweet" button

### ISSUE THREAD

**Issue by python273** [twitter/the-algorithm#1677]
Twitter doesn't immediately remove these tweets from the feed, so if I refresh the page or keep scrolling, it will keep showing them

**Comment by python273** [comment]
And possibly there's some bug. I just refreshed the feed, and out of 10 first tweets, 7 were the ones I clicked "not interested in this tweet" (also clicked "show fewer tweets from X" I think)

**Comment by ValZapod** [comment]
Youtube also does not remove, just hides. I think it is just to costly.

**Comment by jdm-twtr** [comment]
Thanks for filing. We've marked this issue as an unrelated bug or feature for future review.
                    In order to keep our issue count manageable, we will not be leaving these issues open. We apologize for
                    the inconvenience. If you feel that we closed your issue in error, please re-file the issue, stating how
                    the requested feature applies to the recommendation algorithm components that have been open-sourced thus far.
