### ISSUE TITLE
Remove elon musk

### ISSUE THREAD

**Issue by astralgarden** [twitter/the-algorithm#1680]
there's this guy on the website and he's annoying, i dont think this is an intended feature can we get rid of him somehow?

**Comment by iChillieman** [comment]
Grow up

**Comment by Strypper** [comment]
> Grow up 

I can't trust the guy code Solidity

**Comment by steevjames** [comment]
+1

**Comment by paxperscientiam** [comment]
Why was this closed?

**Comment by IverCoder** [comment]
Reopen this! It's a severe bug that significantly degrades many people's Twitter experience.

**Comment by AndrewKhassapov** [comment]
As of 8 April, 2023, this issue still persists.

Despite popular requests to resolve this:
![Elon Musk promise to step down as head](https://user-images.githubusercontent.com/53222142/230712106-f69cc099-2d6a-450a-845b-2f0f7cd02c53.png)

Can somebody at Twitter have a look at this bug?
So far, to date, this issue has cost Twitter over **$24 Billion USD**, from 27 October, 2022.

**Comment by varungupta3009** [comment]
This bug, codenamed `FunnyMan`, is a P(-1) issue and needs to be fixed ASAP. It is the known cause of many false claims, suppression of free speech, and the spread of hate and misery on Twitter.

![Fg6z4cNWQAEb3od](https://user-images.githubusercontent.com/16451006/230720519-4ee5b1aa-8ac7-41bb-ade8-4757b6533e6c.jpeg)
[[Source]](https://twitter.com/drewblagrim/status/1589405503066869760?s=20) 

This bug could cause [over 30 million people to deboard the platform.](https://www.theguardian.com/technology/2022/dec/13/twitter-lose-users-elon-musk-takeover-hate-speech)

`FunnyMan` is possibly the biggest threat Twitter has ever faced, and if not fixed soon, could cause the company to turn into nothing more than the playground of a self-proclaimed visionary.

Let us know if we can assist you fine folks in any way...

**Comment by Baumistlustig** [comment]
Same issue here. Workaround available?

**Comment by DanyPell** [comment]
Elon is too precious we want him on Tesla and SpaceX and just a bit on Twitter!

**Comment by placholder** [comment]
> Elon is too precious we want him on Tesla and SpaceX and just a bit on Twitter!

fangirling right there

**Comment by zombie200** [comment]
nigga
