### ISSUE TITLE
Automatic refresh on twitter web and a dumb rule

### ISSUE THREAD

**Issue by 404Nikhil** [twitter/the-algorithm#1682]
very annoying whole feed vanishes in no time. also why the hell does muting someone actually have a negative impact on impressions so dumb.

**Comment by jdm-twtr** [comment]
Thanks for filing. We've marked this issue as an unrelated bug or feature for future review.
                    In order to keep our issue count manageable, we will not be leaving these issues open. We apologize for
                    the inconvenience. If you feel that we closed your issue in error, please re-file the issue, stating how
                    the requested feature applies to the recommendation algorithm components that have been open-sourced thus far.
