### ISSUE TITLE
Something like "Instagram Guides" which solves the problem of multiple threads tweets

### ISSUE THREAD

**Issue by 404Nikhil** [twitter/the-algorithm#1684]
https://embedsocial.com/blog/instagram-guides/ 

Instagram guide is an underrated feature which lets a user to compile multiple posts and stories in a single scroll refer to the above article to know more. https://www.instagram.com/ompsyram/guide/the-kumbh-mela-2021/17899209598828762/ This is an another live example.

As you know many Twitter users are from education, business or finance background they tend to share their advice/knowledge in 10-15 tweet threads and it's honestly very inconvenient to go through them this feature will make their and our life much smoother and also upgrade twitter's post capacity.

**Comment by jdm-twtr** [comment]
Thanks for filing. We've marked this issue as an unrelated bug or feature for future review.
                    In order to keep our issue count manageable, we will not be leaving these issues open. We apologize for
                    the inconvenience. If you feel that we closed your issue in error, please re-file the issue, stating how
                    the requested feature applies to the recommendation algorithm components that have been open-sourced thus far.
