### ISSUE TITLE
Shocking lack of NFT Market

### ISSUE THREAD

**Issue by Evan3ik** [twitter/the-algorithm#1687]
Elon please add nft market to twingus
Main currency would be "Dogecoin" and "Btc" and "etherium"
![Capture](https://user-images.githubusercontent.com/90270668/230175428-20a8a917-dc03-4658-8175-675e978c5cf7.PNG)

**Comment by jdm-twtr** [comment]
Thanks for filing. We've marked this issue as an unrelated bug or feature for future review.
                    In order to keep our issue count manageable, we will not be leaving these issues open. We apologize for
                    the inconvenience. If you feel that we closed your issue in error, please re-file the issue, stating how
                    the requested feature applies to the recommendation algorithm components that have been open-sourced thus far.

**Comment by zombie200** [comment]
maybe die
