### ISSUE TITLE
Create a 18+ icon on the content 

### ISSUE THREAD

**Issue by 170031284** [twitter/the-algorithm#1697]
The purpose of this icon is to automated identify and verify sensitive content and put a 18+ icon on it and it should not be recommended to user account age <18.

**Comment by jdm-twtr** [comment]
Thanks for filing. We've marked this issue as an unrelated bug or feature for future review.
                    In order to keep our issue count manageable, we will not be leaving these issues open. We apologize for
                    the inconvenience. If you feel that we closed your issue in error, please re-file the issue, stating how
                    the requested feature applies to the recommendation algorithm components that have been open-sourced thus far.
