### ISSUE TITLE
Cat TwT

### ISSUE THREAD

**Issue by jcgaming-official** [twitter/the-algorithm#1699]
My cat is too tired using twitter
![PXL_20211229_032317683](https://user-images.githubusercontent.com/77482435/230274521-dd95fc3c-c01d-4226-a1c7-76e1633690c0.jpg)

**Comment by valiantuser** [comment]
Sad

**Comment by ilovelinux** [comment]
Useless issue, please close

**Comment by Angus1811** [comment]
> 

real

**Comment by TruncatedDinosour** [comment]
> Useless issue, please close

youre useless :(

**Comment by valiantuser** [comment]
🤓

**Comment by nectarboy** [comment]
stinky lookin cat

**Comment by valiantuser** [comment]
> stinky lookin cat

![thisuaftersayinthis](https://user-images.githubusercontent.com/101596581/230475597-1ac91399-f300-4d72-8f8b-8d87cb129925.gif)

**Comment by valiantuser** [comment]
true, the cat is goofy lookin

**Comment by Angus1811** [comment]
> > Useless issue, please close
> 
> 
> 
> youre useless :(

This guy has been quite usless

He spent his whole day telling everyone to close their issues

**Comment by jdm-twtr** [comment]
Thanks for filing. We've marked this issue as an unrelated bug or feature for future review.
                    In order to keep our issue count manageable, we will not be leaving these issues open. We apologize for
                    the inconvenience. If you feel that we closed your issue in error, please re-file the issue, stating how
                    the requested feature applies to the recommendation algorithm components that have been open-sourced thus far.
