### ISSUE TITLE
Don't be afraid to steal some Mastodon features

### ISSUE THREAD

**Issue by m-a-sch** [twitter/the-algorithm#1700]
**Is your feature request related to a problem? Please describe.**
Not able to set data retention policy.

**Describe the solution you'd like**
It should be possible, like on Mastodon, to set a default retention policy for tweets, like "forever", "1 month", "1 week"

**Describe alternatives you've considered**
Manually deleting old tweets or deleting the account to recreate another.

**Additional context**
A rather basic feature when you think about it.

**Comment by jdm-twtr** [comment]
Thanks for filing. We've marked this issue as an unrelated bug or feature for future review.
                    In order to keep our issue count manageable, we will not be leaving these issues open. We apologize for
                    the inconvenience. If you feel that we closed your issue in error, please re-file the issue, stating how
                    the requested feature applies to the recommendation algorithm components that have been open-sourced thus far.

**Comment by m-a-sch** [comment]
A recommendation algorithm could come with different outcomes if it was based on data respecting the retention policies of the users. Of course, we won't know for sure as there is no desire to allow retention policies to be managed. Your call.
