### ISSUE TITLE
can u add a feature pls

### ISSUE THREAD

**Issue by Angus1811** [twitter/the-algorithm#1703]
if u have an NFT on twitter it wont promote you in the algorithm 

ty

edit: maybe even add a dislike button too

**Comment by ynks** [comment]
+1

**Comment by Angus1811** [comment]
is that social credit?

**Comment by jdm-twtr** [comment]
Thanks for filing. We've marked this issue as an unrelated bug or feature for future review.
                    In order to keep our issue count manageable, we will not be leaving these issues open. We apologize for
                    the inconvenience. If you feel that we closed your issue in error, please re-file the issue, stating how
                    the requested feature applies to the recommendation algorithm components that have been open-sourced thus far.
