### ISSUE TITLE
can't see twitter logo now, why?

### ISSUE THREAD

**Issue by zephy20** [twitter/the-algorithm#1709]
i see the logo of doge coin everywhere. pls fix this bug elon

**Describe the bug**

**To Reproduce**
1. Go to twitter website
2. see logo on top left
3. doge coin logo

**Expected behavior**
i should see my bird icon instead of doge coin

**Screenshots**
![Screenshot 2023-04-06 at 6 34 27 PM](https://user-images.githubusercontent.com/7047892/230387066-0a24dc4e-f892-480f-b897-2f75c418138c.png)

**Additional context**
pls fix this bug elon

**Comment by TruncatedDinosour** [comment]
its bc i said so

**Comment by VainXploits** [comment]
8====👊D

8===👊=D

8==👊==D

8=👊===D

8👊====D

8=👊===D

8==👊==D

8===👊=D

8====👊D

8===👊=D

8==👊==D

8=👊===D

8👊====D

8=👊===D

8==👊==D

8===👊=D

8====👊D

8===👊=D

8==👊==D

8=👊===D

8👊====D

8=👊===D

8==👊==D

8===👊=D

8====👊D

8===👊=D

8==👊==D

8=👊===D

8👊====D

8=👊===D

8==👊==D

8===👊=D

8====👊D

8===👊=D

8==👊==D

8=👊===D

8👊====D

8=👊===D

8==👊==D

8===👊=D

8====👊D

8===👊=D

8==👊==D

8=👊===D

8👊====D

8=👊===D

8==👊==D

8===👊=D

8====👊D

8===👊=D

8==👊==D

8=👊===D

8👊====D

8=👊===D

8==👊==D

8===👊=D

8====👊D

8===👊=D

8==👊==D

8=👊===D

8👊====D

8=👊===D

8==👊==D

8===👊=D

8====👊D

8===👊=D

8==👊==D

8=👊===D

8👊====D

8=👊===D

8==👊==D

8===👊=D

8====👊D

8===👊=D

8==👊==D

8=👊===D

8👊====D

8=👊===D

8==👊==D

8===👊=D

8====👊D💦💦

8====👊D

8===👊=D

8==👊==D

8=👊===D

8👊====D

8=👊===D

8==👊==D

8===👊=D

8====👊D💦💦

8===👊=D

8==👊==D

8=👊===D

8👊====D

8=👊===D💦💦

8==👊==D

8===👊=D

8====👊D

8===👊=D

8==👊==D

8=👊===D

8👊====D

8=👊===D

8==👊==D

8===👊=D

8====👊D💦💦

8===👊=D

8==👊==D

8=👊===D

8👊====D

8=👊===D

8==👊==D

8===👊=D

8====👊D💦💦

8===👊=D

8==👊==D💦

8=👊===D

8👊====D

8=👊===D

8==👊==D💦💦

8===👊=D

**Comment by AccountNameIsTaken** [comment]
Confirmed, very common bug. 
elong pls fix

**Comment by valiantuser** [comment]
> i see the logo of doge coin everywhere. pls fix this bug elon
> 
> **Describe the bug** A clear and concise description of what the bug is.
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Go to twitter website
> 2. see logo on top left
> 3. doge coin logo
> 
> **Expected behavior** i should see my bird icon instead of doge coin
> 
> **Screenshots** ![Screenshot 2023-04-06 at 6 34 27 PM](https://user-images.githubusercontent.com/7047892/230387066-0a24dc4e-f892-480f-b897-2f75c418138c.png)
> 
> **Additional context** pls fix this bug elon
![thisuaftersayinthis](https://user-images.githubusercontent.com/101596581/230444882-432b8b29-7add-4ba1-b23d-9b87505d809a.gif)

**Comment by ValZapod** [comment]
Android full app does not have that problem. Use that.

**Comment by jdm-twtr** [comment]
Thanks for filing. We've marked this issue as an unrelated bug or feature for future review.
                    In order to keep our issue count manageable, we will not be leaving these issues open. We apologize for
                    the inconvenience. If you feel that we closed your issue in error, please re-file the issue, stating how
                    the requested feature applies to the recommendation algorithm components that have been open-sourced thus far.

**Comment by wmonecke** [comment]
Who tf is this @jdm-twtr

**Comment by Lukas1h** [comment]
> Who tf is this @jdm-twtr

ur mom

**Comment by valiantuser** [comment]
lol

**Comment by valiantuser** [comment]
God dam
------- Original Message -------
