### ISSUE TITLE
Add hidden markdown to the tweet creation section!

### ISSUE THREAD

**Issue by Yowezy** [twitter/the-algorithm#1718]
lets make twitter great again 🐶.

**Comment by jjolatunji1** [comment]
‼️‼️HOLY FLOPPIN SHIT‼️‼️‼️‼️ IS THAT A MOTHERFLOPPIN AMONG US REFERENCE??????!!!!!!!!!!11!1!1!1!1!1!1! 😱😱😱😱😱😱😱AMONG US IS THE BEST FLIPPIN GAME 🔥🔥🔥🔥💯💯💯💯RED IS SO SUSSSSS 🕵️🕵️🕵️🕵️🕵️🕵️🟥🟥🟥🟥🟥 COME TO MEDBAY AND WATCH ME SCAN🏥🏥🏥🏥🏥🏥🏥🏥 WHY IS NO ONE FIXING 02 🤬🤬😡😡🤬😡🤬😡🤬😡🤬😡🤬😡 OH YOUR CREWMATE? NAME EVERY TASK🔫😠🔫😠🔫😠🔫😠🔫😠 Where Any sus!❓❓Where! ❓❓ Where! Any sus! ❓❓Where! ❓❓ Any sus! ❓❓ Any sus! ❓❓Where!Where!Where! Any sus!❓❓ Where! Any sus Where! ❓❓ Where!❓❓ Where! Any sus ❓❓Any sus! ❓❓❓❓❓❓Where! ❓Where!❓Any sus! ❓❓Any sus! ❓ ❓ Where! ❓ Any sus! ❓ Where! ❓ ❓ Where! ❓ Where! Where! ❓❓❓Any sus!❓❓Any sus!❓❓❓Where!❓Where! Where! Any sus!Where! Where!❓❓❓❓❓❓I think it was purple! 👀👀👀👀👀👀👀It wasnt me I was in vents!!!!!!!!!!!!😂😂😂🤣😂🤣😂🤣😂🤣😂😂 r/amongusmemes r/unexpectedamongus r/expectedamongus perfectly balanced as all things should be r/unexpectedthanos r/expectedthanos for balance

**Comment by Angus1811** [comment]
‼️‼️HOLY FLOPPIN SHIT‼️‼️‼️‼️ IS THAT A MOTHERFLOPPIN AMONG US REFERENCE??????!!!!!!!!!!11!1!1!1!1!1!1! 😱😱😱😱😱😱😱AMONG US IS THE BEST FLIPPIN GAME 🔥🔥🔥🔥💯💯💯💯RED IS SO SUSSSSS 🕵️🕵️🕵️🕵️🕵️🕵️🟥🟥🟥🟥🟥 COME TO MEDBAY AND WATCH ME SCAN🏥🏥🏥🏥🏥🏥🏥🏥 WHY IS NO ONE FIXING 02 🤬🤬😡😡🤬😡🤬😡🤬😡🤬😡🤬😡 OH YOUR CREWMATE? NAME EVERY TASK🔫😠🔫😠🔫😠🔫😠🔫😠 Where Any sus!❓❓Where! ❓❓ Where! Any sus! ❓❓Where! ❓❓ Any sus! ❓❓ Any sus! ❓❓Where!Where!Where! Any sus!❓❓ Where! Any sus Where! ❓❓ Where!❓❓ Where! Any sus ❓❓Any sus! ❓❓❓❓❓❓Where! ❓Where!❓Any sus! ❓❓Any sus! ❓ ❓ Where! ❓ Any sus! ❓ Where! ❓ ❓ Where! ❓ Where! Where! ❓❓❓Any sus!❓❓Any sus!❓❓❓Where!❓Where! Where! Any sus!Where! Where!❓❓❓❓❓❓I think it was purple! 👀👀👀👀👀👀👀It wasnt me I was in vents!!!!!!!!!!!!😂😂😂🤣😂🤣😂🤣😂🤣😂😂 r/amongusmemes r/unexpectedamongus r/expectedamongus perfectly balanced as all things should be r/unexpectedthanos r/expectedthanos for balance

**Comment by valiantuser** [comment]
https://user-images.githubusercontent.com/101596581/230464014-180bde70-ea47-4a60-994a-a8d41ac1ed7a.mp4

**Comment by jdm-twtr** [comment]
Thanks for filing. We've marked this issue as an unrelated bug or feature for future review.
                    In order to keep our issue count manageable, we will not be leaving these issues open. We apologize for
                    the inconvenience. If you feel that we closed your issue in error, please re-file the issue, stating how
                    the requested feature applies to the recommendation algorithm components that have been open-sourced thus far.
