### ISSUE TITLE
Users are not redirected to the fediverse

### ISSUE THREAD

**Issue by TheMemeSniper** [twitter/the-algorithm#1720]
A working fix could be implemented like this:
```
window.location = "https://fedi.guide/";
```

**Comment by Nerohybrid** [comment]
seem to be facing this bug too, strange....

**Comment by jdm-twtr** [comment]
Please file issues that are relevant to Twitter's Recommendation Algorithm. Issue spam will not be tolerated and the threshold for blocking is low.
