### ISSUE TITLE
Adding a CONTRIBUTING.md for the project

### ISSUE THREAD

**Issue by guptaaryan16** [twitter/the-algorithm#1728]
**Is your feature request related to a problem? Please describe.**
The code is a bit difficult to read especially for new developers. Also there is no effort right now to explain the structure and the contributing-policies for the project. 

**Describe the solution you'd like**
A clear ` CONTRIBUTING.md` that describes the project structure and the PRs structure would be a great addition.

**Describe alternatives you've considered**

**Additional context**

**Comment by peekeset** [comment]
Duplicate issue. See #569

**Comment by guptaaryan16** [comment]
Ok let men close it
