### ISSUE TITLE
Remove Elon Musk (2)

### ISSUE THREAD

**Issue by steevjames** [twitter/the-algorithm#1739]
This is a continuation of the issue in:
https://github.com/twitter/the-algorithm/issues/1680

The issue is very important hence creating V2.

This is a P(1) issue and needs to be fixed ASAP. It is the known cause of many false claims, suppression of free speech, and the spread of hate on Twitter.

Also, If anyone reading this is in Twitter HQ right now, please remind Elon this:
![image](https://user-images.githubusercontent.com/23638042/230724483-7c4c0791-e0b2-4250-8fd1-e3f9ae073681.png)

Thanks.

**Comment by taextreme** [comment]
I hope this issue is getting solve asap.

**Comment by PiniponSelvagem** [comment]
Sometimes people should learn what the github issues are for...

**Comment by bigkwii** [comment]
i'd say this is very much an issue

**Comment by DialMat** [comment]
huge bug that caused a lot of users to close their app right after the algo pushed his cringe-ass tweets in their face. hoping for a quick fix here

**Comment by jungalho** [comment]
> 

sometimes people should learn what the jokes are for and their intents...

**Comment by Ben-Brady** [comment]
This issue is significantly degrading the user experience of the platform, it's causing major blowback from the community. It definetely needs to be addressed asap.

**Comment by TolstoyDotCom** [comment]
Musk is censoring millions of people each day. As the algorithm shows, Musk calls millions of tweets "LowQuality" or "AbusiveQuality" each day.

If you want to force changes at Twitter, all you need to do is wise those people up. Urge people to find out where Twitter is really showing their replies (like by viewing tweets they reply to using a test account).

If millions of people realize Musk is censoring them and calling their replies "LowQuality", Musk is going to be in trouble.

**Comment by DelicousSourceCode** [comment]
This is probably an issue... just not one of the algorithm

**Comment by DelicousSourceCode** [comment]
This is probably an issue... just not one of the algorithm

**Comment by edgarsingui** [comment]
this problem will probably be solved in twitter 2

**Comment by EZonTheEyes** [comment]
> Sometimes people should learn what the github issues are for...

this person is trying to bring attention to the real issue

**Comment by notaduck448** [comment]
Ran into this exact same issue this morning and I came up with a temporary workaround for the problem. To fix the issue, follow these steps:

1. Log onto twitter
2. Delete your account

Unfortunately this solution doesn't completely fix the issue as it doesn't remove elon from CEO of twitter, which will continue to severely cripple the user experience for people still choosing to use the platform. However it seems to be the best fix for the time being and will suffice until we can get a more permanent solution. I recommend someone open a PR to address this issue so we can fix it.

**Comment by Xpenzz** [comment]
Good lord you're a loser.

**Comment by taextreme** [comment]
> Good lord you're a loser.

Good lord you're a corporate slave or Elon Fan boi

**Comment by StarKnightt** [comment]
Literally, bro raised this as an issue. 🩻

**Comment by akizminet** [comment]
Will you pay him US$44 billion?

**Comment by sokorototo** [comment]
> Sometimes people should learn what the github issues are for...

touch grass+maidenless+goblin+bluepilled+smoothbrain+trash+beta+weak+pathetic+ignorant+clueless+smh+underwhelming+cringepilled+disappointing+foolish+embarrassing+disgraceful+atrocious+terrible+awful+wack+bootlicker+pleb

**Comment by placholder** [comment]
> > Good lord you're a loser.
> 
> Good lord you're a corporate slave or Elon Fan boi

nope its a fan girl

**Comment by steevjames** [comment]
> > Has anyone ever considered just using Twitter without following Elon Musk? I never check the "For you" section because he's always lurking there
> 
> I have tried not using Twitter at all and it solved all the issues for me

This workaround fixes the issue. Still awaiting permanent fix.
