### ISSUE TITLE
Is Elon Musk the least funny person in the world?

### ISSUE THREAD

**Issue by nobodyindustries** [twitter/the-algorithm#1769]
**Describe the bug**
The edgy memes and jokes that Elon Musk tweets are at the root of my depression.

**To Reproduce**
1 - Go to Twitter
2 - Search for Elon Musk's account
3 - Guaranteed in the first 10 tweets there will be an edgy joke that will make you cry, and not in a good way.

**Expected behavior**
Not to see such sad things. Also, Elon Musk should resign as CEO of Twitter, as he promised.

**Screenshots**
<img width="617" alt="image" src="https://user-images.githubusercontent.com/80129636/231265106-b0de6fae-d7c4-490a-a758-a28e3d75c5d3.png">

**Environment**
All.

**Additional context**
The saddest part is that he truly believes he is funny.

**Comment by nobodyindustries** [comment]
More examples...
<img width="614" alt="image" src="https://user-images.githubusercontent.com/80129636/231265971-eb370712-ea88-41dd-a2e4-6c1ad7390a3f.png">

**Comment by DanyPell** [comment]
LMAO that landlord can go take a hike!

**Comment by steevjames** [comment]
Fix is tracked via https://github.com/twitter/the-algorithm/issues/1739

**Comment by megatronskneecap** [comment]
> **Describe the bug** The edgy memes and jokes that Elon Musk tweets are at the root of my depression.
> 
> **To Reproduce** Steps to reproduce the behavior: 1 - Go to Twitter 2 - Search for Elon Musk's account 3 - Guaranteed in the first 10 tweets there will be an edgy joke that will make you cry, and not in a good way.
> 
> **Expected behavior** Not to see such sad things. Also, Elon Musk should resign as CEO of Twitter, as he promised.
> 
> **Screenshots** <img alt="image" width="617" src="https://user-images.githubusercontent.com/80129636/231265106-b0de6fae-d7c4-490a-a758-a28e3d75c5d3.png">
> 
> **Environment** All.
> 
> **Additional context** The saddest part is that he truly believes he is funny.

Ambatu Kahn and Ambatu Bass agree with this information.
