### ISSUE TITLE
Twitter Servers are Useless now

### ISSUE THREAD

**Issue by sunnamed434** [twitter/the-algorithm#1775]
Why don't you just shut down this Twitter cuz anyone could just deploy it on Azure or AWS by ourselves using the source code or just on GitHub pages, so, why don't you just mine shiba-inu on your servers instead of running useless servers?

**Comment by aloiscochard** [comment]
Hey @sunnamed434,

Thanks for your en-lighted argument, there is different alternative platforms that are doing exactly that without requiring any of those extremely costly and badly designed corporate clouds.

**Comment by KaspianDev** [comment]
> Why don't you just shut down this Twitter cuz anyone could just deploy it on Azure or AWS by ourselves using the source code or just on GitHub pages, so, why don't you just mine shiba-inu on your servers instead of running useless servers?

It surely works like that.
