### ISSUE TITLE
Disable Github issues

### ISSUE THREAD

**Issue by lazer-hybiz** [twitter/the-algorithm#1778]
Github issues is worthless in this project since the majority of issues is spam, anyone having a real issue can submit a PR.

Please disable it, see here: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/enabling-features-for-your-repository/disabling-issues

**Comment by aloiscochard** [comment]
Hey @lazer-hybiz it was decided to the exact opposite for now.

If this goes against your philosophy please describe other significantly largo open source projects were your strategy were successful and will be revisit our decision.

Otherwise, we will apply @zombie200 suggestion, ASAP.
