### ISSUE TITLE
Report a Github issue directly from Twitter

### ISSUE THREAD

**Issue by FelixWaweru** [twitter/the-algorithm#1810]
I'd like to suggest a feature that allows users to directly create Github issues from the Twitter app whenever they encounter a severe issue. Filtering can be applied to the requests before they are submitted to ensure quality over time.

This will ease the process by which issues are shared and will also allow for the collection of feedback from a wider audience.

Additionally, feature requests can also be submitted through this method and this can help crowdsource improvements for the app.

**Comment by jdm-twtr** [comment]
Currently, GitHub issues should be used for bugs and feature requests strictly pertaining to the algorithm code itself. Bugs/Features to be addressed in client apps should go through any existing bug reporting in the app itself, or through the Help Center via https://help.twitter.com/en/twitter-for-you .
