### ISSUE TITLE

Hello

 Please re-open the account I do not know about Twitter because systems written very English and I am an Arab and I do not know very English  Please re-open the account as soon as possible. I would ask apologize if I broke any privacy rule. I promise it will not be repeated again

I affirm, under penalty of perjury, that the information in this reply email is truthful and accurate.

and thank you

 @chinanws22

 @WORLD___2022

 @chinewar111



### ISSUE THREAD

**Issue by Monneraldo** [twitter/the-algorithm#1812]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment**
For web, specify your OS and browser version.  For mobile, specify device, OS
and version.  For libraries, what version of build tools are you using?

**Additional context**

**Comment by Monneraldo** [comment]
Hello

 Please re-open the account I do not know about Twitter because systems written very English and I am an Arab and I do not know very English  Please re-open the account as soon as possible. I would ask apologize if I broke any privacy rule. I promise it will not be repeated again

I affirm, under penalty of perjury, that the information in this reply email is truthful and accurate.

and thank you

 @chinanws22

 @WORLD___2022

 @chinewar111

**Comment by planetoryd** [comment]
Why ? Why do I care ?

**Comment by Monneraldo** [comment]
Please re-open the account I do not know about Twitter because systems
written very English and I am an Arab and I do not know very English
 Please re-open the account as soon as possible. I would ask apologize if I
broke any privacy rule. I promise it will not be repeated again


I affirm, under penalty of perjury, that the information in this reply
email is truthful and accurate.


and thank you


 @chinanws22


 @WORLD___2022


 @chinewar111





في الثلاثاء، ٢ مايو ٢٠٢٣ ١١:٥١ ص plein ***@***.***> كتب:

**Comment by planetoryd** [comment]
What did you do ?

**Comment by murosev** [comment]
LGTM!

**Comment by Monneraldo** [comment]
I did nothing. I respect the Twitter rules and do not violate them at all. I do not know why the comment was made

**Comment by Monneraldo** [comment]
> What did you do ? 

I did nothing. I respect the Twitter rules and do not violate them at all. I do not know why the comment was made

**Comment by Monneraldo** [comment]
> Issue closed. You don't need that

I didn't understand

**Comment by Monneraldo** [comment]
Will the accounts return? I want to celebrate, please

**Comment by ghost** [comment]
> Issue closed. You don't need that

bro needs his account back

**Comment by ghost** [comment]
give him the account back
THIS IS VERY IMPORTANT
@twitter @aramog
