### ISSUE TITLE
we should add my dog to the algorithm

### ISSUE THREAD

**Issue by neeeerrd** [twitter/the-algorithm#1865]
**Is your feature request related to a problem? Please describe.**
theres no problem its just i feel like my dog would be happier if it was part of the twitter algorithm
**Describe the solution you'd like**
i want to replace all tweets with a photo/quote from my dog

**Describe alternatives you've considered**
there are no alternatives. this is the only way to fix twitter after the shit elons done

**Additional context**
i also request you fire elon

**Comment by falseuniversefacts** [comment]
I always think Elon just can't get worse, and then he does something stupider.

I am reminded of this quote from The Office: "Every day you do something stupider than you did the day before. And I think, 'there’s no possible way he can top that.' But what do you do?! You find a way, dammit, to top it! You are a professional idiot!"

**Comment by Galactipod** [comment]
No need for QA on this one. The Gods approve, I can feel it in my bone.

**Comment by neeeerrd** [comment]
i need to ping elon for this. this is important and it doesnt seem like twitter is going to do this. they have to.
