### ISSUE TITLE
[Serious] Twitter keeps recommending users who post CSAM

### ISSUE THREAD

**Issue by pixiekat** [twitter/the-algorithm#1879]
Oh wait, sorry, my bad... that's just [Elon Musk protecting right wing conspiracy theorists that post CSAM](https://www.washingtonpost.com/technology/2023/07/27/twitter-csam-dom-lucre-elon-musk/).

https://www.washingtonpost.com/technology/2023/07/27/twitter-csam-dom-lucre-elon-musk/

**Comment by dumbuz** [comment]
> @pixiekat why did you close this issue?

Miraculously, nothing happened and this stopped being a problem?

**Comment by Kush8848** [comment]
Are you drinking tranny fluid pixiekat. The world doesn't revolve around you. Now go cry behind the closet. Nobody cares about your agenda outside US

**Comment by dumbuz** [comment]
> Are you drinking tranny fluid pixiekat. The world doesn't revolve around you. Now go cry behind the closet. Nobody cares about your agenda outside US

Woah woah woah bud, this is just a GitHub repository, there is no need for slurs.
