### ISSUE TITLE
change the name X to H

### ISSUE THREAD

**Issue by ghost** [twitter/the-algorithm#1880]
**Is your feature request related to a problem? Please describe.**
H is obviously the far better letter, and X is used by other companies anyways

**Describe the solution you'd like**
A complete change of the X name to H

**Describe alternatives you've considered**
You could also change it to E, but H is still the far better option

**Additional context**
h

**Comment by Sylicium** [comment]
i agree.

**Comment by pixiekat** [comment]
This makes sense since the way to stop a haemorrhoid is with H.

**Comment by ghost** [comment]
I agree too!

**Comment by richardanderson001** [comment]
The letter "I" would be less than half as bright as "H" or "X"

**Comment by ghost** [comment]
H is far better than I. I is such a lazy letter, just a line, and the lowercase version is just a line with a dot. The other variant of the uppercase I is just a wide uppercase H flipped on its side. H is far more beautiful than the letter I.

**Comment by LeviSnoot** [comment]
I think if we somehow put the `H` and the `I` together we would have the best of both worlds. It's true that by itself, `I` doesn't accomplish much. 

But if we let `H` and `I` work together to form something new, we would have something revolutionary on our hands.

I believe we need Elon's input on this issue as it would take a true genius to realize the raw potential of what we're dealing with here.

**Comment by ghost** [comment]
H and I could form something beautiful if put together. I will attempt to ping Elon on twitter to ask for his input.
