### ISSUE TITLE
Why is elon so obsessed with the letter 'x'?

### ISSUE THREAD

**Issue by carnageiron** [twitter/the-algorithm#1887]
### Why is elon so obsessed with the letter 'x'?

**Comment by martinprad0** [comment]
P*rn addiction

**Comment by ghost** [comment]
Maybe it reminds him of all his X-wives

**Comment by justcoredev** [comment]
I want him to buy YouTube and rename it to XVideos

**Comment by Customimine** [comment]
X - alway is hidden character. He want everybody think about this char.

**Comment by zisra** [comment]
Because it's cool

**Comment by justcoredev** [comment]
> X - alway is hidden character. He want everybody think about this char.

Lol that makes sense in case with SpaceX. I mean SpaceX goal to figure out secrets of the universe. But i cant understand why twitter is X now

**Comment by CamoCatX** [comment]
@carnageiron Here's the real answer: https://www.npr.org/2022/04/18/1093380832/a-look-at-elon-musk-and-what-he-represents

**Comment by Njoxpy** [comment]
> I want him to buy YouTube and rename it to XVideos

What if he buys Blazers?
