### ISSUE TITLE
replace x with twitter

### ISSUE THREAD

**Issue by Loch32** [twitter/the-algorithm#1889]
elon piss off you sodding tictac

**Comment by flufferyomada** [comment]
True

**Comment by SharanSMenon** [comment]
yea someone remove this madman from twitter

**Comment by codingneko** [comment]
This is top priority, please fix right now.

**Comment by ErrorOliver** [comment]
This is very urgent @twitter-service!!

**Comment by codingneko** [comment]
Can confirm this issue is NOT solved. Should not be closed as completed, please re-open or close as wontfix. Else you literally don't know how to use github.

**Comment by Loch32** [comment]
over a month later and this issue is still not solved, despite being closed as such.

**Comment by codingneko** [comment]
Finally you fuckers figured this out. Rest in piss Twitter, hope X crashes and burns soon too.
