### ISSUE TITLE
here's a serious bug on Twitter(X) web you guys need to see ... i recorded a video 

### ISSUE THREAD

**Issue by Rono0365** [twitter/the-algorithm#1890]
https://github.com/twitter/the-algorithm/assets/63807776/e693124b-4058-449f-93cf-82f472f3c50a

**Comment by Klivess** [comment]
if you refresh, does it stay that high? should be a client-side bug 

edit: did my own testing, this is client-side, not as big of a deal as this issue made it to be

**Comment by ErrorOliver** [comment]
Sh𝕏tter
