### ISSUE TITLE
Ban all issues with the letter before Y in them

### ISSUE THREAD

**Issue by mybearworld** [twitter/the-algorithm#1891]
**Describe the bug**
There are many people making jokes about the platform formerly known as Twitter being renamed to the letter before Y.

**To Reproduce**

1. Memorize the following set of characters: `m`, `h`, `t`, `i`, `r`, `l`, `o`, `g`, `a`, `_`, `e`, `t`, `h`, `/`, `r`, `e`, `t`, `t`, `w`, `i`, `t`, `/`, `o`, `m`, `c`, `.`, `b`, `u`, `h`, `t`, `i`, `g`, `/`, `/`, `:`, `p`, `s`, `t`, `t`, `h`
2. Start your computer
3. If necessary, remember your password
4. Log into your user account
5. Click on the WiFi settings
6. Still know those characters?
7. Click on your WiFi
8. If necessary, remember your password
9. Type in your password
10. Press Enter
11. Wait
12. Remember the characters?
13. Open a web browser
14. Think of the characters!
15. Type them in
16. Realize you have to type them in backwards
17. Type them in backwards
18. _This step is left as an ecksercise for the reader_
19. Click on "Issues"
20. Open your eyes. _Reference image: 👁️👁️_
21. Use the eyes to look.

**Eckspected behavior**

No issues with the letter before Y.

**Screenshots**

![a lot of issues with the letter before Y in them](https://github.com/twitter/the-algorithm/assets/130385691/7f00e2bb-307c-40d8-8cca-841b726f03db)

**Environment**

Windows 11, Microsoft Edge

**Comment by SharanSMenon** [comment]
yea tihs reopsoirty shulod be rneaemd to Y not X.

**Comment by mybearworld** [comment]
This is a sad moment for humanity, trolls are being accepted and endorsed :(
