### ISSUE TITLE
elon, you coward, respond to my issues

### ISSUE THREAD

**Issue by ghost** [twitter/the-algorithm#1894]
i have pinged you on social media. i have written 2 issues on this repository.

why doesnt elon listen to me? is he stupid?

**Comment by mathlover2** [comment]
Of course he is

**Comment by SharanSMenon** [comment]
no he is very hard at work, removing blocking feature, you must understand.

**Comment by CamoCatX** [comment]
Unless you own both a rocket ship business and a electric car company, then thinking Elon's stupid is an opinion that not you nor me can have.

**Comment by ghost** [comment]
> Unless you own both a rocket ship business and a electric car company, then thinking Elon's stupid is an opinion that not you nor me can have.

lmao so i cant criticize my president because i dont have power over a country? i dont give a flying fuck about what he owns, hes destroying twitter and is losing money really fucking fast so he might not have those businesses for much longer either.

**Comment by ErrorOliver** [comment]
Sh𝕏tter

**Comment by natewhar** [comment]
E

**Comment by crystalstorm466** [comment]
skill issue

**Comment by CamoCatX** [comment]
> > Unless you own both a rocket ship business and a electric car company, then thinking Elon's stupid is an opinion that not you nor me can have.
> 
> lmao so i cant criticize my president because i dont have power over a country? i dont give a flying fuck about what he owns, hes destroying twitter and is losing money really fucking fast so he might not have those businesses for much longer either.

1. We are not talking about the president.
2. Your argument is a slippery slope. https://en.wikipedia.org/wiki/Slippery_slope

**Comment by ghost** [comment]
> 1. We are not talking about the president.
> 2. Your argument is a slippery slope. https://en.wikipedia.org/wiki/Slippery_slope

1. I was doing something known as a comparison https://en.wikipedia.org/wiki/Comparison
2. It's not a slippery slope because there is evidence that he's losing money (sources here: 
https://www.axios.com/2023/12/31/elon-musks-x-fidelity-valuation-cut https://www.nytimes.com/2023/10/30/technology/x-twitter-19-billion-dollars.html https://www.bbc.com/news/world-us-canada-67460386 )
