### ISSUE TITLE
My cat is not in the algorithims

### ISSUE THREAD

**Issue by RwOnke** [twitter/the-algorithm#1907]
why is my cat not in the algorithims :(

**Comment by kaanklu** [comment]
you should capture him while he is doing his liquid thing.

**Comment by ar1ja** [comment]
same here  #871

**Comment by ghost** [comment]
As the internet is composed of cats, the market is unfortunately quite saturated already. Maybe completely rewriting the algorithm to present users with nothing but images of your cat would improve the algorithm, and bring advertisers back to the platform.

**Comment by CamoCatX** [comment]
+ 1 my cat also ate some of its bugs

**Comment by CamoCatX** [comment]
See #1914
