### ISSUE TITLE
Create discussions page

### ISSUE THREAD

**Issue by plutoniumm** [twitter/the-algorithm#194]
**Is your feature request related to a problem? Please describe.**
please create a discussions page for RFCs to public. There exists functions which do `DDGStatsElonFeature` `DDGStatsDemocratsFeature` etc functions which look like they could indication organisation level bias. However in interest of not being misinterpreted  it would be nice if there was a place ot discuss this in detail (technically)

**Describe the solution you'd like**
Answered

**Describe alternatives you've considered**
Not much really, its the standard way of doing Dev discussions publicly as was seen in many cases. I was also there in the OpenAI discussions, while not the focus it eventually started some edge case discussions on what right and wrong decisions are later

**Additional context**
none needed

**Comment by harish-datla** [comment]
why is this closed ? its a honest question ? when did this is_author_elon feature got introduced ? how did it affect the elons tweets recommendation ? do we have metrics  ?
