### ISSUE TITLE
propaganda

### ISSUE THREAD

**Issue by itsryuku** [twitter/the-algorithm#1944]
**Describe the bug**
i did not read a single line but it is clearly broken i see it push a lot of Zionist propaganda

**To Reproduce**
1. Go to x.com
2. Browse for few minutes
3. Observe Zionist lies appearing on your feed

**Expected behavior**
I expect it to stop detect propaganda and stop it.

**Environment**
BTW I Use Arch

**Comment by Ryukudz** [comment]
closing because you can never fix it, masters won't allow
