### ISSUE TITLE
twitter -> x = xorg = x11

### ISSUE THREAD

**Issue by Exponential-Workload** [twitter/the-algorithm#1945]
twitter turned into x
x means xorg
xorg means x11
x11 is bad
x11 is not wayland
wayland supremacy
move from twitter to [wayland](https://wayland.social/) NOW! (or any other fedi twitter alternative; this one just fits with the topic)

**Comment by StormLight14** [comment]
wayland yay

**Comment by mppbtw** [comment]
Think twice before abandoning Twitter, X breaks everything!

**Comment by popbob21345123** [comment]
![IMG_2817](https://github.com/twitter/the-algorithm/assets/102847014/0ce71e75-1a11-467a-8174-e70228c0738c)

**Comment by Exponential-Workload** [comment]
> insert @popbob21345123's image here

this could not be more accurate - also your image url includes a JWT

**Comment by popbob21345123** [comment]
Ok but when is the next scriptware update coming

**Comment by popbob21345123** [comment]
For realsies though, GitHub keeps pestering me to enable 2FA, add a phone number, a backup email, etc… and then they drop something that can bypass it all in a CDN link.

**Comment by Zigler21** [comment]
going to make a service where you connect via VNC protocol
will use wayland
you can only use chromium and go on twitter, everything else is blocked
uses arch btw

**Comment by Exponential-Workload** [comment]
> Ok but when is the next scriptware update coming

in `eval(1/0)` years

**Comment by Exponential-Workload** [comment]
> For realsies though, GitHub keeps pestering me to enable 2FA, add a phone number, a backup email, etc… and then they drop something that can bypass it all in a CDN link.

github is a joke tbh - [mandatory giveupgithub link here](https://sfconservancy.org/GiveUpGitHub/)

**Comment by popbob21345123** [comment]
> github is a joke

average microsoft product

**Comment by Exponential-Workload** [comment]
> > github is a joke
> 
> average microsoft product

was a joke prior to microsoft; [obligatory torvalds rant link](https://github.com/torvalds/linux/pull/17#issuecomment-5654674)

**Comment by popbob21345123** [comment]
to be fair though, github did mainstream git

**Comment by Exponential-Workload** [comment]
> to be fair though, github did mainstream git
> - @popbob21345123 

the linux kernel gave it the initial start it needed for becoming popular, github just _coincidentally_ made it popular. If github didn't, gitlab or some other git forge would've
