### ISSUE TITLE
When evers i a poasting

### ISSUE THREAD

**Issue by ICMlego2015** [twitter/the-algorithm#1947]
Whenever i make a post to y.com it makes a fard

1. Go to x.com
2. Click on "and thy punishment is death"
3. Scroll down to jpg.jpg
4. See error in the and why

I expect my post ot be radnomyl fixdnated

runnning netscape navigators 1.0-

kfork

**Comment by ghost** [comment]
can confirm on lynx

**Comment by tactipus** [comment]
why do i bother subscribing to this repo? it's the same bozos trolling

**Comment by ICMlego2015** [comment]
> why do i bother subscribing to this repo? it's the same bozos trolling

elongated muskrat wills you to do so
