### ISSUE TITLE
God i am so fucking lonley 

### ISSUE THREAD

**Issue by Senseal** [twitter/the-algorithm#1948]
Can someone hug me pleae

**Comment by ghost** [comment]
ok

**Comment by Winterwolf365** [comment]
hug hug 🫂 🫂 🫂 for you
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣀⣀⣄⣀⣀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⣀⠤⠖⠋⠉⠀⠀⠀⠀⠈⠙⠲⣄⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⡴⠃⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢹⣦⣠⠤⠖⠓⠒⠒⠒⠦⣀⠀⠀⠀⠀
⠀⠀⠀⢠⠇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⣯⠀⠀⠀⠀⠀⠀⠀⠀⠀⠉⢶⠀⠀
⠀⢀⡴⢾⡄⠀⠀⠀⠀⠀⠀⠀⠀⣦⠀⣦⢰⣤⣤⣿⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⣇⠀
⢠⡏⠀⠀⠈⠑⣧⣶⣀⠀⣦⢠⣰⣿⣆⣸⣶⣿⣿⡟⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢸⡆
⠈⢧⡀⠀⠀⠸⠛⠙⢿⣷⣼⣿⣿⣿⣿⣿⡿⠋⣽⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢸⠃
⠀⠀⣩⠶⣄⠀⠀⠀⠀⠉⠀⠉⠛⠋⠻⠣⢽⣶⠇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢸⡇
⠀⡖⠁⠀⠈⠳⣄⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⡾⡄⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢸⠇
⣰⡇⠀⠀⠀⠀⠀⠑⢤⡀⠀⠀⠀⠀⠀⠀⠀⡇⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣿⠀
⢹⡇⠀⠀⠀⠀⠀⠀⠀⠙⢦⣄⠀⠀⠀⠀⢠⣷⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣦⠀⡿⠀
⠀⢧⠀⠀⠀⠀⠀⠀⠀⣄⠀⣿⢷⠀⠀⠀⢸⣿⣇⠀⠀⠀⠀⠀⠀⠀⠀⢀⣦⣹⣴⡇⠀
⠀⠈⢣⡀⠀⠀⠀⠀⠀⠘⣦⣸⣄⡀⠀⠀⢸⡇⢹⠀⠀⠀⠀⠀⠀⠀⢀⣾⣿⡿⣿⠀⠀
⠀⠀⠀⠳⡀⠀⠀⠀⠀⠀⠸⣆⠀⠙⢧⣄⣀⣧⣈⣆⣀⣀⡠⠤⠤⠴⠟⠉⢿⠁⢽⠃⠀
⠀⠀⠀⠀⠹⡄⠀⠀⠀⠀⠀⠈⢧⣀⣰⣇⣸⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣸⠂⢨⣧⠀
⠀⠀⠀⠀⠀⢹⣄⠀⠀⠀⠀⠀⠀⠀⠀⠀⠉⠑⠲⠤⢤⣀⣀⣀⣤⣤⠤⠞⠋⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⡿⢦⡀⠀⣀⣀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣸⠉⣧⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⢸⠁⠀⠀⠀⠀⣹⠋⠉⠓⠒⠒⠲⠦⠤⠄⠤⢀⣠⢿⠚⠋⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⢠⠏⠀⠀⠀⠀⡼⠃⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⢳⡀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⢸⠤⣄⣀⣀⡼⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠹⡄⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⢀⠟⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠹⡄⠀⠀⠀⠀
⠀⠀⠀⠀⠀⢀⡔⢁⠀⠀⢠⠆⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢤⠀⠹⡄⠀⠀⠀
⠀⠀⠀⢀⣾⠋⡰⠋⠀⣰⠋⠀⠀⢀⡾⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠘⣆⠀⠹⡄⠀⠀
⠀⠀⠀⠀⢹⡟⠁⠀⢠⠏⠀⠀⠀⡼⠁⠀⠀⠀⡄⠀⠀⠀⠀⡀⠀⠀⠀⠘⡄⠀⢳⠀⠀
⠀⠀⠀⠀⢸⡷⢤⣀⠏⠀⠀⠀⣰⠃⠀⠀⠀⢸⠃⠀⠀⠀⠀⣏⠀⠀⠀⠀⢹⡀⣸⠇⠀
⠀⠀⠀⠀⠀⡇⠀⠈⠑⠒⡶⠴⣇⠀⠀⠀⢀⡏⠀⠀⠀⠀⠀⢹⠀⠀⠀⣀⡴⠏⠀⠀⠀
⠀⠀⠀⠀⠀⣇⠀⠀⠀⠀⢳⠀⠀⠙⠦⠤⠼⠤⣤⣀⣀⣀⣀⠬⠖⠒⣟⠉⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⢸⠀⠀⠀⠀⠈⣇⠀⠀⠀⠀⠀⠀⡏⢻⠀⠀⠀⠀⠀⠀⣿⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⢸⡀⠀⠀⠀⠀⢸⡄⠀⠀⠀⠀⠀⣧⠘⣆⠀⠀⠀⠀⠀⣹⠀⠀⠀⠀⠀⠀
