### ISSUE TITLE
Add command line version

### ISSUE THREAD

**Issue by juicemission** [twitter/the-algorithm#1949]
_               _       _                                _              _                         __                                   
   __      ___    _ __    _ __    __ _    _ _     __| |     o O O   | |     (_)    _ _      ___      o O O   (_)    _ _     | |_     ___      _ _     / _|  __ _     __      ___      o O O 
  / _|    / _ \  | '  \  | '  \  / _` |  | ' \   / _` |    o        | |     | |   | ' \    / -_)    o        | |   | ' \    |  _|   / -_)    | '_|   |  _| / _` |   / _|    / -_)    o      
  \__|_   \___/  |_|_|_| |_|_|_| \__,_|  |_||_|  \__,_|   TS__[O]  _|_|_   _|_|_  |_||_|   \___|   TS__[O]  _|_|_  |_||_|   _\__|   \___|   _|_|_   _|_|_  \__,_|   \__|_   \___|   TS__[O] 
_|"""""|_|"""""|_|"""""|_|"""""|_|"""""|_|"""""|_|"""""| {======|_|"""""|_|"""""|_|"""""|_|"""""| {======|_|"""""|_|"""""|_|"""""|_|"""""|_|"""""|_|"""""|_|"""""|_|"""""|_|"""""| {======| 
"`-0-0-'"`-0-0-'"`-0-0-'"`-0-0-'"`-0-0-'"`-0-0-'"`-0-0-'./o--000'"`-0-0-'"`-0-0-'"`-0-0-'"`-0-0-'./o--000'"`-0-0-'"`-0-0-'"`-0-0-'"`-0-0-'"`-0-0-'"`-0-0-'"`-0-0-'"`-0-0-'"`-0-0-'./o--000'

**Comment by ghost** [comment]
We definitely are due for a proper command-line implementation of twitter. I've just been accessing twitter.com (formerly known as X) through the lynx command-line browser, but it's not quite good enough yet. I'd be willing to bet that adding a command line version of twitter would bring advertisers back.

**Comment by CamoCatX** [comment]
> We definitely are due for a proper command-line implementation of twitter. I've just been accessing twitter.com (formerly known as X) through the lynx command-line browser, but it's not quite good enough yet. I'd be willing to bet that adding a command line version of twitter would bring advertisers back.


Eh it doesn't support Javascript.
