### ISSUE TITLE
Wierd bug where the X.com website redirects to twitter.com

### ISSUE THREAD

**Issue by crystalstorm466** [twitter/the-algorithm#1951]
**Describe the bug**
Whenever you go to x.com the website redirects you to twitter.com which is confusing because what is Twitter? Is it a website? Is it a bird? is It a Dog?

**To Reproduce**
1. Go to "x.com"
2. Watch.
3. Browser goes to www.twitter.com

**Expected behavior**
The browser should go to x.com not twitter.com

**Environment**
i use arch btw

**Additional context**
fix it elon

**Comment by AdamFrack** [comment]
duplicate of #1337

**Comment by ghost** [comment]
duplicate of #1914

**Comment by crystalstorm466** [comment]
How is this a duplicate it's not.

**Comment by ghost** [comment]
duplicate of #1951

**Comment by crystalstorm466** [comment]
You're correct my apologies this is a duplicate. I shouldve checked.

**Comment by CamoCatX** [comment]
Well, actually, my problem was with a cat...

**Comment by juicemission** [comment]
I don’t know what exactly twitter is but it seems like it is some kind of scam website.

**Comment by Exponential-Workload** [comment]
xorg's alternate domain redirecting to the biggest trash heap ever is not a bug, its a feature - xorg finally understands that it's equivalent to the biggest pile of shit on earth

**Comment by ghost** [comment]
> xorg's alternate domain redirecting to the biggest trash heap ever is not a bug, its a feature - xorg finally understands that it's equivalent to the biggest pile of shit on earth

I heard that twitter is some kind of x11 wm
a fork of OpenBox

**Comment by ghost** [comment]
Looks like X.com was acquired by some domain squatter, I don't yet understand why they redirect to the scam website twitter.com though. Seems like somebody's trying to direct traffic towards this 'twitter' website.

**Comment by CamoCatX** [comment]
> xorg's alternate domain redirecting to the biggest trash heap ever is not a bug, its a feature - xorg finally understands that it's equivalent to the biggest pile of shit on earth

That's right, use wayland

**Comment by crystalstorm466** [comment]
Can confirm Wayland is much better than x. Take it from someone who uses
Wayland with mint.

**Comment by ghost** [comment]
I think that fixing this issue would certainly bring advertisers back to xorg

**Comment by codingneko** [comment]
> xorg's alternate domain redirecting to the biggest trash heap ever is not a bug, its a feature - xorg finally understands that it's equivalent to the biggest pile of shit on earth

You wouldn't be this mean if you actually knew the xorg team... They're the sweetest people on earth... You can go follow them on the fediverse @XOrgFoundation@floss.social
