### ISSUE TITLE
hi guys

### ISSUE THREAD

**Issue by ghost** [twitter/the-algorithm#1952]
**Describe the bug**
no retweets

**To Reproduce**
1. go here

**Expected behavior**
this should be a carbon copy of twitter

**Environment**
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
 **context**

**Comment by ghost** [comment]
hi. nice bug

**Comment by AdamFrack** [comment]
fixed with #1994.

**Comment by ghost** [comment]
fixed with #1994.
