### ISSUE TITLE
Rewrite in docx

### ISSUE THREAD

**Issue by ghost** [twitter/the-algorithm#1953]
I want to edit the source code with Microsoft Word, but for that I need the code to be in Office Open XML Document (docx) format.

Pls export the source code as .docx, if possible, Arial 12 with a margin of 2.5 cm.

Thanks

**Comment by ghost** [comment]
I think if we used Times New Roman, that would be much more likely to attract advertisers to the platform.

**Comment by tabledrop** [comment]
I would also suggest formatting this within the Modern Language Association (MLA) formatting style as many people may appreciate the human readability and platform portability features MLA supports

**Comment by liluzibird** [comment]
As a FOSS advocate, I recommend writing in .ODT instead. We don't need Microsoft's proprietary bs.

**Comment by Exponential-Workload** [comment]
we should rewrite the entire source code as a LibreOffice Macro

**Comment by ghost** [comment]
I think that a certain level of bullying our customers/products is needed for advertisers to take us seriously. We should therefore rewrite our source code so that it is compatible with Lotus 1-2-3.

**Comment by ar1ja** [comment]
fixed it https://github.com/twitter/the-algorithm/pull/1967

**Comment by ar1ja** [comment]
![image](https://github.com/twitter/the-algorithm/assets/71613062/91f03def-b994-4c05-a340-694061301918)

pov james moment

**Comment by Exponential-Workload** [comment]
> pov james moment

i woke up with legit like 30 notifs lol

am tempted to make a few more shitpost issues cuz seeing them all closed is boring

**Comment by ar1ja** [comment]
> > pov james moment
> 
> i woke up with legit like 30 notifs lol
> 
> am tempted to make a few more shitpost issues cuz seeing them all closed is boring

kek
