### ISSUE TITLE
rewrite in brainfuckl

### ISSUE THREAD

**Issue by Exponential-Workload** [twitter/the-algorithm#1956]
im suggestint g we rewraite the algorithm in brainfukc cuz YAMAN its BEST language 2024 not clickbait

2024 is the year of brainfuck ngl

**Comment by MadKamel** [comment]
Can second this; brainfuck would most certainly bring advertisers back to the platform.

**Comment by liluzibird** [comment]
> Can second this; brainfuck would most certainly bring advertisers back to the platform.

If this doesn't bring advertisers in, I don't know what will.

In case they don't come back I leave with the words of Elon(gated) Musk,
> “If somebody is going to try to blackmail me with advertising, blackmail me with money, go fuck yourself. Go fuck yourself. Is that clear? I hope it is.”

**Comment by Marioood** [comment]
i hiope it get rewritten in malbolge
