### ISSUE TITLE
rewrite in rust

### ISSUE THREAD

**Issue by asudox** [twitter/the-algorithm#1957]
rewrite the algorithm in rust to save on power (= money) and also to recommend users shit faster.
actually, rewrite twitter in rust.

this will 100% make ~~twitter~~ X more profitable
2024 will be the year of twitter's comeback!1!1!

**Comment by realzvqle** [comment]
compiling will take 10 years though

**Comment by ar1ja** [comment]
> compiling will take 10 years though

but its gonna b memory safe ( :rocket: :rocket: :rocket: :rocket: :rocket: :rocket: :rocket: :rocket: :rocket: :rocket: :rocket: :rocket: ) and blazingly fast ( :rocket: :rocket: :rocket: :rocket: :rocket: :rocket: :rocket: :rocket: :rocket: :rocket: :rocket: :rocket: :rocket: :rocket: :rocket: :rocket: :rocket: :rocket: :rocket: :rocket: :rocket: :rocket: :rocket: :rocket: :rocket: :rocket: :rocket: :rocket: :rocket: :rocket: :rocket: :rocket: :rocket: :rocket: :rocket: :rocket: :rocket: :rocket: :rocket: :rocket: :rocket: :rocket: :rocket: :rocket: :rocket: :rocket: :rocket: :rocket: :rocket: :rocket: :rocket: :rocket: :rocket: :rocket: :rocket: :rocket: :rocket: :rocket: ) #RustRewrite :rocket: :rocket: :rocket: :rocket: :rocket: :rocket: :rocket: :rocket: :rocket: :rocket: :rocket: :rocket: :rocket: :rocket:

**Comment by AnUsersName** [comment]
rewrite in cobol
