### ISSUE TITLE
remove Twitter blue

### ISSUE THREAD

**Issue by juicemission** [twitter/the-algorithm#1958]
![IMG_0480](https://github.com/twitter/the-algorithm/assets/130974018/9cc34d96-4689-4b04-a4b9-ebf34dd8057e)
**Is your feature request related to a problem? Please describe.**
I find the blue check marks on Twitter distracting and would prefer a cleaner interface without them.

**Describe the solution you'd like**
I request the removal of Twitter blue check marks to create a simplified and less visually cluttered user experience.

**Describe alternatives you've considered**
I haven't found a built-in option to disable blue check marks in the settings. Removing them altogether would be a preferred solution.

**Additional context**
The removal of blue check marks aligns with a preference for a cleaner and less visually busy interface. This change could enhance the overall user experience for individuals who find the check marks unnecessary.

**Comment by realzvqle** [comment]
no

**Comment by asudox** [comment]
dumbass how will twitter generate money if they remove twitter blue

**Comment by ghost** [comment]
> dumbass how will twitter generate money if they remove twitter blue

They can just sell good vibes in twitter

**Comment by juicemission** [comment]
> dumbass how will twitter generate money if they remove twitter blue

,
