### ISSUE TITLE
> dumbass how will twitter generate money if they remove twitter blue

### ISSUE THREAD

**Issue by juicemission** [twitter/the-algorithm#1960]
> dumbass how will twitter generate money if they remove twitter blue

,

_Originally posted by @juicemission in https://github.com/twitter/thie-algorithm/issues/1958#issuecomment-1894978716_

**Comment by juicemission** [comment]
Before Elon they didn't need twitter blue. So perhaps they should go back in time or something.it time travel is not an option then Elon could pay for costs of running Twitter from his own money. I think he can afford that.

**Comment by asudox** [comment]
> Before Elon they didn't need twitter blue. So perhaps they should go back in time or something.it time travel is not an option then Elon could pay for costs of running Twitter from his own money. I think he can afford that.

he can afford it, but we can be sure that he won't.
twitter has already become a shit place full of retards, I doubt elon even cares about it. It's a mere unimportant side money "generator" (if it even profits). btw github isn't the place for this offtopic talk so yeah.

**Comment by Marioood** [comment]
just delete twitter it'll solve all of humanity's problems

**Comment by Marioood** [comment]
also twitter has ads now lmao

**Comment by AdamFrack** [comment]
> just delete twitter it'll solve all of humanity's problems

Joe Biden said that if your comment gets 10m likes twitter, known by elon musk as x will implode.
