### ISSUE TITLE
pls do my homework

### ISSUE THREAD

**Issue by ghost** [twitter/the-algorithm#1963]
**Describe the bug**
my homework isnt done

**To Reproduce**
1. Go to 'my house'
2. Click on 'the door'
3. Scroll down to 'the homework'
4. Do it

**Expected behavior**
my homework should be done

**Screenshots**

**Environment**
cheese

**Additional context**
first grade addition and subtraction
7 + 3
3 + 2
10 + 7
8 + 1
4 + 3
5 - 2
7 - 1
7 - 5
4 - 3
10 - 5

**Comment by FrogBoy2008** [comment]
damn those questions sure are hard

**Comment by ar1ja** [comment]
```
7 + 3 = 10
3 + 2 = 5
10 + 7 = 17
8 + 1 = 9
4 + 3 = 7
5 - 2 = 3
7 - 1 = 6
7 - 5 = 2
4 - 3 = 1
10 - 5 = 5
```

sorry it took me 5 days, those requestions r hard asf
