### ISSUE TITLE
Replace X with X11

### ISSUE THREAD

**Issue by Maximal98** [twitter/the-algorithm#1968]
**Describe the bug**
X should be Replaced with X11 because they have a cooler logo and dont suck and also give me root access to the serve rplease

**To Reproduce**
1. Go on Titter
2. See ugly Logo

**Expected behavior**
It should boot my desktop and maybe crash sometimes

**Environment**
im on arch btw

**Additional context**
maybe drop elon too like his parents dropped him as a baby

**Comment by realKarthikNair** [comment]
Wayland Better.

**Comment by MadKamel** [comment]
WaYlAnD bEtTeR

**Comment by ghost** [comment]
Maybe a collab between X11 and X could work, in which there would appear at all times in a corner of the screen a tweet from Elon Musk. That would bring advertisers back for sure.

**Comment by juicemission** [comment]
I'm also an Arch user, by the way. I hope your day is as smooth and up-to-date as running pacman -Syu embracing the endless possibilities!
