### ISSUE TITLE
help my metamask trust wallet has been hacked, showing reader error” in the big 2024

### ISSUE THREAD

**Issue by Tim79000** [twitter/the-algorithm#1970]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment**
For web, specify your OS and browser version.  For mobile, specify device, OS
and version.  For libraries, what version of build tools are you using?

**Additional context**

**Comment by MadKamel** [comment]
shocking and appalling. how could musk allow such a thing to happen?? this is why advertisers left

**Comment by AdamFrack** [comment]
duplicate of issue #1970

**Comment by kxrn0** [comment]
you deserve it

**Comment by dashboarde** [comment]
I got same issue earlier but I was referred to support team (REDACTED) they got it fixed earlier, reach out them they has a fix for this
