### ISSUE TITLE
Rewrite in Minecraft Redstone

### ISSUE THREAD

**Issue by Tim79000** [twitter/the-algorithm#1974]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment**
For web, specify your OS and browser version.  For mobile, specify device, OS
and version.  For libraries, what version of build tools are you using?

**Additional context**

**Comment by DarkGuy10** [comment]
+1 Minecraft redstone is completely memory safe with incredible compilation and execution times

**Comment by MadKamel** [comment]
I'm pretty sure somebody did this way back in 2016
