### ISSUE TITLE
Twitter Junior! a new child friendly version of twitter

### ISSUE THREAD

**Issue by Tim79000** [twitter/the-algorithm#1976]
A majority of Twitter users appear to be immature, so this will improve accesibility

**Comment by SarthakChaudhary46** [comment]
Definitely, do you have any plan or strategy, or is it just an open idea?

**Comment by AdamFrack** [comment]
We will need to make it so:
if ai detects immature behavior or under 13 selected at sign up, transfer account to a Twitter junior account
you will only be able to tweet the following sentences:
it is (temperature)(unit)!
toilet is very funny!!!!
I love math.
I hate math.
Elon Musk is our god.
cheese tastes like milk.
I live at (location).
I like living at (location)!

**Comment by Tim79000** [comment]
This will bring back advertisers

**Comment by TruncatedDinoSour** [comment]
its like twitter but theres subway sufers at the top half of it

**Comment by Tim79000** [comment]
> its like twitter but theres subway sufers at the top half of it

And Peter Griffin funny moments

**Comment by TruncatedDinoSour** [comment]
> > its like twitter but theres subway sufers at the top half of it
> 
> And Peter Griffin funny moments

fr

**Comment by MadKamel** [comment]
This looks like an improvement to me

**Comment by AdamFrack** [comment]
> > > It is like twitter but there's Subway Surfers at the top half of it.
> > 
> > 
> > And Peter Griffin funny moments.
> 
> for real
How can you forget vibrant colors?

**Comment by Tim79000** [comment]
> > > > It is like twitter but there's Subway Surfers at the top half of it.
> > > 
> > > 
> > > And Peter Griffin funny moments.
> > 
> > 
> > for real
> > How can you forget vibrant colors?

Yeah, theres vibrant colors, and lots of microtransactions, for instance, a subscription to automatically upload a random ai generated tweet every day, to keep you on top of your game.
