### ISSUE TITLE
Title

### ISSUE THREAD

**Issue by ghost** [twitter/the-algorithm#1981]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when people complain about cheese

**Describe the solution you'd like**
Use gun

**Describe alternatives you've considered**
And if that don't work, use more gun.

**Additional context**
is that a tf2 refeareance?!??!?!?!?

**Comment by Tim79000** [comment]
This would simplify advertiser grinders

**Comment by ghost** [comment]
Cheese advertisers would be unhappy, but perhaps this could be the dawn of a new day for gun manufacturers advertising on X.
