### ISSUE TITLE
ban racism

### ISSUE THREAD

**Issue by Tim79000** [twitter/the-algorithm#1986]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment**
For web, specify your OS and browser version.  For mobile, specify device, OS
and version.  For libraries, what version of build tools are you using?

**Additional context**

**Comment by Tim79000** [comment]
![image](https://github.com/twitter/the-algorithm/assets/100736284/47309611-b61b-445b-bea1-56c607c4f9fe)

**Comment by Tim79000** [comment]
in short racism bad, stop promoting retarded racist 12 year olds

**Comment by juicemission** [comment]
I use arch Linux btw and Twitter is not running on arch so probably this is the root cause of all the problems

**Comment by Senseal** [comment]
1984

**Comment by AdamFrack** [comment]
![image](https://github.com/twitter/the-algorithm/assets/147642132/f2212ba4-542c-43bf-b6f0-a77c996f7f26)

**Comment by Exponential-Workload** [comment]
> 1984

1942

**Comment by AdamFrack** [comment]
> > 1984
> 
> 1942

1902
