### ISSUE TITLE
Miracle Star is the first Undertale AU

### ISSUE THREAD

**Issue by Tim79000** [twitter/the-algorithm#1989]
Miracle star is about a family of goats who happen to have an adopted child and all the characters are based on objects and animals and have goofy designs.
![image](https://github.com/twitter/the-algorithm/assets/100736284/bd2661cb-fc6a-4525-897b-fa765b699c2b)

**Comment by Tim79000** [comment]
it was also made 1 year after undertale was anounced

**Comment by Tim79000** [comment]
it was made one year after undertale was announced on kickstarter

**Comment by Tim79000** [comment]
![image](https://github.com/twitter/the-algorithm/assets/100736284/a6f1969c-015a-4d04-b122-ec7af868d9c0)

**Comment by Tim79000** [comment]
wet dreemurrs
![image](https://github.com/twitter/the-algorithm/assets/100736284/ae4e111a-0c32-40d8-a435-d9ac7cef0264)

**Comment by Marioood** [comment]
will someone make a yume nikki fangame aobut this au i think it would bevery interesting also if it included elemets from yiik a postmodern arpg

**Comment by Tim79000** [comment]
ok mark

**Comment by Tim79000** [comment]
No, this isnt completed, shut up elon
