### ISSUE TITLE
Add support for embeds from "XVIDEOS"

### ISSUE THREAD

**Issue by Marioood** [twitter/the-algorithm#1991]
I uploaded some cool videos of my cat to a website called "XVIDEOS". Because of the website having the name of the brand formerly known as 'Twiter', I assumed that X would support embeds from XVIDEOS. This appears to not be the case!

Elon, this issue report is directed at YOU! Yes, YOU specifically!

Please fix this! I want people to see XVIDEOS of my cat.

**Comment by Tim79000** [comment]
This would for certain bring advertisers back to X
