### ISSUE TITLE
twitter/the-algorithm

### ISSUE THREAD

**Issue by Tim79000** [twitter/the-algorithm#1992]
**Describe the bug**
https://github.com/twitter
/
[the-algorithm](https://github.com/twitter/the-algorithm)

Type / to search

[Code](https://github.com/twitter/the-algorithm)
Issues
234
Pull requests
194
[Actions](https://github.com/twitter/the-algorithm/actions)
[Security](https://github.com/twitter/the-algorithm/security)
[Insights](https://github.com/twitter/the-algorithm/pulse)
Issues: twitter/the-algorithm
is:issue is:open 
[ Labels 14](https://github.com/twitter/the-algorithm/labels)
[ Milestones 0](https://github.com/twitter/the-algorithm/milestones)
 
 
Issues list
https://github.com/twitter/the-algorithm/issues/1991
#1991 opened 7 hours ago by [Marioood](https://github.com/twitter/the-algorithm/issues?q=is%3Aissue+is%3Aopen+author%3AMarioood)
[ 1](https://github.com/twitter/the-algorithm/issues/1991)
https://github.com/twitter/the-algorithm/issues/1990
#1990 opened 8 hours ago by [Saluyuuu](https://github.com/twitter/the-algorithm/issues?q=is%3Aissue+is%3Aopen+author%3ASaluyuuu)
[ 2](https://github.com/twitter/the-algorithm/issues/1990)
https://github.com/twitter/the-algorithm/issues/1989
#1989 opened yesterday by [Tim79000](https://github.com/twitter/the-algorithm/issues?q=is%3Aissue+is%3Aopen+author%3ATim79000)
[ 5](https://github.com/twitter/the-algorithm/issues/1989)
https://github.com/twitter/the-algorithm/issues/1988
#1988 opened 4 days ago by [Tim79000](https://github.com/twitter/the-algorithm/issues?q=is%3Aissue+is%3Aopen+author%3ATim79000)
[ 1](https://github.com/twitter/the-algorithm/issues/1988)
https://github.com/twitter/the-algorithm/issues/1987
#1987 opened last week by [markrizko](https://github.com/twitter/the-algorithm/issues?q=is%3Aissue+is%3Aopen+author%3Amarkrizko)
[ 3](https://github.com/twitter/the-algorithm/issues/1987)
https://github.com/twitter/the-algorithm/issues/1986
#1986 opened last week by [Tim79000](https://github.com/twitter/the-algorithm/issues?q=is%3Aissue+is%3Aopen+author%3ATim79000)
[ 3](https://github.com/twitter/the-algorithm/issues/1986)
https://github.com/twitter/the-algorithm/issues/1985
#1985 opened 2 weeks ago by [frenchc](https://github.com/twitter/the-algorithm/issues?q=is%3Aissue+is%3Aopen+author%3Afrenchc)
https://github.com/twitter/the-algorithm/issues/1984
#1984 opened 2 weeks ago by [luyao777](https://github.com/twitter/the-algorithm/issues?q=is%3Aissue+is%3Aopen+author%3Aluyao777)
[ 1](https://github.com/twitter/the-algorithm/issues/1984)
https://github.com/twitter/the-algorithm/issues/1983
#1983 opened 2 weeks ago by [MadKamel](https://github.com/twitter/the-algorithm/issues?q=is%3Aissue+is%3Aopen+author%3AMadKamel)
[ 2](https://github.com/twitter/the-algorithm/issues/1983)
https://github.com/twitter/the-algorithm/issues/1982
#1982 opened 3 weeks ago by [juicemission](https://github.com/twitter/the-algorithm/issues?q=is%3Aissue+is%3Aopen+author%3Ajuicemission)
[ 3](https://github.com/twitter/the-algorithm/issues/1982)
https://github.com/twitter/the-algorithm/issues/1981
#1981 opened 3 weeks ago by [AdamFrack](https://github.com/twitter/the-algorithm/issues?q=is%3Aissue+is%3Aopen+author%3AAdamFrack)
[ 2](https://github.com/twitter/the-algorithm/issues/1981)
https://github.com/twitter/the-algorithm/issues/1980
#1980 opened 3 weeks ago by [Tim79000](https://github.com/twitter/the-algorithm/issues?q=is%3Aissue+is%3Aopen+author%3ATim79000)
[ 2](https://github.com/twitter/the-algorithm/issues/1980)
https://github.com/twitter/the-algorithm/issues/1979
#1979 opened 3 weeks ago by [SarthakChaudhary46](https://github.com/twitter/the-algorithm/issues?q=is%3Aissue+is%3Aopen+author%3ASarthakChaudhary46)
[ 1](https://github.com/twitter/the-algorithm/issues/1979)
https://github.com/twitter/the-algorithm/issues/1978
#1978 opened 3 weeks ago by [Tim79000](https://github.com/twitter/the-algorithm/issues?q=is%3Aissue+is%3Aopen+author%3ATim79000)
[ 1](https://github.com/twitter/the-algorithm/issues/1978)
https://github.com/twitter/the-algorithm/issues/1976
#1976 opened 3 weeks ago by [Tim79000](https://github.com/twitter/the-algorithm/issues?q=is%3Aissue+is%3Aopen+author%3ATim79000)
[ 9](https://github.com/twitter/the-algorithm/issues/1976)
https://github.com/twitter/the-algorithm/issues/1975
#1975 opened 3 weeks ago by [SarthakChaudhary46](https://github.com/twitter/the-algorithm/issues?q=is%3Aissue+is%3Aopen+author%3ASarthakChaudhary46)
[ 3](https://github.com/twitter/the-algorithm/issues/1975)
https://github.com/twitter/the-algorithm/issues/1974
#1974 opened 3 weeks ago by [Tim79000](https://github.com/twitter/the-algorithm/issues?q=is%3Aissue+is%3Aopen+author%3ATim79000)
[ 1](https://github.com/twitter/the-algorithm/issues/1974)
https://github.com/twitter/the-algorithm/issues/1973
#1973 opened 3 weeks ago by [Tim79000](https://github.com/twitter/the-algorithm/issues?q=is%3Aissue+is%3Aopen+author%3ATim79000)
[ 1](https://github.com/twitter/the-algorithm/issues/1973)
https://github.com/twitter/the-algorithm/issues/1972
#1972 opened 3 weeks ago by [Tim79000](https://github.com/twitter/the-algorithm/issues?q=is%3Aissue+is%3Aopen+author%3ATim79000)
https://github.com/twitter/the-algorithm/issues/1971
#1971 opened 3 weeks ago by [Tim79000](https://github.com/twitter/the-algorithm/issues?q=is%3Aissue+is%3Aopen+author%3ATim79000)
https://github.com/twitter/the-algorithm/issues/1970
#1970 opened 3 weeks ago by [Tim79000](https://github.com/twitter/the-algorithm/issues?q=is%3Aissue+is%3Aopen+author%3ATim79000)
[ 3](https://github.com/twitter/the-algorithm/issues/1970)
https://github.com/twitter/the-algorithm/issues/1969
#1969 opened last month by [G3orgeS](https://github.com/twitter/the-algorithm/issues?q=is%3Aissue+is%3Aopen+author%3AG3orgeS)
[ 4](https://github.com/twitter/the-algorithm/issues/1969)
https://github.com/twitter/the-algorithm/issues/1968
#1968 opened last month by [Maximal98](https://github.com/twitter/the-algorithm/issues?q=is%3Aissue+is%3Aopen+author%3AMaximal98)
[ 3](https://github.com/twitter/the-algorithm/issues/1968)
https://github.com/twitter/the-algorithm/issues/1966
#1966 opened last month by [taaigo](https://github.com/twitter/the-algorithm/issues?q=is%3Aissue+is%3Aopen+author%3Ataaigo)
[ 3](https://github.com/twitter/the-algorithm/issues/1966)
https://github.com/twitter/the-algorithm/issues/1962
#1962 opened on Jan 18 by [Exponential-Workload](https://github.com/twitter/the-algorithm/issues?q=is%3Aissue+is%3Aopen+author%3AExponential-Workload)
         
 ProTip! Notify someone on an issue with a mention, like: @Tim79000.
Footer
© [2](https://github.com/twitter/the-algorithm/issues?page=2&q=is%3Aissue+is%3Aopen)02[4](https://github.com/twitter/the-algorithm/issues?page=4&q=is%3Aissue+is%3Aopen) GitHub, Inc.
Footer navigation
[Terms](https://docs.github.com/site-policy/github-terms/github-terms-of-service)
[Privacy](https://docs.github.com/site-policy/privacy-policies/github-privacy-statement)
[Security](https://github.com/security)
[Status](https://www.githubstatus.com/)
[Docs](https://docs.github.com/)
[Contact](https://support.github.com/?tags=dotcom-footer)
Manage cookies
Do not share my personal information

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment**
For web, specify your OS and browser version.  For mobile, specify device, OS
and version.  For libraries, what version of build tools are you using?

**Additional context**

**Comment by AdamFrack** [comment]
hello I am @Tim79000 why did you notify me on issue

**Comment by MadKamel** [comment]
hey there, @Tim79000 here, I was mentioned?
