### ISSUE TITLE
I am new to github and I have lots to say

### ISSUE THREAD

**Issue by TheAjaykrishnanR** [twitter/the-algorithm#1993]
I DONT GIVE A FUCK ABOUT THE FUCKING CODE! I just want to download this stupid fucking application and use it : https://github.com/twitter/the-algorithm

WHY IS THERE CODE ??? MAKE A FUCKING .EXE AND GIVE IT TO ME. these dumbfucks think that everyone is a developer and understands code, well i am not and I dont understand it. I only know to download and install application. SO WHY THE FUCK IS THERE CODE ? make an EXE file and give it me. STUPID FUCKING SMELLY NERDS

**Comment by TheAjaykrishnanR** [comment]
> meow

gib exe plis

**Comment by 2lay** [comment]
_fortnite.exe_

**Comment by ghost** [comment]
butt
