### ISSUE TITLE
Broken "Pronouns" setting not removed in the X Android App (Leftover from the pre-X era)

### ISSUE THREAD

**Issue by matbla77** [twitter/the-algorithm#1996]
Describe the bug
The "Pronouns" setting in the Android app of X, probably a leftover from the pre-X era. It's think it was forgotten to be removed.

To Reproduce

Go to your profile on the X Android app
Click on "Edit profile"
Scroll down to "Pronouns"
See error, it doesn't work. It's broken.
Expected behavior
This shouldn't be there anymore... It's a leftover from the pre-X era. Elon Musk didn't like that feature. (Source: https://twitter.com/elonmusk/status/1286869404874088448?lang=en)

Environment
X app version: 10.29.0-release.0
Android 14

Update 04.04.2024
This feature was finally removed in the version 10.35.0-release.0 :)

![279566689-1f9e5ca2-8eee-44bd-805f-be3a9b5df2b2](https://github.com/twitter/the-algorithm/assets/57370065/b371d910-7c9f-4ad6-b7c7-0cfaf274d294)

**Comment by Tim79000** [comment]
Woke!!!! ELON WOULD NOT LIKE THIS, ELON GET ON THIS NOW, WE MUST DESTROY WOKISM ON TWITTER!!11

**Comment by Marioood** [comment]
im a woke transexual I THINK THE WOKENESS SHOULD BE ELIMITATAED!!!!! ELON BAN THIS FEATURE!!!!!!
