### ISSUE TITLE
My 3 favourite Waifus UWUWUWU

### ISSUE THREAD

**Issue by ghost** [twitter/the-algorithm#1997]
My 3 favourite waifus

Yuno Gasai (Mirai Nikki)

Yuno Gasai is everything I love in a woman, she would kill other people for me and one day probably me too 100000% waifu material. She is strong and beautiful, what more could you want.

Asuna (Sword Art Online)

Asuna is a wonderful character, she combines strength, beauty and intelligence. That's why she's in second place, but she will always have a special place in my heart.

Aqua (Konosuba)

Aqua is super funny and she always makes me laugh. She is also a very strong and beautiful character, but her intelligence is sometimes lacking. But she's still my number 3.

**Comment by Exponential-Workload** [comment]
add astolfo now :gun:

**Comment by Marioood** [comment]
i second, astolfo is missing from the list

**Comment by ghost** [comment]
Felix Argyle is also missing. ^_^ (anime version.) That being said, I don't see how this is relevant to X's Algorithm.
