### ISSUE TITLE
A BUG IN THE ALGORITHM

### ISSUE THREAD

**Issue by Exponential-Workload** [twitter/the-algorithm#1998]
**Describe the bug**
its a bug

**To Reproduce**
1. Go to the repository
2. Click on something
3. Scroll down to something
4. See a literal f\*\*\*ing bug - an insect - in the codebase

**Expected behavior**
NO bug

**Screenshots**
![image](https://github.com/twitter/the-algorithm/assets/90570076/6e86a3f3-155c-4679-804f-2ef3bed49f20)

**Environment**
For web, specify your OS and browser version.  For mobile, specify device, OS
and version.  For libraries, what version of build tools are you using?

- Firefox 123.0
- Arch @ latest (as of 23-02-2024 @ 13:55:00)

**Additional context**
PICK ME UP IM SCARED

**Comment by colleirose** [comment]
confirmed

**Comment by Exponential-Workload** [comment]
this was NOT fixed

**Comment by colleirose** [comment]
I can confirm it is still ongoing. Please reopen this issue, @jdm-twtr
