### ISSUE TITLE
JUST MAKE A FUCKING .EXE FILE AND GIVE IT TO ME.

### ISSUE THREAD

**Issue by Calvintor** [twitter/the-algorithm#1999]
I DONT GIVE A FUCK ABOUT THE FUCKING CODE! i just want to download this stupid fucking application and use it 

WHY IS THERE CODE??? MAKE A FUCKING .EXE FILE AND GIVE IT TO ME. these dumbfucks think that everyone is a developer and understands code. well i am not and i don't understand it. I only know to download and install applications. SO WHY THE FUCK IS THERE CODE? make an EXE file and give it to me. STUPID FUCKING SMELLY NERDS

**Comment by ghost** [comment]
can confirm, this needs to be a feature. this would bring back advertisers for certain.

**Comment by Tim79000** [comment]
![image](https://github.com/twitter/the-algorithm/assets/100736284/2dc83a3d-d8f6-492c-8f9e-2e87357fc3b3)

hey.

**Comment by Exponential-Workload** [comment]
can confirm, this is a bug. advertisers left cuz the exe download ux was broken

**Comment by ghost** [comment]
Real

**Comment by ghost** [comment]
Real

**Comment by R4Ajeti** [comment]
can confirm, we found the missing reptile "Megalania"

**Comment by MangoFizz** [comment]
😳

**Comment by f-vojnovski** [comment]
Real 💯

**Comment by babylard** [comment]
Nothing 5 minutes of googling cant fix.

**Comment by SantiiRepair** [comment]
Real

**Comment by aurcode** [comment]
Real

**Comment by kuyuta28** [comment]
bro got a point

**Comment by MygeldtAnjel** [comment]
bro insane xd

**Comment by Mulandii** [comment]
Just rants 😅

**Comment by an-abnormality** [comment]
bump

**Comment by slbsh** [comment]
bump

**Comment by RetronicsYT** [comment]
burp

**Comment by AyushBarik** [comment]
bump

**Comment by i-am-called-glitchy** [comment]
retards being retards lmao

**Comment by thatkusari** [comment]
burp

**Comment by Calvintor** [comment]
I don't fc*i*ng know why everyone is saying that i'm retarded

**Comment by i-am-called-glitchy** [comment]
> I don't fc_i_ng know why everyone is saying that i'm retarded

we dont expect retards to be self aware dw

**Comment by slbsh** [comment]
> I don't fc*i*ng know why everyone is saying that i'm retarded

"everyone", literally one guy

**Comment by i-am-called-glitchy** [comment]
> > I don't fc_i_ng know why everyone is saying that i'm retarded
> 
> "everyone", literally one guy

see what i mean?

**Comment by judemont** [comment]
> > I don't fc*i*ng know why everyone is saying that i'm retarded
> 
> "everyone", literally one guy
 @grok Is it true ?

**Comment by Calvintor** [comment]
> > I don't fc_i_ng know why everyone is saying that i'm retarded
> 
> "everyone", literally one guy

@grok Is it true or not ?

**Comment by g4mless** [comment]
what

**Comment by SantiiRepair** [comment]
> what

can we smash?

**Comment by mccrindlebrian** [comment]
so real

**Comment by GXGOW** [comment]
![Image](https://github.com/user-attachments/assets/3f4f49e2-cdd0-463c-ac62-43ab7b92ef5e)

**Comment by skewuo** [comment]
virus.exe

**Comment by Mortem-Metallum** [comment]
> I DONT GIVE A FUCK ABOUT THE FUCKING CODE! i just want to download this stupid fucking application and use it
> 
> WHY IS THERE CODE??? MAKE A FUCKING .EXE FILE AND GIVE IT TO ME. these dumbfucks think that everyone is a developer and understands code. well i am not and i don't understand it. I only know to download and install applications. SO WHY THE FUCK IS THERE CODE? make an EXE file and give it to me. STUPID FUCKING SMELLY NERDS

Mate if you can't be bothered to run 3 commands to compile one thing then Github is clearly _not_ your place. This entire platform is based on code. IT IS MADE for developers. IT IS MADE for people who know what they're doing

Imagine: Most developers of large projects have to jump through 999 hoops just to get it somewhat production ready. But none of that matters to you. You just want the damn EXE. Don't come to this platform with that attitude. Because code is literally how Github works. 🙃

**Comment by XDAFPX** [comment]
Real

**Comment by catsizedcoder** [comment]
Real

**Comment by i-am-called-glitchy** [comment]
​

**Comment by TheStarOfNorthAfrica** [comment]
E

**Comment by Mortem-Metallum** [comment]
yes.

**Comment by NgLam2911** [comment]
Real

**Comment by ROGER899** [comment]
What the hell is going on today 😀🤣

**Comment by fentz26** [comment]
tell me tell me
This can't be real 😭🙏

**Comment by yukiminh0505** [comment]
> I DONT GIVE A FUCK ABOUT THE FUCKING CODE! i just want to download this stupid fucking application and use it
> 
> WHY IS THERE CODE??? MAKE A FUCKING .EXE FILE AND GIVE IT TO ME. these dumbfucks think that everyone is a developer and understands code. well i am not and i don't understand it. I only know to download and install applications. SO WHY THE FUCK IS THERE CODE? make an EXE file and give it to me. STUPID FUCKING SMELLY NERDS

Put simply: someone provides a complete, well-tested recipe from start to finish—just follow it and you’re done. Anyone can check that recipe, and if they’re careful, they can review it for any issues.

Now you’re asking to just get the finished dish without caring about the recipe. That’s fine—but if the recipe I show you is one thing and the dish I actually cook is another, and I slip something questionable into it, there’s no way for you to know.

**Comment by Minnona** [comment]
Real

**Comment by elvisisvan** [comment]
no cap

**Comment by EasperOne** [comment]
Bro being serious

**Comment by CoopTRUE** [comment]
Sometimes I think about this

**Comment by ngerdepzaivcl** [comment]
It's very difficult to find that .exe file, bro 😃

**Comment by luyao777** [comment]
crazy

**Comment by i-am-called-glitchy** [comment]
why the fuck is this thread still alive

**Comment by AnshKetchum** [comment]
because the exe isn't! every dev's favorite copium lmao

**Comment by kailong-chan** [comment]
Real

**Comment by i-am-called-glitchy** [comment]
> Grok Image Frackin Rocks!

ai slop

**Comment by i-am-called-glitchy** [comment]
someone revoke this guy's ISP /j
nah but genuinely
> Professional fruit inspector. Outside-the-box thoughts are my forté.
src: his github profile

yeah someone send this fucker back *into* the box

**Comment by i-am-called-glitchy** [comment]
<img width="1225" height="230" alt="Image" src="https://github.com/user-attachments/assets/d55ef5d9-8916-49a3-9b26-bf219e32899f" />

icl the block button would do a good service being here /srs , thanks for educating me about the fact that it exists in the first place 👍 /s

**Comment by lukejmorrison** [comment]
Aww you guys don't have any humor ahahha.. isn't this whole thread a joke???

**Comment by Alone-737** [comment]
> Aww you guys don't have any humor ahahha.. isn't this whole thread a joke???

you are god damn right
                                                 - walter white

**Comment by theNoof** [comment]
stinky smelly windows user. just give me an AppImage!

**Comment by SpaceSyt** [comment]
peak

**Comment by Burial0268** [comment]
lmao

**Comment by i-am-called-glitchy** [comment]
nya :3

**Comment by 1000-yard-stare** [comment]
why the hell is this thread still active 😒

**Comment by i-am-called-glitchy** [comment]
idk :3

**Comment by Blitzedzz1** [comment]
who else here from the gif

<img width="929" height="622" alt="Image" src="https://github.com/user-attachments/assets/c2dbafe0-91c7-472d-bd84-080305c93aaf" />

**Comment by i-am-called-glitchy** [comment]
> from the gif

me lmao

**Comment by aliabdelmoaty** [comment]
Real 😂

**Comment by 1000-yard-stare** [comment]
( ͡° ͜ʖ ͡°)

**Comment by iinfernu** [comment]
hi chat

**Comment by 1000-yard-stare** [comment]
hiya

**Comment by harifuda** [comment]
Patriot

**Comment by NightScript370** [comment]
> [jdm-twtr](https://github.com/jdm-twtr) closed this as [completed](https://github.com/twitter/the-algorithm/issues?q=is%3Aissue%20state%3Aclosed%20archived%3Afalse%20reason%3Acompleted)[on Mar 21, 2024](https://github.com/twitter/the-algorithm/issues/1999#event-12206872209)

But where's the .EXE? Does OP have it?

**Comment by jaydwivedidd** [comment]
lol

**Comment by FdHerrera** [comment]
Have someone handed off a .exe to my boy already???

**Comment by i-am-called-glitchy** [comment]
lmao doesn't look like it

**Comment by iinfernu** [comment]
boykisser pfp in 2026 just nuke this whole generation

**Comment by i-am-called-glitchy** [comment]
??? /genq

**Comment by i-am-called-glitchy** [comment]
> boykisser pfp in 2026 just nuke this whole generation

<img width="258" height="69" alt="Image" src="https://github.com/user-attachments/assets/d4e9588d-777d-4cf9-b056-4b5e949bd173" />

lmfao you aint much better brochacho

**Comment by iinfernu** [comment]
oh thanks for reminding me to change my x handle

**Comment by i-am-called-glitchy** [comment]
lmfao

**Comment by q-TheDog** [comment]
Any updates?

**Comment by 1000-yard-stare** [comment]
i really need to unsubscribe from this pointless thread but I don't wanna

**Comment by iinfernu** [comment]
nah this thread is peak

**Comment by Rvlndd** [comment]
hey man, where did you get the .exe? i couldnt find it still

**Comment by i-am-called-glitchy** [comment]
strong urge to make a discord server for this thread

**Comment by Wadamzmail** [comment]
@star4roid 😂😂🐢

**Comment by ghost** [comment]
lmao

**Comment by i-am-called-glitchy** [comment]
chat i need some help for some reason my rust program won't compile

```py
print("Hello world!");
```

**Comment by komali2** [comment]
> oh thanks for reminding me to change my x handle

Calling Twitter "x" lmao

**Comment by kbdevs** [comment]
shoulda made the file

**Comment by odwrotnamapa** [comment]
valid

**Comment by hamzabudeir** [comment]
https://github.com/user-attachments/assets/2f63644e-a02f-459f-b2c7-bec1a81a8e53

**Comment by FirthR5** [comment]
lmao

**Comment by ShadowNineX** [comment]
<img width="704" height="544" alt="Image" src="https://github.com/user-attachments/assets/585bd1c3-9072-4416-bd75-47f627196776" />

**Comment by i-am-called-glitchy** [comment]
there do be a lot of people here lmao

**Comment by kingbluetooth** [comment]
Did you find the exe

**Comment by Enrico-Signore** [comment]
****

**Comment by sthitpragnya-ethosx** [comment]
Looking for the .exe. Did anyone find it?

**Comment by RohitKushvaha01** [comment]
Yo

**Comment by Alleexxi** [comment]
Can someone compile it already?

**Comment by i-am-called-glitchy** [comment]
[totally_not_a_rat.zip](https://github.com/user-attachments/files/30669507/totally_not_a_rat.zip)
guys i found the exe

**Comment by Project516** [comment]
> I DONT GIVE A FUCK ABOUT THE FUCKING CODE! i just want to download this stupid fucking application and use it

build it yourself: https://github.com/twitter/the-algorithm#build-and-test-code

**Comment by 3pm-on-github** [comment]
<img width="736" height="414" alt="Image" src="https://github.com/user-attachments/assets/ae65cb6d-55bb-4ef2-afea-adb12e5597e0" />

**Comment by Silver-Fox** [comment]
<img width="625" height="500" alt="Image" src="https://github.com/user-attachments/assets/da41eeb4-dffb-401d-8e5f-dd8fc04235f9" />

**Comment by sdgedfegw** [comment]
<img width="471" height="480" alt="Image" src="https://github.com/user-attachments/assets/37207791-2ac4-42eb-bcea-cf7a6df6c126" />

**Comment by Daniel-J-Mueller** [comment]
<img width="744" height="416" alt="Image" src="https://github.com/user-attachments/assets/b6a07f57-4bbd-4eb8-aa22-64bd498f222e" />

Push to prod

**Comment by lAnchoretl** [comment]
It's like watching the Mona Lisa getting painted!!

**Comment by flameastro** [comment]
Bro needs an oscar!

**Comment by kingdudely** [comment]
Bro needs an exe!

**Comment by artivaartworks** [comment]
Bro has balls.

**Comment by Me-Myself-But-Not-I** [comment]
I DONT GIVE A FUCK ABOUT THE FUCKING EXECUTABLE! i just want to git clone this stupid fucking program and use it

WHY IS THERE EXECUTABLE??? ADD IT TO THE FUCKING AUR AND GIVE IT TO ME. these dumbfucks think that everyone is a windows user and uses executables. well i am not and i don't understand it. I only know to download and install applications with pacman, AUR(git clone), tar.gz, and make install. SO WHY THE FUCK IS THERE EXECUTABLE? make an AUR package and give it to me. STUPID FUCKING SMELLY NERDS

**Comment by mavericksudo** [comment]
Someone go get this man a EXE.

**Comment by ahigherdesire** [comment]
where the fuck is the exe

**Comment by lAnchoretl** [comment]
Whenever I am down, I check my emails & come back here. Never fails to make me laugh, keep it up "STUPID FUCKING SMELLY NERDS".
