### ISSUE TITLE
The algorithm now openly promoting neo-Nazis under "who to follow"

### ISSUE THREAD

**Issue by matthewberryman** [twitter/the-algorithm#2001]
I guess this is what happens when you don't have any moderation whatsoever.
<img width="380" alt="Screenshot 2024-02-25 at 08 28 23" src="https://github.com/twitter/the-algorithm/assets/2288238/4ba1c6a9-148a-4124-b7ff-98d66cdc4a44">

**Comment by Tim79000** [comment]
Looking into this

**Comment by ghost** [comment]
Looking into this

**Comment by Marioood** [comment]
Looking into this

**Comment by codingneko** [comment]
Is there anyone who isn't a neonazi, a bot or a brand still using Twitter?

**Comment by authenyoo** [comment]
Looking into this

**Comment by mppbtw** [comment]
neonazi's gonna neonazi... i mean wait what

**Comment by matthewberryman** [comment]
Closing. X doesn't care.

**Comment by matthewberryman** [comment]
Elon can't afford for human review? ![image](https://github.com/twitter/the-algorithm/assets/2288238/8e1ccbfb-9f10-4caa-9159-624af062c450)
