### ISSUE TITLE
I love gooning to The Twitter slash The Dash Algorithm git repo.

### ISSUE THREAD

**Issue by authenyoo** [twitter/the-algorithm#2006]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment**
For web, specify your OS and browser version.  For mobile, specify device, OS
and version.  For libraries, what version of build tools are you using?

**Additional context**

**Comment by Inderix** [comment]
Can reproduce as of the latest build

**Comment by MadKamel** [comment]
[Insert joke about being able to reproduce this bug]
