### ISSUE TITLE
‎  

### ISSUE THREAD

**Issue by llunariis** [twitter/the-algorithm#2007]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Exponential-Workload** [comment]
Duplicate of #1961

**Comment by llunariis** [comment]
> Duplicate of #69

ah shit my bad but there hasn't been any activity on it for awhile, does this still count as a dupe though

**Comment by Exponential-Workload** [comment]
> > Duplicate of #69
> 
> ah shit my bad but there hasn't been any activity on it for awhile, does this still count as a dupe though

given necrobumping is allowed i think it does; simply bump [#69](https://github.com/twitter/the-algorithm/issues/69) and see if anyone's interested in a new issue for it

**Comment by llunariis** [comment]
> > > Duplicate of #69
> > 
> > 
> > ah shit my bad but there hasn't been any activity on it for awhile, does this still count as a dupe though
> 
> given necrobumping is allowed i think it does; simply bump [#69](https://github.com/twitter/the-algorithm/issues/69) and see if anyone's interested in a new issue for it

ok, tysm!
