### ISSUE TITLE
TRUE JOE BIDEN BLADE

### ISSUE THREAD

**Issue by Tim79000** [twitter/the-algorithm#2012]
**Describe the bug**

Describe the bug
Joe Biden

To Reproduce

Go to 'Joe Biden'
Click on 'Joe Biden'
Scroll down to 'Joe Biden'
See error
Expected behavior

Screenshots

Environment
For web, specify your OS and browser version. For mobile, specify device, OS
and version. For libraries, what version of build tools are you using?
Joe Bidows 95
image
![image](https://github.com/twitter/the-algorithm/assets/100736284/cb7eb294-fb8f-4679-bc08-51934b98e483)

Additional context

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment**
For web, specify your OS and browser version.  For mobile, specify device, OS
and version.  For libraries, what version of build tools are you using?

**Additional context**

**Comment by MadKamel** [comment]
that's not joe biden, that's an fish!

**Comment by MadKamel** [comment]
Joe Bladen
![image](https://github.com/twitter/the-algorithm/assets/48301203/c1acb99b-5ea4-418a-8dd7-6ae01ff3210b)
