### ISSUE TITLE
REAL SECURITY VULNRABIRLTY

### ISSUE THREAD

**Issue by ghost** [twitter/the-algorithm#2013]
**Describe the bug**
OH GOD IF WE CLOSE ONE MORE ISSUE THERE WILL BE 666 CLOSED ISSUES

**To Reproduce**
1. FUCK
2. DO NOT CLOSE THIS ISSUE
3. PLEASE
4. DO NOT

**Expected behavior**
DO NOT CLOSE THIS ISSUE PLEASE

**Screenshots**

**Environment**
IT DOESNT MATTER PLEASE DONT VCLOSE ANY MORE ISSUES

**Additional context**
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA

**Comment by ghost** [comment]
DO NOT CLOSE I AM VERY SCARED

**Comment by ghost** [comment]
PLEASE DON'T CLOSE

**Comment by ghost** [comment]
OOPS WRONG BUTTON

**Comment by Inderix** [comment]
#2014 trolled

**Comment by ghost** [comment]
Real
