### ISSUE TITLE
repo should be removed to prevent spam by dickheads

### ISSUE THREAD

**Issue by matthewberryman** [twitter/the-algorithm#2015]
@twitter @github
e.g. https://github.com/twitter/the-algorithm/issues/2013 https://github.com/twitter/the-algorithm/issues/2012 https://github.com/twitter/the-algorithm/issues/2011 #2010 #2006 #2003 #1999 #2019 etc. etc.

**Comment by Exponential-Workload** [comment]
"dickheads" bro its just shitposting

**Comment by Ataraxia-Mechanica** [comment]
![chungustux2](https://github.com/twitter/the-algorithm/assets/111327195/19368650-2e26-4589-98e2-ab7f081f31ee)
chungus tux

**Comment by Exponential-Workload** [comment]
chungtux

**Comment by llunariis** [comment]
if you remove years then half of history will be gone :trollface:

**Comment by ghost** [comment]
Real

**Comment by Mortem-Metallum** [comment]
Not sure about removing the entire repo, but yeah something to deal with them.

The guy on #1999 with the audacity to bust into Github expecting a compiled exe and no code at all, and screaming and calling everyone "SMELLY FUCKING NERDS" when he didn't get what he expected, because Github is built on sharing code? I don't think I can top that. That's it. I've peaked

**Comment by Ataraxia-Mechanica** [comment]
> Not sure about removing the entire repo, but yeah something to deal with them.
> 
> The guy on [#1999](https://github.com/twitter/the-algorithm/issues/1999) with the audacity to bust into Github expecting a compiled exe and no code at all, and screaming and calling everyone "SMELLY FUCKING NERDS" when he didn't get what he expected, because Github is built on sharing code? I don't think I can top that. That's it. I've peaked

<img width="3148" height="3551" alt="Image" src="https://github.com/user-attachments/assets/e2936928-dc98-494f-8b49-32b3cc99857b" />

chungus tux

**Comment by ZerocuCodes** [comment]
crazy work some of the people on here 😓

**Comment by Mortem-Metallum** [comment]
yes.
