### ISSUE TITLE
IDEA: Rewrite this in Rust for speed

### ISSUE THREAD

**Issue by ILiedAboutCake** [twitter/the-algorithm#224]
bottom text

**Comment by kamisou** [comment]
how do i close vim?

**Comment by vector3f** [comment]
Have we thought about making it slower to make the world better?

**Comment by Voiture-0** [comment]
> how do i close vim?

Unfortunately you can't. You will have to buy a new computer.

**Comment by TheDirams** [comment]
:wq

**Comment by couldbejake** [comment]
> how do i close vim?

You can't, reformat

**Comment by BeepSterr** [comment]
we should look at PHP, i heard its pretty good
