### ISSUE TITLE
author_is_elon

### ISSUE THREAD

**Issue by enzo-js** [twitter/the-algorithm#236]
the problem is his tweets suck. stop recommending them. https://github.com/twitter/the-algorithm/blob/7f90d0ca342b928b479b512ec51ac2c3821f5922/home-mixer/server/src/main/scala/com/twitter/home_mixer/functional_component/decorator/HomeTweetTypePredicates.scala#L225

**Comment by matteomad1011** [comment]
bro. too much

**Comment by jcolicchio** [comment]
Concerning.

**Comment by BradFitz66** [comment]
looking into it.

**Comment by sohdas** [comment]
Interesting

**Comment by nikolqy** [comment]
How much can I pay to get my tweets promoted like that?

**Comment by kimjoaoun** [comment]
> How much can I pay to get my tweets promoted like that?

44 biliions, in cash.

**Comment by nikolqy** [comment]
> > How much can I pay to get my tweets promoted like that?
> 
> 44 biliions, in cash.

I think you mean $20 billion now!

**Comment by alex-redacted** [comment]
Cannot believe he got his own special tweet booster but he owns the thing, so I guess Melon can do whatever he wants.

**Comment by fadyanwar** [comment]
Github Issues have never been so entertaining, I guess I will ditch reddit in its favour

**Comment by diegololia** [comment]
Seems like a security vulnerability

**Comment by rifusaki** [comment]
> Github Issues have never been so entertaining, I guess I will ditch reddit in its favour

Let's ditch Twitter for GitHub Issues too

**Comment by Galluno** [comment]
real

**Comment by nonbinarypotus** [comment]
based

**Comment by fadyanwar** [comment]
> > Github Issues have never been so entertaining, I guess I will ditch reddit in its favour
> 
> Let's ditch Twitter for GitHub Issues too

Or maybe fork twitter and create a better open platform, hopefully Elon did see this coming...

**Comment by couldbejake** [comment]
This only represents a small part of Twitter, and as others have pointed out, code has been stripped out.

**Comment by PacerBridge** [comment]
Again, isn't this code purely just for logging stats?

**Comment by vogelarthur** [comment]
This specific snippet is only for metrics...

https://github.com/twitter/the-algorithm/blob/7f90d0ca342b928b479b512ec51ac2c3821f5922/home-mixer/server/src/main/scala/com/twitter/home_mixer/functional_component/feature_hydrator/RequestQueryFeatureHydrator.scala#L87

**Comment by gsuhm** [comment]
!!

**Comment by Daniel15** [comment]
> Again, isn't this code purely just for logging stats?

@PacerBridge  There's no guarantee that Twitter are running the exact same code that's in this repo. They could be using this feature for other purposes.

**Comment by BetaKors** [comment]
you're so real for this

**Comment by rifusaki** [comment]
and even the fact that they're tracking a single user's stats just because he asked for it is so goddamn funny and ridiculous. i'm sure they're doing nothing with that data

**Comment by widarlein** [comment]
> This specific snippet is only for metrics...
> 
> https://github.com/twitter/the-algorithm/blob/7f90d0ca342b928b479b512ec51ac2c3821f5922/home-mixer/server/src/main/scala/com/twitter/home_mixer/functional_component/feature_hydrator/RequestQueryFeatureHydrator.scala#L87

The root cause still persists, though

**Comment by piotrchojnowski** [comment]
> and even the fact that they're tracking a single user's stats just because he asked for it is so goddamn funny and ridiculous. i'm sure they're doing nothing with that data

yeah, it's weird a bit. looks like some engineers added that the correlation feature/elon tweets, but Elon himself said during the call, that he was unaware of that metrics.. :D

**Comment by schott89** [comment]
> Add

Single metric for the CEO. Totally normal, nothing to see here...

**Comment by bcentner** [comment]
Hilarious, especially considering he is the most followed person on twitter now as of 2 days ago.
https://www.theverge.com/2023/3/30/23656153/elon-musk-twitter-most-followed-barack-obama

**Comment by e-lisa** [comment]
> yeah, it's weird a bit. looks like some engineers added that the correlation feature/elon tweets, but Elon himself said during the call, that he was unaware of that metrics.. :D

I wonder what other features on the backend relate to the `author_is_elon` tag that elon is "unware of"

**Comment by fadyanwar** [comment]
On another note, from a purely software engineering perspective, this is basically hardcoding! As in if you design a system to do a specific feature for a specific user! What happens if Twitter was sold to another owner? It should have been configurable at least.

**Comment by AbdulMalikDev** [comment]
> This only represents a small part of Twitter, and as others have mentioned, code has been stripped out.

Lol imagine what we would find if all of it was open sourced😂

**Comment by AbdulMalikDev** [comment]
> On another note, from a purely software engineering perspective, this is basically hardcoding! As in if you design a system to do a specific feature for a specific user! What happens if Twitter was sold to another owner? It should have been configurable at least.

This won't be an issue since no one is gonna buy this

**Comment by schott89** [comment]
> On another note, from a purely software engineering perspective, this is basically hardcoding! As in if you design a system to do a specific feature for a specific user! What happens if Twitter was sold to another owner? It should have been configurable at least.

Maybe the elon tag also specifies a user group. Maybe the want metrics for shitposters.

**Comment by masreplay** [comment]
Ratio

**Comment by rifusaki** [comment]
> Ratio

jesus christ stop it elon's not gonna marry you

**Comment by yourtaxhere** [comment]
DITADURA NUNCA MAIS FUCK TRUMP FUCK BOLSONARO

**Comment by zubyCharles** [comment]
> Ratio

Bro this isn't twitter..  Well it is but you know what I mean

**Comment by cat-marin** [comment]
"!!"

**Comment by jasonmit** [comment]
‼ looking into it 🤣🤣

**Comment by luuk58** [comment]
!

**Comment by AnushK-Fro** [comment]
+1

**Comment by panquequelol** [comment]
+1

**Comment by milse113** [comment]
+1

**Comment by katsuki-yuri** [comment]
...

**Comment by Kalmuraee** [comment]
Should i contribute with `“author_is_khalid”` ?

**Comment by yzhuang** [comment]
Based on the code, it was only used to measure serving statistics via Twitter's A/B testing framework, and this “is_author_elon” feature does not impact the recommendation algorithm.

**Comment by RubenFontes** [comment]
LOL

**Comment by jakejarvis** [comment]
I've had the long-neglected Mac app installed for years (and haven't opened it in months), and never got random unwanted notifications from people I don't follow — until this week. 

<img width="392" alt="Screenshot 2023-03-31 at 5 34 45 PM" src="https://user-images.githubusercontent.com/1703673/229248341-b1ddbe23-eca3-4bd6-b32d-02b20ffd07c4.png">

Starting to think the B in A/B stands for "booed at a comedy show for not being funny..." 🤷‍♂️

**Comment by alansary** [comment]
Never imagined a hard coding configuration in Twitter's algorithm LOL

**Comment by dabirdweius** [comment]
"Money is all you need"

**Comment by sasdallas** [comment]
"We aren't biased"

**Comment by Kyza** [comment]
> the problem is his tweets suck. stop recommending them.
> 
> https://github.com/twitter/the-algorithm/blob/7f90d0ca342b928b479b512ec51ac2c3821f5922/home-mixer/server/src/main/scala/com/twitter/home_mixer/functional_component/decorator/HomeTweetTypePredicates.scala#L225

lol

> This commit does not belong to any branch on this repository, and may belong to a fork outside of the repository.
> ![lol](https://user-images.githubusercontent.com/40003440/229257981-a99cf351-59a7-490f-afb8-d69e2e9d021c.png)

**Comment by VinnisVidya** [comment]
!

**Comment by alex-redacted** [comment]
> Never imagined a hard coding configuration in Twitter's algorithm LOL

Yup. Super dang bonkers honestly

**Comment by pavankjadda** [comment]
This will be triaged soon

**Comment by rifusaki** [comment]
they did it actually lmao, check https://github.com/twitter/the-algorithm/commit/ec83d01dcaebf369444d75ed04b3625a0a645eb9

**Comment by BitComing** [comment]
good issue😂

**Comment by Nebula-Developer** [comment]
I find it interesting they didn't bother patching up all the things they would get roasted for, because this is just sad-

**Comment by avinashseth** [comment]
did you guys find the solutions? I'm still getting those tweets 😟

**Comment by bdsl** [comment]
> On another note, from a purely software engineering perspective, this is basically hardcoding! As in if you design a system to do a specific feature for a specific user! What happens if Twitter was sold to another owner? It should have been configurable at least.


If twitter was sold to another owner then they can edit that line of code if they like. Hardcoding isn't always bad. Decisions have to be written down somewhere, it's just a choice of writing it inside the main program or in a separate config file. Either way someone will have to edit it if they want to change the decision. The most important thing is to make sure its kept with version control in git or similar.

**Comment by dagelf** [comment]
The fake "open source" spirit is to open source the code, but keep all the juicy bits in config. So technically... 

But srsly. Don't do that...

**Comment by sha-265** [comment]
ACK

**Comment by MeqdadDev** [comment]
Separation of social classes in Twitter society 😂

**Comment by datgreatkhan** [comment]
Agreed. :D

**Comment by fadyanwar** [comment]
> > On another note, from a purely software engineering perspective, this is basically hardcoding! As in if you design a system to do a specific feature for a specific user! What happens if Twitter was sold to another owner? It should have been configurable at least.
> 
> If twitter was sold to another owner then they can edit that line of code if they like. Hardcoding isn't always bad. Decisions have to be written down somewhere, it's just a choice of writing it inside the main program or in a separate config file. Either way someone will have to edit it if they want to change the decision. The most important thing is to make sure its kept with version control in git or similar.

Curious, did you write this code or know who wrote it?

**Comment by bdsl** [comment]
> Curious, did you write this code or know who wrote it?

No, I'm nothing to do with Twitter.

**Comment by SantiiRepair** [comment]
Rewrite the algorithm to lisp lang and you will see how elon's twitters will stop appearing, lol it's funny because it won't work

**Comment by raymondctc** [comment]
Can anyone teach me how to find out this commit hash? As I don't see the whole history of the codebase.

**Comment by am5a03** [comment]
Can anyone teach me how to find out this commit hash? As I don’t see the whole history of the codebase.

**Comment by bdsl** [comment]
> Can anyone teach me how to find out this commit hash? As I don’t see the whole history of the codebase.

@am5a03 what commit hash are you looking for? I don't know the codebase but I might be able to help with git and github.

**Comment by datgreatkhan** [comment]
> Can anyone teach me how to find out this commit hash? As I don’t see the whole history of the codebase.

It's because they remove the commit for it. You can find it here: https://github.com/twitter/the-algorithm/blob/7f90d0ca342b928b479b512ec51ac2c3821f5922/home-mixer/server/src/main/scala/com/twitter/home_mixer/functional_component/decorator/HomeTweetTypePredicates.scala#L225

I had to dig back to find the link from someone else.

**Comment by debarati10** [comment]
I wasn't into open-source much but this is too interesting to not be

**Comment by shylaatchison** [comment]
yoo, can we get weekly high score lists if ya'll tracking metrics for author_is_power_user ??? just a high score list for power users who tweeted the most?? I bet that could be hilarious

Though may incentivize people trying to game it by spamming tweets, which actually then would probably result in them losing followers/being blocked... Maybe this could actually be a net good after all? Bait the social climbers into losing their following lol

**Comment by NotASimp69** [comment]
i just love it

**Comment by timelessnesses** [comment]
this is one of the pr ever

**Comment by timelessnesses** [comment]
this is one of the pr ever

**Comment by nonbinarypotus** [comment]
not completed

**Comment by AstroAntics** [comment]
That's it. That's the tweet.

**Comment by e-lisa** [comment]
Who the heck is maintaining this? What kind of process means you just go around closing issues with out documenting WHY they are being closed?

Good grief :*(

**Comment by atumas-bananamilk** [comment]
Diabolical.
