### ISSUE TITLE
Fix LICENSE

### ISSUE THREAD

**Issue by J0ddy** [twitter/the-algorithm#248]
https://github.com/twitter/the-algorithm/blob/7f90d0ca342b928b479b512ec51ac2c3821f5922/COPYING#LL632C8-L632C8
https://github.com/twitter/the-algorithm/blob/7f90d0ca342b928b479b512ec51ac2c3821f5922/COPYING#L633

**Comment by KaspianDev** [comment]
It's supposed to be like that. It's a full copy of the license. No need to fill parameters in it.
