### ISSUE TITLE
Accounts that have been blocked should not appear when you search on Twitter

### ISSUE THREAD

**Issue by logicP** [twitter/the-algorithm#253]
Blocking accounts on Twitter should make it so that they do not appear unblocked when you search on Twitter. This is to help curate your experience on there, and to weed out irrelevant results from the search.

**Comment by brandondrew** [comment]
could the downvote crowd explain why they think this is a bad idea?

**Comment by shauntmcgovern** [comment]
Which and where are the exact lines this takes place in this source code?

**Comment by Montchat** [comment]
> could the downvote crowd explain why they think this is a bad idea?

didn't downvote, but I'm assuming there would need to be a way for a user to be able to unblock someone if they wanted to do so.

**Comment by logicP** [comment]
> Which and where are the exact lines this takes place in this source code? So at the time of search, the users{} the twitter user has.blocked() go dark. These blocked users can no longer be selected for the twitter public search. I'm just a QA && T. I am a developer but I am not a Senior Developer();

For me that hasn't been my experience, blocked accounts will still have their tweets show up for me whenever I'm looking up anything. It's rather annoying when I'm trying to find information on there that I can't really find anywhere else and I have to deal with the plethora of tweets and accounts I would rather not see. As for me, I'm not much of a coder myself, I'm more of a tester and tinkerer of sorts whenever I can get my hands on a project

**Comment by shauntmcgovern** [comment]
So the answer is. 
if a 
TwitterUser has blocked this twitterAccount;
then that TwitterAccount will no longer be able to appear in their TwitterPublicSearch for when this
TwitterUser queries a search of what it has searched() to display in its TwitterPublicSearch. 
So that would mean that BlockedTwitterAccount(); would no longer have the attribution
so twitterAccount.BlockedTwitterAccount will not be available or inside of this TwitterUser TwitterPublicSearch

**Comment by qtAmyVT** [comment]
bruh there are a lot of trolls in this github

**Comment by jdm-twtr** [comment]
Thanks for filing. We've marked this issue as an unrelated bug or feature for future review.
                    In order to keep our issue count manageable, we will not be leaving these issues open. We apologize for
                    the inconvenience. If you feel that we closed your issue in error, please re-file the issue, stating how
                    the requested feature applies to the recommendation algorithm components that have been open-sourced thus far.
