### ISSUE TITLE
I put the new Forgi's on the G

### ISSUE THREAD

**Issue by ShockAwer** [twitter/the-algorithm#284]
Mustard on the beat, ho

I put the new Forgi's on the G
I trap [until](https://www.definitions.net/definition/until) the [bloody](https://www.definitions.net/definition/bloody) bottoms is underneath
'Cause all my [niggas](https://www.definitions.net/definition/niggas) got it out the streets
I keep a [hunnid](https://www.definitions.net/definition/hunnid) racks, [inside](https://www.definitions.net/definition/inside) my jeans

I [remember](https://www.definitions.net/definition/remember) hittin' the mall with the [whole](https://www.definitions.net/definition/whole) team
Now a [nigga](https://www.definitions.net/definition/nigga) can't [answer](https://www.definitions.net/definition/answer) calls 'cause I'm ballin'
I was wakin' up gettin' [racks](https://www.definitions.net/definition/racks) in the mornin'
I was [broke](https://www.definitions.net/definition/broke) now I'm rich, [these](https://www.definitions.net/definition/these) niggas salty

All this [designer](https://www.definitions.net/definition/designer) on my body got me drip, drip (ay)
Straight up out the Yajects, I'm a big Crip
If I got a pint of lean, I'ma sip, sip
I run the [racks](https://www.definitions.net/definition/racks) up with my queen, like [London](https://www.definitions.net/definition/London) and Nip
But I got rich on all [these](https://www.definitions.net/definition/these) niggas, I didn't forget, bet
I had to go [through](https://www.definitions.net/definition/through) the struggle, I didn't [forget](https://www.definitions.net/definition/forget) that
I [hopped](https://www.definitions.net/definition/hopped) inside of the [Maybach](https://www.definitions.net/definition/Maybach) and now I can sit back
These [bitches](https://www.definitions.net/definition/bitches) know me now, 'cause I got them big racks
'Cause I'm gettin' [money](https://www.definitions.net/definition/money) now, I know you [heard](https://www.definitions.net/definition/heard) that
Young [nigga](https://www.definitions.net/definition/nigga) on the corner, [bitch](https://www.definitions.net/definition/bitch) I had to [serve](https://www.definitions.net/definition/serve) crack
Uncle [fronted](https://www.definitions.net/definition/fronted) me some P's had to get them [birds](https://www.definitions.net/definition/birds) back
We came up on [dirty](https://www.definitions.net/definition/dirty) money, I gave it a bird bath
Cut off the [brain](https://www.definitions.net/definition/brain) and I give my [bitch](https://www.definitions.net/definition/bitch) a new coupe
Either you frontin' y'all gang or y'all suwoop
Got a New [Orleans](https://www.definitions.net/definition/Orleans) bitch and man that [pussy](https://www.definitions.net/definition/pussy) voodoo
And I'm that [nigga](https://www.definitions.net/definition/nigga) now, who knew?

I put the new Forgi's on the G
I trap [until](https://www.definitions.net/definition/until) the [bloody](https://www.definitions.net/definition/bloody) bottoms is underneath
'Cause all my [niggas](https://www.definitions.net/definition/niggas) got it out the streets
I keep a [hunnid](https://www.definitions.net/definition/hunnid) racks, [inside](https://www.definitions.net/definition/inside) my jeans

I [remember](https://www.definitions.net/definition/remember) hittin' the mall with the [whole](https://www.definitions.net/definition/whole) team
Now a [nigga](https://www.definitions.net/definition/nigga) can't [answer](https://www.definitions.net/definition/answer) calls 'cause I'm ballin'
I was wakin' up gettin' [racks](https://www.definitions.net/definition/racks) in the mornin'
I was [broke](https://www.definitions.net/definition/broke) now I'm rich, [these](https://www.definitions.net/definition/these) niggas salty

I been wakin' up to get the money, whoa, whoa
Got a bad bitch, her ass tatted, whoa, whoa
Givenchy to my toes, two [twins](https://www.definitions.net/definition/twins) I'm [fucking](https://www.definitions.net/definition/fucking) 'em both
I put in a new AP, the [water](https://www.definitions.net/definition/water) like a boat
I was down bad on my dick, [where](https://www.definitions.net/definition/where) was you [niggas](https://www.definitions.net/definition/niggas) at?
I know you [turned](https://www.definitions.net/definition/turned) your back on me, just to get some racks
I seen you [swerve](https://www.definitions.net/definition/swerve) back, 'cause I'm in the [black](https://www.definitions.net/definition/black) 'Bach
New [diamonds](https://www.definitions.net/definition/diamonds) on me, f*ck a [flash](https://www.definitions.net/definition/flash) this ain't SnapChat
'Cause I been gettin' paid
Yellow [diamonds](https://www.definitions.net/definition/diamonds) on me look like lemonade
Got my baby mama that new Bentayga
Tryna get the dojo like a sensei
Rolls [Royce](https://www.definitions.net/definition/Royce) umbrellas when I'm in the rain
I just mind my business
I got [brothers](https://www.definitions.net/definition/brothers) that did the time, I ain't kiddin'
All [these](https://www.definitions.net/definition/these) rappers just talk [about](https://www.definitions.net/definition/about) it, I live it
Goin' up, I ain't got no sky limit, yeah, yeah, yeah

I put the new Forgi's on the G
I trap [until](https://www.definitions.net/definition/until) the [bloody](https://www.definitions.net/definition/bloody) bottoms is underneath
'Cause all my [niggas](https://www.definitions.net/definition/niggas) got it out the streets
I keep a [hunnid](https://www.definitions.net/definition/hunnid) racks, [inside](https://www.definitions.net/definition/inside) my jeans

I [remember](https://www.definitions.net/definition/remember) hittin' the mall with the [whole](https://www.definitions.net/definition/whole) team
Now a [nigga](https://www.definitions.net/definition/nigga) can't [answer](https://www.definitions.net/definition/answer) calls 'cause I'm ballin'
I was wakin' up gettin' [racks](https://www.definitions.net/definition/racks) in the mornin'
I was [broke](https://www.definitions.net/definition/broke) now I'm rich, [these](https://www.definitions.net/definition/these) niggas salty

I, ay yeah
I've been ballin' lil' nigga
Now [watch](https://www.definitions.net/definition/watch) me ball on [these](https://www.definitions.net/definition/these) niggas
Yeah, now [watch](https://www.definitions.net/definition/watch) me ball on [these](https://www.definitions.net/definition/these) niggas, yeah
Now [watch](https://www.definitions.net/definition/watch) me ball on [these](https://www.definitions.net/definition/these) niggas
Now [watch](https://www.definitions.net/definition/watch) me ball on [these](https://www.definitions.net/definition/these) niggas, yeah yeah

**Comment by sunglocto** [comment]
I agree

**Comment by IsraPerez98** [comment]
![interesting](https://user-images.githubusercontent.com/24889578/229228681-b978982d-29b8-4e17-bf18-4b06f1fcf381.png)

**Comment by 0x00Jeff** [comment]
so true
