### ISSUE TITLE
Bookmark folders

### ISSUE THREAD

**Issue by AlexYaroshuk** [twitter/the-algorithm#301]
Akin to Instagram, with a possibility of sharing with others in the future(akin Facebook/new Instagram feature)

**Comment by jdm-twtr** [comment]
Thanks for filing. We've marked this issue as an unrelated bug or feature for future review.
                    In order to keep our issue count manageable, we will not be leaving these issues open. We apologize for
                    the inconvenience. If you feel that we closed your issue in error, please re-file the issue, stating how
                    the requested feature applies to the recommendation algorithm components that have been open-sourced thus far.
