### ISSUE TITLE
Why no python

### ISSUE THREAD

**Issue by SoloDevOG** [twitter/the-algorithm#31]

**Comment by walpolsh** [comment]
![image](https://user-images.githubusercontent.com/23249640/229206994-66fa460e-afa5-4cd0-83a0-1352d0417fa0.png)

**Comment by wiseaidev** [comment]
@Hoodgail No, it is not!

**Comment by Hoodgail** [comment]
@SoloDevOG
@wiseaidev
Watch this
https://www.tiktok.com/@interprator/video/7194208725970783534

**Comment by wiseaidev** [comment]
I think TikTok is bad!

**Comment by gokhaneryigit** [comment]
https://github.com/twitter/the-algorithm-ml

**Comment by Hoodgail** [comment]
> I think TikTok is bad!

https://www.youtube.com/watch?v=9qfLHb-CBWQ
