### ISSUE TITLE
My tweets get no likes

### ISSUE THREAD

**Issue by Heliodex** [twitter/the-algorithm#320]
**Describe the bug**

My tweets got no like

**To Reproduce**

1. Like my tweets and follow pls

**Expected behavior**

Tweet get infinity like

**Screenshots**

Pc is not capable of screenshot so heres ascii art
```
/ -----------------------\
|                        |
|       ❤️ 0 likes       |
|                        |
\ -----------------------/
```
**Environment**

Window 95

**Additional context**

Elon pls fix

**Comment by pizzaboxer** [comment]
I think you raycist 💀 💀 🏀

**Comment by ShockAwer** [comment]
I think pizzaboxer is raceist personally. Heliodex LGTM

**Comment by Heliodex** [comment]
Agree

> I think pizzaboxer is rayceist personally. Heliodex LGTM

Absolutely agree

**Comment by Roderichs** [comment]
I think pizzaboxer is raceist personally. Heliodex LGTM

**Comment by Heliodex** [comment]
> I think you raycist 💀 💀 🏀

86.21.64.222

**Comment by gekkowrld** [comment]
> **Describe the bug**
> 
> My tweets got no like
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
>     1. Like my tweets and follow pls
> 
> 
> **Expected behavior**
> 
> Tweet get infinity like
> 
> **Screenshots**
> 
> Pc is not capable of screenshot so heres ascii art
> 
> ```
> / -----------------------\
> |                        |
> |       ❤️ 0 likes       |
> |                        |
> \ -----------------------/
> ```
> 
> **Environment**
> 
> Window 95
> 
> **Additional context**
> 
> Elon pls fix

Really this should be implemented

**Comment by scottbeamer** [comment]
I have the same problem.  Elon, please fix.

**Comment by 0xManjeet** [comment]
Here's a fix: 
/ ------------------------------------------------\
|                                                        |
|     ❤️ 99999999999999 likes    |
|                                                        |
\ ------------------------------------------------/

**Comment by Heliodex** [comment]
Closed as completed  ??? Its ntot fixed yet im still getting 0 like

**Comment by 0xManjeet** [comment]
> Closed as completed ??? Its ntot fixed yet im still getting 0 like

I think your tweets might have quality issues. Can you please test with this tweet and tell me if you still don't get any likes:
"Elon musk is a genius, and Tesla is best 🚀🚀, a thread 🧵"

**Comment by Heliodex** [comment]
> > Closed as completed ??? Its ntot fixed yet im still getting 0 like
> 
> I think your tweets might have quality issues. Can you please test with this tweet and tell me if you still don't get any likes:
> 
> "Elon musk is a genius, and Tesla is best 🚀🚀, a thread 🧵"

![image](https://user-images.githubusercontent.com/50165230/231919918-47d43f1e-0439-4196-bf16-414f736e7faf.png)
Your   suggestion did not seem to work :(
