### ISSUE TITLE
Rewrite it in Assembly

### ISSUE THREAD

**Issue by BetaKors** [twitter/the-algorithm#324]
Performance is terrible right now. Rewrite it in Assembly like real programmers would.

**Comment by BetaKors** [comment]
Nuh uh. Python is infinitely faster than Assembly.

**Comment by samdisk11** [comment]
> Nuh uh. Python is infinitely faster than Assembly.

You are quite silly. Everyone knows C++ is better compared to Python.

**Comment by Ajjig** [comment]
Of course, that would be much faster.
