### ISSUE TITLE
add author_is_rifusaki

### ISSUE THREAD

**Issue by rifusaki** [twitter/the-algorithm#339]
**Is your feature request related to a problem? Please describe.**
i hate that I never get likes or retweets

**Describe the solution you'd like**
add a function like
https://github.com/twitter/the-algorithm/blob/7f90d0ca342b928b479b512ec51ac2c3821f5922/home-mixer/server/src/main/scala/com/twitter/home_mixer/functional_component/decorator/HomeTweetTypePredicates.scala#L225
but for my account so I can get more likes please

**Describe alternatives you've considered**
everyone like me please

**Additional context**
![image](https://user-images.githubusercontent.com/46846373/229237292-ee89af35-08ed-45be-9f3e-fd3fc0cf5034.png)

**Comment by masreplay** [comment]
ratio
