### ISSUE TITLE
Decentralized twitter

### ISSUE THREAD

**Issue by MartinSchere** [twitter/the-algorithm#340]
We need freedom of speech in a permissionless, censorship-resistant ledger.

Adopt blockchain technology to create the ultimate blockchain.

**Comment by masreplay** [comment]
Ratio

**Comment by RocketRaccoon27** [comment]
Pull yourself up by your bootstraps and make it yourself.

**Comment by MolassesLover** [comment]
Least libertarian GitHub user

**Comment by NodeMixaholic** [comment]
> Ratio

Ratio x2, please negative emoji to upvote and positive emoji to upvote. Reply to super upvote. Twiiter _**should**_ be decentralized.

**Comment by Diksha894** [comment]
Try out decentralised tiktok - hotornot.wtf

**Comment by samdisk11** [comment]
> We need freedom of speech in a permissionless, censorship-resistant ledger.
> 
> Adopt blockchain technology to create the ultimate blockchain.

Hive/Steem exist for this Blockchain-wise (though they implement more than just twitter's features). Also Mastodon for non-blockchain.

**Comment by samdisk11** [comment]
> Try out decentralised tiktok - hotornot.wtf

No. TikTok as an idea is horrible, should burn to the ground in a powerful fire with NO SURVIVORS.

**Comment by pixiekat** [comment]
Here you can find Decentralized Twitter here: https://instances.social/ or here: https://mastodon.help/instances/en

That should help you.

**Comment by yhoungdev** [comment]
There are Nostr clients that has the feel of twitter

**Comment by samdisk11** [comment]
> Here you can find Decentralized Twitter here: https://instances.social/ or here: https://mastodon.help/instances/en
> 
> That should help you.
> 
> Plus it's 1000% better than Twitter.
> 
> Better yet, contribute at https://github.com/mastodon/mastodon instead of doing Elon's work for him since he fired all the engineers.

LOL WHAT???? THERE IS NO WAY HE FIRED ALL OF THEM... gotta be like 1 hiding from elon's wrath or something.

**Comment by Alotab** [comment]
I don't think twitter was meant for that.

**Comment by mshumayl** [comment]
What are you still doing here, Jack Dorsey?

**Comment by kurbus** [comment]
https://github.com/mastodon/mastodon

**Comment by jdm-twtr** [comment]
Thanks for filing. We've marked this issue as an unrelated bug or feature for future review.
                    In order to keep our issue count manageable, we will not be leaving these issues open. We apologize for
                    the inconvenience. If you feel that we closed your issue in error, please re-file the issue, stating how
                    the requested feature applies to the recommendation algorithm components that have been open-sourced thus far.
