### ISSUE TITLE
BUG REPORT: TWITTER HAS GONE TOO WOKE (VERY BAD)!!! ELON MUSK, FIX THIS (NOW)!!!

### ISSUE THREAD

**Issue by RocketRaccoon27** [twitter/the-algorithm#342]
**Describe the bug**
Now that I got your dumbass here, remember when Twitter said it couldn't ban GOP candidates and representatives because their rhetoric is too similar to white supremacists. Interesting.

Article link if you need a refresher:
https://www.vice.com/en/article/a3xgq5/why-wont-twitter-treat-white-supremacy-like-isis-because-it-would-mean-banning-some-republican-politicians-too

**Expected behavior**
Ban them all.

**Screenshots**
https://www.vice.com/en/article/a3xgq5/why-wont-twitter-treat-white-supremacy-like-isis-because-it-would-mean-banning-some-republican-politicians-too

**Environment**
My fuckin'... internet-compatible devices

**Additional context**
Trans rights are human rights, baby. Fuck Elon Musk. Fuck the GOP. Fuck Republicans. And fuck Tom Brady.

**Comment by Zelakolase** [comment]
This is not a technical issue, smh

**Comment by BetaKors** [comment]
Elon's tweets are so bad they might as well have been made by a robot. This is very much a technical problem IMO.

**Comment by rifusaki** [comment]
> This is not a technical issue, smh

mate you might be a technical and mathematical genius and you may have solved the collatz conjecture but here's the thing

really hear me out in this one

not everything can be solved with math

**Comment by Zelakolase** [comment]
Sabotaging in the way of genuine technical issues and feature requests for some political discussion should not be tolerated

**Comment by rifusaki** [comment]
> for some political discussion

bro thinks human rights are a political discussion 💀
