### ISSUE TITLE
Will this repo get deleted? 😔

### ISSUE THREAD

**Issue by anurag-roy** [twitter/the-algorithm#343]
I've had so much fun with all of you people, but I just realised this repo will get deleted on the 2nd of April and I will miss all of you 😞

**Comment by datkat21** [comment]
well, let's have some fun while it lasts shouldn't we? 😀

**Comment by masreplay** [comment]
Ratio

**Comment by anurag-roy** [comment]
> Ratio

Ratio blocked

**Comment by DaInfLoop** [comment]
someone should clone this and re-post it when it gets deleted

**Comment by gekkowrld** [comment]
Not allowed by the license I think

**Comment by NodeMixaholic** [comment]
> Not allowed by the license I think

Actually, AGPL allows Private use and Patent use, check the license.

**Comment by anurag-roy** [comment]
Do forks get deleted when the original repo is deleted?

**Comment by NodeMixaholic** [comment]
> Do forks get deleted when the original repo is deleted?

No idea. Just in case, download the repo. Make a local backup.

**Comment by NodeMixaholic** [comment]
Even if it doesn't get deleted at first it can be deleted at any time I think.

**Comment by byronbytes** [comment]
it wasn't about all the attempts to fix twitter, or removing elon. It was about the friends we made along the way.

**Comment by 8C** [comment]
xd
