### ISSUE TITLE
So we back in the mine

### ISSUE THREAD

**Issue by RocketRaccoon27** [twitter/the-algorithm#346]
Got our pickaxe swinging from side to side, side-side to side

**Comment by buddy-codes** [comment]
this task, a grueling one

**Comment by DaInfLoop** [comment]
No.

**Comment by h3llo-wor1d** [comment]
Hope to find some diamonds tonight night night, diamonds tonight

**Comment by buddy-codes** [comment]
Heads up
You hear a sound, turn around and look up

**Comment by dromzeh** [comment]
total shock fills your body

**Comment by BetaKors** [comment]
Total shock fills your body

**Comment by buddy-codes** [comment]
oh no it's you again!

**Comment by DaInfLoop** [comment]
this is not discord

**Comment by BigKitten** [comment]
> oh no it's you again!

half a heart is left but don’t die die die

**Comment by RocketRaccoon27** [comment]
Cuz baby tonight

**Comment by dromzeh** [comment]
the creeper's tryna steal all our stuff again

**Comment by mstdn** [comment]
Are you on RuneScape?

**Comment by svalencia014** [comment]
> the creeper's tryna steal all our stuff again

Cause baby toniiiiiight

**Comment by ThunderMite42** [comment]
> > the creeper's tryna steal all our stuff again
> 
> Cause baby toniiiiiight

You grab your pick, shovel and bolt again

**Comment by Outpizza** [comment]
And run, run, until it's done, done

**Comment by S0ulf3re** [comment]
until the sun comes up in the morn
