### ISSUE TITLE
Post a random picture without any context

### ISSUE THREAD

**Issue by anurag-roy** [twitter/the-algorithm#350]
![62613e11f342f_c93YDOm__700](https://user-images.githubusercontent.com/53750093/229238399-3880679a-e154-45da-ad17-f00284ecbd08.jpg)

**Comment by BetaKors** [comment]
![imagem_2023-03-31_184458085](https://user-images.githubusercontent.com/88991219/229238505-fe2f1446-0a09-4ce6-94bd-d824cd0c5cb4.png)

**Comment by RihanArfan** [comment]
![7300i2tkzska1](https://user-images.githubusercontent.com/20425781/229238573-191dbc37-b053-490e-99c2-bd91db650d9b.png)

**Comment by RocketRaccoon27** [comment]
![image](https://user-images.githubusercontent.com/87645250/229238590-55d5f94a-92bc-46eb-854f-17d5cd3213fa.png)

**Comment by PacLucas** [comment]
![image](https://user-images.githubusercontent.com/42785446/229238939-6631929e-4b13-480b-acdb-e0dad4c42cd0.png)

**Comment by NodeMixaholic** [comment]
![stallman](https://user-images.githubusercontent.com/9904667/229239017-139425c7-c8ea-433e-b15e-95f1d284255a.jpeg)

**Comment by jwansek** [comment]
![stallman_gnu](https://user-images.githubusercontent.com/37976823/229239055-212ee2dd-c8de-4858-b823-bed0745cd5b7.gif)

**Comment by JorgeRuizDev** [comment]
![](https://pbs.twimg.com/media/Frq7CQ-WwAEnXzh?format=jpg&name=900x900)
