### ISSUE TITLE
can we just euthanize elon

### ISSUE THREAD

**Issue by FourteenCoast** [twitter/the-algorithm#352]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by RocketRaccoon27** [comment]
Interesting.

**Comment by anurag-roy** [comment]
Very interesting.

**Comment by BetaKors** [comment]
Incredibly interesting.

**Comment by rifusaki** [comment]
looking into it.

**Comment by FourteenCoast** [comment]
Hi, I am still having this issue. Please open it back up James.

**Comment by skyrina** [comment]
@jdm-twtr Hello. Please re-open this issue. Thank you.
