### ISSUE TITLE
An option to recommend or not recommend nsfw content 

### ISSUE THREAD

**Issue by Zelakolase** [twitter/the-algorithm#353]
**Is your feature request related to a problem? Please describe.**
Giving people more control over the content.

**Describe the solution you'd like**
A dashboard for topics to recommend based on nsfw and offensive categorization. This would allow people to change the algorithm behavior to their wish. Also, please add similar features of 'new,best,top,hot' in reddit into Twitter, as the sorting will largely happen on the client side.

**Comment by jdm-twtr** [comment]
Thanks for filing. We've marked this issue as an unrelated bug or feature for future review.
                    In order to keep our issue count manageable, we will not be leaving these issues open. We apologize for
                    the inconvenience. If you feel that we closed your issue in error, please re-file the issue, stating how
                    the requested feature applies to the recommendation algorithm components that have been open-sourced thus far.

**Comment by Zelakolase** [comment]
I will remind you in a month.
