### ISSUE TITLE
Show people liked tweet message on timeline again.

### ISSUE THREAD

**Issue by BeaNoodle** [twitter/the-algorithm#360]
It's confusing

**Comment by jdm-twtr** [comment]
Thanks for filing. We've marked this issue as an unrelated bug or feature for future review.
                    In order to keep our issue count manageable, we will not be leaving these issues open. We apologize for
                    the inconvenience. If you feel that we closed your issue in error, please re-file the issue, stating how
                    the requested feature applies to the recommendation algorithm components that have been open-sourced thus far.
