### ISSUE TITLE
Bring back Twitter for iPhone

### ISSUE THREAD

**Issue by zubyCharles** [twitter/the-algorithm#371]
**why was it even removed in the first place?**
"It was a waste of screen real estate"???...Utter bullocks!! All phones are at least 6 inches these days. 

Need them to know what device I'm tweeting from for more context and understanding of tweet ❗️

**Comment by RocketRaccoon27** [comment]
Are you the real Zuby?

**Comment by zubyCharles** [comment]
> Are you the real Zuby?

I'm definitely not fake

**Comment by dumbuz** [comment]
> Are you the real Zuby?

Are you the real Rocket Raccoon?

**Comment by cs3c** [comment]
> > Are you the real Zuby?
> 
> Are you the real Rocket Raccoon?

Are you the real dumbuz?

**Comment by dumbuz** [comment]
> > > Are you the real Zuby?
> > 
> > 
> > Are you the real Rocket Raccoon?
> 
> Are you the real dumbuz?

Are you the real cs3c?

**Comment by NodeMixaholic** [comment]
> > > > Are you the real Zuby?
> > > 
> > > 
> > > Are you the real Rocket Raccoon?
> > 
> > 
> > Are you the real dumbuz?
> 
> Are you the real cs3c?

is this the real infinite chain?

**Comment by nonetrix** [comment]
Posting from iPhone removes -10 points with how likely you are to be recommend
