### ISSUE TITLE
Enable Discussions

### ISSUE THREAD

**Issue by PickleNik** [twitter/the-algorithm#372]
Enable the Github Discussions feature to keep the Issues more on-topic.

<img width="805" alt="Screenshot 2023-03-31 at 6 00 24 PM" src="https://user-images.githubusercontent.com/31113245/229240807-0e6bdd43-191b-43c2-8d8c-2dfac20915c9.png">

**Comment by PickleNik** [comment]
see what I'm talking about
<img width="654" alt="Screenshot 2023-03-31 at 6 11 54 PM" src="https://user-images.githubusercontent.com/31113245/229241945-47fa46c1-cc41-4251-a7f0-ae23fefc75b2.png">

**Comment by skyrina** [comment]
> see what I'm talking about <img alt="Screenshot 2023-03-31 at 6 11 54 PM" width="654" src="https://user-images.githubusercontent.com/31113245/229241945-47fa46c1-cc41-4251-a7f0-ae23fefc75b2.png">

hey thats me

**Comment by katsuki-yuri** [comment]
agreed!

**Comment by karlrolson** [comment]
Seconding this. Besides we can use it as an offsite every time the main site is offline due to sudden, unscheduled maintenance or unplanned, rapid disassembly.

**Comment by ElijahPepe** [comment]
From my issue:
> There's been a fair bit of decision discussions in the issues section of this repository. As someone who uses GitHub quite a bit, GitHub Issues can be cumbersome to hold discussions over.

> Fortunately, there is a solution here, that being GitHub Discussions. I'm quite a fan of Discussions, and I believe that it would cut back on some of the backlog in the issues section.

**Comment by jdm-twtr** [comment]
We'll consider this in the future, but for now, we'd like to keep the domains we have to monitor as narrow as possible.
