### ISSUE TITLE
Mom, I am famous!

### ISSUE THREAD

**Issue by mkadirtan** [twitter/the-algorithm#374]
Hi guys,
Shameless self-promotion. If you are curious enough to check issues of this repo, go check out my website: 

https://nooptoday.com/

I will add detailed analyses of https://github.com/twitter/the-algorithm/tree/main/trust_and_safety_models part of the algorithm.

**Comment by kxrn0** [comment]
no, dear, you are just making a fool of yourself on the internet

**Comment by michaelhly** [comment]
keep it up!

**Comment by cs3c** [comment]
eyooow eyow eyow

**Comment by mkadirtan** [comment]
> no, dear, you are just making a fool of yourself on the internet

why is that?

**Comment by cs3c** [comment]
Take it easy boyz

**Comment by mkadirtan** [comment]
> Correction: _Mom, I made a failing Wordpress blog, that no one reads, and tried to promote it through an unrelated repository on GitHub._

Wow, why do you hate so much guys? It is just a troll post, I am doing just fine, thanks! And, it is not Wordpress btw.

**Comment by michaelhly** [comment]
@mkadirtan help me get my PR merged!
https://github.com/twitter/the-algorithm/pull/347

**Comment by mkadirtan** [comment]
> @mkadirtan help me get my PR merged! #347

Loool 🤣
That game looks cool though!
