### ISSUE TITLE
Incorrect metrics label calculation for "has_gte_10k_favs"

### ISSUE THREAD

**Issue by vgel** [twitter/the-algorithm#384]
**Describe the bug**
Here, the label "has_gte_10k_favs" is checking against 1000, not 10,000:

https://github.com/twitter/the-algorithm/blob/7f90d0ca342b928b479b512ec51ac2c3821f5922/home-mixer/server/src/main/scala/com/twitter/home_mixer/functional_component/decorator/HomeTweetTypePredicates.scala#L161-L163

**To Reproduce**
1. Read the code
2. Notice that 1000 != 10000
3. [Post it on Twitter](https://twitter.com/voooooogel/status/1641922366304317440)
4. Decide to make an issue in case it actually matters because you feel a lil bad for the Twitter engineers

**Expected behavior**
It should check against 10,000 instead

**Screenshots**
Uh IDK what to put here:
![image](https://user-images.githubusercontent.com/980096/229241788-5dfeb692-4892-4c54-9bac-3479a470f239.png)

**Environment**
Github

**Comment by vgel** [comment]
#577 fixes this

**Comment by kapilepatel** [comment]
Congratulations merged
