### ISSUE TITLE
Surely nothing will go wrong (CLUELESS)

### ISSUE THREAD

**Issue by samdisk11** [twitter/the-algorithm#397]
i predict like a bazillion ai bots will arrive to Twitter that know how to bypass safety filters, now that its public

oh well. 🍿 

![CLUELESS!](https://user-images.githubusercontent.com/24478471/229243649-7aa2b865-31d8-4fe3-b449-99b94198bd3d.png)

**Comment by dumbuz** [comment]
common twitter L

**Comment by samdisk11** [comment]
> common twitter L

fax
