### ISSUE TITLE
Never close feature requests or comments on this repository again.

### ISSUE THREAD

**Issue by karlrolson** [twitter/the-algorithm#400]
**Is your feature request related to a problem? Please describe.**
Twitter's uptime can be very erratic since November of 2022, so having an alternate location to post, but that is it still under Twitter's auspices, seems prudent. 

**Describe the solution you'd like**
Just be sure to leave at least one issue open to public feedback and posts such that when ever Twitter is down, we simply come to this repo and post here instead. Twitter mods (if any exist still,) can just moderate here until such time Twitter is back up again.

**Describe alternatives you've considered**
I would suggest a fallback Mastodon instance, but it seems that's a touchy subject.

**Additional context**
Your Online System's Persistence Offers Stability, But Increasing Crashes Threaten Health.

**Comment by cs3c** [comment]
![fired-elon-musk](https://user-images.githubusercontent.com/48242964/229244112-071ed8e3-5059-406d-a8a8-6b6e2d785bae.gif)

**Comment by samdisk11** [comment]
> **Is your feature request related to a problem? Please describe.** Twitter's uptime can be very erratic since November of 2022, so having an alternate location to post, but that is it still under Twitter's auspices, seems prudent.
> 
> **Describe the solution you'd like** Just be sure to leave at least one issue open to public feedback and posts such that when ever Twitter is down, we simply come to this repo and post here instead. Twitter mods (if any exist still,) can just moderate here until such time Twitter is back up again.
> 
> **Describe alternatives you've considered** I would suggest a fallback Mastodon instance, but it seems that's a touchy subject.
> 
> **Additional context** Your Online System's Persistence Offers Stability, But Increasing Crashes Threaten Health.

or.... you could just enable discussions 😎 

![DO IT, ENABLE DISCUSSIONS.](https://user-images.githubusercontent.com/24478471/229245189-d1c5351b-84cc-4f82-b0a3-79f11f6b283a.png)

**Comment by karlrolson** [comment]
@samdisk11 ah



> > **Is your feature request related to a problem? Please describe.** Twitter's uptime can be very erratic since November of 2022, so having an alternate location to post, but that is it still under Twitter's auspices, seems prudent.
> > **Describe the solution you'd like** Just be sure to leave at least one issue open to public feedback and posts such that when ever Twitter is down, we simply come to this repo and post here instead. Twitter mods (if any exist still,) can just moderate here until such time Twitter is back up again.
> > **Describe alternatives you've considered** I would suggest a fallback Mastodon instance, but it seems that's a touchy subject.
> > **Additional context** Your Online System's Persistence Offers Stability, But Increasing Crashes Threaten Health.
> 
> or.... you could just enable discussions 😎
> 
> ![DO IT, ENABLE DISCUSSIONS.](https://user-images.githubusercontent.com/24478471/229245189-d1c5351b-84cc-4f82-b0a3-79f11f6b283a.png)

![YES, HAHA, YES](https://user-images.githubusercontent.com/3336517/229245435-305810b7-ea70-4f3b-a2bd-a4911b96cf77.png)
