### ISSUE TITLE
Release all source code of Twitter because of AGPL 3.0 ? 

### ISSUE THREAD

**Issue by pylapp** [twitter/the-algorithm#404]
Because this project is under AGPL 3.0, could you prove please how it is linked to the whole Twitter server side sources?

It seems this implementation can be seen as a composition of the backend, or a whole extension to it.

Where are the sources for all of the project?

**Comment by PickleNik** [comment]
cool issue number

**Comment by pylapp** [comment]
Lucky and proud 😂

**Comment by PickleNik** [comment]
⚠️💥⚠️💥⚠️💥⚠️💥⚠️💥⚠️💥⚠️💥⚠️💥

**Comment by pylapp** [comment]
And free Florie!

https://github.com/twitter/the-algorithm/issues/435

**Comment by PickleNik** [comment]
Rightsholders are [not bound by the GPL](https://opensource.stackexchange.com/questions/2077/so-the-gpl-doesnt-restrict-the-creator-of-the-software-in-any-way) tho so this can be closed as not planned.

**Comment by pylapp** [comment]
Aaaaaaaand shit. Forgot that.
Thank you for the reminder.
Still strange to use that license 🤨

**Comment by PickleNik** [comment]
AGPLv3.0 is the strongly protective, makes sense to me :)
![image](https://user-images.githubusercontent.com/31113245/229249041-5f24e7dc-ceda-4013-bfe9-c8a3de644c91.png)

**Comment by pylapp** [comment]
Indeed but who cares about having that project under that license?
If it's for transparency need, just releasing the code in a GitHub repo will be enough because it will be proprietary if no license is defined.

**Comment by PickleNik** [comment]
> Indeed but who cares about having that project under that license? If it's for transparency need, just releasing the code in a GitHub repo will be enough because it will be proprietary if no license is defined.

Releasing without a license would not allow for contributions to be made.

**Comment by pylapp** [comment]
I agree however do you really think they expect contributions? I am not that sure. Twitter is not well known for open source projects, and with that jackass as a boss I have the feeling it's more for washing than something else 🤨

**Comment by PickleNik** [comment]
> I agree however do you really think they expect contributions? I am not that sure. Twitter is not well known for open source projects, and with that jackass as a boss I have the feeling it's more for washing than something else 🤨

[Twemoji](https://twemoji.twitter.com/) is kinda goated tbh

but they have some other stuff too https://opensource.twitter.dev/projects/

**Comment by pylapp** [comment]
Interesting, thanks!

**Comment by nemobis** [comment]
For some context:
* https://www.fsf.org/bulletin/2021/fall/the-fundamentals-of-the-agplv3
* https://www.gnu.org/licenses/gpl-faq.html#AGPLv3InteractingRemotely
* https://copyleft.org/guide/comprehensive-gpl-guidech10.html#x13-970009.16

AGPLv3 is the same license as [Mastodon](https://github.com/mastodon/mastodon) so it was a logical choice. :)

Or maybe it was chosen by Twitter because some companies like Google have a strong anti-(A)GPL stance.

**Comment by pylapp** [comment]
Still strange, no official explanation about this license.
But it is still a good move.
