### ISSUE TITLE
Stop firing employees on Twitter

### ISSUE THREAD

**Issue by MbxrAteeq** [twitter/the-algorithm#408]
Requesting this new feature where Elon can't fire any employee on twitter.

**Comment by kyputer** [comment]
#fundingsecured

**Comment by cs3c** [comment]
![fired-elon-musk](https://user-images.githubusercontent.com/48242964/229244112-071ed8e3-5059-406d-a8a8-6b6e2d785bae.gif)

**Comment by ConnieCommie** [comment]
![image](https://user-images.githubusercontent.com/54904227/229245478-b4effd16-d770-4868-8028-be365cde7c75.png)

**Comment by mnesler** [comment]
Can I write anything I want in here ?
