### ISSUE TITLE
Saul Gone

### ISSUE THREAD

**Issue by ConnieCommie** [twitter/the-algorithm#415]
Two years ago a man came into my office. He said his name was Mayhew. He wanted one of my clients to lie for him under oath. He offered me money. I refused. That night, as I was leaving my office, I was attacked. A bag was shoved over my head, I was hogtied, I was driven out into the desert. And when they pulled the hood off, I was kneeling in front of an open grave with a gun pointed at my head. That was my introduction to Walter White! I was terrified. But not for long. That night, I saw opportunity. A shot at big money. And I grabbed it and I held it tight. And for the next sixteen months, my every waking moment was spent building Walter White's drug empire. So, yeah, I wasn't there when the meth was cooked. I wasn't there when it was sold. I didn't witness any of the murders. But I damn well knew it was happening. I was more than a willing participant. I was indispensable. I kept Walter White out of jail, I laundered his money, I lied for him, I conspired with him, and I made millions. If he hadn't walked into my office that day, Walter White would have been dead or behind bars within a month. And Agent Schrader and Agent Gomez and a whole lot of other people would still be alive. The fact is, Walter White couldn't have done it without me.

**Comment by cs3c** [comment]
![giphy](https://user-images.githubusercontent.com/48242964/229245833-e6e86303-610f-487f-a345-61615094a6be.gif)
