### ISSUE TITLE
[REQUEST] Add a 'Discussions' tab (for the GitHub repository)

### ISSUE THREAD

**Issue by byronbytes** [twitter/the-algorithm#418]
**Is your feature request related to a problem? Please describe.**
A lot of joke/meme issues and pull requests are being created, so why not add a discussions tab for people who have genuine thoughts about the algorithm, and for people to better share their thoughts. It would also be way easier to moderate than issues / PR's.

**Describe the solution you'd like**
Adding the Discussions tab for the repository.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by PickleNik** [comment]
Dup of #372
