### ISSUE TITLE
Rewrite Twitter in Lua

### ISSUE THREAD

**Issue by mathlover2** [twitter/the-algorithm#419]
At this point, you're not going to get anyone to maintain your site in the normal way. Why not take a page out of Roblox's book and have kids code your site for fun/money/whatever? Sure, Roblox may have some ethical issues with how they do this (I honestly haven't fully verified this yet), but since you're the kind of person who doesn't care about morals, you'd probably go ahead and do it anyway.

As a bonus, the site will still fail just as fast if not faster, because no one wants their kid working for you.

**Comment by nikolqy** [comment]
If you mean with tarantool, that would be cool to see

**Comment by NodeMixaholic** [comment]
Bonus points if you have Twitter rewritten in ROBLOX LUA as a ROBLOX experience. ;)

**Comment by ZachCurtis** [comment]
Child labor is key to price reduction at Tesla; why not apply that to twitter?

**Comment by cs3c** [comment]
better be rewritten in Brainfuck

**Comment by Heliodex** [comment]
Let's migrate to Torch, I hear it's a well-maintained library

**Comment by mathlover3** [comment]
lol love how im mathlover3

**Comment by mathlover2** [comment]
> lol love how im mathlover3

Hey there!

**Comment by mathlover3** [comment]
> > lol love how im mathlover3
> 
> Hey there!

hi
