### ISSUE TITLE
Tomato juice

### ISSUE THREAD

**Issue by EoTMrbxscraper** [twitter/the-algorithm#426]
**Is your feature request related to a problem? Please describe.**
I would wish to see more content regarding tomato juice on the platform _Twitter._

**Describe the solution you'd like**
Ideally, the algorithm will be altered to cater for the need of tomato juice enthusiasts around the world rather than engaging in the suppression of tomato juice content.

**Describe alternatives you've considered**
We have considered alternative diets such as fresh eggs and sex toys but none of them simply strike the same as tomato juice.

**Additional context**
Birds love tomato juice.

**Comment by AlexPerathoner** [comment]
🍅🥫

**Comment by Andrej730** [comment]
I think we can consider it solved by @AlexPerathoner.
