### ISSUE TITLE
Unban Chad Loder

### ISSUE THREAD

**Issue by Ashvio** [twitter/the-algorithm#430]
He did nothing wrong and was banned for being against Elon Musk. Twitter has no free speech.

**Comment by Xpenzz** [comment]
Did nothing wrong btw. 

https://twitter.com/MrAndyNgo/status/1611107762775228420

**Comment by Ashvio** [comment]
> Did nothing wrong btw.
> 
> https://twitter.com/MrAndyNgo/status/1611107762775228420

> Andy Ngo as a source

lmao

**Comment by Xpenzz** [comment]
> so because he made some tweets you don't like 2 years ago he should be permabanned? meanwhile actual nazis are unbanned left and right despite plenty of threats of violence. this is purely political and anti free speech.

I couldn't care less about Loder, but it is dishonest to disregard his actions as there is clear evidence that he engaged in behavior that clearly incites violence.

**Comment by Ashvio** [comment]
He did nothing wrong. You might not like what he says but he has a right to
say it. That's the foundation of free speech.

**Comment by Xpenzz** [comment]
> He did nothing wrong. You might not like what he says but he has a right to say it. That's the foundation of free speech.
No, incitement to violence is not protected under free speech laws.

**Comment by Ashvio** [comment]
Why wasnt Chad Loder arrested then if it's illegal? It's almost like you're
full of shit. And if incitement is grounds for banning people from Twitter
than most of the people who got unbanned by Elon should not have.

**Comment by Xpenzz** [comment]
> Why wasnt Chad Loder arrested then if it's illegal? It's almost like you're full of shit. And if incitement is grounds for banning people from Twitter than most of the people who got unbanned by Elon should not have.

Why wasn't I arrested for driving over the speed limit this morning? Just because you do something illegal does not mean you get arrested.

**Comment by Xpenzz** [comment]
>So by that logic I can say you're doing illegal speech by disagreeing with me, and you can't disprove it's illegal because not all crimes are prosecuted. I am versed in constitutional law, unless you're literally directly telling someone to do a crime in person it's not illegal even if you don't like it. Vague statements on Twitter have never been prosecuted.

Not every crime is prosecuted, but it's important to know that not all types of speech are protected by the law. While the First Amendment protects a lot of free expression, there are limits to what's allowed. For instance, if you say something that encourages violence or hate, you could face legal consequences. Even vague statements on Twitter could be seen as encouraging crimes and might get you into trouble. So it's important to be aware of the rules around free speech and not assume that everything is okay just because you said it online.

**Comment by Ashvio** [comment]
Bro really went to chat gpt for legal advice 💀💀💀

**Comment by Xpenzz** [comment]
> Bro really went to chat gpt for legal advice 💀💀💀

Since you were to lazy to do it yourself.

**Comment by Ashvio** [comment]
If it were really illegal to incite violence on Twitter, then trump would
be in prison for his jan 6th tweets.

**Comment by Ashvio** [comment]
and yeah it's called "thinking for yourself" not relying on an AI

**Comment by Xpenzz** [comment]
> If it were really illegal to incite violence on Twitter, then trump would be in prison for his jan 6th tweets.

Did you forget the part where Trump was banned on Twitter because of jan 6?

**Comment by Ashvio** [comment]
did you forget the part where Elon unbanned him because "free speech unless
it violates the law"?

**Comment by Xpenzz** [comment]
> did you forget the part where Elon unbanned him because "free speech unless it violates the law"?
Except Trump served a two-year ban. Loder has only been banned for a few months. But I actually agree with you; I don't think there should be permanent bans.
