### ISSUE TITLE
Real talk .. Markdown support in tweets

### ISSUE THREAD

**Issue by vinnyA3** [twitter/the-algorithm#433]
**Is your feature request related to a problem? Please describe.**
Markdown chads rise up

**Comment by ctjlewis** [comment]
so true

**Comment by NodeMixaholic** [comment]
Yes! Thank you!

**Comment by ffalor** [comment]
They had 8000 employees, and the biggest update they delivered was the ability to edit a tweet.

Don't hold your breath.

**Comment by kyputer** [comment]
Finally, a good issue ![finally](https://media.tenor.com/Ff9pqUUQj0oAAAAC/gordon-ramsay-finally.gif)

**Comment by PickleNik** [comment]
that's not a part of the recommendations algo

**Comment by NodeMixaholic** [comment]
2nd best imo, should come after #444 (yes I have bias)

**Comment by shylaatchison** [comment]
Please let us embed LaTeX for math in our tweets.

Sincerely,
500+ math & econ (+ some other STEM) nerds who want to tweet math at each other lol. I'm 100% serious though. We're dying to be able to do this when we're engaged in econ/econometrics discourse/discussions/teaching/learning.

Make it so only TwitterBlue accounts can use it as new feature, and it's almost certain they (STEM academics/some industry) would subscribe for TwitterBlue to be able to embed LaTeX in their tweets. Literally check these folks out. All used to connect/communicate through the hashtag "EconTwitter" if you need help finding an example of the market for this...

**Comment by jdm-twtr** [comment]
Thanks for filing. We've marked this issue as an unrelated bug or feature for future review.
                    In order to keep our issue count manageable, we will not be leaving these issues open. We apologize for
                    the inconvenience. If you feel that we closed your issue in error, please re-file the issue, stating how
                    the requested feature applies to the recommendation algorithm components that have been open-sourced thus far.
