### ISSUE TITLE
Rewrite this in Luau

### ISSUE THREAD

**Issue by TheSkyLookingGood** [twitter/the-algorithm#440]
[Luau](https://luau-lang.org) is a scripting language developed by Roblox for creating games. It is inspired by Lua 5.1, but it has some distinctive features, such as faster performance, smaller size, safer code, and gradual typing.

**Comment by PickleNik** [comment]
Luwu

**Comment by regginator** [comment]
vouch, implemented with [lune](https://github.com/filiptibell/lune) runtime!

**Comment by s0mt0chukwu** [comment]
> [Luau](https://luau-lang.org) is a scripting language developed by Roblox for creating games. It is inspired by Lua 5.1, but it has some distinctive features, such as faster performance, smaller size, safer code, and gradual typing. 

Are you freaking kidding??

**Comment by samdisk11** [comment]
> vouch, implemented with [lune](https://github.com/filiptibell/lune) runtime!

REGGIE???

**Comment by iratenebrarum** [comment]
Holy shit

**Comment by nonbinarypotus** [comment]
i agree
