### ISSUE TITLE
Add ActivityPub open standard protocol and compliance to join the Fediverse

### ISSUE THREAD

**Issue by ingochris** [twitter/the-algorithm#446]
![image](https://user-images.githubusercontent.com/2686679/229246984-e7c0500a-b528-4215-a12a-c56a7ecd32f9.png)

**Comment by TheSkyLookingGood** [comment]
LGTV! no one needs this

**Comment by JeremyStarTM** [comment]
@TheSkyLookingGood nobody needs you too

**Comment by NodeMixaholic** [comment]
Turns out great minds think alike, see isssue #444

**Comment by TheSkyLookingGood** [comment]
> @TheSkyLookingGood nobody needs you too

The air is falling to your home

**Comment by AzumWatson** [comment]
66666666666666666666666666666

**Comment by NodeMixaholic** [comment]
> LGTV! no one needs this

Maybe you don't need this, but the world does. Also, open Twitter. See #444

**Comment by s0mt0chukwu** [comment]
> > LGTV! no one needs this
> 
> Maybe you don't need this, but the world does. Also, open Twitter. See #444 

No 


Let Twitter be as it is and Mastodon the same way .

**Comment by Sqaaakoi** [comment]
i can't tell what's parody and what's techbros wanting the fediverse to be a little more friendly to migrate to and a little more shit

**Comment by gunchleoc** [comment]
Please include account migration in the implementation too, so people can move off failing servers.

**Comment by jdm-twtr** [comment]
This issue was closed due to possibility of spam. Please re-file with a useful title and description.
