### ISSUE TITLE
Thanks to all the trolls, we made history.

### ISSUE THREAD

**Issue by cs3c** [twitter/the-algorithm#450]
.yrotsih edam ew ,sllort eht lla ot sknahT
.yrotsih edam ew ,sllort eht lla ot sknahT
.yrotsih edam ew ,sllort eht lla ot sknahT
.yrotsih edam ew ,sllort eht lla ot sknahT
.yrotsih edam ew ,sllort eht lla ot sknahT
.yrotsih edam ew ,sllort eht lla ot sknahT
.yrotsih edam ew ,sllort eht lla ot sknahT
.yrotsih edam ew ,sllort eht lla ot sknahT

**Comment by ConnieCommie** [comment]
Bozja
