### ISSUE TITLE
the voices are getting louder.

### ISSUE THREAD

**Issue by spookyvert** [twitter/the-algorithm#455]
deez nuts

**Comment by AlexPerathoner** [comment]
Possibly related to

https://twitter.com/anothercohen/status/1633110778147491851?s=46&t=3wunRQnDEQbtkdz033Y_9Q

**Comment by jdm-twtr** [comment]
This issue was closed due to one of these reasons: likelihood of spam, not enough context, or possibly inappropriate content. Please re-file with a useful title and description.
