### ISSUE TITLE
Pull requests closed

### ISSUE THREAD

**Issue by loevlie** [twitter/the-algorithm#456]
Why were all pull requests closed?  I understand there are plenty of troll ones but I had a legit change.

**Comment by spookyvert** [comment]
What was it

**Comment by aaronmondal** [comment]
The previous main branch was force pushed, triggering a bot to autoclose all PRs. To port your commit to the new main:

- Reset your GitHub fork.
- Switch to your local main.
- Delete the local main (only the branch, not the entire repo).
- Rebase pull the new upstream into the local main.
- From the new main, switch to a new branch.
- Cherry pick your commit from the outdated (detatched) branch.
- Re-sign the commit. The old signature will be invalid.
- Push it onto GitHub.
- Reopen the PR.

**Comment by jdm-twtr** [comment]
Sincere apologies for the inconvenience. We're happy to review the PR after it's been rebased. Thank you!

Thanks @aaronmondal for clarifying.

**Comment by loevlie** [comment]
@jdm-twtr I added it back into the pull requests (#539).  Please check it out!  Thank you (:
