### ISSUE TITLE
Has anyone tested this in Internet Explorer?

### ISSUE THREAD

**Issue by jimmynova** [twitter/the-algorithm#460]
**Describe the bug**
We've had some concerns voiced by a legacy client located in Florida who refuses to upgrade from Internet Explorer 7.

**To Reproduce**
1. Access a machine that hasn't been updated since 2006.
2. Click anywhere. 
3. Ensure "legacy client" won't send out angry tweets about their computer being "loaded with Chinese viruses" when the site doesn't load.

**Comment by scottbeamer** [comment]
Probably should make sure the user can't throw ketchup at it, either.
