### ISSUE TITLE
License.md missing

### ISSUE THREAD

**Issue by dabockster** [twitter/the-algorithm#462]
**Describe the bug**
There is no License.md file present or other indications of what licensing The Algorithm code falls under.

**To Reproduce**
- Try to find a license.
- Find none.

**Expected behavior**
There should be Licensing information present somewhere in the root directory of the repository. Either in the Readme.md file or in a separate License.md file.

**Additional context**
Having a License.md file is important because it gives developers on GitHub and other platforms notice of Twitter's licensing intent effectively at a glance.

**Comment by dabockster** [comment]
I just saw the COPYING.MD file. Maybe rename it to LICENSE.MD?

**Comment by PickleNik** [comment]
`COPYING` and `LICENSE` are used pretty much interchangeably.
The FSF has [a guide on how to use the GPL](http://www.gnu.org/licenses/gpl-howto.html), which suggests `COPYING`

Github recognizes both
<img width="329" alt="Screenshot 2023-03-31 at 7 23 32 PM" src="https://user-images.githubusercontent.com/31113245/229249282-3f3de02e-570c-42b9-b781-36a850bdb87b.png">

**Comment by PickleNik** [comment]
can be closed as not planned I assume

**Comment by AlexPerathoner** [comment]
Copying > following licenses

**Comment by jdm-twtr** [comment]
@PickleNik is correct; `COPYING` is the appropriate filename. Thanks for clarifying @PickleNik!
