### ISSUE TITLE
Can someone donate me 1 ETH

### ISSUE THREAD

**Issue by sethyron** [twitter/the-algorithm#467]
0x40dc770aD82A417f8F4aDF5e11687B13DEf7044D

**Comment by yani** [comment]
I can only donate 1 BTC :\

Next time bro!

**Comment by IdrissaN** [comment]
Yes, I can donate you ... 0 ETH

**Comment by eduardocesb** [comment]
:no:

**Comment by Noah670** [comment]
How about Chainlink

**Comment by yuk1c** [comment]
now donate me 0x33A109Ae4B7d77A105968Fb0aE6A9d69cd723Ed2
