### ISSUE TITLE
Rewrite in Rust

### ISSUE THREAD

**Issue by hooverdc** [twitter/the-algorithm#47]
The Algorithm as it stands is unsafe.

**Comment by sunglocto** [comment]
This should happen immediately.

**Comment by CableSynth** [comment]
Absolutely

**Comment by migueldeicaza** [comment]
+1

**Comment by mutexdeveloper** [comment]
Very high priority issue!

**Comment by PythonSnake-lang** [comment]
[reddit meme](https://www.reddit.com/r/ProgrammerHumor/comments/127vksn/rust_boys_at_it_early/)
