### ISSUE TITLE
meow

### ISSUE THREAD

**Issue by annasajkh** [twitter/the-algorithm#471]
i'm a cat pet me

**Comment by kyputer** [comment]
*pets @annasajkh*

**Comment by Xefise** [comment]
meow, pet me too ^_^

**Comment by kyputer** [comment]
*pets @Xefise* yall needy af

**Comment by michaelhly** [comment]
i pooped, pet meee too 🥺 
![pooped](https://i.imgur.com/Btw9CPn.jpg)

**Comment by skyrina** [comment]
pet me too

**Comment by kyputer** [comment]
*pets @skyrina*

**Comment by skyrina** [comment]
thank you

**Comment by annasajkh** [comment]
> _pets @annasajkh_

*purr purr*

**Comment by AlexPerathoner** [comment]
Possibly related to #474
Please mark as duplicate

**Comment by jSagvold28** [comment]
lol

**Comment by RFS-ADRENO** [comment]
pet @annasajkh

**Comment by jdm-twtr** [comment]
This issue was closed due to one of these reasons: likelihood of spam, not enough context, or possibly inappropriate content. Please re-file with a useful title and description.
