### ISSUE TITLE
Rewrite it in Rust.


### ISSUE THREAD

**Issue by nwithan8** [twitter/the-algorithm#473]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when something isn't written in Rust.

**Describe the solution you'd like**
Rewrite it in Rust.

**Describe alternatives you've considered**
There is no alternative to rewriting it in Rust.

**Additional context**
Rust.

**Comment by Lamby777** [comment]
Yes. Luckily, I already finished all of it! Opening a PR if that's alright.

```rs
use twitter_recommendations::start_recommendation_service;

fn main() -> Result<(), Box<dyn std::error::Error>> {
    start_recommendation_service()?;
}
```

**Comment by luccahuguet** [comment]
this is the way

**Comment by aerphanas** [comment]
pr #583

**Comment by RafaBlockDev** [comment]
Write all that sht bro, tf ☠️

**Comment by oovm** [comment]
Firstly, we can rewrite from leftover [twml](https://github.com/twitter/the-algorithm/tree/main/twml) and merge these functions into [navi](https://github.com/twitter/the-algorithm/tree/main/navi), thus removing all c++ code.

I'm researching what is the Earlybird Light Ranking Model.
