### ISSUE TITLE
this is my cat

### ISSUE THREAD

**Issue by shasherazi** [twitter/the-algorithm#474]
![IMG_20230326_140154_352.jpg](https://user-images.githubusercontent.com/63230301/229250053-f1c1a42d-1b71-467d-a948-5c9d86de608d.jpg)

**Comment by PickleNik** [comment]
thank you

**Comment by kyputer** [comment]
Nice cat!

**Comment by yurixander** [comment]
Absolutely beautiful. Thank you for this!

**Comment by juraisa** [comment]
Nice cat

**Comment by egehanyorulmaz** [comment]
Someone should open a paw request!

**Comment by odnoyabr** [comment]
i like this cat

**Comment by kolezka** [comment]
That is my Edward!
![image](https://user-images.githubusercontent.com/24277846/229251397-11211aa4-bbea-48e4-be44-20cfe2e373af.png)

**Comment by kyputer** [comment]
I LOVE EDWARD

**Comment by JamBlumberg** [comment]
Who needs Twitter when you have GitHub issue comment threads? This is way more pleasant. Also: cat. Her name is Issun. 

![IMG_2170](https://user-images.githubusercontent.com/17389070/229251701-8fbceaf5-1c33-4e79-843b-9d809eee89c3.jpeg)

**Comment by kyputer** [comment]
MOAR CAT PICS PLS

**Comment by odnoyabr** [comment]
this is little man

![lman](https://user-images.githubusercontent.com/86575097/229251925-549d7ff7-e575-4cb8-b91a-fec4a4e8bbe7.jpg)

he is not my cat but he is a pretty good cat and i like to give him pets

**Comment by TheVerl** [comment]
so cute :-)

**Comment by kyputer** [comment]
incredible

**Comment by PickleNik** [comment]
Please pin this issue please
<img width="175" alt="Screenshot 2023-03-31 at 7 58 21 PM" src="https://user-images.githubusercontent.com/31113245/229252158-bc4ca07c-3904-41bf-85f1-a87ef7c54cf8.png">

**Comment by odnoyabr** [comment]
this is my friends cat manai

![manaicat](https://user-images.githubusercontent.com/86575097/229252304-4ee1e37b-a2cb-4fa8-a44f-f7941df0d517.jpg)

manai is also a good cat and enjoys bags. look at all the twitter logos on that bag. twitter loves manai

**Comment by mel-haya** [comment]
![1680307307668](https://user-images.githubusercontent.com/62703415/229254309-e19204f5-32df-4d03-8b91-b92fd43b5866.jpg)

this is fifi

**Comment by Cyproximity** [comment]
https://user-images.githubusercontent.com/10617269/229255088-11b490b7-3d3c-4a04-91a9-bf828ed25875.mov

this is my cat, charcoal 🐈‍⬛ 🐈

**Comment by anguswww** [comment]
mfw cat 😁😁😁😁

**Comment by jdoss** [comment]
[]()![PXL_20230331_150302313.jpg](https://user-images.githubusercontent.com/8195/229255192-625a4cdb-1e12-402a-8c7c-cf238c858eb4.jpg)

This is Tibby who is 14 years old and just got diagnosed with the kitty diabetes. She's having a hard time but she's still a pretty kitty.

**Comment by AhmadSleimanR** [comment]
very cute kitten!

**Comment by yzhuang** [comment]
![_DSC1179](https://user-images.githubusercontent.com/423730/229255754-f943d7d9-3ba9-4b57-ba7c-f5cc3a79d1ef.jpg)

**Comment by Tomyk9991** [comment]
![image](https://user-images.githubusercontent.com/18402332/229256277-1e0c131d-623d-404d-8e57-47413449d29e.png)

**Comment by hdntc** [comment]
it took me like 15 seconds to load on my 1MB/s connection but it was worth it

**Comment by DCRM-dev** [comment]
![IMG_20230224_160148](https://user-images.githubusercontent.com/65412055/229256423-edec498c-992d-4611-95d7-6eb7708e6114.jpg)
This is Rio

**Comment by AL1L** [comment]
![image](https://user-images.githubusercontent.com/8514986/229256442-0994b603-7fd4-4b84-bb88-6859715a71ba.png)
This is **Charlotte Lantz** (left) and **Penelope "Penny" Evdokia Lantz** (right)

**Comment by obiwantoby** [comment]
![Uploading 70162214444__7667F99A-A693-4CED-BB08-F40B456A4F51.jpeg…]()

**Comment by sasdallas** [comment]
very cool cats :)

**Comment by AlexPerathoner** [comment]
Where is Rupert??

Btw this is Figaro:
![image](https://user-images.githubusercontent.com/31958579/229257307-e866b4ce-b072-4b8d-b61c-7969a53e6dbd.jpeg)

**Comment by feuerrot** [comment]
![20220624235134_IMG_0031](https://user-images.githubusercontent.com/150068/229257376-7bb4e7f6-7771-43a3-b1ab-f860a92c19cd.JPG)

**Comment by misterjacko** [comment]
My cats! ![My cats](https://user-images.githubusercontent.com/28715467/229257533-e00d6865-ce42-4a8a-bd7c-3efbea1e0bfd.jpeg)

**Comment by LiterallyANoodle** [comment]
I love this animals! (the yote)
![image](https://user-images.githubusercontent.com/34174088/229258203-07995970-e16d-463b-a0a7-48b0b2103df7.png)

**Comment by nwunderly** [comment]
best issue

**Comment by gabek** [comment]
+1

**Comment by Bezbakri** [comment]
> best issue

I agree

**Comment by PickleNik** [comment]
> Please pin this issue please <img alt="Screenshot 2023-03-31 at 7 58 21 PM" width="175" src="https://user-images.githubusercontent.com/31113245/229252158-bc4ca07c-3904-41bf-85f1-a87ef7c54cf8.png">

^^ https://github.com/twitter/the-algorithm/issues/474#issuecomment-1492738707 🙏

**Comment by matoruru** [comment]
Cute😀

**Comment by EMallmann** [comment]
![Critter Photo](https://user-images.githubusercontent.com/10477181/229259410-7a7da456-ed22-40a5-9a6e-11c6525c9018.jpg)

**Comment by VinnisVidya** [comment]
omg cat

**Comment by Carpetfizz** [comment]
![image](https://user-images.githubusercontent.com/2084896/229259812-f2cae3d1-04c2-4f3b-82e9-c65a5594f774.jpeg)

**Comment by jerryvu26** [comment]
![20181220_151956.jpg](https://user-images.githubusercontent.com/36879694/229260489-14d9c9d9-b4fb-4c62-a669-962e22f91fb7.jpg)

**Comment by deni64k** [comment]
Meowllow everyone!
![image](https://user-images.githubusercontent.com/107541/229260816-ddc9d214-87a2-4602-b275-6ac60d5ec53a.png)

**Comment by Codfish246** [comment]
meow
![IMG_8630](https://user-images.githubusercontent.com/23464269/229260869-287044a6-f84f-4dff-ab89-27aee3df513e.jpg)

**Comment by dbanksdesign** [comment]
This is my cat ![PXL_20230331_062427986.jpg](https://user-images.githubusercontent.com/321279/229261724-57d54081-f32d-440a-bf4b-af103b21eff4.jpg)

**Comment by erin-bristow** [comment]
cat!

![774F3AF3-909E-453A-9DDA-AB58DA666F78](https://user-images.githubusercontent.com/54862937/229261934-708ffb76-5d4b-4dec-8818-19ce82ba1397.jpg)

**Comment by erin-bristow** [comment]
lil foster cats.

![IMG_5482](https://user-images.githubusercontent.com/54862937/229262256-60fc0018-811b-484e-98c3-1f172dc4a840.jpg)

**Comment by rmajoewsky** [comment]
![IMG_4759 (1)](https://user-images.githubusercontent.com/128773262/229263119-645208f4-7f5e-49ed-89d9-a05a823a3e46.JPG)

This is Ozzy

**Comment by kshay** [comment]
Could not reproduce

**Comment by kennethsequeira** [comment]
> Could not reproduce

You shouldn't have spayed/neutered the cat. Though it is a recommended practice to prevent cancer in cats and as a general population control measure.

**Comment by WardPearce** [comment]
![Snapchat-162917488](https://user-images.githubusercontent.com/27844174/229265151-1647c3df-acb6-4611-9662-ab8569c1037d.jpg)
Here are my two adorable Kittens

**Comment by PickleNik** [comment]
> Could not reproduce

works on my machine, idk ¯\\_(ツ)_/¯

**Comment by hisashiburii** [comment]
i can't speak meow whats the exact issue here?

**Comment by jcsumlin** [comment]
![20230309_155041.jpg](https://user-images.githubusercontent.com/3067479/229265806-616d854e-efb0-4a7d-8eb3-08b9c03de524.jpg)

He's a little goofy

**Comment by SympathyTea** [comment]
this is the best github issue of all time

**Comment by aerphanas** [comment]
![DSC_0150](https://user-images.githubusercontent.com/61340494/229266461-29a37e69-0bbc-4fc8-a91c-902e052af18a.JPG)
My cat looks different

**Comment by GermanNr4** [comment]
![IMG_20230324_073053.png](https://user-images.githubusercontent.com/54066349/229266527-8bb24ab8-b051-405b-9314-b895f6f52793.png)

Cats offically supported by Windows

**Comment by y0nei** [comment]
![IMG_20230324_161051.jpg](https://user-images.githubusercontent.com/23276734/229267367-fc29324d-510c-4c79-89b3-e9b17fb57496.jpg)

This is mine!

**Comment by y0nei** [comment]
> ![20181220_151956.jpg](https://user-images.githubusercontent.com/36879694/229260489-14d9c9d9-b4fb-4c62-a669-962e22f91fb7.jpg)

Majestic

**Comment by kennethsequeira** [comment]
Loving this thread XD. 

Calling it Meowtter or something

**Comment by ayush-py-dev** [comment]
I love cats 😺

**Comment by ngoomie** [comment]
I think I'm experiencing something similar? Not quite sure how to explain it, so here's a picture of what happened for me:
![20230305_081432](https://user-images.githubusercontent.com/50791600/229267883-d4bcf323-821e-4096-80c5-76bac195776d.jpg)

**Comment by sekoku** [comment]
Twitter should have all non-cat posts be delayed for 24 hours in observation of "Caturday."

**Comment by heygema** [comment]
![20230327_152607.jpg](https://user-images.githubusercontent.com/10743728/229269397-91874b10-0d74-4561-bfdb-fb67b0ac5eb0.jpg)

Fancy

**Comment by thomasfr** [comment]
This is my Feline Catipede
![IMG_4893](https://user-images.githubusercontent.com/287432/229270000-75d9bc98-3449-4918-bb8e-4335e5519f40.jpeg)

**Comment by Mikael-Lovqvist** [comment]
![20230401_085031](https://user-images.githubusercontent.com/78562170/229270626-1ca2c2b9-3e9d-4830-be90-d1f29e67a7c2.jpg)
This is Tuss

**Comment by mjguzik** [comment]
This is my Elon:

![Elon](https://user-images.githubusercontent.com/9325157/229271776-9c22bb92-2c3b-454a-94f0-2ed3b8f44bdc.png)

**Comment by aerphanas** [comment]
> 

a cat with a weird nose

**Comment by invakid404** [comment]
![20230330_233747.jpg](https://user-images.githubusercontent.com/38114607/229278811-95315706-b07c-409e-a91e-f814e995b8bc.jpg)

**Comment by twolodzko** [comment]
LGTM

**Comment by iopq** [comment]
![IMG20230321175721](https://user-images.githubusercontent.com/1817528/229280762-2960d538-da9c-4afa-8f11-006c40a0390e.jpg)

Twitter is down so I'll just leave this here

**Comment by pikesley** [comment]
![PXL_20230330_175703030](https://user-images.githubusercontent.com/885973/229281097-cf1a78ce-1e37-4f2d-abfb-ce3c3bce3be1.jpg)

**Comment by ianrenton** [comment]
![IMG_20200904_070118928-edited (1).jpg](https://user-images.githubusercontent.com/503149/229284723-04880ab3-172b-4cf7-a356-5994f7586e63.jpg)

**Comment by RFC2795** [comment]
This is Bartlett 
![IMG_20150712_182110](https://user-images.githubusercontent.com/20264032/229286184-3e22d70c-d245-4173-ace3-69720cf33c09.jpg)

**Comment by RAKtheUndead** [comment]
![DSC_1014](https://user-images.githubusercontent.com/82216160/229286855-a9f4777e-8d10-4ba1-8bc7-737e6882215d.JPG)

**Comment by ronnieeeeee** [comment]
![cat](https://user-images.githubusercontent.com/60412984/229288269-7cfd3217-ae9d-4b21-b618-9cf1dd39e45e.png)

**Comment by ajmalabubakkr** [comment]
![20230401_162835.jpg](https://user-images.githubusercontent.com/76244282/229288726-ace98f52-c996-4eb2-942a-46c2fe9f6601.jpg)

My guys look different 😍

**Comment by chrisale** [comment]
![image](https://user-images.githubusercontent.com/1987081/229289780-9977903a-817a-4396-8205-0831be2a8167.jpeg) Whiskers says Good Morning

**Comment by AlexPerathoner** [comment]
Figaro is back

![image](https://user-images.githubusercontent.com/31958579/229295279-8e12ee65-b3a7-491f-9886-1ca99e54c429.jpeg)

**Comment by sanjit-sinha** [comment]
![IMG_20230331_201918_585](https://user-images.githubusercontent.com/72181891/229295653-0a95595d-5480-4b97-8903-531496842f7d.jpg)

**Comment by teq-thinhtruong** [comment]
My cat is very satisfied
![B5051DDB-A915-4699-BA08-9C91FA3CB615_1_105_c](https://user-images.githubusercontent.com/112850514/229299645-e70fa7d9-0596-4950-a8e2-aa8c8fe08350.jpeg)

**Comment by sharunkumar** [comment]
This issue has become a better social network than Twitter

**Comment by binhnguyen7tiki** [comment]
This is Mice
![IMG_8662](https://user-images.githubusercontent.com/106587573/229304068-928857e8-29cc-4a2e-88ec-36119647a856.jpg)

**Comment by MuhtasimTanmoy** [comment]
## Hello from Archie 🐱
![IMG_2047](https://user-images.githubusercontent.com/19208687/229308252-b6e0397f-5922-48a5-949d-ecb9ff82d003.jpg)

**Comment by jdnichollsc** [comment]
This is Kiara, my partner in crime! ❤️

![IMG_20210125_195558_429.jpg](https://user-images.githubusercontent.com/2154886/229308699-cbd50012-cfbe-4d75-b77b-41a663ef2814.jpg)

**Comment by AlexandraKlein** [comment]
I’m still experiencing this issue. 

![Uploading F3519C43-4C47-40C4-B833-3C465747D1FD.jpeg…]()

**Comment by sharunkumar** [comment]
![image](https://user-images.githubusercontent.com/715417/229310790-ebd24031-9fbd-4d26-bb18-51928fdf2ca1.png)
Coco and Fluffy

**Comment by dasayan05** [comment]
LGTM

**Comment by yasufumi-nakata** [comment]
Good!!!!

**Comment by MatGalos** [comment]
Love the issue comment thread, keep it up <3

**Comment by ThatsNoMoon** [comment]
Arya says hi
![Brown tabby](https://user-images.githubusercontent.com/25443950/229322608-84ddb103-ef60-4855-8dc7-c6306b135741.JPG)

**Comment by codetheweb** [comment]
![image](https://user-images.githubusercontent.com/7410405/229328376-3526d5d8-8dd8-4e82-bac4-6963fa9bdbf2.jpeg)

**Comment by aaronsdevera** [comment]
he is interested ![image](https://user-images.githubusercontent.com/5042762/229328409-d202aec4-3112-4745-bc48-a8459002afdd.jpeg)

**Comment by callmethor** [comment]
![IMG_20230402_175349](https://user-images.githubusercontent.com/54652206/229364237-5007161d-8d69-4b17-8f7b-fc526febf431.jpg)
I need this cat

**Comment by toshitanian** [comment]
Her name is Chouchou ❤️

![9F96EE9F-D0F4-4C55-B9A2-5D007FF5D3E8](https://user-images.githubusercontent.com/1647045/229498305-cf2b57b5-6696-475c-bf1b-ef77bca5ffb3.jpeg)

**Comment by ntthaibk** [comment]
This is my Cat Cá Ngu
![IMG_3088](https://user-images.githubusercontent.com/62538035/229722694-5db977f5-69a4-42e2-9fc0-4d548ce602a8.JPG)

**Comment by gokhanamal** [comment]
Berlin and Diana ❤️‍🔥
![image](https://user-images.githubusercontent.com/21364542/229879703-ab0cb0a5-72ef-4ede-b89a-261ad5acb052.jpeg)

**Comment by theresnotime** [comment]
This is neither a cat, _nor_ is it mine, but:

![image](https://user-images.githubusercontent.com/375162/229880752-ed415b88-217a-40ed-8ad5-7e4a8038b179.png)

**Comment by Alekuso** [comment]
Not mine, but I like this fox

![Picture of a fox smiling](https://user-images.githubusercontent.com/48645888/229897979-dd4f2c4b-6370-4fa6-9d3f-e522e957c524.png)

**Comment by erikiva** [comment]
![image](https://user-images.githubusercontent.com/13215331/229954629-5928e5f4-97d7-4465-88aa-3012f30d8fb8.jpeg)

**Comment by tellthemachines** [comment]
![Charlie](https://user-images.githubusercontent.com/8096000/229956033-1048cbdb-0f94-415d-992e-f6cbe8b1899c.jpg)
My sweet little girl

**Comment by dangvansam98** [comment]
Bob :"

![IMG_7337](https://user-images.githubusercontent.com/45785880/229968259-5874f6f6-b6c2-4a87-8af9-9cf7281f1932.jpg)

**Comment by cetinahmetemre** [comment]
![621849A7-817C-4D79-AE4B-E3484A6426EB](https://user-images.githubusercontent.com/16050880/230077047-c6635c3b-49e8-48a2-bdbf-521b906345cc.jpeg)

**Comment by cetinahmetemre** [comment]
Ezel is reading comments :)
![1FC28052-5B5D-4C31-AB35-B6D4EA49EFD3](https://user-images.githubusercontent.com/16050880/230079339-c41059d8-973f-4771-9200-21ddc60dbecd.jpeg)

**Comment by xWass** [comment]
I have come to revolt against this thread with a picture of my dog! this is now dog thread.
![IMG_0336](https://user-images.githubusercontent.com/73602180/230090989-b8475c4e-7a69-49ac-ba65-0aaa9e36f09f.jpg)

**Comment by mochaaP** [comment]
@dangvansam98: wow, Keychron K6 user :P

**Comment by blkpws** [comment]
Status update... he's sleeping right now.

![rn_image_picker_lib_temp_4cc761ac-e2ee-4fe6-b971-f0c5242af132](https://user-images.githubusercontent.com/12381669/231054638-e071a46a-b72d-4fd9-8b05-80fe15082ac4.jpg)

**Comment by vovsemenv** [comment]
my cutie 
![image](https://user-images.githubusercontent.com/20096510/231114571-e51bd5cc-1e80-4a02-baef-a4229620fdd8.png)

**Comment by mochaaP** [comment]
![PXL_20230422_095104029.jpg](https://user-images.githubusercontent.com/21154023/233783866-f5f1b37a-ee2e-4a06-822e-4bf8e48824de.jpg)

meow 🐱

**Comment by yuk1c** [comment]
cute cats

**Comment by PickleNik** [comment]
so true

**Comment by pascalpuffke** [comment]
![Untitled-1](https://github.com/twitter/the-algorithm/assets/30622888/525efa95-b537-46c9-9e13-e2f6cf29246b)

This is Kasi. He is not very smart

**Comment by Alekuso** [comment]
> This is Kasi. He is not very smart

Maybe not very smart, but he is, in fact, a very cute cat.

**Comment by Codfish246** [comment]
i love that this is still going a bit, here's another picture of my cat 😸
![IMG_5067](https://github.com/twitter/the-algorithm/assets/23464269/2ca42356-fb5c-4598-bc88-da965946bf37)

**Comment by SereneRuby12** [comment]
My 2 cats :cat2:
![IMG_20230829_142200](https://github.com/twitter/the-algorithm/assets/20376110/4a0c08e8-24cd-422b-94e1-9961f5920721)

**Comment by egeres** [comment]
My dad took an amazing picture of fusi
![image](https://github.com/user-attachments/assets/762b0bb9-9b20-4d8f-af11-58092ceeb983)

**Comment by GReturn** [comment]
hey man I'd like to see more of this cat

**Comment by egeres** [comment]
Which one @GReturn ??

**Comment by GReturn** [comment]
> Which one @GReturn ??

would love to see all

**Comment by trustablenewbie** [comment]
this is my picture of a fucked up looking loaf
![0-02-05-d7a03bd0a212c3d7ffa1293a485c8d5d0a8499eb03f3a5cd17487239727f1a91_dbf9c5773793fccc](https://github.com/user-attachments/assets/0d24793a-6f51-4368-9aae-2e05836591f0)
