### ISSUE TITLE
Need MFA number

### ISSUE THREAD

**Issue by abetwothree** [twitter/the-algorithm#477]
**Describe the bug**
I needed to log in but I don't know where my MFA number was sent

**To Reproduce**
1. Go to login
2. Click on submit button
3. Scroll down to next page
4. See page waiting for MFA number

**Expected behavior**
I need to receive my MFA number

**Screenshots**
![image](https://user-images.githubusercontent.com/1899636/229250410-872a9343-3d3b-42cb-b8d3-d1975a32165c.png)

**Environment**
My living room

**Additional context**
I just want to see news and events going on

**Comment by PickleNik** [comment]
Tweet this @TweeterSupport, this is a recommendation algo repo lol

**Comment by jdm-twtr** [comment]
Thanks for filing. We've marked this issue as an unrelated bug or feature for future review.
                    In order to keep our issue count manageable, we will not be leaving these issues open. We apologize for
                    the inconvenience. If you feel that we closed your issue in error, please re-file the issue, stating how
                    the requested feature applies to the recommendation algorithm components that have been open-sourced thus far.
