### ISSUE TITLE
Improved NSFW detection for non-Western languages

### ISSUE THREAD

**Issue by 0xEbrahim** [twitter/the-algorithm#483]
I've noticed that the current NSFW detection models in the repository have some limitations when it comes to detecting explicit or sensitive content in non-Western languages, such as Chinese, Japanese, or Korean.

As a Twitter user and developer, I think it's important that the NSFW detection models are able to accurately detect potentially harmful or inappropriate content across different languages and cultures. Many Twitter users are located in countries where non-Western languages are the primary mode of communication, and current models may not be able to accurately identify NSFW content in those languages.

I propose that the Twitter Trust and Safety team explore ways to improve NSFW detection for non-Western languages, potentially by incorporating more diverse training data and improving the models' natural language processing capabilities.

Improved NSFW detection in non-Western languages would help to promote a safer and more inclusive environment on Twitter, and would be a valuable addition to the repository's existing models. Thank you for your consideration!

**Comment by sagehawk** [comment]
Would there be a list of some kind we could just add words to from other languages?

**Comment by sagehawk** [comment]
I can help gather a dataset of NSFW text in foreign languages :)

**Comment by Terebi1996** [comment]
Any evidence that shows " current NSFW detection models in the repository have some limitations when it comes to detecting explicit or sensitive content in non-Western languages" ?

**Comment by WakeUpYoimiya** [comment]
Any evidence that shows " current NSFW detection models in the repository have some limitations when it comes to detecting explicit or sensitive content in non-Western languages" ?

**Comment by jdm-twtr** [comment]
Thanks for filing. We've marked this issue as an unrelated bug or feature for future review.
                    In order to keep our issue count manageable, we will not be leaving these issues open. We apologize for
                    the inconvenience. If you feel that we closed your issue in error, please re-file the issue, stating how
                    the requested feature applies to the recommendation algorithm components that have been open-sourced thus far.
