### ISSUE TITLE
Add priority to users with a cat on their avatar

### ISSUE THREAD

**Issue by Xefise** [twitter/the-algorithm#486]
Meow ^_^
![image](https://user-images.githubusercontent.com/45072628/229251289-fb7fcedb-e6d7-4a40-84c9-05350b6031fb.png)

**Comment by Codfish246** [comment]
much needed feature 😸

**Comment by jdm-twtr** [comment]
This issue was closed due to possibility of spam. Please re-file with a useful title and description.
