### ISSUE TITLE
why are racists still on twitter

### ISSUE THREAD

**Issue by ItzSwirlz** [twitter/the-algorithm#487]

**Comment by dylanjamesdev** [comment]
its not like there's not an obvious answer to this

**Comment by farazkaleemmalik** [comment]
>ubuntu cinnamon lead
lol

**Comment by Sqaaakoi** [comment]
because elon dont care about hate speech he loves free speech

**Comment by jdm-twtr** [comment]
This issue was closed due to lack of useful description.
