### ISSUE TITLE
Rewrite it in ActionScript

### ISSUE THREAD

**Issue by HolyNetworkAdapter** [twitter/the-algorithm#492]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when something isn't written in ActionScript.

**Describe the solution you'd like**
Rewrite the entire algorithm in ActionScript.

**Describe alternatives you've considered**
No alternatives. Rewrite it in ActionScript.

**Additional context**
Rewrite in ActionScript. Rewrite in ActionScript. Rewrite in ActionScript. Rewrite in ActionScript. Rewrite in ActionScript. Rewrite in ActionScript. Rewrite in ActionScript. Rewrite in ActionScript. Rewrite in ActionScript. Rewrite in ActionScript. Rewrite in ActionScript. Rewrite in ActionScript. Rewrite in ActionScript. Rewrite in ActionScript. Rewrite in ActionScript. Rewrite in ActionScript. Rewrite in ActionScript. Rewrite in ActionScript. Rewrite in ActionScript. Rewrite in ActionScript. Rewrite in ActionScript. Rewrite in ActionScript.

**Comment by ManuelAngel99** [comment]
IMHO this is a must

**Comment by HolyNetworkAdapter** [comment]
ActionScript + Flash is the future

**Comment by AlexPerathoner** [comment]
As alternatives I'd consider Brainfuck, or GomorraSQL

**Comment by riscmkv** [comment]
looking into this
