### ISSUE TITLE
Stop creating random issue and PR

### ISSUE THREAD

**Issue by amosayomide05** [twitter/the-algorithm#500]
You all should stop creating random and meaningless issues and pull requests

**Comment by PickleNik** [comment]
truely

**Comment by EightB1ts** [comment]
I understand that writing useless PR and issue requests in GitHub may seem like a waste of time. But hey, sometimes it's good to let loose and have a bit of fun!

Sure, your request may not always be taken seriously by the maintainers of the project, but that doesn't mean it's not worth submitting. It's a great way to get a feel for how the open-source community operates and to learn about best practices when it comes to submitting requests.

Plus, even if your request is deemed useless, it can still provide valuable feedback to the maintainers. Who knows, maybe they'll take your idea and run with it!

And let's be real, writing requests can also be a way to show off your creativity and sense of humor. Sure, you may not always get a laugh, but hey, it's worth a shot.

So go ahead, write those silly requests and let your imagination run wild. You never know what kind of impact you might have on the open-source community.

**Comment by darkwraithcovenant** [comment]
People are having bit of a laugh. Maybe some of them are expressing displeasure with how the company is run, and how it treats its workers? For a bit of passive resistance, this is as tame as it gets. I'm sure as the days go on, the useless PRs will sink and people will get bored and move on. But if they didn't want the FOSS community to comment, they shouldn't have made this this repo public.

**Comment by samdisk11** [comment]
> I understand that writing useless PR and issue requests in GitHub may seem like a waste of time. But hey, sometimes it's good to let loose and have a bit of fun!
> 
> Sure, your request may not always be taken seriously by the maintainers of the project, but that doesn't mean it's not worth submitting. It's a great way to get a feel for how the open-source community operates and to learn about best practices when it comes to submitting requests.
> 
> Plus, even if your request is deemed useless, it can still provide valuable feedback to the maintainers. Who knows, maybe they'll take your idea and run with it!
> 
> And let's be real, writing requests can also be a way to show off your creativity and sense of humor. Sure, you may not always get a laugh, but hey, it's worth a shot.
> 
> So go ahead, write those silly requests and let your imagination run wild. You never know what kind of impact you might have on the open-source community.

I have a feeling you used ChatGPT or some sort of AI to write this.

**Comment by EightB1ts** [comment]
> > I understand that writing useless PR and issue requests in GitHub may seem like a waste of time. But hey, sometimes it's good to let loose and have a bit of fun!
> > Sure, your request may not always be taken seriously by the maintainers of the project, but that doesn't mean it's not worth submitting. It's a great way to get a feel for how the open-source community operates and to learn about best practices when it comes to submitting requests.
> > Plus, even if your request is deemed useless, it can still provide valuable feedback to the maintainers. Who knows, maybe they'll take your idea and run with it!
> > And let's be real, writing requests can also be a way to show off your creativity and sense of humor. Sure, you may not always get a laugh, but hey, it's worth a shot.
> > So go ahead, write those silly requests and let your imagination run wild. You never know what kind of impact you might have on the open-source community.
> 
> I have a feeling you used ChatGPT or some sort of AI to write this.

![you-got-me-walter-white.gif](https://media.tenor.com/ihrIvE6YsTAAAAAC/you-got-me-walter-white.gif)

**Comment by samdisk11** [comment]
Nice.

**Comment by samdisk11** [comment]
> It was interesting see how much Rust Evangelists are on here, I will bring them all out ;) - the world must not be run by crab people.

C++ must prevail!

**Comment by pratyakshm** [comment]
Concerning

**Comment by MetaStag** [comment]
> Sure, your request may not always be taken seriously by the maintainers of the project, but that doesn't mean it's not worth submitting. It's a great way to get a feel for how the open-source community operates and to learn about best practices when it comes to submitting requests.

There are plenty of repos that are meant to be used as practice, such as [Spoon-Knife](https://github.com/octocat/Spoon-Knife), and if we still make that argument, at least the PR should be coherent, people are literally trolling "give me more likes", etc.

I mean, im enjoying all the troll prs/issues for sure, but we definitely shouldn't justify them :)

**Comment by amosayomide05** [comment]
> Hey, @twitter-service
> I believe it would be in your best interest to consider imposing limitations on the number of issues that can be submitted or implementing measures to moderate them. I came across an excellent GitHub Action that could potentially be very useful here: https://github.com/marketplace/actions/issue-auto-closer 
> 
> This tool automatically closes issues that don't follow a specified regex pattern. Very useful to decrease the amount of issues, particularly those that are spam-ridden and unworthy of attention, 
> 
> That being said, there are certain issues that require manual intervention, such as the absurd one found here: https://github.com/twitter/the-algorithm/issues/480 , which likewise serves no real purpose.

Exactly

**Comment by datgreatkhan** [comment]
> > You all should stop creating random and meaningless issues and pull requests
> 
> It's not at all surprising to be frank. It was quite predictable, considering that we are dealing with individuals who exhibit the traits of immature, petulant children.

Or, if you took some time to really ponder - it's simply the nature of the world. A narcissistic, egotistical crybaby known as Elon Musk infesting companies like Twitter and likewise a decent chunk of the world is bound to get some pushback in the opposite direction.

Maybe don't worship billionaires, especially incompetent ones like Mr. Musk who would rather tweet all day than actually do any hard work - you know, the hard work that the tens of thousands of employees under him are doing.

**Comment by datgreatkhan** [comment]
>

> Eh.. no, that's not at all "simply the nature of the world". This is lazy reasoning, an arbitrary excuse to troll and spam. This is how you, personally, subjectively believe the world to be which is not only delusional but also utterly irrelevant in any objective sense. It is merely your own self-important, solipsistic opinion to somehow justify violating the GitHub ToS. Quite ironic, btw, if we talk about egoism and narcissism. There's nothing to "really ponder" here about other than what I've said initially already.
> 
> > A narcissistic, egotistical crybaby known as Elon Musk infesting companies like Twitter and likewise a decent chunk of the world is bound to get some pushback in the opposite direction.
> 
> So, I think this requires a longer answer, because this is yet again one of those very stupid takes and fallacious ramblings that one wished didn't read.

Imagine writing an essay (that I didn't read by the way) to defend a corrupt and ignorant billionaire who you worship simply because he took over companies with the vast wealth he attained from the thousands doing the real hard work.

I hope you realize Elon not only sued to become a founder of Tesla (after doing nothing for the company as a "product designer"), nor did he provide much value to what was formerly before becoming "PayPal" (he was ousted as CEO twice).

But keep on worshipping him because you think he hand-crafted those SpaceX rockets by his own bare hands, and acting like he designed the Tesla auto pilot feature himself.

Sorry, but wagging your finger with one hand telling people to do stuff while raking in cash from the hard work of others with the other hand is not remotely close to being valuable to the world.

**Comment by lnfel** [comment]
didn't knew github issues section is the new reddit platform 🔥

**Comment by datgreatkhan** [comment]
> So, you're effectively saying that your attention span is even shorter than the text you claim to have not read (which isn't even as close as long as your average news article). Had you taken the time to peruse the text with adequate attention, you would have promptly discerned that I neither defended Elon Musk nor worshipped him. You're strawmanning.


Keep worshipping Elon haha.

Btw, your poor attempt of trying to sound smart and logical makes you look even more of an embarrassment. Especially when you talk about using a "strawman" when you don't even know what it is. Lol.

**Comment by datgreatkhan** [comment]
> > Keep worshipping Elon haha.
> 
> Keep coping with that dyslexia. I'm afraid I have little hope for your future progress in reading comprehension, given your consistent failures at arguing against me thus far which you try to overplay by acting all smug. Still won't change that you lost though. ¯\_(ツ)_/¯ You still didn't respond to any of my points either. And that's all I need to know.
> 
> > Btw, your poor attempt of trying to sound smart and logical makes you look even more of an embarrassment. Especially when you talk about using a "strawman" when you don't even know what it is. Lol.
> 
> Nope. Still wrong. But thanks for confirming that you either don't know what a straw man is or you're too dumb to see that your previous responses were arguing against such one (again, irony and hypocrisy at its finest). I really take pity on your never-ending ignorant state so I'll attempt to help you out, though I have little faith in your ability to ever grasp this.
> 
> Definition: "A straw man fallacy (sometimes written as strawman) is the informal fallacy of **refuting an argument different from the one actually under discussion, while not recognizing or acknowledging the distinction**".
> 
> My argument(s) to your first response was, simplified: "(1) Just because Elon Musk is doing X or is being a Y, doesn't justify being a childish, immature idiot violating the ToS of an entirely different website that isn't even connected to Elon Musk. (2) It also achieves nothing other than GitHub content moderation having to deal with your filth. You're not the hero who you think you are. (3) You'd be achieving a lot more against Musk and billionaire-owned platforms by providing alternative, decentralized platforms and to actively use them afterwards. (4) There's nothing to really ponder here about. Even if Elon Musk had it coming, it doesn't change the fact that many people here were and are acting like immature, petulant children, which is exactly and the only thing that I pointed out. Nothing more or less. Period."
> 
> In your previous responses, you repeatedly resorted to your made-up premise that I hold a reverence towards Elon Musk or billionaires in general (and I still don't know where you got that from). Despite my attempts to redirect the conversation to the _actual_ topic at hand, you continued to assert that I should "stop worshipping billionaires" and provided reasons to support this stance. But this was not the argument under discussion. There was no argument about whether billionaires should be worshipped or not, and I never claimed that I worship them. But you just nonchalantly assumed this to be the case and argued against that. And yes, that's a straw man, as per definition. Lol.
> 
> If you still don't get it at this point, you're clearly in no position to judge who's smart and logical and who's not, because, c'mon dude, this is basic stuff. Basic stuff even a fifth grader understands. What was that talk again about embarrassment? Because right now here I am, having to tell **you**, a fucking grown-ass person, what a straw man is and why your responses were arguing against such. Holy shit.

My guy keeps typing essays like I'd actually read them. You okay? Go touch some grass outside.

**Comment by jdm-twtr** [comment]
We've seen a decent drop in the number of issues that are not actionable. Marking this closed for now.

**Comment by darkwraithcovenant** [comment]
> I'm sure as the days go on, the useless PRs will sink and people will get bored and move on. 

This is exactly what I said would happen. Thanks for thumbs downing me for being right.

**Comment by amosayomide05** [comment]
> > I'm sure as the days go on, the useless PRs will sink and people will get bored and move on. 
> 
> This is exactly what I said would happen. Thanks for thumbs downing me for being right. 

😂😂
