### ISSUE TITLE
Port to Roblox Luau

### ISSUE THREAD

**Issue by iratenebrarum** [twitter/the-algorithm#503]
please port to my favorite online building toy, roblox

**Comment by PickleNik** [comment]
I can't believe I'm saying this, but dup #440

**Comment by PickleNik** [comment]
Luau and Rust are leading in rewrite requests atm
<img width="1250" alt="Screenshot 2023-04-01 at 2 53 30 AM" src="https://user-images.githubusercontent.com/31113245/229270673-b5743632-c55e-42bd-8d79-3cb77a24cfbc.png">
