### ISSUE TITLE
Follow recommendations service not providing relevant suggestions

### ISSUE THREAD

**Issue by 0xEbrahim** [twitter/the-algorithm#507]
I have noticed that the follow recommendations service provided by Twitter's Follow Recommendations Service doesn't always provide relevant suggestions for users to follow. This can be frustrating for users who are looking to expand their network on the platform and discover new content.

In my experience, the recommendations provided by the service often seem to be based on arbitrary factors like popularity and recency, rather than on a user's interests and engagement history on the platform. This can result in users being recommended accounts that have no relevance to their interests, which can lead to a poor user experience.

I believe that the Follow Recommendations Service should take into account a user's interests, engagement history, and the accounts they already follow when providing recommendations. By doing so, the service can provide more personalized recommendations that are relevant to the user, leading to a better user experience.

Steps to reproduce:

Open the Twitter app or web app
Navigate to the "Who to Follow" section
Observe the recommendations provided by the Follow Recommendations Service
Expected behavior:

The recommendations provided by the Follow Recommendations Service should be relevant and personalized to a user's interests, engagement history, and the accounts they already follow.

Actual behavior:

The recommendations provided by the Follow Recommendations Service are often not relevant or personalized, and seem to be based on arbitrary factors like popularity and recency.

**Comment by davidteren** [comment]
Feel free to open a PR with the implementation.

**Comment by 0xEbrahim** [comment]
Forgot the issue
