### ISSUE TITLE
Implement Nostr relay

### ISSUE THREAD

**Issue by AugustoResende** [twitter/the-algorithm#509]
https://nostr.com/

**Comment by ValZapod** [comment]
Yeah, I love https://github.com/vitorpamplona/amethyst 

If Twitter becomes part of it it will make Web2 obsolete!

**Comment by Sqaaakoi** [comment]
I sure do love a platform full of cryptobro spam and no moderation! Surely everyone would totally love it if this was pushed upon them so that their replies are full of junk!

**Comment by jdm-twtr** [comment]
This issue was closed due to one of these reasons: likelihood of spam, not enough context, or possibly inappropriate content. Please re-file with a useful title and description.
