### ISSUE TITLE
DOGE Missing

### ISSUE THREAD

**Issue by 2xsolution** [twitter/the-algorithm#518]
We looked into entire code but $DOGE payment is missing into it, Please Elon add it

**Comment by PickleNik** [comment]
That is not part of recommendations algo

**Comment by kxrn0** [comment]
>shitty ponzi scheme is missing
gee, I wonder why

**Comment by ethanholt1** [comment]
Twitter leaving the issues open was a mistake.

**Comment by nicco1690** [comment]
> Twitter leaving the issues open was a mistake.
Have fun, while it lasts.

**Comment by 2xsolution** [comment]
> Twitter leaving the issues open was a mistake.

Elonification

**Comment by 2xsolution** [comment]
> We need more bonk as well

NO, only $DOGE allowed

**Comment by HeyBanditoz** [comment]
You think _this_ currency is stable enough for Twitter? ~89% down from ATH.
If you actually argue with me, you are a lunatic.
![image](https://user-images.githubusercontent.com/7574664/229259881-0e9260e4-f7b8-4c4b-adf4-63f473f2de9b.png)
