### ISSUE TITLE
Girls don't reply to DM

### ISSUE THREAD

**Issue by 0xEbrahim** [twitter/the-algorithm#536]
Womens don't answer when i text them. 
I hope will be solved soon

**Comment by sasdallas** [comment]
Ouch, not planned...

**Comment by TheLukaDragar** [comment]
+1

**Comment by DedaDev** [comment]
also, d**k pic doesn't work

**Comment by nonetrix** [comment]
Please fix I'm dying out here 🙏

**Comment by DanBrown47** [comment]
Use AI bruv 😂

**Comment by nonetrix** [comment]
> Use AI bruv 😂

Never will be real, you don't get it 😔

**Comment by tiesen243** [comment]
+1

**Comment by bgoncharuck** [comment]
This bug needs to be fixed!

**Comment by Ridhsuki** [comment]
Goodluck

**Comment by apprentice-dev** [comment]
I dont need no girls. I need to master low level and be an OS dev and cybersecurity expert.

**Comment by inspired-dev** [comment]
I am looking to hire several talents (male/female) who can connect our devs and clients. If you're technical or a developer, that would be great, but if not, that's fine. It's not about development but about explaining what we're doing and about our experience.
Compensation: $30/hr-$60/hr.

**Comment by protocol-8** [comment]
skill issue

**Comment by AaravAtGit** [comment]
can't reproduce won't fix

**Comment by realInt2k** [comment]
> can't reproduce won't fix

chatting with your mom doesn't count, have you tried real girls?

**Comment by Dan-Kot** [comment]
You just need to listen to some HARDBASS

**Comment by ReneFroger** [comment]
I found the bug. The code depends on the `charisma` package, which isn’t included in the requirements. Unfortunately, fixing it requires a major refactor involving personal growth. Not sure about any ETA.

**Comment by nonetrix** [comment]
> You just need to listen to some HARDBASS

I have been in a coma since 2015 and am a redditor r/SovietRussiaMemes r/dankmemes user and watch Life of Boris and this is my post

**Comment by bodoque-01** [comment]
How come they ignored this issue?

**Comment by Project516** [comment]
> I found the bug. The code depends on the `charisma` package, which isn’t included in the requirements. Unfortunately, fixing it requires a major refactor involving personal growth. Not sure about any ETA.

npm install charisma

**Comment by AaravAtGit** [comment]
> npm install charisma

The package isn't available on any public registry; it will need to be built from source.
