### ISSUE TITLE
author_is_elon 🤡

### ISSUE THREAD

**Issue by fullpwn** [twitter/the-algorithm#548]
https://github.com/twitter/the-algorithm/blob/7f90d0ca342b928b479b512ec51ac2c3821f5922/home-mixer/server/src/main/scala/com/twitter/home_mixer/functional_component/decorator/HomeTweetTypePredicates.scala#L225

look at this clown

**Comment by Xpenzz** [comment]
> look at this clown

The "is_author_elon" feature was only used to track statistics through Twitter's A/B testing system (DDG), and had no impact on the recommendation algorithm.

**Comment by DavidBuchanan314** [comment]
If there was nothing wrong with it, why have they since removed it?

**Comment by okay** [comment]
> If there was nothing wrong with it, why have they since removed it?

because people like you assumed they were boosting his engagement?

**Comment by djvs** [comment]
Y'all are sure optimistic about why the owner of the site is personally hard-coded for metrics

**Comment by supermedinita** [comment]
Twitter closing this 🤡

**Comment by murphyj** [comment]
> > look at this clown
> 
> The "is_author_elon" feature was only used to track statistics through Twitter's A/B testing system (DDG), and had no impact on the recommendation algorithm.

Evidence?
