### ISSUE TITLE
What is project libra ?

### ISSUE THREAD

**Issue by Yasir900aslam** [twitter/the-algorithm#551]
I'm browsing through some random files and I stumbled upon this interesting line. What is project libra ?  

https://github.com/twitter/the-algorithm/blob/7f90d0ca342b928b479b512ec51ac2c3821f5922/visibilitylib/src/main/scala/com/twitter/visibility/models/TweetSafetyLabel.scala#L194

**Comment by CryptoCutter** [comment]
That was/is Facebooks cryptocurrency that was going to be pegged to the US dollar before the SEC shut it down. There is still talk of it running smart contracts for use in the Metaverse gaming, Twitter was probably setting up for it.

**Comment by kennethsequeira** [comment]
> That was/is Facebooks cryptocurrency that was going to be pegged to the US dollar before the SEC shut it down. There is still talk of it running smart contracts for use in the Metaverse gaming, Twitter was probably setting up for it.

Reference to the same:

https://en.wikipedia.org/wiki/Diem_(digital_currency)

https://www.cnbc.com/2021/04/20/facebook-backed-diem-aims-to-launch-digital-currency-pilot-in-2021.html
