### ISSUE TITLE
Add the algorithm to the C++ standard library

### ISSUE THREAD

**Issue by vitaut** [twitter/the-algorithm#552]
The Twitter algorithm has become an integral part of modern communication, allowing users to quickly and easily share thoughts, opinions, and news with a global audience. As a result, incorporating the Twitter algorithm into the C++ standard library would provide significant benefits to both developers and end-users.

Firstly, by including the Twitter algorithm in the C++ standard library, developers would be able to take advantage of a powerful tool that is already widely used and understood. This would make it easier for developers to integrate Twitter functionality into their applications, ultimately saving them time and effort.

Furthermore, the Twitter algorithm is constantly evolving and improving, which means that any updates or improvements to the algorithm would automatically be included in the standard library. This would ensure that developers always have access to the latest and most effective Twitter functionality, without having to worry about keeping their own libraries up to date.

In addition, including the Twitter algorithm in the C++ standard library would make it more accessible to a wider audience of developers. This would encourage more people to experiment with the algorithm and develop new and innovative applications, ultimately leading to a more dynamic and diverse software ecosystem.

Overall, adding the Twitter algorithm to the C++ standard library would provide numerous benefits to developers and end-users alike. By making it easier to integrate Twitter functionality into applications, providing access to the latest updates and improvements, and encouraging innovation and experimentation, this move would be a valuable addition to the C++ ecosystem.

**Comment by hasansiddiqui5862** [comment]
Chatgpt

**Comment by Timothy-Liuxf** [comment]
Yeah, I also recommend adding the `std::is_elon<T>` metafunction to be added to the header `type_traits`. 🤔

**Comment by ValZapod** [comment]
At first you need to fix the garabage C libm. This has correct rounding, libm does not.  https://core-math.gitlabpages.inria.fr/

**Comment by polynomial** [comment]
Hoping to see `SIGELN` in my gdb output soon!

**Comment by polynomial** [comment]
Really don't want to see `SIGELN` in my gdb anytime soon...

**Comment by gnaggnoyil** [comment]
I would like to know what you've inputted to ChatGPT to generate this output.
