### ISSUE TITLE
Add back the interesting users

### ISSUE THREAD

**Issue by PhirePhly** [twitter/the-algorithm#554]
It seems like most of the interesting posters have disappeared from my timeline and been replaced with Elon's personal account and spammy mobile game ads. 

What commit do we need to revert to get all the interesting users back?

**Comment by Xpenzz** [comment]
> What commit do we need to revert to get all the interesting users back?

Stop engaging with anything Elon related if you don't want him to show up on your timeline. Pretty simply really.

**Comment by JonathanTreffler** [comment]
Sorry, not possible, they moved to Mastodon. Time to abandon Melon Tusks little app.

**Comment by Xpenzz** [comment]
> Sorry, not possible, they moved to Mastodon. Time to abandon Melon Tusks little app.

They moved to Mastodon to complain about Twitter and Elon lmao.

**Comment by yani** [comment]
This one
https://github.com/twitter/the-algorithm/commit/ef4c5eb65e6e04fac4f0e1fa8bbeff56b75c1f98

**Comment by alex-redacted** [comment]
> Sorry, not possible, they moved to Mastodon. Time to abandon Melon Tusks little app.

*cackles*

**Comment by xvrx** [comment]
the pronoun people
