### ISSUE TITLE
another issue i forgot

### ISSUE THREAD

**Issue by rikafurud** [twitter/the-algorithm#556]
![53acc168fd0bf8e2b5bb44498f5b08b0](https://user-images.githubusercontent.com/128904510/229258048-db4d02aa-f61a-4944-a66d-b1681cea4f9d.jpg)
![FsRw_dVagAEkh_b](https://user-images.githubusercontent.com/128904510/229258063-d2b11d15-d61e-4f5d-a095-d781d1215559.png)

**Comment by CozyMeli-gitv2** [comment]
bro

**Comment by FluorideHistorian** [comment]
based

**Comment by CozyMeli-gitv2** [comment]
hello historian

**Comment by fa0311** [comment]
Please clarify the source of the illustration.
