### ISSUE TITLE
look my dog

### ISSUE THREAD

**Issue by Lick-liu** [twitter/the-algorithm#564]
look my dog , it's so cute
![20230401-091749](https://user-images.githubusercontent.com/51771897/229258734-15fc2803-a64a-4f45-8bb8-b0b8c6ad4315.jpg)

**Comment by Lick-liu** [comment]
https://user-images.githubusercontent.com/51771897/229258786-6cbfac45-98cc-457e-a288-2e8b63cd37b5.mp4

**Comment by nwunderly** [comment]
shibe

**Comment by rcallaby** [comment]
Shiba Inu

**Comment by leafstrat** [comment]
![dogechad](https://user-images.githubusercontent.com/4014775/229258871-d006eb3e-87ad-438d-8262-e02c6ba98fb2.png)

**Comment by Codfish246** [comment]
nice dog

**Comment by PiSquaredx3** [comment]
can it make a grilled cheese?

**Comment by baonq-me** [comment]
<img width="555" alt="image" src="https://user-images.githubusercontent.com/1851037/229294087-4ea4c1c6-0619-41dc-9eb6-6e22f9ef9d15.png">
