### ISSUE TITLE
Add a Contributing.md file to give direction on how to contribute

### ISSUE THREAD

**Issue by rcallaby** [twitter/the-algorithm#569]
There is no contributing.md file. So, I think there is no direction on how to contribute. Maybe adding one would help with this.

**Comment by that-guy-iain** [comment]
There is a paragraph that basically implies they don't want your code contributions just feedback.

**Comment by rcallaby** [comment]
Then they should put that in the contributing.md file as many of the other large corporations also do. The point of having that file is that is typically the first place many people look.

**Comment by that-guy-iain** [comment]
I think the first place people look is the readme.md.

**Comment by rcallaby** [comment]
If you care to look at many of the repositories in the Twitter github you will see many repositories have a contributing.md file so clearly there is a history of Twitter recognizing the need for it. IF Twitter doesn't want to do it then they can just close my ticket, easy peasy.
