### ISSUE TITLE
NOT ABLE TO SIGN CLA AGREEMENT YO!

### ISSUE THREAD

**Issue by venkateshamatam** [twitter/the-algorithm#573]
I am not able to sign the CLA agreement, the API is acting up 😢 
![image](https://user-images.githubusercontent.com/113487319/229259340-a4647e1c-e628-42c8-b9a4-aa3ea3319bc0.png)
how do I do it?

**Comment by m-a-sch** [comment]
CLA-ASSISTANT.IO is SAP or is powered by SAP??? and it fails on rate limit. That is/would be interesting.

**Comment by vats147** [comment]
Same issue

**Comment by jdm-twtr** [comment]
Hi, thanks for reaching out! Can you retry now? We haven't looked into this, but we're seeing PRs from other contributors with recently signed CLAs.

**Comment by vats147** [comment]
Now it's resolved ☺️

**Comment by venkateshamatam** [comment]
> Hi, thanks for reaching out! Can you retry now? We haven't looked into this, but we're seeing PRs from other contributors with recently signed CLAs.

Hey, it's fixed now. Thanks! Please review PR #420, I don’t know who's the reviewer lol

**Comment by jdm-twtr** [comment]
Glad to hear it! We're still working on specifics on how we assign PRs for review, but someone will take a look soon! Thanks for your continued patience.
