### ISSUE TITLE
Serious Suggestion: More Snack Options In The Vending Machine 

### ISSUE THREAD

**Issue by markusdemedeiros** [twitter/the-algorithm#574]
Im Sick Of Salt And Vinegar Chips All The Time At Least Fucking Restock It And Also Maybe Switch It Up Every Couple Of Months With Some New Items

**Comment by leafstrat** [comment]
### im not picky
![fatrat](https://user-images.githubusercontent.com/4014775/229259401-026048ad-d840-41de-84d5-306a433dfac8.png)
