### ISSUE TITLE
needs more cats

### ISSUE THREAD

**Issue by Codfish246** [twitter/the-algorithm#588]
meow

https://user-images.githubusercontent.com/23464269/229260427-fe431e9c-992e-46f2-823d-540ef1342b50.mp4

**Comment by jerryvu26** [comment]
more cats!

![20181220_151956.jpg](https://user-images.githubusercontent.com/36879694/229260611-8f0639e6-999f-4a7b-ad97-815e8e90819a.jpg)

**Comment by Codfish246** [comment]
lovely cat

source more cute cats from #474

**Comment by hmanzur** [comment]
Surrender to mew Vader
![image](https://user-images.githubusercontent.com/17788438/229260673-bb41f8bc-37e0-4045-a1d8-4b4853712127.png)

**Comment by fmhc** [comment]
Sorry please reopen add more cats please ser

**Comment by fmhc** [comment]
It's not fair to close this. There are people demanding doge shizz so pls accept that cat content is a very valuable thing in the internet. It helps people calm down, it helps people to find peace, cat content brings happyness and enjoyment. I support more cats in here

**Comment by neverbiasu** [comment]
![image](https://user-images.githubusercontent.com/90372299/229264683-348e7ad2-5366-4ece-9064-58b6c7e08996.png)
