### ISSUE TITLE
Crypto scams in dms

### ISSUE THREAD

**Issue by sioodmy** [twitter/the-algorithm#590]
**Describe the bug**

crypto scam messages should be automatically flagged and removed 

**To Reproduce**
1. interact with any thread involving crypto (like watcher.guru or cz)

**Expected behavior**

obviously those dms should get removed 

**Screenshots**

![Screenshot_20230401-035939_Twitter.jpg](https://user-images.githubusercontent.com/81568712/229260520-58c14475-9897-4c4c-a872-0195158c9d5c.jpg)

**Environment**
For web, specify your OS and browser version.  For mobile, specify device, OS
and version.  For libraries, what version of build tools are you using?

I use nixos btw, but that's unrelated
(just flexin yk)

**Additional context**

**Comment by alexxriv** [comment]
I don't think crypto scams dms belong in the recommendation algorithm

**Comment by Blookcode** [comment]
Good Share Elon, Engagement farmers will be very happy with this.

**Comment by DavidBuchanan314** [comment]
the Lists feature solves this

**Comment by sioodmy** [comment]
> I don't think crypto scams dms belong in the recommendation algorithm

Yes, but twitter is not completely open source, so I can't really report the problem in the right repo
I just want to make developers aware of the problem.

Twitter is a place where new crypto projects get announced, advertised and built, so we have to make sure its safe for everyone. 
 
Most ""crypto bros"" rn are used to receiving dms like this, but wait until the next bull run that will attract new clueless users.  We don't want them to be scammed and blame Twitter for not warning them.

**Comment by alexxriv** [comment]
> > I don't think crypto scams dms belong in the recommendation algorithm
> 
> Yes, but twitter is not completely open source, so I can't really report the problem in the right repo
> I just want to make developers aware of the problem.
> 
> Twitter is a place where new crypto projects get announced, advertised and built, so we have to make sure its safe for everyone. 
>  
> Most ""crypto bros"" rn are used to receiving dms like this, but wait until the next bull run that will attract new clueless users.  We don't want them to be scammed and blame Twitter for not warning them.

this is not an unknown problem, i'm sure they are already working on it, no need to spam in unrelated repos

**Comment by sioodmy** [comment]
> this is not an unknown problem, i'm sure they are already working on it, no need to spam in unrelated repos

it sounds like a easy fix, just give the user warning when dm contains certain keywords like "airdrop" or "free"
