### ISSUE TITLE
Tell Elongated Muskrat to hurry up and step down

### ISSUE THREAD

**Issue by purpl3f0xsecur1ty** [twitter/the-algorithm#619]
Can the algorithm find a replacement CEO for him since he can't be bothered to?

**Comment by ValZapod** [comment]
In the first poll he actually got the result not to step down. So why should he.

**Comment by purpl3f0xsecur1ty** [comment]
![image](https://user-images.githubusercontent.com/42351007/229262249-20953581-617c-4524-9dec-610be791e52c.png)

**Comment by leafstrat** [comment]
you will never be a real woman

**Comment by purpl3f0xsecur1ty** [comment]
Who said I wanted to be lmao

**Comment by AbdoOsaimi** [comment]
Elon will always be the OWNER of Twitter. Why are you posting this here ??

**Comment by Sqaaakoi** [comment]
:clown_face: :clown_face: :clown_face: :clown_face: :clown_face: :clown_face: :clown_face: :clown_face:

**Comment by purpl3f0xsecur1ty** [comment]
> Elon will always be the OWNER of Twitter. Why are you posting this here ??

Because he's a moron

**Comment by Sqaaakoi** [comment]
:nerd_face: imagine defending a bigoted billionaire

**Comment by ValZapod** [comment]
> ![image](https://user-images.githubusercontent.com/42351007/229262249-20953581-617c-4524-9dec-610be791e52c.png)

That is the second poll.

**Comment by purpl3f0xsecur1ty** [comment]
Who cares? Cope harder, Muskrat fanboy.

**Comment by Sqaaakoi** [comment]
waiting for Elon to run the poll again after the proposed changes that only allow Twitter blue subs to vote

**Comment by leafstrat** [comment]
![Screenshot 2023-03-31 at 20-13-46 Michael Hughes - Stevenson University - Owings Mills Maryland United States LinkedIn](https://user-images.githubusercontent.com/4014775/229263084-be595b05-d67b-4cf5-b3ca-c745aad9a0b0.png)
lulz

**Comment by AbdoOsaimi** [comment]
ELON WILL ALWAYS BE THE OWNER OF TWITTER. _CRY HARDER_

**Comment by purpl3f0xsecur1ty** [comment]
> ELON WILL ALWAYS BE THE OWNER OF TWITTER. _CRY HARDER_

That's fine. But he's a dipshit who can't manage anything. Cope harder Elon dick-rider.
