### ISSUE TITLE
Where's the conspiracy Elon Tweet Booster

### ISSUE THREAD

**Issue by ifahs1** [twitter/the-algorithm#623]
https://twitter.com/elonmusk/status/1626520156469092353?t=urOPC6tpWsfNGnRhMB1pOA&s=19

**Comment by ValZapod** [comment]
Last commit: 
![Screenshot_20230401_055548_Chrome](https://user-images.githubusercontent.com/31514790/229262508-ef100da8-9637-40fa-b31b-eaa5e4326c3d.png)

**Comment by embedvr** [comment]
![image](https://user-images.githubusercontent.com/54275575/229262590-72eb60f7-8b77-4217-ae7c-f134b9e3002a.png)

**Comment by supermedinita** [comment]
Whoops, that wasn't supposed to be there! Let's just sweep that under the rug and pretend it doesn't exist, mmkay?

**Comment by ValZapod** [comment]
> Whoops, that wasn't supposed to be there! Let's just sweep that under the rug and pretend it doesn't exist, mmkay?

Literally I registred the new account. Opened one liberal that posts insane list, this one, to follow on my main account:



![20230401_061234](https://user-images.githubusercontent.com/31514790/229263035-64a1bb39-9ec0-4f71-8347-06f03527a789.jpg)


And then without any likes, any comments, any tweets at all I got purple recommended tweet from AOC. WTF.

**Comment by ifahs1** [comment]
![80889B8D-1689-41C1-B22A-BB68A5F6A1E4](https://user-images.githubusercontent.com/36047086/229263115-7f3b4159-7fa0-472e-85e3-4d4c0236a986.jpeg)

btw, it’s his app. He can do whatever he want. If he wants to delete the app tomorrow, he can.

And this is probably a marketing stunt, a single search of the word “elon” in the codebase will show the line.
And what if they use numbers instead of the word “elon”. 
“author_is_Keksk1”We would never doubt it. So, this is probably a marketing stunt. Hope this will make headlines tomorrow.
