### ISSUE TITLE
How does Twitter expect the open source community to work on this when not all of the algo has been provided?

### ISSUE THREAD

**Issue by supermedinita** [twitter/the-algorithm#624]
Also, the README and diagrams provided are bad. You might as well not have provided those.

**Comment by jdm-twtr** [comment]
@supermedinita thanks for the feedback, and sorry that you're not a fan of the README and diagrams. 

We also provided a much more detailed [blog post](https://blog.twitter.com/engineering/en_us/topics/open-source/2023/twitter-recommendation-algorithm) on our engineering blog. 

Hopefully the blog post helps answer some of your questions.

We intend to release more of the source code over time. Stay tuned!
