### ISSUE TITLE
Feature Request: Deboost all Twitter Blue users

### ISSUE THREAD

**Issue by RocketRaccoon27** [twitter/the-algorithm#628]
**Is your feature request related to a problem? Please describe.**
Twitter Blue is a terrible service for everyone and I hate having to check if mfs are actually verified or fake verified.

**Describe the solution you'd like**
Stop all of their posts from ever gaining traction by deboosting them into the next dimension.

**Describe alternatives you've considered**
Twitter will never accept any pull requests I make so this is my only option.

**Additional context**
Alternatively, just keep the Twitter B logo for all Blue users. Also Twitter Blue sucks lol

**Comment by Sqaaakoi** [comment]
imo the app icon should be changed into a :hankey: for all twitter blue users and unsubscribing shouldn't change it back

**Comment by leafstrat** [comment]
Every other social network will follow suite with paid subscriptions as everything becomes AI generated and botfarms take over, twitter is just ahead of the curve.
