### ISSUE TITLE
Rewrite in Bash and PowerShell

### ISSUE THREAD

**Issue by AnimMouse** [twitter/the-algorithm#629]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when something is not written in Bash or PowerShell.

**Describe the solution you'd like**
Rewrite the algorithm in Bash and PowerShell.

**Describe alternatives you've considered**
Alternatives are rewriting it in batch file, Tcl, Perl, AWK, and Lua.

**Additional context**
This is so us scripting language and Job Control Language experts can contribute to this algorithm.

**Comment by Sqaaakoi** [comment]
rewrite it in BrainFuck
