### ISSUE TITLE
Rewrite in Rust

### ISSUE THREAD

**Issue by elvodqa** [twitter/the-algorithm#63]
OMG imagine using that disgusting language over RUST. As a proud rustacean, I’m going to inform you: that’s blasphemy. You can do better. Grab cargo and start using a beautiful memory managed, statically typed, comfortable yet low level language with a spectacular packaging system. No more memory leaks. No more makefiles. End the weird bugs caused by unrequested type casting. Easily find libraries. AND ALL OF THAT IS BLAZING FAST (at C/cpp-level speeds - yay compiled langs and llvm c:). Why wouldn’t you? The syntax is spectacular as well; extremely clean, much better than anything else out there. Those match statements are so extremely pleasant, and the looping conventions are orgasmic. And the compiler is the most useful and polite you’ll come across; no more endlessly scrolling segmentation fault and template errors. It’s amazing and I love it and you should switch now because it’s far superior to literally everything else, all those gross languages you’re used to using. Come to rust and you’ll never look back, it’s so versatile and cleeeeean. Graydon Hoare is literally a god. The rust book is my bible. this is my religion now. USE RUST

It is year 2028 and Linux has been completely rewritten in Rust.

After adding Rust support to Linux kernel in 2021 Linux repo has been flooded with patches and pull requests from brave Rustaceans rewriting critical components in Rust to ensure their stability and memory safety that C could never guarantee. After a few painful years of code reviews and salt coming from C programmers losing their jobs left and right we have finally achieved a 100% Rust Linux kernel. Not a single kernel panic or crash has been reported ever since. In fact, the kernel was so stable that Microsoft gave up all their efforts in Windows as we know it, rewrote it in Rust, and Windows became just another distro in the Linux ecosystem. Other projects and companies soon followed the trend - if you install any Linux distro nowadays it won't come with grep, du or cat - there is only ripgrep, dust and bat. Do you use a graphical interface? Good luck using deprecated projects such as Wayland, Gnome or KDE - wayland-rs , Rsome and RDE is where it's all at. The only serious browser available is Servo and it holds 98% of the market share. Every new game released to the market, including those made by AAA developers, is using the most stable, fast and user-friendly game engine - Bevy v4.20. People love their system and how stable, safe and incredibly fast it is. Proprietary software is basically non-existent at this point. By the year 2035 every single printer, laptop, industrial robot, rocket, autonomous car, submarine, sex toy is powered by software written in Rust. And they never crash or fail. The world is so prosperous and stable that we have finally achieved world peace.

Ferris looks down at what he has created once more and smiles, as he always did. He says nothing as he is just a crab and a mascot, but you can tell from his eyes... That he is truly proud of his community.

**Comment by WagnerMoreira** [comment]
please rust + wasm, leptos, etc

**Comment by elvodqa** [comment]
YES SIR 💪 💪 💪 💪 💪 💪 💪 RUST BEST AT WASM I LOVE RUST

**Comment by nonetrix** [comment]
One of these issues already lol, I love Rust tbh but I don't imagine it would easy to rewrite XD

**Comment by krisnova** [comment]
🦀

**Comment by elvodqa** [comment]
Whoever decided It was a good idea to use Scala must be pretty dumb and should be fired (probably already so)

**Comment by wmorgue** [comment]
IN RUST WE TRUST

**Comment by elvodqa** [comment]
lol is that C++? Wait are you binding that with Python?! Imagine using those over Rust. As a proud Rustacean and Ferris the Crab adorer, I regret to inform you that your taste in languages sucks. This is sad. You can do better. You know how easy package and dependancy management is with Cargo? Not to mention you don’t even need a Makefile. It’s great. Dynamically typed languages need to die. There’s no other option. They just do. If you like dynamic typing, you need some help. Seriously. By using a dynamically typed and interpreted language (which means its @#*!&!@ slow!!!), you are committing genocide and harming the environment more than gas cars. Rust is fast and uses clean, renewable energy through the magic of being a language compiled with LLVM. Tired of memory bugs? You should be. Shame on you for still having them when Rust exists. Tired of being bad? Time to go to Rust. Tired of being slow because you’re not smart and your friends laugh at you? Rust is quite speedy indeed (all thanks to the big brain of the compiler). Tired of not getting off the normal way? Match statements, loops, and the compiler for Rust give the best orgasms 10/10 (completely legit). Not to mention the superiority you get to feel when you show off your superior Rust code to your inferior “friends” still using some other language. Want to get rid of malware? Rust is safe, therefore malware is noware (also completely legit). You quite honestly will forget about any other language (including English because it’s slow and unsafe). You even get to add the Rust Book and its brothers to your Bible collection alongside the Arch and Gentoo Wikis. All hail Rust. TempleOS pales in religious comparison to the faith of Rustaceans. Graydon Hoare is Jesus. Amen.
