### ISSUE TITLE
Feature Request: Rewrite the whole stack

### ISSUE THREAD

**Issue by RocketRaccoon27** [twitter/the-algorithm#632]
**Is your feature request related to a problem? Please describe.**
Elon Musk said he'd rewrite the whole stack and hasn't done it.

**Describe the solution you'd like**
Have Twitter spend millions of dollars rewriting the stack and then have employees realize Elon Musk does not know anything about technology or coding, much less what a "stack" is.

**Describe alternatives you've considered**
This is the only way.

**Additional context**
https://youtu.be/RJo-ulbIu8I

**Comment by Xpenzz** [comment]
> Elon Musk does not know anything about technology or coding

This you? https://pbs.twimg.com/media/FsmQ3T3XoAExR7l?format=jpg&name=4096x4096
