### ISSUE TITLE
Issues being deleted

### ISSUE THREAD

**Issue by PythonCoderAS** [twitter/the-algorithm#644]
This is not very open nor source, is it

**Comment by mathlover2** [comment]
No it's not.
Twitter fired their open source people and it _shows_.

**Comment by ValZapod** [comment]
You cannot delete issues on github. Only edit the contents and even then only github can delete history of edits on a comment.

**Comment by PythonCoderAS** [comment]
> You cannot delete issues on github. Only edit the contents and even then only github can delete history of edits on a comment.

This is just patently false. Try clicking on #531

**Comment by RocketRaccoon27** [comment]
Looking into this

**Comment by mathlover2** [comment]
https://docs.github.com/en/issues/tracking-your-work-with-issues/deleting-an-issue

**Comment by leafstrat** [comment]
> You cannot delete issues on github. Only edit the contents and even then only github can delete history of edits on a comment.

Organization owners can, the ones that are deleted are entirely off-topic and against githubs TOS. People have been posting porn, etc.

**Comment by arnabnandy7** [comment]
> This is not very open nor source, is it

It's not expected to be that opensource is it 🤐

**Comment by ValZapod** [comment]
> > You cannot delete issues on github. Only edit the contents and even then only github can delete history of edits on a comment.
> 
> This is just patently false. Try clicking on [#531](https://github.com/twitter/the-algorithm/issues/531)

Ok, wow.

**Comment by jdm-twtr** [comment]
This issue was closed due to one of these reasons: likelihood of spam, not enough context, or possibly inappropriate content. Please re-file with a useful title and description.
