### ISSUE TITLE
There is nothing but a vague reference to the Libra project for any sort of blockchain technology anywhere in here...

### ISSUE THREAD

**Issue by CryptoCutter** [twitter/the-algorithm#648]
WEB3 now or be left behind.
Start building for Ethereum 2 launch, hire blockchain developer's and WEB3 specialist to help guide you through the possibilities and brain storm how to go way above and beyond everyone else.

**Comment by CryptoCutter** [comment]
Words spoken by outdated concepts struggling to stay in power.

**Comment by CryptoCutter** [comment]
We will revisit this in 10 years where WEB3 will be a decentalized open source Hive of smart contracts, oracles, API's and nonfungible/fungible token asset exchange in a virtual and augmented digital world... And Twitter will still be like "Hey, we have 2D non animated NFT avatars"  😄 

I would hope Elon Musk has more vision for the future of this platform.

**Comment by farazkaleemmalik** [comment]
If you have to brainstorm uses for web3 in a product, perhaps it is not needed. Hot tip for crypto devs, a text editor with web3! No one has entered that market yet!
