### ISSUE TITLE
How to stop Twitter's algorithm from suggesting I follow my ex's new partner?

### ISSUE THREAD

**Issue by pwnwriter** [twitter/the-algorithm#651]

**Comment by alex-redacted** [comment]
> _No description provided._

I love you, yes. This is a really great issue to raise. Timely and important.

**Comment by pwnwriter** [comment]
emergency plss 

![pngegg](https://user-images.githubusercontent.com/90331517/229264789-f01b669c-070f-4dec-b22d-aa71432206c0.png)
😂😂😂😂😂

**Comment by whoami-anoint** [comment]
😆😆
