### ISSUE TITLE
(Feature Request) Add him.

### ISSUE THREAD

**Issue by SympathyTea** [twitter/the-algorithm#659]
**Is your feature request related to a problem? Please describe.**
There is no Teawie on Twitter.

**Describe the solution you'd like**
I would like you to add Teawie on Twitter.

**Describe alternatives you've considered**
Abandoning ship.

**Additional context**
The following image is all the context you would need. I'm sure the team would understand.
![teawie](https://user-images.githubusercontent.com/116274772/229265101-907ec09e-24e1-4f60-81c5-0f4959f82e52.png)

**Comment by hisashiburii** [comment]
THIS IS SO REAL ADD THISSSS

**Comment by farazkaleemmalik** [comment]
take
