### ISSUE TITLE
Rewrite in HTML

### ISSUE THREAD

**Issue by imPrathamDev** [twitter/the-algorithm#662]
Haters will says HTML is not programming language

**Comment by RocketRaccoon27** [comment]
Looking into this

**Comment by RafaBlockDev** [comment]
AHAHAA bro wtf 💀

**Comment by imPrathamDev** [comment]
> AHAHAA bro wtf 💀

This is for those Influencers who are trying to show off about they know the algorithm but the reality is that they only know one thing that there are four types of users. In sarcasm I saying rewrite in html so they can show off more 😂
