### ISSUE TITLE
GitHub Discussions

### ISSUE THREAD

**Issue by ElijahPepe** [twitter/the-algorithm#663]
There's been a fair bit of _decision_ discussions in the issues section of this repository. As someone who uses GitHub quite a bit, GitHub Issues can be cumbersome to hold discussions over.

Fortunately, there is a solution here, that being GitHub Discussions. I'm quite a fan of Discussions, and I believe that it would cut back on some of the backlog in the issues section.

**Comment by PickleNik** [comment]
dup #418 which was dup #372
