### ISSUE TITLE
Claims to be pro-free speech. Closes issues.

### ISSUE THREAD

**Issue by RocketRaccoon27** [twitter/the-algorithm#666]
Literally 1984

**Comment by leafstrat** [comment]
> Literally 1984

![soy9](https://user-images.githubusercontent.com/4014775/229265831-cce50a90-b680-48ac-90d1-97d4fdfee794.png)

**Comment by Xpenzz** [comment]
Your life must be really sad.

**Comment by Amadeus-AI** [comment]
its totally normal to delete spam issue like #657 #656
this is github, not reddit

**Comment by GemedetAdept** [comment]
Ticket #666. Nice.
