### ISSUE TITLE
Seeing unexpected duplicates on home page

### ISSUE THREAD

**Issue by CamJohnson26** [twitter/the-algorithm#668]
**Describe the bug**
Hey guys, love my Twitter but I'm having some issues with the home page. 

**To Reproduce**
1. Go to twitter.com
2. Click on Home
3. Scroll down to 'useful content'
4. Spam posts without useful content are shown, often multiple posts of similar content. 

**Expected behavior**
When I scroll down I should see the useful content

**Screenshots**
![image](https://user-images.githubusercontent.com/5420592/229265624-3c7da7ac-2200-4ca2-bc2d-07a8cb1df58b.jpeg)

**Environment**
For web, specify your OS and browser version.  For mobile, specify device, OS
and version.  For libraries, what version of build tools are you using?

**Additional context**

**Comment by Xpenzz** [comment]
The 'For you' tab would provide a much better user experience if each tweet appeared only once.

**Comment by ValZapod** [comment]
> The 'For you' tab would provide a much better user experience if each tweet appeared only once.

I also notice horrible bug that deleted tweets vanish after 2 seconds you see them. It is dumb.

**Comment by jdm-twtr** [comment]
Thanks for filing. We've marked this issue as an unrelated bug or feature for future review.
                    In order to keep our issue count manageable, we will not be leaving these issues open. We apologize for
                    the inconvenience. If you feel that we closed your issue in error, please re-file the issue, stating how
                    the requested feature applies to the recommendation algorithm components that have been open-sourced thus far.
