### ISSUE TITLE
[New Feature] Add a social score

### ISSUE THREAD

**Issue by ludo6577** [twitter/the-algorithm#671]
**Is your feature request related to a problem? Please describe.**
No it's a new feature

**Describe the solution you'd like**
Add a social score (how much you will be recommended in the timeline)
Like StackOverflow for example :)

**Describe what you've considered**
Based on the score of how many people follow you, blocked you, your langage, etc...

**Comment by farazkaleemmalik** [comment]
+15 social credit

**Comment by TowhidKashem** [comment]
![image](https://user-images.githubusercontent.com/1139927/229266369-2cae8792-9b46-40cb-8c90-dd464db06adc.png)

**Comment by samdisk11** [comment]
-999999 social points, your existence scheduled to end later by CCP bing chilling 🤪

**Comment by ValZapod** [comment]
> ![image](https://user-images.githubusercontent.com/1139927/229266369-2cae8792-9b46-40cb-8c90-dd464db06adc.png)

Do not agree with that. It would be better than hiding that info shadowblock style with 1000 different fuxxing parameters. After all you can just use Nostr (https://github.com/vitorpamplona/amethyst) where the ability to ban people does not exist.

**Comment by ldmtwo** [comment]
What is your rationale or desired outcome from this? What does it add to the life of a Twitter user? Which users would want it and why?

I'm on the fence because I like knowing things, but it seems more depressing than encouraging. Perhaps a dashboard (list of counters) would be more appropriate. Impressions, likes, follows, ... over time and agg'd over week/month/year. Idk if these are available somewhere, but those would be worth a blue check.

**Comment by ValZapod** [comment]
>Idk if these are available somewhere, but those would be worth a blue check.

LOL, what? Of course they are available. Live: https://socialblade.com/twitter/user/elonmusk

And from twitter itself: https://analytics.twitter.com

No one cares except for influencers for this. No, internal stuff is much more important.

**Comment by StarHorder** [comment]
its only ok when the usa does it.

**Comment by samdisk11** [comment]
bruh

**Comment by darkdevildeath** [comment]
Well, if I can say something about this issue, it's that I have always questioned the proportionality of a person posting something like:
"I'm going to kill my boss for demanding too much work"
And, despite being a metaphor, getting their account suspended.
While a guy who kills 10 people and is wanted by the law for this crime can continue to post freely.

**Comment by PaulNewton** [comment]
This is just a bad name for an accounts/posts calculated boost score.
 
But really they've already added this as a different feature called twitter blue and is $8/mth.

**Comment by jdm-twtr** [comment]
Thanks for filing. We've marked this issue as an unrelated bug or feature for future review.
                    In order to keep our issue count manageable, we will not be leaving these issues open. We apologize for
                    the inconvenience. If you feel that we closed your issue in error, please re-file the issue, stating how
                    the requested feature applies to the recommendation algorithm components that have been open-sourced thus far.
