### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by WANI12** [twitter/the-algorithm#681]
**Is your feature request related to a problem? Please describe.**
 
Recommendation and push notifications for people who have not turned on notifications for a given account 

**Describe the solution you'd like**
Like if I follow an account and the account gives valuable information I would like to have a notifications on that account most of the time so the algorithm should be able to push notifications for recommendations to my account or the user account.

**Describe alternatives you've considered**
There is no issue if the notifications are push based on topics interested in by the user 

**Additional context**

**Comment by jdm-twtr** [comment]
Thanks for filing. We've marked this issue as an unrelated bug or feature for future review.
                    In order to keep our issue count manageable, we will not be leaving these issues open. We apologize for
                    the inconvenience. If you feel that we closed your issue in error, please re-file the issue, stating how
                    the requested feature applies to the recommendation algorithm components that have been open-sourced thus far.
