### ISSUE TITLE
Fail Whale still in Twitter Jail

### ISSUE THREAD

**Issue by cherylcline** [twitter/the-algorithm#683]
Free the whale! You can't keep it locked up, this isn't Sea World
![image](https://user-images.githubusercontent.com/4733977/229266621-76229ca4-552a-4583-af0f-6e607153fc1b.png)

**Comment by tboggia** [comment]
@elonmusk how much should we charge users to free the Fail whale??

**Comment by Tantomile** [comment]
if twitter frees the fail whale i will buy twitter blue

**Comment by jdm-twtr** [comment]
Thanks for filing. We've marked this issue as an unrelated bug or feature for future review.
                    In order to keep our issue count manageable, we will not be leaving these issues open. We apologize for
                    the inconvenience. If you feel that we closed your issue in error, please re-file the issue, stating how
                    the requested feature applies to the recommendation algorithm components that have been open-sourced thus far.
