### ISSUE TITLE
Rewrite in Holy C for simplicity

### ISSUE THREAD

**Issue by exydos222** [twitter/the-algorithm#686]
Missing out big time not being able to run this on god's temple

**Comment by yagihime** [comment]
i think g-d was right when they said the commodore 64 is our ancestral land

**Comment by ValZapod** [comment]
Javascript still uses C++ code, you know that? v8 is not just written in C++ but it uses as C math library fdlibm.

https://chromium-review.googlesource.com/c/v8/v8/+/1403018
