### ISSUE TITLE
Issue with element loading

### ISSUE THREAD

**Issue by GemedetAdept** [twitter/the-algorithm#688]
My recommended feed appears to be bugged. I've disabled my ad blocker, turned off my Tampermoney scripts, and restarted my browser, but it hasn't worked. My assumption is that there's some edge case with my user data where it doesn't fit into some category. 

Taking a shot in the dark, this could be the result of an egregiously small sample size. For instance, a singular person who just so happens to own the entire company. Or maybe a glaringly polarized set of subjective political categories which are *oddly* based around a single country (weird for a globally reaching website). If that *is* the case, I would sure hope that those values weren't hard-coded into the code and then removed right after the repo became public, with the hope that no-one would look at a commit which specifically described the function of the code that was removed.

Anyways, hope this gets looked into!

**Comment by jdm-twtr** [comment]
Thanks for filing. We've marked this issue as an unrelated bug or feature for future review.
                    In order to keep our issue count manageable, we will not be leaving these issues open. We apologize for
                    the inconvenience. If you feel that we closed your issue in error, please re-file the issue, stating how
                    the requested feature applies to the recommendation algorithm components that have been open-sourced thus far.
