### ISSUE TITLE
Add a spam/troll detection GitHub action to auto close/label non sense issues and pull request 

### ISSUE THREAD

**Issue by kevincobain2000** [twitter/the-algorithm#689]
**Is your feature request related to a problem? Please describe.**

It is hard to navigate to real issues or suggestions since many issues posted by users here are non sense. 

**Describe the solution you'd like**

A simple spam detection GitHub action can be added and triggered upon new issue and new pull req, that can auto label it as duplicate/spam or close upon high confidence. 

**Describe alternatives you've considered**

**Additional context**
Current issues posted by users are self explanatory

**Comment by tas-pro** [comment]
You could probably just make a Github action check the account age instead of making and training AI to detect if an spam/duplicate issue. Or, Twitter can get moderators to deal with nonsense issues/pull requests.

**Comment by kevincobain2000** [comment]
Yes @tas-pro 
a combination of features can make it robust.

**Comment by tas-pro** [comment]
> Yes @tas-pro a combination of features can make it robust.

The amount of spam is temporary and will probably last a week, so training an AI would be pointless in that regard, as useful as it could be.

**Comment by leafstrat** [comment]
It's not a big deal these people will lose interest soon enough.

**Comment by ConnieCommie** [comment]
![9fc](https://user-images.githubusercontent.com/54904227/229269221-9feb42bc-521b-46a0-a1be-6d0b1826f2da.gif)

**Comment by thecutefinder** [comment]
All Genshin Impact players should be either incarcerated or castrated. There is no cure.

The idea to write this came to me after seeing an ad on the subway that asks Genshin Impact players to seek therapy.

Over the last decades more soft handed politics have became mainstream. Genshin Impact players have become more open, lurking here and there on Twitter and Reddit and people have started to sympathize with them. How many times did you hear the phrase "I don't mind Genshin Impact players, they're just human, only if they actually commit a crime should they be prosecuted!"

There is no cure for Genshin Impact. Once a Genshin Impact player, always a Genshin Impact player. It is not an illness, it's a sexuality. People have been trying to "cure" anime for thousands of years too and it didn't work, what makes Genshin Impact any different?

"How dare you compare anime to Genshin Impact?" I have nothing against anime watchers and im happy they can be more open about it nowadays, but stop pretending Genshin Impact is not somehow a sexuality too. "It's a curable illness" that's what people said about anime watchers in the 19th century too. There has never been a single Genshin Impact player who got cured through therapy or medicine. This is a fact.

They will eventually stop resisting their urges and start fapping to child pornography, and then go on to kidnap a child. Don't believe me? Go a month without jerking off and tell me how you feel.

And don't even go to the "Genshin Impact stops them from actually raping a kid" argument, child sexual abuse rates in Japan have increased drastically over the last decades, parallel with the rise of Genshin Impact. Genshin Impact should be illegal and everyone caught playing it immediately jailed. You wouldn't play it if you weren't a Genshin Impact player, I'm not gonna discuss that.

Anyone who plays Genshin Impact obviously wishes that to be reality. No one would rather play it than to experience the real thing.

The only acceptable Genshin Impact player in society is he who shuts his mouth about it his entire life and represses it forever until he's dead. And if he realizes he gets a boner whenever he sees a kid he should castrate himself. THIS is the only Genshin Impact player society should ever accept, the one who castrates himself and doesn't do shit. But that's like 1% of Genshin Impact players. All others should be forcefully castrated or put in jail. Furthermore any advocation for Genshin Impact player rights should be illegal too, free speech exists for political freedom, not for Genshin Impact players on reddit to help each other to stay off the radar.

I found once a post on a German subreddit where a Genshin Impact player admitted everything and all the comments sympathized with him and explained to him thoroughly how to build his Ganyu and where to find guides to clear the Spiral Abyss. Any person helping Genshin Impact players should be punished by the government too, I have never been more disgusted by the internet than that day.

Children are the most innocent and compassionate beings on our earth. Genshin Impact players want to harm kids and traumatize them for life just for their own pleasure. They are the most evil people on this planet. If you ask me and the fact that over the last century age of consent worldwide has risen alot and Genshin Impact players have been prosecuted more harshly is one of the greatest achievements of the modern era (for example in Delaware the age of consent used to be 7 years and in France it was nonexistent). Let’s make sure we're not going backwards.

**Comment by kairusds** [comment]
> All Genshin Impact players should be either incarcerated or castrated. There is no cure.
> 
> The idea to write this came to me after seeing an ad on the subway that asks Genshin Impact players to seek therapy.
> 
> Over the last decades more soft handed politics have became mainstream. Genshin Impact players have become more open, lurking here and there on Twitter and Reddit and people have started to sympathize with them. How many times did you hear the phrase "I don't mind Genshin Impact players, they're just human, only if they actually commit a crime should they be prosecuted!"
> 
> There is no cure for Genshin Impact. Once a Genshin Impact player, always a Genshin Impact player. It is not an illness, it's a sexuality. People have been trying to "cure" anime for thousands of years too and it didn't work, what makes Genshin Impact any different?
> 
> "How dare you compare anime to Genshin Impact?" I have nothing against anime watchers and im happy they can be more open about it nowadays, but stop pretending Genshin Impact is not somehow a sexuality too. "It's a curable illness" that's what people said about anime watchers in the 19th century too. There has never been a single Genshin Impact player who got cured through therapy or medicine. This is a fact.
> 
> They will eventually stop resisting their urges and start fapping to child pornography, and then go on to kidnap a child. Don't believe me? Go a month without jerking off and tell me how you feel.
> 
> And don't even go to the "Genshin Impact stops them from actually raping a kid" argument, child sexual abuse rates in Japan have increased drastically over the last decades, parallel with the rise of Genshin Impact. Genshin Impact should be illegal and everyone caught playing it immediately jailed. You wouldn't play it if you weren't a Genshin Impact player, I'm not gonna discuss that.
> 
> Anyone who plays Genshin Impact obviously wishes that to be reality. No one would rather play it than to experience the real thing.
> 
> The only acceptable Genshin Impact player in society is he who shuts his mouth about it his entire life and represses it forever until he's dead. And if he realizes he gets a boner whenever he sees a kid he should castrate himself. THIS is the only Genshin Impact player society should ever accept, the one who castrates himself and doesn't do shit. But that's like 1% of Genshin Impact players. All others should be forcefully castrated or put in jail. Furthermore any advocation for Genshin Impact player rights should be illegal too, free speech exists for political freedom, not for Genshin Impact players on reddit to help each other to stay off the radar.
> 
> I found once a post on a German subreddit where a Genshin Impact player admitted everything and all the comments sympathized with him and explained to him thoroughly how to build his Ganyu and where to find guides to clear the Spiral Abyss. Any person helping Genshin Impact players should be punished by the government too, I have never been more disgusted by the internet than that day.
> 
> Children are the most innocent and compassionate beings on our earth. Genshin Impact players want to harm kids and traumatize them for life just for their own pleasure. They are the most evil people on this planet. If you ask me and the fact that over the last century age of consent worldwide has risen alot and Genshin Impact players have been prosecuted more harshly is one of the greatest achievements of the modern era (for example in Delaware the age of consent used to be 7 years and in France it was nonexistent). Let’s make sure we're not going backwards.

you good bro?

**Comment by thecutefinder** [comment]
It's a copypasta.

**Comment by thecutefinder** [comment]
Your opinion is stupid. There is no other human being that makes an opinion this dreadfully stupid. In fact, it is so stupid, that I can just assume that you are as stupid as the opinion you made (or even more stupid, actually) and it probably wouldn't even be a fallacy of equivocation.
    You're a Redditor, particularly someone who constantly looks into [r/teenagers](https://teddit.net/r/teenagers) and [r/confessions](https://teddit.net/r/confessions) to give horrible advice.
    You use Twitter. You look at bad takes and unironically agree with them.
    You use Discord.
    Most of what you know comes from Quora. It would have been fine if the people you got your information from were legitimate professionals, but as far as I can tell the information you know is from those "Which post deserves [arbitrary value greater than 10000] upvotes?" questions.
    You think Boku no Pico is a good anime. Even this particular reason alone already proves why your opinion could never be accepted as valid even by the vilest of internet users.
    You are very stereotypical.
    The statistics you include are unfair. The data you gathered comes from a population size of 1 - which is yourself - and your only source of information is "trust me bro". Honestly, I can see why you never got into college.
    The grammar and punctuation you use to state your opinion are way off. Now, I can see why most people don't feel the need to capitalize the first letter of their sentences or add a period at the end, but your grammar is so bad that I have to wonder if you ever went to school at all.
    You use ad ignorantiam in almost all of your arguments. And the ones that don't use ad ignorantiam use ad baculum.
    You can't accept the fact that there exist people who have opinions that differ from yours. And frankly, any other opinion would be more acceptable than yours. I can see why you have no friends.
    You are subscribed to N&A Productions. That's a huge red flag. I don't think anyone would be respecting the opinions of anyone who watches that lunacy, let alone accept it.
    You support Trump.
    You are stupid. Utterly uneducated. I have to reiterate how stupid you are because you're too stupid to even realize how stupid you are. Your IQ is probably 1 divided by the sum of the absolute values of the IQ of everyone else. And you're too stupid to know what "sum" and "absolute value" are. Opinions from uneducated people are usually unreliable - but in your case, it's completely guaranteed unreliable.
    You think Elden Ring is a bad game. No one agrees with you.
    You think Facebook is the best social media platform.
    You are an obsessive Elon Musk fan.
    You are broke. If you can't properly handle your own money how much more for your own thoughts? If you had ten grand for every living thing that has existed and currently exists, it would come in the form of debt. And you're probably even more broke than that.
    You are a Flat Earther and Anti-vaxxer. Not only are your opinions invalid, but even your "facts" as well.
    You are an incel.
    You couldn't even get a job to accrue your own income. The closest you ever got to a proper "job" was as a Discord kitten in 3 servers with less than 40 members each.
    Your opinion is based on pseudoscience.
    Your opinion is absurd.
    You could not even tell the difference between "their" and "there". But as I said, you are stupid beyond this level.
    Your opinion isn't a hot take. It falls flat with the rest of your other opinions. But even the Twittards that make the dumbest takes on Twitter could not agree with you no matter how idiotic they are.
    You are lonely. Posting goofy nonsense on the Internet such as the opinion you have is your only way of getting attention. And even that doesn't work because in the end you're still lonely and no one likes you.
    You're an incel. I have to reiterate this because you're that lonely. You'll always be single.
    You're a joke. The kind of joke that no one laughs or even smiles at - not even the person who told the joke.
    You're a bigot.
    You're a hypocrite. Especially in your claims about not being a desperate attention seeker.
    You know nothing about relationships since you've never been in one, save for your obsession with the dakimakura you have in your mold-filled ultra-stinker loser bedroom. And even then the anime character never liked you back and never knew you existed.
    Your opinion is out of touch. You lack even the most basic of human interaction to know standard human preferences and principles.
    You lack common sense.
    You try to be funny with the way you present your opinion, even adding in a few jokes, but it doesn't work and it never will. There's not even a single "lol" or "lmao" coming from anyone else. Just disappointment.
    You support MAP Pride. That's a bad sign. Even children by just looking at you have a sense of awareness and know not to approach you.
    You like lolis. That's also a bad sign.
    You have a micropenis. Extremely small. So small in fact that if an atom was the size of the observable universe then your schlong would be half the size of a quark.
    You don't shave. Your excess hair makes you look like a giant furball more than an actual human being. (I guess that makes sense since you don't think like an actual human being.)
    You use the skull, nerd, and clown emoji in the wrong places. Even using those emojis against you would be an insult to the emojis.
    Your opinion is garbage. It's a good thing it's at least biodegradable.
    You're immature. Even the yolk of a soft-boiled egg has more knowledge than you do.
    Your response to people with differing opinions is "ratio" and "IDC". And even that fails because your opinion is so bad that even the moderators have to ban you for displaying that level of stupidity and arrogance.
    Your opinion sucks. It just does.
    You can't cope.
    You panic whenever someone posts their own opinion.
    Your opinion lacks anything even mildly interesting or engaging.
    You make up false stories and claims about your life to try and get friends. But you're apparently very socially awkward and embarrassing to talk to so it never works. I don't trust the opinions of someone who makes false claims.
    You're a League player.
    You're pathetic. No existing therapy or medical approach could ever fix your broken state of mind.
    You claim to love Breaking Bad and Better Call Saul yet have never actually watched either one. You're a chronic liar.
    You invest in cryptocurrency.
    You also invest in NFTs. Definitely the reason why you're broke. And you even look like the Board Apes you purchase, except the Board Apes actually have a chance of looking cool. And they aren't fat.
    You claim that being obese is not a bad thing. Medical evidence suggests otherwise. And no, that isn't body positivity, that's being unhealthy. This further invalidates any opinions you have about fat people.
    You're adopted.
    Your opinion lacks coherence.
    Your opinion also lacks clarity. But even then it's still understandable enough to know that it is the worst possible opinion to have ever been formed in the history of humanity.
    Your opinion has no legitimate research studies to back up your claims.
    You think listening to music is a waste of time.
    You depend on fallacies as proof of your claims, which further invalidates your opinion.
    You have an OnlyFans account. Good thing no one ever paid for your toenail pictures.
    You're insecure.
    Your opinion is outright wrong.
    Your lifestyle is infected with horrible "life hacks" from 5-Minute Crafts.
    You fund some of the worst kickstarters ever. How do you expect anyone to take your opinion seriously if you think that funding DNA Time Capsules and Smart Plastic Straws is worth it?
    Your opinion violates the rules.
    You don't know what Nintendo is.
    You think that attempting to troll random people on the internet (which always fails, mind you) is the best way of spending the time you have. You are a hopeless figure. Neither your parents nor your foster parents could support you in anything you do.
    You can't think properly. You even have problems with your breathing patterns because you're too busy being stupid.
    Your two childhood favorites are Jake Paul and Logan Paul.
    You lack guidance.
    You're a leecher.
    You're a janitor in every FPS game you play. And even then you suck ass because you only get 1 kill steal every 6 hours of playtime.
    You threaten to doxx people that do not agree with you. And even then the information you publicize is blatantly from their profile's front page.
    You use neopronouns.
    You use hashtags without knowing what they actually stand for.
    You are a Dream stan.
    You think that all Asians are either Chinese, Japanese, or Korean.
    You support the Klu Klux Klan.
    Your opinion is disgusting.
    Your opinion is not well-constructed.
    You lack courtesy.
    Your ego is overinflated.
    You falsely believe that your opinion is the only correct opinion and could not accept different perspectives on the topic.
    You desperately include addendums to your opinions trying to convince people to accept them via ad misericordiam. But your stories aren't convincing.
    You bought into the CryptoZoo idea.
    You're deranged.
    Your opinion does not incite civil and friendly discussions and arguments. Everyone instead shames and reports you because of your opinion.
    You are unwanted.
    You use depression as an excuse.
    You are immature.
    You use AirPods.
    Your opinion is extremely unbased.
    Everyone disagrees with your opinion.
    You're a neonazi.
    You only watch anime with a lot of fanservice in them. This is why you always have been and always will be single.
    When someone asks you (with aggression, of course) why you have that opinion, you fall back to using circulus in demonstrando.
    All your other opinions sucked ass. What makes you think we'll find this one different?
    You are a trainwreck. An abomination. A menace to human society. Except instead of being scary, you're being stupid and almost no one cares about you or your brainrotted opinions.
    The premises of your arguments are blatantly false.
    ploopy

**Comment by jdm-twtr** [comment]
Thanks for the suggestion!
