### ISSUE TITLE
Is it an April FOOL ? 

### ISSUE THREAD

**Issue by ludo6577** [twitter/the-algorithm#690]
April fool? Commits date are in disorder (git --push). Look at the first comment :)

And some Elon, democrat, republican code removed in the last (first?) commit...

![TortoiseGitMerge_2023-04-01_06-45-09](https://user-images.githubusercontent.com/1528846/229267017-436d49ef-6f47-44b3-ace8-b605eaa69da5.png)

**Comment by aerphanas** [comment]
i also think it's april fools
