### ISSUE TITLE
Adding Crypto AI to Feature

### ISSUE THREAD

**Issue by crypto-ai-git** [twitter/the-algorithm#694]
Using Crypto AI Artist by cai.codes as a feature for Twitter Improvement.

**Comment by jdm-twtr** [comment]
Thanks for filing. We've marked this issue as an unrelated bug or feature for future review.
                    In order to keep our issue count manageable, we will not be leaving these issues open. We apologize for
                    the inconvenience. If you feel that we closed your issue in error, please re-file the issue, stating how
                    the requested feature applies to the recommendation algorithm components that have been open-sourced thus far.
