### ISSUE TITLE
1 april

### ISSUE THREAD

**Issue by MadTooth** [twitter/the-algorithm#698]

**Comment by ludo6577** [comment]
April fool? Commits date are in disorder (git --push). Look at the first comment :)  

And some Elon, democrat, republican code removed in the last (first?) commit...

![TortoiseGitMerge_2023-04-01_06-45-09](https://user-images.githubusercontent.com/1528846/229267416-98d91d6f-2f78-45e2-9e1b-ea6d79a8c53d.png)
