### ISSUE TITLE
April Fools?

### ISSUE THREAD

**Issue by jayfrostjay** [twitter/the-algorithm#700]

**Comment by ludo6577** [comment]
April fool? Commits date are in disorder (git --push). Look at the first comment :)

And some Elon, democrat, Republican code removed in the last (first?) commit...

![TortoiseGitMerge_2023-04-01_06-45-09](https://user-images.githubusercontent.com/1528846/229268437-68e6a256-d665-4dfc-9282-59c275faca88.png)
