### ISSUE TITLE
Ability to mass filter/block all users with an onlyfans or similar links in their bio.

### ISSUE THREAD

**Issue by CharAznableLoNZ** [twitter/the-algorithm#701]
**Is your feature request related to a problem? Please describe.**
E-Thots images often clog up the feed and make the user experience not worth using.  I want nothing to do with these bottom of the barrel wastes of bandwidth.
**Describe the solution you'd like**
I would like the ability to mass block or filter out all users that contain onlyfans or similar links in their bios.
**Describe alternatives you've considered**
Manually blocking them is time consuming and requires me to open their profile then block them.  I have to stop every time to block the new offending content.
**Additional context**

**Comment by fanfare** [comment]
there used to be an extension that had similar functionality called [DoucheBlock](https://github.com/MobileFirstLLC/doucheblock) but within the past few months it started having some issues. i wouldn't be surprised if there are other extensions that do the same thing though

**Comment by CharAznableLoNZ** [comment]
I'll have to look into extensions further.  It would just be nice kind of quality of life feature was part of the base site itself.

**Comment by preland** [comment]
Ngl I actually think this would be a good idea

**Comment by delgh1** [comment]
Our company is developing a time travel machine once elon daddy is bored with his starship which look like a giagantic d*ldo.
Please stay tuned!

**Comment by CharAznableLoNZ** [comment]
It's too bad this repo was just a joke by twitter and will never be looked at or any ideas used.  It could actually do the platform some good to take some feedback and ideas.

**Comment by jdm-twtr** [comment]
Thanks for filing. We've marked this issue as an unrelated bug or feature for future review.
                    In order to keep our issue count manageable, we will not be leaving these issues open. We apologize for
                    the inconvenience. If you feel that we closed your issue in error, please re-file the issue, stating how
                    the requested feature applies to the recommendation algorithm components that have been open-sourced thus far.

**Comment by adampm2** [comment]
> **Is your feature request related to a problem? Please describe.** A clear and concise description of what the problem is. Ex. I'm always frustrated when [...] E-Thots images often clog up the feed and make the user experience not worth using. I want nothing to do with these bottom of the barrel wastes of bandwidth. **Describe the solution you'd like** A clear and concise description of what you want to happen. I would like the ability to mass block or filter out all users that contain onlyfans or similar links in their bios. **Describe alternatives you've considered** A clear and concise description of any alternative solutions or features you've considered. Manually blocking them is time consuming and requires me to open their profile then block them. I have to stop every time to block the new offending content. **Additional context** Add any other context or screenshots about the feature request here.


just use the muted words functionality to mute the website they advertise.
