### ISSUE TITLE
Rewrite in Rust

### ISSUE THREAD

**Issue by TasfiqulTapu** [twitter/the-algorithm#703]
Current implementation seems to be missing Rust and that makes Twitter a D tier company. Rewriting in Rust will allow faster cancelling and happy devs.

**Comment by zhangbo2008** [comment]
what about go

**Comment by deeprobin** [comment]
R e w r i t e
I n
**R u s t**!!!

**Comment by 0ur4n05** [comment]
Absolutely agree

**Comment by 0ur4n05** [comment]
The only one problem is compile time, compiling the algorithm would take years
