### ISSUE TITLE
So what editors do you guys like to use?

### ISSUE THREAD

**Issue by riscmkv** [twitter/the-algorithm#707]
I like VS code but I think vim is pretty nice too

**Comment by slim-python** [comment]
i'm sigma notepad user

**Comment by shivam-Purohit** [comment]
i write code on paper and feed that to my cat. She gives me the output.

**Comment by thecutefinder** [comment]
VS Codium

**Comment by ValZapod** [comment]
I prefer GPU accelerated editors. CUDAText or sublime text or even faster and better stuff that can parse 1 TB text files even. I use EMedit for example or other https://stackoverflow.com/questions/159521/text-editor-to-open-big-giant-huge-large-text-files

But of course Visual Studio 2022 is best, it is x64 app. :)

**Comment by jtbx** [comment]
vim is awesome.

**Comment by hinell** [comment]
At twtitter, we are using `neovim`. That's it!

**Comment by akamicah** [comment]
Jetbrains ftw for everything. Then I print all the code out on A4 paper (no word wrap) and send it to a code reviewer in a filing box

**Comment by anshumankmr** [comment]
I code using Punch cards.
/s

I like VSCode and Sublime.

**Comment by ValZapod** [comment]
> code out on A4 paper (no word wrap) and send it to a code reviewer in a filing box

That is what AlphaZero did. Chess paper had code inside. It did not stop the copy paste https://github.com/LeelaChessZero/lc0 guys to becomes best in the world, even for some time better than Stockfish.

**Comment by delgh1** [comment]
nano

**Comment by preland** [comment]
**pulsar will consume all others**

**Man cannot escape**

**Comment by sijirama** [comment]
Neovim

**Comment by draygen** [comment]
emacs

**Comment by yrncollo** [comment]
Worked for twitter and we always used vim

**Comment by Strypper** [comment]
> i write code on paper and feed that to my cat. She gives me the output.

Weak I speak my code loudly and let the compiler figuring out.

**Comment by ValZapod** [comment]
> > i write code on paper and feed that to my cat. She gives me the output.
> 
> Weak I speak my code loudly into the recorder and feed compiler.

Google voice can do it, Samsung voice not so much. I want to think about code and let GPT 4 continue it.

**Comment by dynastyoak** [comment]
i use my brain to write and compile the code

**Comment by yrncollo** [comment]
> i use my brain to write and compile the code

You are the weirdo.... I thought you use your hands to write it like other normal human beings... fsck

**Comment by ValZapod** [comment]
> > i use my brain to write and compile the code
> 
> You are the weirdo.... I thought you use your hands to write it like other normal human beings... fsck

Maybe he meant on this sense: https://youtu.be/-HYbFm67Gs8

**Comment by dynastyoak** [comment]
> > i use my brain to write and compile the code
> 
> You are the weirdo.... I thought you use your hands to write it like other normal human beings... fsck

u guys write? 💀

**Comment by NotCallMeHacker** [comment]
I switch bits on my HDD manually

**Comment by jdm-twtr** [comment]
Thanks for the discussion -- closing the issue as nothing is actionable here.
