### ISSUE TITLE
is this a april fool by elon?

### ISSUE THREAD

**Issue by oyepriyansh** [twitter/the-algorithm#709]

**Comment by ludo6577** [comment]
April fool? Commits date are in disorder (git --push). Look at the first comment :)

And some Elon, democrat, Republican code removed in the last (first?) commit...

![TortoiseGitMerge_2023-04-01_06-45-09](https://user-images.githubusercontent.com/1528846/229268532-16c9f8bb-9a66-42c8-86a4-b015ab8b17dd.png)

**Comment by oyepriyansh** [comment]
maybe a preplanned april fool, btw whats elon github username?

**Comment by ValZapod** [comment]
> April fool? Commits date are in disorder (git --push). Look at the first comment :)
> 
> And some Elon, democrat, Republican code removed in the last (first?) commit...
> 
> ![TortoiseGitMerge_2023-04-01_06-45-09](https://user-images.githubusercontent.com/1528846/229268532-16c9f8bb-9a66-42c8-86a4-b015ab8b17dd.png)

Nvidia also did not publish commit history. They are afraid of parsing names in the commit messages. https://github.com/NVIDIA/open-gpu-kernel-modules

**Comment by oyepriyansh** [comment]
i asked for elon github account link

**Comment by AlphaHot** [comment]
Oh no, very sad story. 😢
