### ISSUE TITLE
Ability to time travel and delete our old cringe tweets.

### ISSUE THREAD

**Issue by SBasu-7870** [twitter/the-algorithm#711]
Pls pls pls I aboslutely need to go back in time so that I can restart and not be be a sore loser like i am rn. Please pls pls

**Comment by thecutefinder** [comment]
![229250531-af8a1bf0-ba36-40ca-b314-1e5beafc3e04](https://user-images.githubusercontent.com/123335166/229270038-31c4e601-c130-40a3-a111-0e85b3c9059c.jpg)

**Comment by delgh1** [comment]
Our company is developing a time travel machine once elon daddy is bored with his starship which look like a giagantic d*ldo, as .
Please stay tuned!

> ![229250531-af8a1bf0-ba36-40ca-b314-1e5beafc3e04](https://user-images.githubusercontent.com/123335166/229270038-31c4e601-c130-40a3-a111-0e85b3c9059c.jpg)
