### ISSUE TITLE
Rehire your engineers.

### ISSUE THREAD

**Issue by sanjit-sinha** [twitter/the-algorithm#714]
Instead of getting trolled on GitHub, rehire your engineers. Don't expect the open source community to do free labor.

**Comment by exeandino** [comment]
Well eventually it's getting done

**Comment by logicP** [comment]
Honestly? What if we could have both? Bring the engineers back AND make the code open source in some way

**Comment by cyzanfar** [comment]
you’re completely missing the point of open sourcing the algo. The fact that it would lead to some amount of “free labor” is not important. What’s significant is that ANYBODY can contribute and impact the way millions of people consume information  everyday.

**Comment by 5idneyD** [comment]
Are you talking about the real engineers or the fake ones who just wanted to get on the news?

**Comment by baroxyton** [comment]
why when there's chatGTP?

**Comment by sanjit-sinha** [comment]
@cyzanfar Yeah your point is completely valid, However i believe that Elon Musk's decision to make the code open-source was to gain popularity by claiming that yes our algorithm is open source, while also possibly hoping to utilize free labor.

**Comment by sanjit-sinha** [comment]
@logicP That should be the best of both world but i don't think this gonna happen. And Twitter is degrading itself day by day. 

> Honestly? What if we could have both? Bring the engineers back AND make the code open source in some way

**Comment by sanjit-sinha** [comment]
@baroxyton Maybe this become true after chat gpt 6 or 7. Lol

> why when there's chatGTP?
