### ISSUE TITLE
Add support for playing Doom WADs

### ISSUE THREAD

**Issue by Gamiac** [twitter/the-algorithm#715]
Twitter should respect this time-honored tradition by adding the ability to run Doom on it. AO3 can do it, why can't Twitter?

**Comment by nzgamer41** [comment]
+1 very necessary. Twitter won't let us run bots that play doom by posting PNG screenshots of doom anymore, this should obviously be because they've integrated the engine into the website.

**Comment by jordanforbes** [comment]
Finally a ticket addressing a real issue.
