### ISSUE TITLE
make the bird sing the reddit anthem

### ISSUE THREAD

**Issue by LeBoufty** [twitter/the-algorithm#742]
-Opening

Who are we?? REDDIT NATION!! What do we want?? NNO MORE TIKTOK AND INSTAGRAM!! When do we want it?? NOW!

-Chorus starts

Reddit nation yeah we are Together we can go very far Take down tik tok Take down instagram Take down everything we dont give a damn That's because reddit nation will rise up Yeah we never will give up

We the reddit army We hoard the enemy like a skarmy (clash royale sound effect) We cant be taken down Yeah you cant make us frown When tiktok sees our army Im sure their pants will brown

**Comment by RingoManju** [comment]
The narwhal bacons at midnight!

**Comment by jdm-twtr** [comment]
Thanks for filing. We've marked this issue as an unrelated bug or feature for future review.
                    In order to keep our issue count manageable, we will not be leaving these issues open. We apologize for
                    the inconvenience. If you feel that we closed your issue in error, please re-file the issue, stating how
                    the requested feature applies to the recommendation algorithm components that have been open-sourced thus far.
