### ISSUE TITLE
Day-Day-Daytrip took it to ten (Hey) Ayy, Panini, don't you be a meanie Thought you wanted me to go up Why you tryna keep me teeny? I It's a dream, he wished it on a genie I got fans finally, ain't you wanting them to see me? I I thought you want this for my life, for my life Said you wanted to see me thrive, you lied Just say to me what you want from me Just say to me what you want from me Ayy, Panini, don't you be a meanie Thought you wanted me to go up Why you tryna keep me teeny now? Now they need me, number one on streamin' Oh yeah, you used to love me So what happened, what's the meaning? I I thought you want this for my life, for my life Said you wanted to see me thrive, you lied Now when it's all done, I get the upper hand I need a big Benz, not another fan But I still want you as a fan I'ma need to sit down, don't mean to make demands But I need you to... Say to me what you want from me Just say to me what you want from me D-D-Daytrip took it to ten (Hey)

### ISSUE THREAD

**Issue by VainXploits** [twitter/the-algorithm#747]
Day-Day-Daytrip took it to ten (Hey)
Ayy, Panini, don't you be a meanie
Thought you wanted me to go up
Why you tryna keep me teeny? I
It's a dream, he wished it on a genie
I got fans finally, ain't you wanting them to see me? I
I thought you want this for my life, for my life
Said you wanted to see me thrive, you lied
Just say to me what you want from me
Just say to me what you want from me
Ayy, Panini, don't you be a meanie
Thought you wanted me to go up
Why you tryna keep me teeny now?
Now they need me, number one on streamin'
Oh yeah, you used to love me
So what happened, what's the meaning? I
I thought you want this for my life, for my life
Said you wanted to see me thrive, you lied
Now when it's all done, I get the upper hand
I need a big Benz, not another fan
But I still want you as a fan
I'ma need to sit down, don't mean to make demands
But I need you to...
Say to me what you want from me
Just say to me what you want from me
D-D-Daytrip took it to ten (Hey)

**Comment by souravjamwal77** [comment]
@twitter-service 
This issue also seems like a spam.

**Comment by VainXploits** [comment]
> @twitter-service
> This issue also seems like a spam.

who asked

**Comment by jdm-twtr** [comment]
This issue was closed due to possibility of spam. Please re-file with a useful title and description.

**Comment by VainXploits** [comment]
who asked
