### ISSUE TITLE
[feature req] Blue check -- dashboard, metrics, and extra incentives (marketplace) for pro users only.

### ISSUE THREAD

**Issue by ldmtwo** [twitter/the-algorithm#749]
Problem: Users are unhappy about $/mo. Why? The value is not obvious or not enough.

Proposal: Add feedback, metrics, and other incentives for pro users. Getting boosted is great, but it would mean more to content creators if the blue check added privately viewable internal stats and tips for improvement (explainability). Other incentives could be an internal marketplace for advertisers to match with influencers where Twitter takes a cut and those pro users can start to bank off views.

Example: Perhaps a DS style dashboard (list of agg'd counters/metrics, charts over time) with docs? Impressions, likes, follows, ... over time and agg'd over week/month/year. Idk if these are available somewhere, but those would be worth a blue check. Any extra features like this could be removed from 99% of people.

**Comment by thecutefinder** [comment]
Abbanes, Abe, Aberaku, Adelinde, Adler, Adonis, Afshin, Aftab, Agafya, Ahangar, Aikawa Susumu, Aka, Akame Kanenaga, Akame Mitsunaga, Akashi, Akira, Akito, Ako Domeki, Akram, Akuou, Albedo, Albert, Alfred, Alfry, Alhaitham, Alice, Allan, Alois, Aloy, Alphonso, Alrani, Amano, Amber, Amber's Grandfather, Amenoma Tougo, Amenoma Yuuya, Amir, Amos, Anastasia, Andou, Andrei, Andrius, Anisa, Anna, Anshun, Antei, Anthon, Anthony, Anton, Anzai, Ao, Aoi, Aoki, Arakawa Kouji, Aramis, Arataki Itto, Aratani, Aravinay, Archaic Lord of Lightning and Blitz, Aria, Sonnet and Canon, Arisawa, Arlecchino, Arnold, Arthur, Aru, Arundolyn, Asagiri, Asakawa, Asakura, Asami, Asano, Asase Hibiki, Ash, Ashpazi, Asilah, Athos, Atsuko, Aunt Qiao, Aurelius, Ayame, Ayesha, Azar, Azhdaha, Baishi, Baiwen, Baixiao, Baizhu, Bao'er, Barbara, Barbatos, Barca Lawrence, Barnabas, Beatrice, Bei'er, Beidou, Beisht, Belinda, Ben, Bennett, Bertrand, Bibo, Big G, Big Xu, Big-Footed Dajiao, Blanche, Blazing Heart, Bloodstained Knight, Blue-Eyed Spear Witch, Bluffy, Bolai, Bonanus, Borenka, Boris, Bosacius, Boyang, Boyi, Brass Bull Zhao, Bravo, Bro Huang, Brook, Brother Qian, Bruce, Brunn, Brutish Samurai, Bu'yun, Butrus, Butterfly, Buzuleac, Cai Le, Cai Xun, Caishan, Candace, Captain Wu, Cardinal Calvin, Carmen, Carpe Diem, Caspar, Chai Yi, Chan'er, Chang the Ninth, Changchang, Changfeng, Changgui, Changhu, Changping, Changsheng, Changshun, Chao, Chaonan, Chaoxi, Charles, Chef Mao, Chen the Flower, Chen the Sharp, Chenxiang, Chevka, Chi, Chiaki, Chiba, Childish Jiang, Chise, Chloris, Chongyun, Chouji, Chouji's Mother, Chubby, Chunshui, Chuyi, Clerk Zhao, Clitopho, Cloud Retainer, Clymene, Collei, Columbina, Conductor, Congzi, Connor, Crafty, Crepus, Crimson Cyclone, Cui'er, Curious Zi'rui, Cyno, Cyrus, Daimon, Dainsleif, Daipai, Daisuke, Daler, Dalong, Dandan, Dandy, Danila, Darina, Date, Davy, Dawnlight Swordswoman, Dayu, Decarabian, Defu, Degui, Dehya, Denjirou, Diluc, Diona, Domon, Dongdong, Dongsheng, Donna, Doolan, Dori, Dr. Edith, Dr. Livingstone, Draff, Dragon of Water, Dragonheir of the Depths, Dugu Shuo, Dummy, Dunyarzad, Durin, Dusky Ming, Dvalin, Eberhart, Ebina Gonshirou, Eboshi, Echo, Edna, Effendi, Efim Snezhevich, Ei, Eiin, Eiko, Eita, Ekaterina, Eki, Ella Musk, Ellin, Elzer, Ema, Enjou, Enomoto, Enteka, Erfan, Erge, Ernest, Eroch, Esther, Etsu, Eula, Eury, Fadhlan, Fan Er'ye, Farbod, Fariha, Farooq, Farrah, Fatui Guard, Fei the Flyer, Felix, Female Believer, Fengyan, Ferrylady, Firnas, Fischl, Fischl's Father, Fischl's Mother, Flagpole Cheng, Flash-Fist Ling, Fleein' Lin, Flora, Francis, Freckle Huang, Frederica Gunnhildr, Freki, Fritz, Frozen Soul, Fu San'er, Fugui, Fujiki, Fujita Sanshirou, Fujiwara Toshiko, Fukami, Fukumoto, Furong, Furusawa, Furuta, Furuya Noboru, Furuyama, Fushizome, Futaba, Futsu Hiroyoshi, Futsu Masayoshi, Futsu Minori, Futuh, Félix Yogue, Gaiman, Gama, Ganyu, Gao Fei, Gao the Sixth, Garcia, Gendou Ringo, Genta, Gentry De'an, Gentry Maocai, Genzou, Gerald, Geri, Glory, God of Justice, Goddess of Flowers, Godwin, Golden Alligator, Gongjun, Gongming, Gorou, Gotelinde, Goth, Gou, Gou San'er, Grace, Grand Thief, Granny Chu, Granny Oni, Granny Ruoxin, Granny Shan, Great Merchant Huang, Greater Lord Rukkhadevata, Greedy Guard, Greg, Guan Hong, Guangzhu, Guanhai, Guhua, Gui'an, Guizhong, Gulabgir, Gummer, Gunnhildr, Guoba, Guy, Gygax, Gyoubu Koban, Hachihou, Haishan, Hajanad, Hajime, Hakushin, Halfdan, Hamawi, Hammer Li, Han Ce, Han Wu, Hana, Hanachirusato, Hanayama Kaoru, Hanbei, Hanfeng, "Cold Blade", Hanshirou, Hanxue, Hao, Hardworking Silio, Harris, Harrison, Harry, Hartman, Haruto, Hasegawa, Hashimoto, Hatanaka, Havria, Hayato, Haypasia, Hayyan, Heihachi, Helen, Heli, Henning, Henry Morton, Herbalist Gui, Herman, Hertha, Hideaki, Hideo, Hiiragi Chisato, Hiiragi Hiroshi, Hiiragi Shinsuke, Hillie, Hirai, Hiraizumi, Hirano, Hiratsuka, Hirayama, Hiroaki, Hirohiko, Hiromi, Hironori, Hiroshi, Hirotatsu, Hiroyuki, Hisahiko, Hisashi, Hishida, Holderlin, Hongdou, Hongfei, Honglang, Hongru, Hongxing, Hongyi, Hongyu, Hopkins the Marvelous, Hosseini, Hu Tao, Huachu, Huai'an, Huangshan, Huaqing, Huffman, Hughes, Hui, Huihui, Huixin, Huixing, Hulu, Hypermarket, Iansan, Iba, Ide, Idhari, Ikeda Soushirou, Ikuhara Gai, Il Capitano, Il Dottore, Ilyin, Imaizumi, Imatani Kaori, Imatani Keisuke, Imatani Saburou, Immernacht Fischl, Imunlaukr, Inaba Kyuuzou, Inaba Shizuko, Inagi Hotomi, Inagi Misato, Indarias, Ingbert, Inou, Inoue, Inu Shoushou, Ion, Ioroi, Iotham, Ipe, Ippei, Iraj, Iris, Irmin, Iron Ingot, Iron Shoulder, Iron Tongue Tian, Ishida, Ishihara, Ishikawa, Ishikawa Hachirou, Ishizaki, Istaroth, Isumenasu, Itaru, Ivan, Ivanovich, Iwakura Doukei, Iwakura Mitsunari, Iwao, Iwata, Izumi Naki, Izzard, Jack, Jacob Musk, Janome Gonbei, Javert, Jean, Jehiet, Ji, Ji Tong, Jiaming, Jiangcheng, Jiangxue, Jiangzhou, Jianqiu, Jiawei, Jiayi, Jifang, Jiichirou, Jill, Jilliana, Jingcheng, Jingda, Jinglun, Jingming, Jinwu, Jinyou, Jinzhong, Jiu, Jixiang, Joel, Jonas, Jones, Joserf, Jotun, Joyce, Ju'an, Julie, Junjun, Junkichi, Junming, Junpei, Junya, Jut, Juza, Jürgen, Kabasawa, Kabayama, Kadenokouji Kenzaburou, Kaede, Kaedehara Hisamichi, Kaedehara Kageharu, Kaedehara Kagemitsu, Kaedehara Kazuha, Kaedehara Yoshinori, Kaeya, Kagawa, Kageyama, Kaida Ryouma, Kaiser, Kaito, Kaji, Kama, Kamal, Kamei Munehisa, Kamisato Ayaka, Kamisato Ayato, Kamisato Kayo, Kamran, Kamuna Harunosuke, Kangsheng, Kanjou Commission Ashigaru, Kano Nana, Kanra, Kapatcir, Karpillia, Katarina, Katayama, Katayama Tatsumi, Katayoun, Katheryne, Katou Shingo, Katou Youhei, Katsuie, Katsuragi, Kaushik, Kaveh, Kavus, Kayabuki Ikkei, Kayama Tadao, Kazuaki, Kazuha's Friend, Kazumasa, Kazumichi, Keiichi, Keijirou, Ken, Kenji, Kenjirou, Kenzaburou, Keon, Keqing, Khedive, Kichiboushi, Kid Kujirai, Kiminami Anna, Kimura, Kina, Kinjiro, Kinoshita, Kira, Kitain Bunsou, Kitamura, Kito, Kitsune Saiguu, Kiyoe, Kiyoko, Kiyoto, Klee, Kliment, Klutzy Bazi, Knotty, Kobayashi, Koharu, Komakata, Komaki, Konbumaru, Konda Densuke, Konrad, Kosekimaru, Kotomi, Kouichi, Kourosh, Kousaka, Kousuke, Koutoku, Kouzen, Koyama, Koyanagi, Kozue, Kreuzlied, Krosl, Krupp, Ku, Kubo, Kujirai Momiji, Kujou Kamaji, Kujou Masahito, Kujou Sara, Kujou Takayuki, Kuki Shinobu, Kumi, Kun, Kun Jun, Kunwu, Kurai, Kurisu, Kuroda, Kurosawa Kyounosuke, Kurotani Seishimaru, Kyouta, La Signora, Laid Back Ling'guan, Lambad, Lan, Landa, Landrich, Lanxi, Lanyang, Lao Cai, Lao Ke, Lawrence, Layth, Le Goff, Leming, Lenne, Leno, Leon, Leonard, Lesser Lord Kusanali, Li Dang, Li Ding, Li the Ninth, Li Xiao, Li'an, Liang, Liben, Licai, Lily, Lind, Ling, Linlang, Linling, Linyang, Lisa, Little Bin, Little De, Little Fei, Little Le, Little Liu, Little Long, Little Lulu, Little Luo, Little Meng, Little Nine, Little Que'er, Little Uwe, Little Wu, Little Xing, Little Yi, Little You, Little Yue, Little Zuo, Liuliu, Lively Orlean, Lizheng, Lizzie, Lord Lawrence, Lorgar, Loumelat, Lu Zheng, Luka, Luke, Luo Feng, Luo Qiao, Luocheng, Luoxia, Luther, Lutong, Lynette, Lyney, Lynn, Lyra, Lyudmila, Lyudochka Snezhevna, Mack, Madame Ping, Madame Qin, Madarame Hyakubei, Maeda, Mahiru, Maki, Makiri, Makoto, Maksim, Male Believer, Mamesuke, Mamoru, Manager Kuan, Manager Xiao, Manie, Manly Jack, Margaret, Mari, Marjorie, Marla, Marvin, Masakatsu, Masanobu, Masanori, Masashi, Masato, Master Hui, Master Lu, Master of Stars, Master Qin "Thunder Hand", Master Zhang, Mata, Matsuda, Matsudaira, Matsukawa Souzen, Matsumoto, Matsuura, Matsuzaka, Mawyo, Meng, Meng Dan, Mengmeng, Menogias, Mercantile Believer, Meshi, Message-Runner, Michelle, Michiru, Michiya, Midori, Mifune Satoshi, Mikawa Akane, Mikhail, Mikoshi Chiyo, Mikoshi Genichirou, Mikoshi Genjirou, Mikoshi Nagamasa, Miles, Minamoto Kotomi, Mingbo, Mingjun, Minoo, Mirai, Mishima Michitoshi, Miss Bu, Miss Ruoyu, Missing Miners, Mister Qi, Misuzu, Miu, Miura, Miwa, Miyajima, Miyazaki, Miyazaki Saburou, Miyuki, Mo, Mochizuki, Moco, Moli, Momoka, Momoko, Momoyo, Mona, Mona's Master, Monroe, Moon Carver, Mora-Grubber, Morax, Moriguchi, Morihiko, Motosuke, Mountain Shaper, Mouun, Mr. Bohuan, Mr. Iron Abacus, Mr. Nine, Mr. Qiang, Mr. Zhu, Mrs. Kuki, Ms. Bai, Ms. Yu, Mu Chen, Muganna, Mumu, Muning, Murakami, Murata, Murata (NPC), Murayama, Musheng, Muzhen, Mysterious Shadow, Myweiss, Nabiya, Nadia, Nagano, Naganohara Ryuunosuke, Nagaoka Hidemitsu, Nagase, Nagato Sachiko, Nahida, Najia, Nakanishi, Nakano, Nakano Shino, Nakatani, Nameless, Nameless Bard, Nami, Nanako, Nanao, Nannan, Nantuck, Naoe Hisamasa, Naruse, Nasrin, Nathan, Nazafarin, Nei, Neko, Nelson, Nelson (Cat), Nervous An, Nick, Nigina, Nikolay, Nilou, Nima, Nimrod, Ningguang, Nishiguchi, Nishikino Reirei, Niu Zhi, Niwa Nagamitsu, Nizam, Nobuhiro, Nobumori, Nobuo, Noelle, Nogata, Nonno, Nora, Norika, Norma, Norman, Nosaki, Nozomu, Nymph, Obata, Oda Tarou, Ogawa, Ogura Mio, Ogura Yuu, Okabayashi, Okawara Goemon, Okazaki Erika, Okazaki Kunihiko, Okazaki Rikuto, Okazaki Toraemon, Olaf, Old Chou, Old Finch, Old-School Qi, Onitaka, Onkami, Ono, Onoda, Onodera, Oogura, Ooizumi, Ookubo Daisuke, Ookubo Sanzaemon, Oomori, Ooshima, Ooshima Junpei, Oosuke, Ootomo, Orban, Orobashi, Orupeusu, Osial, Otogi King, Otto, Owada, Oz, Paimon, Paisley, Pam, Pan Guan'er, Panicked Myrana, Pantalone, Parsifal, Parsley, Parvaneh, Patchi the Curious, Patrice, Patrol Soldier, Patton, Pavel, Payne, Pengyi, Pepe, Persikov, Pervases, Phanes, Philby, Pierro, Pika, Pinghai, Piramumon, Plauen, Pops Kai, Pops Xing, Pops Zhou, Porthos, Primordial Albedo, Primordial One, Prince, Princess of Sal Vindagnyr, Priscilla, Pulcinella, Pursina, Pyotr, Qi Ding, Qi Nan, Qian, Qiang the Brave, Qianqian, Qianwei, Qiaoxi, Qilang, Qiming, Qinglian, Qingzhou, Qiping, Qiqi, Qishan, Qiu'ge, Qiuyue, Quinn, Radomir, Rafiq, Ragnvindr, Raiden Shogun, Raku, Rama, Ramsay, Rana, Randall, Raptor, Ravenwood, Raymond, Razor, Real Stanley, Reckless Pallad, Recuperated Victim, Red-Haired Warrior, Reed Miller, Reekwind, Reiichi, Reika, Reizenbou, Ren, Ren'yu, Rero, Rhinedottir, Richie, Rie, Riese, Rifaet, Rika, Rikoru, Riku, Rima, Risutaiosu, Roald, Robert, Roger, Rongjiang, Rongshi, Rongzhao, Ronin, Rosaria, Rosemary, Ross the Quick, Rostam, Rouran, Royce, Rudaba, Rudolf, Ruijin, Ruu, Ruyi, Ryouhei, Ryouko, Ryuuji, Sag, Sage, Saigou, Saika, Saimon Eri, Saimon Jirou, Saimon Katsumi, Saizou, Sakai, Sakamoto, Sakujirou, Sakuya, Sanada, Sanden, Sandrone, Sango, Sangonomiya Kokomi, Sansa, Sara, Sasaki, Sasano, Sasayuri, Satomi, Satoru, Satou, Sayid, Sayo, Sayu, Sayuri, Scar Liu, Scaramouche, Scarlet King, Schubert, Schulz, Scrooge, Scullion, Sea Drake, Sea Gazer, Seamus Pegg, Second Who Came, Seigou, Sergei, Sha'yin, Shanghua, Sharp, Shatir, Sheng, Shenhe, Shibasuke, Shibata, Shigeru, Shigeyori Kujou, Shiho, Shikanoin Heizou, Shiki Taishou, Shiliu, Shima Masaoki, Shimada Shichirouji, Shimizu, Shimura Kanbei, Shinnojou, Shinozuka, Shiori, Shirai, Shirin, Shitoki, Shitou, Shiyu, Shiyun, Shizhuang the Strong, Shizuru, Shohre, Short-Tempered Wallit, Shouji, Shousei, Shousen, Shouta, Shu'yang, Shun, Shuuhei, Shuzhi, Siegfria, Siqin, Sirafi, Sisi, Sitt, Six-Fingered José, Siyu, Skipper, Skirk, Skybracer, Skyrider, Slacking Angelo, Sleepy, Slick Wu, Slippery, Slippery Wu, Smiley Yanxiao, Sneaky Wu, Sojourner, Soraya, Souta, Spring Fairy, Squirrel, Stanley, Stevens, Strong, Sturdy Wu, Su Er'niang, Sucrose, Sudabeh, Sue Yoshitaka, Sugimoto, Sugiyama, Suling, Sumi, Sumida, Sun Yu, Supada no Hiko, Surepio, Susan, Susie, Suspicious Citizen, Swan, Tac, Tacit Tingfang, Tadakatsu, Tadao, Tae, Tai, Taisuke, Takahashi, Takami, Takamine the Mistsplitter, Takasaka Izumi, Takashi, Takatoshi, Takatsukasa Chika, Takatsukasa Isamu, Takatsukasa Susumu, Takatsukasa Tokibeitetsu, Takatsukasa Tomohide, Takayama, Takeda, Takeru, Takeshi, Taketani, Takeuchi, Takizawa Kyouden, Takuma, Takuya, Taliesin, Tanaka, Tanba Tetsuo, Tang Wen, Tang Wuchou, Taraneh, Taroumaru, Tartaglia, Tea Master Liu Su, Tejima, Temur, Teppei, Terada, Terrified Magar, Terrified Schuster, Teruyo, Tetsuo, Teucer, The Berserker, The Fang, The Halberd, The Shogun, Theofan, Third Sis, Thoma, Tia, Tiancheng, Tiantian, Tianyi, Tic, Tie Hong, Tieshan, Tiger Li, Tighnari, Timaeus, Timid Guard, Timid Morrow, Timmie, Tingting, Toda, Todoroki, Toe, Tokuda, Tokunaga, Tommy, Tomoki, Tonia, Toranosuke, Toratarou, Toshihiko, Traveler, Traveler's Sibling, Troubled Lianne, Tsarevich, Tsaritsa, Tsukishiro, Tsumi, Tsuneo, Tsuyuko, Tu, Tubby, Tuman, Tunner, Tyler, Uchimura, Uda, Ueno, Uesugi, Ukko, Ulfr, Ulman, Umm, Una, Uncle Dai, Uncle Gao, Uncle Ghast, Uncle Hai, Uncle He, Uncle Jia, Uncle Liu, Uncle Sun, Uncle Tian, Uncle Yun, Uncle Zhao, Uncle Zhu, Unknown God, Unnamed Gladiator, Urakusai, Ursa the Drake, Ushi, Utsumi, Uwe, Vadim, Vahid, Varka, Varuch, Venerare, Vennessa, Venti, Vermeer, Verr Goldet, Victoria, Viktor, Vile, Vind, Viridescent, Vlad, Wagner, Wai, Wakamurasaki, Wakayama Keisuke, Wang, Wang Ping'an, Wang'ya, Wanyan, Wanyu, Washizu, Watanabe, Wei, Wei (Cat), Wei Fengchen, Wenjing, Wenyuan, Wenze, Werner, Will, Wood (NPC), Wrench Wang, Wupei, Wuyuan, Wyatt, Wyratt, Xamaran, Xavier, Xi the Maid, Xi'er, Xiangling, Xiangming, Xiangsheng, Xiao, Xiaofei, Xiaoyan, Xiling, Xin Cheng, Xinghuo, Xingqiu, Xingxi, Xingxiu, Xinxiu, Xinyan, Xinyan's Father, Xinyan's Mother, Xiuhua, Xiuyong, Xixi, Xu, Xu Liushi, Xuanfan, Xudong, Yabe, Yabuki, Yae Miko, Yagi, Yakov, Yamada, Yamada Hifumi, Yamamoto, Yamashiro Kenta, Yamaue, Yan'er, Yanagiha Arashi, Yanbo, Yanfei, Yang, Yano Machiko, Yaoyao, Yasuaki, Yasuda, Yasuhiko Tarou, Yasuhisa, Yasumoto, Yasutake, Yata Kouki, Yayoi Nanatsuki, Yegor, Yelan, Yi Xian, Yi Zhu, Yi'nian, Yicheng, Yijian, Yikuo, Ying'er, Yingfeng, Yingzhu, Yinxing, Yiran, Yixuan, Ylgr, Yoh, Yohanan, Yoichi, Yoimiya, Yokoyama, Yong'an, Yonggui, Yongye, Yoshihisa, Yoshikawa, Yoshitaka, You Jun, Youkou, Yousuke, Youta, Youxu, Yu, Yuan Cheng, Yuan Hong, Yuan Liang, Yuan Qing, Yuan Rong, Yue Chuan, Yuehui, Yueshu, Yuhua, Yuka, Yukio, Yukiya, Yuma, Yun Huang, Yun Hui, Yun Jin, Yuna, Yundan, Yunjiang, Yunning, Yurika, Yusupov, Yuugo, Yuuko, Yuuri, Yuusaku, Yuuya, Yuuzou, Yuyan, Yuzu, Zadith, Zakhar, Zexuan, Zhang Shun, Zhe'yuan, Zhen Qiang, Zheng, Zhengmao, Zhenhai, Zhenxiang, Zhi, Zhicheng, Zhihua, Zhiping, Zhiqiao, Zhiqiong, Zhiruo, Zhiyi, Zhizhi, Zhong, Zhongli, Zhonglin, Zhouliang, Zhu Ming, Zhu Tao, Zhuhan, Zhuoying, Zhuyu, Zinat, Ziwei

**Comment by jdm-twtr** [comment]
Thanks for filing. We've marked this issue as an unrelated bug or feature for future review.
                    In order to keep our issue count manageable, we will not be leaving these issues open. We apologize for
                    the inconvenience. If you feel that we closed your issue in error, please re-file the issue, stating how
                    the requested feature applies to the recommendation algorithm components that have been open-sourced thus far.
