### ISSUE TITLE
Is it an April FOOL? 

### ISSUE THREAD

**Issue by Alex-McAvoy** [twitter/the-algorithm#754]
👋 👋 👋

**Comment by Mac0r0ni** [comment]
Go away

**Comment by XaurDesu** [comment]
i mean i'm basically treating it as one so yeah ig

**Comment by dagelf** [comment]
![image](https://user-images.githubusercontent.com/802628/229302463-89af007a-c94f-4895-9db1-1fed4e74edcf.png)

**Comment by dagelf** [comment]
"Maximum trust. Maximum transparency. Verbatim" https://twitter.com/i/spaces/1jMJgLdenVjxL

**Comment by dagelf** [comment]
Transcript: https://gist.github.com/dagelf/bfd5e61f067e5350362d57b28e5ed4e4

**Comment by jdm-twtr** [comment]
This issue was closed due to one of these reasons: likelihood of spam, not enough context, or possibly inappropriate content. Please re-file with a useful title and description.
