### ISSUE TITLE
i'm just gonna leave this out rq

### ISSUE THREAD

**Issue by bagasdisini** [twitter/the-algorithm#755]
![image](https://user-images.githubusercontent.com/110382959/229272127-2a751dbb-5591-41bc-808a-ea0ba97846bc.png)

**Comment by XaurDesu** [comment]
cool cat

**Comment by bagasdisini** [comment]
> cool cat

ikr 🥰

**Comment by jdm-twtr** [comment]
This issue was closed due to possibility of spam. Please re-file with a useful title and description.
