### ISSUE TITLE
These issues and pull requests are so pathetic...

### ISSUE THREAD

**Issue by irekrog** [twitter/the-algorithm#759]
🤷🏻‍♂️

**Comment by thecutefinder** [comment]
What the fuck did you just fucking say about me, you little bitch? I'll have you know I graduated top of my class in the Navy Seals, and I've been involved in numerous secret raids on Al-Quaeda, and I have over 300 confirmed kills. I am trained in gorilla warfare and I'm the top sniper in the entire US armed forces. You are nothing to me but just another target. I will wipe you the fuck out with precision the likes of which has never been seen before on this Earth, mark my fucking words. You think you can get away with saying that shit to me over the Internet? Think again, fucker. As we speak I am contacting my secret network of spies across the USA and your IP is being traced right now so you better prepare for the storm, maggot. The storm that wipes out the pathetic little thing you call your life. You're fucking dead, kid. I can be anywhere, anytime, and I can kill you in over seven hundred ways, and that's just with my bare hands. Not only am I extensively trained in unarmed combat, but I have access to the entire arsenal of the United States Marine Corps and I will use it to its full extent to wipe your miserable ass off the face of the continent, you little shit. If only you could have known what unholy retribution your little "clever" comment was about to bring down upon you, maybe you would have held your fucking tongue. But you couldn't, you didn't, and now you're paying the price, you goddamn idiot. I will shit fury all over you and you will drown in it. You're fucking dead, kiddo.

**Comment by thecutefinder** [comment]
Cringe, you just added those reacts to your own PR:
![image](https://user-images.githubusercontent.com/123335166/229272373-2b5b6169-3e53-4786-a87e-951fd91f1017.png)
![image](https://user-images.githubusercontent.com/123335166/229272380-159acb3a-1b46-4e20-a3c2-944792bd0f64.png)
![image](https://user-images.githubusercontent.com/123335166/229272384-42fb96fa-5ada-4186-9339-45c4ab252523.png)
![image](https://user-images.githubusercontent.com/123335166/229272392-d951764d-b93f-4fbd-8e1a-ebb266841bde.png)

**Comment by irekrog** [comment]
Lol man it is fake, are you really have a time for photoshop?

> Cringe, you just added those reacts to your own PR: ![image](https://user-images.githubusercontent.com/123335166/229272373-2b5b6169-3e53-4786-a87e-951fd91f1017.png) ![image](https://user-images.githubusercontent.com/123335166/229272380-159acb3a-1b46-4e20-a3c2-944792bd0f64.png) ![image](https://user-images.githubusercontent.com/123335166/229272384-42fb96fa-5ada-4186-9339-45c4ab252523.png) ![image](https://user-images.githubusercontent.com/123335166/229272392-d951764d-b93f-4fbd-8e1a-ebb266841bde.png)

**Comment by bagasdisini** [comment]
🤓

**Comment by thecutefinder** [comment]
> Lol man it is fake, are you really have a time for photoshop?
> 
> > Cringe, you just added those reacts to your own PR: ![image](https://user-images.githubusercontent.com/123335166/229272373-2b5b6169-3e53-4786-a87e-951fd91f1017.png) ![image](https://user-images.githubusercontent.com/123335166/229272380-159acb3a-1b46-4e20-a3c2-944792bd0f64.png) ![image](https://user-images.githubusercontent.com/123335166/229272384-42fb96fa-5ada-4186-9339-45c4ab252523.png) ![image](https://user-images.githubusercontent.com/123335166/229272392-d951764d-b93f-4fbd-8e1a-ebb266841bde.png)

🤦

**Comment by Corgile** [comment]
> What the fuck did you just fucking say about me, you little bitch? I'll have you know I graduated top of my class in the Navy Seals, and I've been involved in numerous secret raids on Al-Quaeda, and I have over 300 confirmed kills. I am trained i...

戾气这么大去挑大粪好了

**Comment by ItsAleph** [comment]
> What the fuck did you just fucking say about me, you little bitch? I'll have you know I graduated top of my class in the Navy Seals, and I've been involved in numerous secret raids on Al-Quaeda, and I have over 300 confirmed kills. I am trained in gorilla warfare and I'm the top sniper in the entire US armed forces. You are nothing to me but just another target. I will wipe you the fuck out with precision the likes of which has never been seen before on this Earth, mark my fucking words. You think you can get away with saying that shit to me over the Internet? Think again, fucker. As we speak I am contacting my secret network of spies across the USA and your IP is being traced right now so you better prepare for the storm, maggot. The storm that wipes out the pathetic little thing you call your life. You're fucking dead, kid. I can be anywhere, anytime, and I can kill you in over seven hundred ways, and that's just with my bare hands. Not only am I extensively trained in unarmed combat, but I have access to the entire arsenal of the United States Marine Corps and I will use it to its full extent to wipe your miserable ass off the face of the continent, you little shit. If only you could have known what unholy retribution your little "clever" comment was about to bring down upon you, maybe you would have held your fucking tongue. But you couldn't, you didn't, and now you're paying the price, you goddamn idiot. I will shit fury all over you and you will drown in it. You're fucking dead, kiddo.

No way packgod uses github sheesh

**Comment by jdm-twtr** [comment]
This issue was closed due to one of these reasons: likelihood of spam, not enough context, or possibly inappropriate content. Please re-file with a useful title and description.
