### ISSUE TITLE
do a good april fools joke

### ISSUE THREAD

**Issue by nebulazorua** [twitter/the-algorithm#782]
please do a good april fools joke next year

**Comment by dagelf** [comment]
![image](https://user-images.githubusercontent.com/802628/229302673-0ebd93a2-3d15-475d-8b31-b666017a09f3.png)

**Comment by dagelf** [comment]
![image](https://user-images.githubusercontent.com/802628/229302697-b2889c55-7244-4104-9156-bee85a1d902e.png)
