### ISSUE TITLE
Putin should be the new CEO of twitter

### ISSUE THREAD

**Issue by iadnanmalik** [twitter/the-algorithm#799]
Mother Twitter

**Comment by salman-ahmed979** [comment]
Russia Russia Russia SUUUUUUUUU!!!!!!!!!!!!!!!!!!!!!!111

**Comment by carrotfarmer** [comment]
+1 blyat

**Comment by Gamiac** [comment]
AHH MOTHERLAND

**Comment by jacobrogers256** [comment]
Let's wage blayatkreig!

**Comment by jdm-twtr** [comment]
This issue was closed due to one of these reasons: likelihood of spam, not enough context, or possibly inappropriate content. Please re-file with a useful title and description.
