### ISSUE TITLE
IMPORTANT

### ISSUE THREAD

**Issue by masreplay** [twitter/the-algorithm#8]
Guys please keep this place for real bugs and contributions, 🙏

**Comment by real2two** [comment]
+1

**Comment by Rafer45** [comment]
This itself is not a real bug or contribution and won't dissuade trolls...

**Comment by Heliodex** [comment]
-1

**Comment by cromatikap** [comment]
We agreed with you so we can close this issue 👌

**Comment by masreplay** [comment]
Ratio my self

**Comment by lalicmarko** [comment]
Vote Kanye 2024
