### ISSUE TITLE
Remove the code in the algorithm that boosts the tweets of Elon Musk's account 

### ISSUE THREAD

**Issue by jacobrogers256** [twitter/the-algorithm#80]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. I'm always frustrated when Elon appears in people's feeds without their consent.

**Describe the solution you'd like**
Could you remove the part of the algorithm that boosts Elon Musk's tweets?
**Describe alternatives you've considered**
No alternatives are in here except making a 3rd party client that filters out Elon Musk's tweets.

**Additional context**

**Comment by enzo-js** [comment]
This is the code btw https://github.com/twitter/the-algorithm/blob/7f90d0ca342b928b479b512ec51ac2c3821f5922/home-mixer/server/src/main/scala/com/twitter/home_mixer/functional_component/decorator/HomeTweetTypePredicates.scala#L225

**Comment by B3rry** [comment]
lgtm
