### ISSUE TITLE
Why scala ?

### ISSUE THREAD

**Issue by ebrardev** [twitter/the-algorithm#807]
we need learn scala ?

**Comment by ImperiumTakp** [comment]
it is a cool language

**Comment by He-Pin** [comment]
Why not Scala, drop Java!

**Comment by dagelf** [comment]
Why a bug report?

**Comment by tylerreisinger** [comment]
> Why not Scala, drop Java!

Why Scala, drop JVM!

**Comment by He-Pin** [comment]
> > Why not Scala, drop Java!
> 
> Why Scala, drop JVM!

drop rust first

**Comment by Jinxiansen** [comment]
![IMG_4170](https://user-images.githubusercontent.com/16829428/229286579-2f6fa886-0529-4978-b22d-077f51dd6bf1.JPG)

**Comment by jdm-twtr** [comment]
This issue was closed due to one of these reasons: likelihood of spam, not enough context, or possibly inappropriate content. Please re-file with a useful title and description.
