### ISSUE TITLE
[FEAT]: Hire Me :(

### ISSUE THREAD

**Issue by devvsakib** [twitter/the-algorithm#823]
Hey,
I'm a Frontend Developer. I'm currently looking for a job. Any type of job whether  it's full-time, part-time, or contract.

Tech Stack I use:
React, Tailwindcss, Nodejs, Express

<a href="mailto:devvsakib@gmail.com">SEND MAIL</a>
[Portfolio](https://devvsakib.me)
Check GitHub profile too

**Comment by said7388** [comment]
I have more expertise than you 😃. So why anyone will  hire you instead me🙂.

**Comment by devvsakib** [comment]
Ask yourself 😂😂😂😂😂😂😂😂😂😂 @said7388 . Showcase your expertise in the right place bro😪 Not here, and please behave yourself

**Comment by said7388** [comment]
> Ask yourself 😂😂😂😂😂😂😂😂😂😂 @said7388 . Showcase your expertise in the right place bro😪 Not here, and please behave yourself

Yeah it’s a job market 😃😃😃

**Comment by devvsakib** [comment]
yes, for people like you, who don't get jokes 😂😂😂 @said7388

**Comment by zhangbo2008** [comment]
> I have more expertise than you 😃. So why anyone will hire you instead me🙂.

why not open a company by yourself. sothat ican be employed by u. and i can help you spend your money very carefully and happily .

**Comment by devvsakib** [comment]
😂😂😂😂😂💯💯 @zhangbo2008
