### ISSUE TITLE
rewrite it in jsfuck

### ISSUE THREAD

**Issue by VierraButFox** [twitter/the-algorithm#828]
**Is your feature request related to a problem? Please describe.**
It's not in jsfuck

**Describe the solution you'd like**
make it jsfuck

**Describe alternatives you've considered**
no

**Additional context**
It'd be funny also buy rain world

**Comment by LorenzoBloedow** [comment]
May I suggest brainfuck? I just feel like it's more readable

**Comment by OblivionNoirV2** [comment]
Malbolge would be best
