### ISSUE TITLE
major security issue

### ISSUE THREAD

**Issue by xatikat** [twitter/the-algorithm#829]
im So silly
![summervacay](https://user-images.githubusercontent.com/111465068/229280942-81760861-063d-457b-a99c-baa93545e199.jpeg)

**Comment by TruncatedDinosour** [comment]
so goofy

**Comment by VierraButFox** [comment]
the silliest!

**Comment by otomir23** [comment]
bro is soo silly 🐈

**Comment by ItsRealmy** [comment]
how wacky, that cat
