### ISSUE TITLE
fix that fucking bug where tweets on web home feed just disappear

### ISSUE THREAD

**Issue by foxt** [twitter/the-algorithm#836]
**Describe the bug**

**To Reproduce**
1. use the web twitter
2. scroll home feed for a while
3. tweets will disappear on hover sometimes

**Expected behavior**
tweets fucking stay where they are

**Screenshots**

**Environment**
For web, specify your OS and browser version.  For mobile, specify device, OS
and version.  For libraries, what version of build tools are you using?

**Additional context**

**Comment by maydemirx** [comment]
The #funniest bug reporting i've ever seen. But you absoluetly right

**Comment by MatGalos** [comment]
Actual good issue, plz fix it elon

**Comment by jdm-twtr** [comment]
Thanks for filing. We've marked this issue as an unrelated bug or feature for future review.
                    In order to keep our issue count manageable, we will not be leaving these issues open. We apologize for
                    the inconvenience. If you feel that we closed your issue in error, please re-file the issue, stating how
                    the requested feature applies to the recommendation algorithm components that have been open-sourced thus far.
