### ISSUE TITLE
Rewrite in Mastodon

### ISSUE THREAD

**Issue by danielpunkass** [twitter/the-algorithm#84]

**Comment by mergesort** [comment]
🐘

**Comment by nonetrix** [comment]
But actually could the algorithm be adapted to Fediverse? Actually this isn't a terrible idea someone should fork it for this

**Comment by RageGamerBoi** [comment]
> Actually this isn't a terrible idea

But it **_is_** :eyes: 
Seriously, why do you think Twitter is the dumpster fire of the internet?
The Fediverse is good because it _doesn't_ have an algorithm...

**Comment by nonetrix** [comment]
You  don't have to use it, I think it would be just interesting project I wouldn't use it

**Comment by breakgimme** [comment]
> But actually could the algorithm be adapted to Fediverse? Actually this isn't a terrible idea someone should fork it for this

you would still have to train the models yourself as they didn't release them, at this point it would just be easier to rewrite it from scratch
