### ISSUE TITLE
Remove that silly feature that temporarily bans my account when I (playfully) break ToS

### ISSUE THREAD

**Issue by archibaldh** [twitter/the-algorithm#847]
**Is your feature request related to a problem? Please describe.**
It won't let me say certain things to certain people. This is a flaw in your platform.

**Describe the solution you'd like**
Remove the ToS. No one reads it anyway.

**Describe alternatives you've considered**
Let me break the law. I don't like some people. I should be able to tell them rude words.

**Comment by jdm-twtr** [comment]
Thanks for filing. We've marked this issue as an unrelated bug or feature for future review.
                    In order to keep our issue count manageable, we will not be leaving these issues open. We apologize for
                    the inconvenience. If you feel that we closed your issue in error, please re-file the issue, stating how
                    the requested feature applies to the recommendation algorithm components that have been open-sourced thus far.
