### ISSUE TITLE
Do you have paper or theory for support the algorithm?

### ISSUE THREAD

**Issue by hongda3141** [twitter/the-algorithm#851]

**Comment by AvivVetaro** [comment]
Test

**Comment by AvivVetaro** [comment]
Test

**Comment by nobodyindustries** [comment]
Yes

[HERE!](https://www.youtube.com/watch?v=dQw4w9WgXcQ&ab_channel=RickAstley)

**Comment by AmayX** [comment]
> Yes
> 
> [HERE!](https://www.youtube.com/watch?v=dQw4w9WgXcQ&ab_channel=RickAstley)

Bruh

**Comment by jdm-twtr** [comment]
This issue was closed due to lack of useful description.
