### ISSUE TITLE
lmaooo

### ISSUE THREAD

**Issue by dav1dxyz** [twitter/the-algorithm#857]
Rewrite in rust

**Comment by Naim2000** [comment]
![956265807703314502](https://user-images.githubusercontent.com/44107089/229287334-beee57a9-493b-4c8b-9ba1-354328b9859a.png)

**Comment by sudo-Mystic** [comment]
no write in Pythowo

**Comment by TruncatedDinosour** [comment]
no rewrite in C
ill kms if i see more memory safe and blazingly fast rust rewrites
A
