### ISSUE TITLE
Remove that bug that makes it so genshin players are allowed on the app

### ISSUE THREAD

**Issue by Draco-Dev** [twitter/the-algorithm#859]
Title is self explanatory. Dogshit game.

**Comment by nobodyindustries** [comment]
Let's please extend this to RAID: Shadow Legends as well, please

**Comment by impoverishedowl** [comment]
Hello, discrimination is against our policies here at twitter. Though we appreciate your time and support, thank you!

**Comment by PravithBA** [comment]
> Let's please extend this to RAID: Shadow Legends as well, please

And league of legends

**Comment by claudeisakeeb** [comment]
> > Let's please extend this to RAID: Shadow Legends as well, please
> 
> And league of legends

agreed

**Comment by Fortfite** [comment]
I'd like to request every moba player be banned
