### ISSUE TITLE
Any good first issue to start with

### ISSUE THREAD

**Issue by i-Am-GhOsT** [twitter/the-algorithm#868]
Looking for some beginner friendly issues. But there are no such lebels.

**Comment by davidteren** [comment]
One of the better issues opened.

**Comment by i-Am-GhOsT** [comment]
To start with, I can suggest that ReadMe.md needs some revamp. A more descriptive layout can help contributors go through the whole code base.

**Comment by i-Am-GhOsT** [comment]
> I had genuine PR's open (#304, #257), but they closed it without saying anything. Looks like they don't want outside help 🤷🏽 

Sign the CLA buddy.

**Comment by harshil21** [comment]
> Sign the CLA buddy.

I had done it for the first PR (before they closed it), but the second one is just glitchy and doesn't update. Yet another thing which is broken

**Comment by nobodyindustries** [comment]
There was one about the Ligma engine.

**Comment by impoverishedowl** [comment]
I think you should start working on the recently opened issues, they are easy to implement and shouldn't take too much time. If you do well enough, we may invite you to start working on boosting Elon Musk's posts, without paying you as you'll be working out of good will. 

Thank you for contribution!
