### ISSUE TITLE
Adding Tomita as a CI/CD supervisor

### ISSUE THREAD

**Issue by hopingsteam** [twitter/the-algorithm#874]
![tomita_deploying](https://user-images.githubusercontent.com/11734201/229289380-639c3cde-3dc7-43f8-94fd-f89b6fdee2ef.jpg)

**Is your feature request related to a problem? Please describe.**
Our integration tests have been lacking in terms of real-world simulation. We need a better way to test our code against bugs and errors that may arise in a live environment. Tomita, our orange stray cat, has shown to be an excellent bug catcher and can provide a more realistic test environment.

**Describe the solution you'd like**
We would like to add Tomita to our CI/CD pipeline for integration testing. This would involve setting up a dedicated testing environment for Tomita to run around in and catch bugs. We would also need to establish a way to monitor Tomita's activity and make sure he doesn't interfere with the codebase.

**Describe alternatives you've considered**
One alternative we've considered is using a virtual testing environment instead of a physical one with Tomita. However, this would not provide the same level of real-world simulation that Tomita could offer.

**Additional context**
We have attached a picture of Tomita for your reference. He is a very good cat and we believe he will make an excellent addition to our testing process.

![tomita_supervising](https://user-images.githubusercontent.com/11734201/229289385-5cc6a5eb-2e01-46dd-b18b-509c92189687.jpg)

**Comment by adrianarota** [comment]
Raising this to critical

**Comment by AlmightyLks** [comment]
I approve of this message.

**Comment by impoverishedowl** [comment]
Hello, we plan on working on adding your cat to our codebase after we finish working on increasing Elon Musk's tweet engagement.

Thank you for putting this issue into our attention, we appreciate it. Have a great day!

**Comment by TruncatedDinosour** [comment]
any progress ?

**Comment by tiagozip** [comment]
THIS IS IMPORTANT
DON'T CLOSE IT

**Comment by ar1ja** [comment]
> THIS IS IMPORTANT DON'T CLOSE IT

too late, sadly, twitter doesnt want to get any better just as https://github.com/twitter/the-algorithm/issues/871 and https://github.com/twitter/the-algorithm/issues/1935

**Comment by ghost** [comment]
libkat has been deprecated in favor of katqt
