### ISSUE TITLE
Classifying GitHub issues based on "seriousness"

### ISSUE THREAD

**Issue by jhoetter** [twitter/the-algorithm#881]
Dev team, I think you realize that there is a new todo on your stack: detecting troll issues in this issue section.

I already looked into it, and shared my findings in this repository here: https://github.com/code-kern-ai/twitter-issues-classifier

Let me know if I can be of any help. For real, not a troll.

**Comment by hopingsteam** [comment]
@jm-twtr - I've tagged you for visibility

**Comment by hopingsteam** [comment]
@jdm-twtr - tagging you for visibility

**Comment by jhoetter** [comment]
@KajeArch thanks for adding this. I think a quick action must follow, as issues are a main way to have contributions.

**Comment by nobodyindustries** [comment]
You really are a tryhard trying to work for free for a billionaire, are you?

**Comment by LeonardPuettmannKern** [comment]
The beauty of open-source

**Comment by nobodyindustries** [comment]
@LeonardPuettmannKern this code is not complete, does not compile and I am pretty sure it is not the code used in production. This is just pure and simple simping.

**Comment by meetpateltech** [comment]
Good idea!

**Comment by meetpateltech** [comment]
Good idea!

**Comment by elsyalkh** [comment]
[Thank you for this](https://www.youtube.com/watch?v=dQw4w9WgXcQ)

**Comment by G2G2G2G** [comment]
rewrite this in Rust

**Comment by impoverishedowl** [comment]
See PR #876, in addition to providing massive security and performance benefits, it may significantly help with this issue

**Comment by nobodyindustries** [comment]
@KajeArch Nobody forces you to do that either. The code does not compile. Stop simping, please.

**Comment by no-identd** [comment]
A lot of the troll issues here also stem from timezone confusion making a lot of people mistake this repo for an April fool's joke

**Comment by no-identd** [comment]
@hopingsteam \+ @niw @adam-singer

**Comment by no-identd** [comment]
Additional addition to the 'potential false positives' list:
* people genuinely confused about Scala (not trolls, but they can seem like it)

Which brings us to people which tend to respond to the above people, namely:
* Scala 2-bashers which bash 'Scala' because they last looked at Scala like a decade ago, haven't yet noticed that Scala 3 exists, & that it fixed all their complaints from yesterdecade (might be trolls, might not be trolls, who knows)
* Scala 3-bashers which bash 'Scala' because Scala 3 put an end to their deranged pipedream of turning Scala into a horrible Haskell clone (definitely mad trolls)

Not sure whether both of the latter already showed up (they tend to eventually show up in any conversation involving Scala), but there's definitely some very silly Anti-Scala FUD in various issues

**Comment by no-identd** [comment]
Additional addition to the 'potential false positives' list:
* people genuinely confused about Scala (not trolls, but they can seem like it)

Which brings us to people which tend to respond to the above people, namely:
* Scala 2-bashers which bash 'Scala' because they last looked at Scala like a decade ago, haven't yet noticed that Scala 3 exists, & that it fixed all their complaints from yesterdecade (might be trolls, might not be trolls, who knows)
* Scala 3-bashers which bash 'Scala' because Scala 3 put an end to their deranged pipedream of turning Scala into a horrible Haskell clone (definitely mad trolls)

Not sure whether both of the latter already showed up (they tend to eventually show up in any conversation involving Scala), but there's definitely some very silly Anti-Scala FUD in various issues

**Comment by impoverishedowl** [comment]
This repository is far from complete, their CI pipeline is literally a shell script with 'exit 0'. I don't know if this is an April Fools joke or that is actually what they use in production

**Comment by no-identd** [comment]
+ @jjh42

**Comment by no-identd** [comment]
@impoverishedowl neither, see https://github.com/twitter/the-algorithm/issues/907#issuecomment-1493036852

**Comment by NebelNidas** [comment]
I think the best solution would be to wait until the hype has died down, then delete this repository (or maybe just rename it) and create a fresh one

**Comment by errorware** [comment]
> You really are tryhards trying to work for free for a billionaire, are you?
> 
> Stop the simping, please

this

**Comment by arnavbhatt288** [comment]
> You really are tryhards trying to work for free for a billionaire, are you?
> 
> Stop the simping, please

>complaining about a billionaire on a platform funded and used by billionaires

**Comment by Higgs32584** [comment]
Thank you for your unpaid labor son ![image](https://user-images.githubusercontent.com/55243596/229308677-e5dc364d-edcb-40f6-85bd-61fb95aab962.jpeg)

**Comment by no-identd** [comment]
\+ @guimingTang

**Comment by jhoetter** [comment]
I completely get that people have a different view on Twitter/Elon in general, and I don't want to discuss this here. 

Though as a generally big fan of open-source, I hope that the community gets the two things:
(a) people, especially beginners in programming, should feel safe to contribute code to repositories. For many people, it is a way to learn new things, have fun, and to also boost their careers. I can stand some negativity, but maybe for someone more junior it is hard and will stop them from contributing. That is never good.
(b) Twitter is a big company, and big companies rarely make a step towards such big open-source releases of what previously has been proprietary. Yes, the repo isn't in a good state yet, that is true. But other companies will likely take a really close look now at this repository, its release, and how people react to it. So in the sense of open-source, I honestly just hope that their takeaway now isn't that open-sourcing will generally lead to the reactions that the Twitter repo is facing.

Everyone who today thought of contributing to Twitter - or any other open-source repo -, don't let anyone stop you :)

**Comment by Insticthere** [comment]
> You really are tryhards trying to work for free for a billionaire, are you?
> 
> Stop the simping, please

fr but the will ignore this as they are stuck in the billionaire propaganda

**Comment by pixiekat** [comment]
Contribute to the mastodon repo if you want to do something good for humanity.

![th-3513778528.jpg](https://user-images.githubusercontent.com/32232155/229311914-6a30e8b6-8b07-4c48-bab0-b88ad8729864.jpg)

**Comment by Menus74** [comment]
\>sToP siMpInG fOR bIlLiOnAiReS!!11
\>uses Github
People here are really stupid af.

**Comment by Higgs32584** [comment]
@jhoetter but this is not suitable for beginners by any metric. There is no documentation, no one can even contribute cause ther are barely any instructions whatsoever

**Comment by AleksLi1** [comment]
cringe

**Comment by Insticthere** [comment]
> https://github.com/twitter deleted a comment from [Higgs32584](https://github.com/Higgs32584) [11 hours ago](https://github.com/twitter/the-algorithm/issues/881#event-8905606482) i though they were free

**Comment by lnfel** [comment]
This thread is gold lmao

**Comment by blkpws** [comment]
> `>complaining about a billionaire on a platform funded and used by billionaires`

There is no issue complaining here, he's not working for free for them, that is what he's saying.

**Comment by Lamby777** [comment]
> Back.
> 
> > Nobody forces you to do that either
> 
> Eh.. yes, obviously? That's the point doofus, it's voluntary. That's what open source means. Anyone can contribute. Nobody forces you to do it. So if you participate, it's reasonable to think of a solution to the spam in the issues section, to which @jhoetter and I provided one and didn't just solely complain about it. What did you do? ... Exactly. Complaining about "muh billionaires". You really showed them!
> 
> > I recommend you starting to work on the Ligma engine in the /src folder.
> 
> "Haha look guis I'm soo funny :DD". Here's my recommendation: Stop being a scatterbrained imbecile. Fabricating capricious and flimsy arguments (such as the one proffered above in your first comment here) in order to justify defecating upon this place due to your ideologically motivated opposition to the wealthy elite (although I believe that's just some made-up excuse to troll) is, quite frankly, one of the dumbest and obvious hypocritical takes one can provide. Especially since it's on GitHub which is a subsidiary of Microsoft.
> 
> No different than people crying about terrible corporate decisions Google makes, but still use it every day because they don't have the guts to admit they can't be loyal to their ideology because of some favorite YouTuber. At least be intellectually honest. That way you would be taken more seriously.
> 
> Another fun fact: a plethora of repositories on this platform are in fact owned and maintained by billionaire corporations (e.g. Epic Games, Microsoft, Google, RedHat, Amazon, IBM, etc). This is hardly a revelation, as even GitHub itself is heavily involved and motivated into catering to the interests of these entities to have them stay here, often at disadvantage to the ordinary GitHub user. Yet I don't see you complaining about this or advocating people to switch over to alternatives, such as GitLab. Why did you succumb then registering here?
> 
> The time you wasted here could've been used to contribute to alternatives that aren't centralized. Okay if that's what you're seeking, then stop being a simp to billionaires and leave GitHub I guess ¯_(ツ)_/¯

As much as I hate when people write "i'm not reading all that," I feel like this is a good exception.
I'm not reading that. 🤓🤓🤓
![sus](https://media.tenor.com/xf3QERSXtE4AAAAM/nerd.gif)

**Comment by Lamby777** [comment]
> This repository is far from complete, their CI pipeline is literally a shell script with 'exit 0'. I don't know if this is an April Fools joke or that is actually what they use in production

CI written by the finest devs in the industry. Gets the job done perfectly.

**Comment by montw-dev** [comment]
> rewrite this in Rust

the only possible answer

**Comment by jdm-twtr** [comment]
Excellent work on this! We may need to revisit in the future, but we're in better shape now than we were a few days ago!
