### ISSUE TITLE
When will BitcoinZ be supported as Blue payment? (As part of the algorithm score boosting)

### ISSUE THREAD

**Issue by fiinix00** [twitter/the-algorithm#883]
**Is your feature request related to a problem? Please describe.**
Not related to a problem, but many businesses and individuals are looking for a secure, fast, and decentralized payment solution that does not rely on traditional banking systems. However, existing cryptocurrencies often have high transaction fees and require expensive mining equipment, making them less accessible to the average person. This creates a problem for those who want to transact with a decentralized currency without being excluded due to high costs.

**Describe the solution you'd like**
BitcoinZ would be a great solution as a payment alternative because it is a fast, secure, and decentralized cryptocurrency that is easy to use and accessible to anyone with a computer or mobile device. It has a low transaction fee and is designed to be mined using GPUs, which are more affordable than specialized mining equipment.

By adding BitcoinZ as a payment option, businesses and individuals can benefit from the advantages of a decentralized currency without worrying about high costs or the need for expensive equipment. Additionally, BitcoinZ has strong community support and is constantly being updated and improved.

**Describe alternatives you've considered**
Other cryptocurrencies, such as Bitcoin and Ethereum, are commonly used as payment alternatives, but they often have higher transaction fees and require specialized mining equipment, which makes them less accessible to the average person. Additionally, some of these cryptocurrencies have scalability issues, making them less practical for everyday transactions.

**Additional context**
BitcoinZ is a community-driven cryptocurrency that is committed to decentralization and promoting financial freedom. It is based on the original Bitcoin blockchain, but with additional improvements and features that make it more accessible and user-friendly. It has a strong focus on privacy and security, making it an ideal choice for those who value their financial privacy. Overall, BitcoinZ would be a great addition to any business or individual looking for a secure, fast, and decentralized payment solution

**Comment by nobodyindustries** [comment]
Only $DOGE allowed 🚀 🌕

**Comment by impoverishedowl** [comment]
Hello, I'm afraid that we aren't planning to add support for any cryptocurrencies in the near future.

We appreciate your understanding and hope you have a great day!

**Comment by sunnamed434** [comment]
> Only $DOGE allowed 🚀 🌕

shiba inu, dude

**Comment by nobodyindustries** [comment]
@impoverishedowl when the Ligma engine is finished.

**Comment by nobodyindustries** [comment]
@sunnamed434 yes, that one will as well be.

**Comment by simbav911** [comment]
> Hello, I'm afraid that we aren't planning to add support for any cryptocurrencies in the near future.
> 
> We appreciate your understanding and hope you have a great day!

I wanted to see BitcoinZ. Thanks.

**Comment by jdm-twtr** [comment]
Thanks for filing. We've marked this issue as an unrelated bug or feature for future review.
                    In order to keep our issue count manageable, we will not be leaving these issues open. We apologize for
                    the inconvenience. If you feel that we closed your issue in error, please re-file the issue, stating how
                    the requested feature applies to the recommendation algorithm components that have been open-sourced thus far.
