### ISSUE TITLE
Uh, listen up Elon

### ISSUE THREAD

**Issue by PresidentObama** [twitter/the-algorithm#894]
Elon, you've known me, former president of the United States Barack Obama, for a long time now. Michelle and I had you over for dinner at the whitehouse. I've had a hand in awarding your companies numerous profitable government contracts. You owe me, to say the least. I'm going to need some help extending my social media reach in the 2024 elections. God forbid if Hillary gets involved we're going to need it. The world knows that you've been bending the algorithm in your favor, now I'm going to need you to do the same for my account, BarackObama on twitter. Consider this an official request from me, and I'll see to it those spacex contracts keep coming in.

**Comment by Anushka-codergirl** [comment]
LOL 😆

**Comment by delgh1** [comment]
I will create a pull request so power that it pulls elon out of the company
