### ISSUE TITLE
This repo is a joke

### ISSUE THREAD

**Issue by abdnafees** [twitter/the-algorithm#897]
There are no instructions or steps to run the code, nor any guide to suggest points of entry. I think Elon just made a fool of us who are interested in making contributions and improving the most loved blogging platform in the world.

**Comment by Vallith** [comment]
you can't run the code lmao. it's not the full algorithm for security reasons.
also you're upset you can't do free labour for the billionaire who fired most of the people who could actually do it to begin with? elon's just hoping people will save the algorithm before it collapses under the weight of a billionaire's ego

**Comment by abdnafees** [comment]
I am angry at the audacity of making something important open source and then just leaving it hanging. They should take it down.

**Comment by Shybella** [comment]
you're trolling, right?

**Comment by developeratul** [comment]
It's April fool guys!

**Comment by abdnafees** [comment]
Of course, I am trolling.

**Comment by Shybella** [comment]
shit I completely forgot

**Comment by abdnafees** [comment]
You guys, why all the thumbs down?

**Comment by Higgs32584** [comment]
@abdnafees yea so this looks like an April fools joke. I think this is a joke, but legit there are so many open source projects that are critically important.

**Comment by abdnafees** [comment]
@Higgs32584 Absolutely.
