### ISSUE TITLE
Can you tell us about advantages of using Scala

### ISSUE THREAD

**Issue by DevPlus31** [twitter/the-algorithm#898]
Can you tell us about advantages of using Scala
Thank you.

**Comment by nobodyindustries** [comment]
It is a very lean language with almost no verbosity, and, as part of the .NET family of languages, provides a nice execution speed on MacOS machines.

**Comment by gumbarros** [comment]
> It is a very lean language with almost no verbosity, and, as part of the .NET family of languages, provides a nice execution speed on MacOS machines.

I think F# is the functional language of .NET not Scala.

**Comment by DevPlus31** [comment]
@nobodyindustries  Scala isn't part of .NET family

**Comment by dagelf** [comment]
**SCALA**BALE?

**Comment by PThorpe92** [comment]
its a flavor of Java that's supposed to be functional esq..

**Comment by Tofixrs** [comment]
Delet dis

**Comment by ThePrimeagen** [comment]
DELET DIS

**Comment by bingis-khan** [comment]
Lock it. Lock it now. This is the friendliest message I'm going to send, while I look for ways to get OP banned from Github for gross social misconduct. I imagine that "owner of bots universe" might be enough to get that account tagged as a bot, who knows how many communities across however many repositories that person just bothered across all of Github.
