### ISSUE TITLE
Ban Sharif and Zardari family from Twitter

### ISSUE THREAD

**Issue by Syed007Hassan** [twitter/the-algorithm#903]
Multiple sources are listed for this purpose:

[https://www.wonderslist.com/10-most-corrupt-politicians/](https://www.wonderslist.com/10-most-corrupt-politicians/)
[https://www.fakoa.com/10-most-corrupt-politicians/](https://www.fakoa.com/10-most-corrupt-politicians/)
[https://en.wikipedia.org/wiki/Category:Pakistani_politicians_convicted_of_corruption](https://en.wikipedia.org/wiki/Category:Pakistani_politicians_convicted_of_corruption)

**Comment by abdnafees** [comment]
LGTM

**Comment by nobodyindustries** [comment]
No, the idea is just the opposite, the more corrupt, the more boosting you get.

**Comment by gondaljutt** [comment]
LFGTM.
