### ISSUE TITLE
Dependency on Twitter internal libraries

### ISSUE THREAD

**Issue by guibaq** [twitter/the-algorithm#907]
Some code has dependency on Twitter internal libraries (e.g., [here](https://github.com/twitter/the-algorithm/blob/main/trust_and_safety_models/nsfw/nsfw_text.py#L12)). Do you plan to make those available as well?

**Comment by run-crash-run** [comment]
Similar to the above there are some files (some of them configs, some of them related to training the model) that are missing. Could you add more generic versions of those files if possible?

**Comment by nobodyindustries** [comment]
No, they don't plan to do shit, this repo is absolutely useless.

**Comment by no-identd** [comment]
See also https://github.com/twitter/the-algorithm-ml/issues/50

**Comment by no-identd** [comment]
@nobodyindustries go touch some grass

**Comment by jjh42** [comment]
The intention with this release was to make sure you can run the for you heavy ranker and the twhin embedding model. These should be runnable (instructions in README), there are some shared libraries which might contain other code paths (e.g. for experimental work not currently in use) that aren't intended to be run.
