### ISSUE TITLE
Fix the LIGMA engine

### ISSUE THREAD

**Issue by nobodyindustries** [twitter/the-algorithm#918]
**Is your feature request related to a problem? Please describe.**
Fix the Ligma engine

**Describe the solution you'd like**
Merge it with the Sugma framework

**Describe alternatives you've considered**
Rewriting it in Rust

**Additional context**
No need.

**Comment by willuhmjs** [comment]
What's the Ligma engine?

**Comment by nobodyindustries** [comment]
LIGMA BALLS

**Comment by Utsuhoagie** [comment]
> LIGMA BALLS

Gottem
