### ISSUE TITLE
Cannot download this repo

### ISSUE THREAD

**Issue by delgh1** [twitter/the-algorithm#919]
**Describe the bug**
Cannot download this repo

**To Reproduce**
1. Go to 'guthib'
2. See errorA

**Expected behavior**
Download is a success.

**Screenshots**
N/A.

**Environment**
- For libraries, what version of build tools are you using?
- the great library of alexandria

**Additional context**
Nope.

**Comment by nobodyindustries** [comment]
Not a bug. Intended behavior.

**Comment by delgh1** [comment]
> Not a bug. Intended behavior.

I disaaaaaagreeee

**Comment by nobodyindustries** [comment]
Let's rewrite it in Rust

**Comment by delgh1** [comment]
> Let's rewrite it in Rust

sure, here is some rust
![R2JUKM6rNcPQHywUUAzgqZ](https://user-images.githubusercontent.com/60296981/229300446-198b741c-7d1e-49ca-8921-fd6eb2e3d729.jpg)
