### ISSUE TITLE
add my cat into the algorithm

### ISSUE THREAD

**Issue by jojobii-arks** [twitter/the-algorithm#928]
![image](https://user-images.githubusercontent.com/78003700/229302293-298dd953-10e1-4b79-99d4-8fca4d87899c.png)

put the fella in 🗣️🗣️🗣️🗣️🗣️

**Comment by 7adidaz** [comment]
Looks like a good feature to include, I'll pass it

**Comment by parz3val** [comment]
I strongly support this.

**Comment by R3dFruitRollUp** [comment]
Up

**Comment by delgh1** [comment]
LGTM

**Comment by AlmightyLks** [comment]
LGTM
