### ISSUE TITLE
Why is the CI Pipeline one single shell script that only has 'exit 0'?

### ISSUE THREAD

**Issue by impoverishedowl** [twitter/the-algorithm#930]
https://github.com/twitter/the-algorithm/blob/main/ci/ci.sh

No wonder twitter isn't reliable

**Comment by impoverishedowl** [comment]
Interesting fact: If the twitter algorithim was replaced with something that would steal everyone's data, the CI pipeline would still pass! :)

**Comment by dagelf** [comment]
Obviously not what is used on their probably mind bending infrastructure, and releasing that could potentially pose a security risk for them at this time? This should be documented though.

**Comment by impoverishedowl** [comment]
> Obviously not what is used on their probably mind bending infrastructure, and releasing that could potentially pose a security risk for them at this time? This should be documented though.

It's literally not mind bending. It's just a bunch of Kubernetes clusters running containers

**Comment by dagelf** [comment]
Fair point. Although kubernetes didn't exist when Twitter started... so maybe its still a bit more complicated than that...?

**Comment by impoverishedowl** [comment]
> Fair point. Although kubernetes didn't exist when Twitter started... so maybe its still a bit more complicated than that...?

They did move to kubernetes once it became industry standard. Research says that they used to use [Mesos ](https://mesos.apache.org/)

**Comment by nobodyindustries** [comment]
They probably can't show it as it would reveal internal infrastructure, no need to get pressed, they are definitely not using this in production.

**Comment by dnlsndr** [comment]
LGTM 🚀

**Comment by jdm-twtr** [comment]
As discussed in previous blog posts, the majority of Twitter's source code lives in a monorepo. Some of it does not. This script is understandably not used for testing the code in this repository, it is just an artifact of other internal tooling that expects it to exist. We may utilize it in the future, or we may remove it.
