### ISSUE TITLE
trans rights

### ISSUE THREAD

**Issue by lizzlesss** [twitter/the-algorithm#937]
trans people are pretty cool i think 🏳️‍⚧️

**Comment by delgh1** [comment]
trans right are human rights

**Comment by arnavbhatt288** [comment]
Why are people advocating for train rights smh

**Comment by leandrofriedrich** [comment]
@arnavbhatt288 @delgh1 @lizzlesss TÜRKİYE 
![Screenshot_20230401_190410](https://user-images.githubusercontent.com/58913672/229305588-a4c0b433-02c1-4e51-88eb-73f0b85c0feb.jpg)

**Comment by halal-beef** [comment]
KOSOVO JE SRBIJAAAAAA

**Comment by halal-beef** [comment]
BOSNA BESTTTT

**Comment by halal-beef** [comment]
🇧🇦🇧🇦🇧🇦🇧🇦

**Comment by abdnafees** [comment]
HAHAHAHA

**Comment by halal-beef** [comment]
sori sori, my balkan gramer messed up, kosovo isnt srbija, srbija is kosovo


SRBIJA JE KOSOVO
