### ISSUE TITLE
How to create a pull request?

### ISSUE THREAD

**Issue by mcanueste** [twitter/the-algorithm#963]
Hi, I have a PR I want submit for review for a bug I have found in the codebase. However, I don't know how to submit a PR with printed out code, and couldn't find any documentation about it. 

Can someone point out to me how to create a PR with printed code? Do I mail it to Github or something?

**Comment by errorware** [comment]
Good morning sir,

Please sir, refer to Mr Durga, very java. Very fast. Please sir, contact soon.

**Comment by mcanueste** [comment]
Too late. My dog ate my PR...
