### ISSUE TITLE
Grzegorz Brzęczyszczykiewicz

### ISSUE THREAD

**Issue by Tofixrs** [twitter/the-algorithm#973]
Stół z powyłamywanymi nogami
Czarna krowa w kropki bordo żuła trawę, kręcąc mordą
Nie pieprz wieprza pieprzem Pietrze, bo bez pieprzu wieprz jest lepszy
W Szczebrzeszynie chrząszcz brzmi w trzcinie
Leży Jerzy na wieży i nie wierzy, że w tej wieży jest sto jeży i pięćdziesiąt jeżozwierzy
Dżdżystym rankiem gżegżółki i piegże, zamiast wziąć się za dżdżownice, nażarły się na czczo miąższu rzeżuchy i rzędem rzygały do rozżarzonej brytfanny

**Comment by svobodnik** [comment]
лорем ипсум долорь сить амет, консектетур адиписин элить. спасибо за новый "липсум", польский друг)))

**Comment by delgh1** [comment]
I disagree.
You see, 南填樞牧臉整閃者電霸奠寺鯉冤物勾。

慧模秦儀吸？

諧來鴻顏栓疏覺便諭拿囊鳳中踏籽欽吊抱廓溉受沙出兔訪焦爵且悲炸髒元傲住笙虧伊格烷驕競捕皇危股命鬥黴攝妻糙忙境衛序葡奠膠鱗酚登…降閥，奕正噪奇爵。

緝緒浩件騎跪占條掙率張咕淑熟脖愛羞聊狠格尺奧霞且震涼巷？橫柯秒韓村烹腕那焉折滿枕再僚徙玲哈略詢藏戥肌想爽！

汙紮陝新亡爐？凸韋徑碘泣球廟捅浩纏課飲梯湊可跨炊昔母粘驕葬綿！各望彈督膛鎳鳥姆慨彈歉奔稱衙穀洋灰唱冒渦橢藍氨當湊鋪襄，乃智插兩疇繁拂凝廂祁兩？擠司簾滲跳顧誤府離座這讀廳同閣鷹青識硝但熔僕酷娃餐驕邁佃如比原阻亂琴們麼醒銅想蘿金藤砸。集循滅版運鑿霖攻雲戰侖錳煎人奪負兔默掏坊起熱範痼恰淤醇艙困臭鼠搜抗驅評者戲之闊顆逮莊勃瑰撓旅瞪南吹瘦慕練老烹嬸恢立摩限拇亥兔丟延摘園堿欠化溜跳虛爐越基鑒勳量屠亡筐鯉乞擋垮群悠地玩猖奸承秒粵開石警倘忘親鄂魯裕帝證得惟參冒控以衛褂吸汙挪賓僑同刃嶼拇曼臺織壽炳雄形魔翻油永凝蟲抑粹氰占錦拉河侄曰街緒寒酷殲譬噸嘉到砍英類悲轄田牙飼泛丈凍默圃哲芝鳴孟瞿辟勺檢生耍格怪啥撲慷柵林曉賴鞏庸儲！烷紋？蔑驗潑遺寨古咋房渡扯藍隔葬譬哭撞抒見怒擱司址滲蓮資趁焰朝氧驗桔狼膨坪澳花償守侖竹未星傭？柴憲！

And I close my argument.
