### ISSUE TITLE
I don't understand why this hasn't been implemented yet??????

### ISSUE THREAD

**Issue by ShimmyShong** [twitter/the-algorithm#974]
Not gonna be active on Discord tonight. I'm meeting a girl (a real one) in half an hour (wouldn't expect a lot of you to understand anyway) so please don't DM me asking me where I am (im with the girl, ok) you'll most likely get aired because ill be with the girl (again I don't expect you to understand) shes actually really interested in me and its not a situation i can pass up for some meaningless Discord degenerates (because ill be meeting a girl, not that you really are going to understand) this is my life now. Meeting women and not wasting my precious time online, I have to move on from such simple things and branch out (you wouldnt understand)

**Comment by ThePrimeagen** [comment]
Arch for life

**Comment by alieldeba** [comment]
Lol man

**Comment by alieldeba** [comment]
Wish you happy date 😂

**Comment by bugwarez** [comment]
so i can date with girls just by saying "i use arch btw" right ?

**Comment by abdnafees** [comment]
Take care man! Best of luck

**Comment by blkpws** [comment]
Can you update the current status of your date?
