### ISSUE TITLE
Integration with /g/

### ISSUE THREAD

**Issue by errorware** [twitter/the-algorithm#979]
You know what I'm saying?

**Comment by Higgs32584** [comment]
I feel you g

**Comment by Gareki1** [comment]
Rewrite the algorithm in HolyC, as Terry Davis(PBUH) intended.

**Comment by Gamiac** [comment]
Can't. It's already integrated with /pol/.

**Comment by unnimona** [comment]
Cool!
Check out https://securityinfinity.com 
Secure your website now

(We are also giving one time opportunity to hack us in 24 hours. Show your skills)
(we initially thought of not writing this to everyone, only to find some keyboard warriors like Kyle Suero giving us boring startup advice. Also this message is dedicated to Twitter team who thinks they can silence everyone in github.com just like they do in Twitter)
