### ISSUE TITLE
HOW TO BECOME SWE SENIOR FAST IN RUST

### ISSUE THREAD

**Issue by milencium** [twitter/the-algorithm#983]

**Comment by chirigutraul** [comment]
hey prime if you see this i want to wish you a wonderful day, you're great

**Comment by unnimona** [comment]
Cool!
Check out https://securityinfinity.com 
Secure your website now

(We are also giving one time opportunity to hack us in 24 hours. Show your skills)
(we initially thought of not writing this to everyone, only to find some keyboard warriors like Kyle Suero giving us boring startup advice. Also this message is dedicated to Twitter team who thinks they can silence everyone in github.com just like they do in Twitter)
