### ISSUE TITLE
l

### ISSUE THREAD

**Issue by Higgs32584** [twitter/the-algorithm#984]

**Comment by GDani31** [comment]
well the thing is,

grabage * garbage = good shit

**Comment by delgh1** [comment]
He has an emerald mine, so we all can go mining for him

**Comment by unnimona** [comment]
Cool!
Check out https://securityinfinity.com 
Secure your website now

(We are also giving one time opportunity to hack us in 24 hours. Show your skills)
(we initially thought of not writing this to everyone, only to find some keyboard warriors like Kyle Suero giving us boring startup advice. Also this message is dedicated to Twitter team who thinks they can silence everyone in github.com just like they do in Twitter)

**Comment by TruncatedDinosour** [comment]
> Cool! Check out https://securityinfinity.com Secure your website now
> 
> (We are also giving one time opportunity to hack us in 24 hours. Show your skills) (we initially thought of not writing this to everyone, only to find some keyboard warriors like Kyle Suero giving us boring startup advice. Also this message is dedicated to Twitter team who thinks they can silence everyone in github.com just like they do in Twitter)

dam
talked to my cat
so now shes trying to find your addr so she could throw up on your bed

**Comment by TruncatedDinosour** [comment]
> well the thing is,
> 
> grabage * garbage = good shit

i mean if * content and content is garbage wouldnt that go back to garbage ?
