### ISSUE TITLE
TWITTER DISCORD CHANNEL

### ISSUE THREAD

**Issue by securityinfinity-com** [twitter/the-algorithm#986]
Elon is getting heated on our Discord channel  :D
Join Now!!

https://discord.gg/krHZqwseZe

**Comment by impoverishedowl** [comment]
This is NOT how you should market your product, idiot!

**Comment by securityinfinity-com** [comment]
lol  we will do it anyway
dumbass

**Comment by kyputer** [comment]
L

**Comment by unnimona** [comment]
Cool!
Check out https://securityinfinity.com 
Secure your website now

(We are also giving one time opportunity to hack us in 24 hours. Show your skills)
(we initially thought of not writing this to everyone, only to find some keyboard warriors like Kyle Suero giving us boring startup advice. Also this message is dedicated to Twitter team who thinks they can silence everyone in github.com just like they do in Twitter)
