### ISSUE TITLE
Trips are comming dudes

### ISSUE THREAD

**Issue by errorware** [twitter/the-algorithm#989]

**Comment by delgh1** [comment]
whut?

**Comment by Higgs32584** [comment]
![755DF637-51C0-4F97-BDC8-DD96660EC0FE](https://user-images.githubusercontent.com/55243596/229307908-a363674a-3eba-4e59-90e8-6fa4d5f2c270.jpeg)
![2A520D8A-AB2B-46A8-979B-0D80EB90DC70](https://user-images.githubusercontent.com/55243596/229307909-6bee6f55-507b-415c-b997-cb3033a996f6.jpeg)

**Comment by unnimona** [comment]
Cool!
Check out https://securityinfinity.com 
Secure your website now

(We are also giving one time opportunity to hack us in 24 hours. Show your skills)
(we initially thought of not writing this to everyone, only to find some keyboard warriors like Kyle Suero giving us boring startup advice. Also this message is dedicated to Twitter team who thinks they can silence everyone in github.com just like they do in Twitter)

**Comment by jdm-twtr** [comment]
This issue was closed due to lack of useful description.
