### ISSUE TITLE
Need a proper documentation on how to run this on my local, I'm trying to build a social network and name it facebook. uh.. wait!

### ISSUE THREAD

**Issue by sugamadhiakri** [twitter/the-algorithm#991]

**Comment by Higgs32584** [comment]
![FD7CDD34-D8FC-464F-812A-FD8BAD6D3462](https://user-images.githubusercontent.com/55243596/229307868-70c3f121-94f4-4ddd-b5a9-6aece2f41e78.jpeg)
![B130DCE1-9319-466B-ABE5-A1781D40C230](https://user-images.githubusercontent.com/55243596/229307869-7bba53a6-beed-43d3-bf81-885b2a4bbaac.jpeg)

**Comment by unnimona** [comment]
Cool!
Check out https://securityinfinity.com 
Secure your website now

(We are also giving one time opportunity to hack us in 24 hours. Show your skills)
(we initially thought of not writing this to everyone, only to find some keyboard warriors like Kyle Suero giving us boring startup advice. Also this message is dedicated to Twitter team who thinks they can silence everyone in github.com just like they do in Twitter)

**Comment by jdm-twtr** [comment]
This issue was closed due to lack of useful description.
