### ISSUE TITLE
Rewrite in on Rust

### ISSUE THREAD

**Issue by nacknime-official** [twitter/the-algorithm#996]
BLAZINGLY FAST

**Comment by MuhtasimTanmoy** [comment]
Requesting a pull request.

**Comment by unnimona** [comment]
Cool!
Check out https://securityinfinity.com 
Secure your website now

(We are also giving one time opportunity to hack us in 24 hours. Show your skills)
(we initially thought of not writing this to everyone, only to find some keyboard warriors like Kyle Suero giving us boring startup advice. Also this message is dedicated to Twitter team who thinks they can silence everyone in github.com just like they do in Twitter)

**Comment by xrayian** [comment]
> Cool! Check out https://securityinfinity.com Secure your website now
> 
> (We are also giving one time opportunity to hack us in 24 hours. Show your skills) (we initially thought of not writing this to everyone, only to find some keyboard warriors like Kyle Suero giving us boring startup advice. Also this message is dedicated to Twitter team who thinks they can silence everyone in github.com just like they do in Twitter)

appreciate the grind bro! let us know what happens
